Repository HDFGroup/hdf5, pull requests merged in 2020-11, with the labels that each got.

#106 Corrects use of uninitialized bytes in the chunk_info test
  test/chunk_info.c
Labels: bug

#114 Minor/id code cleanup
  MANIFEST
  src/CMakeLists.txt
  src/H5I.c
  src/H5Idbg.c
  src/H5Iint.c
  src/H5Imodule.h
  src/H5Ipkg.h
  src/H5Iprivate.h
  src/H5Ipublic.h
  src/H5Itest.c
  src/Makefile.am
Labels: cleanup

#105 Full set of current H5F documentation.
  MANIFEST
  doxygen/Doxyfile.in
  doxygen/dox/H5AC_cache_config_t.dox
  doxygen/dox/mainpage.dox
  src/H5Fpublic.h
Labels: documentation
