Repository HDFGroup/hdf5, pull requests merged in 2021-11, with the labels that each got.

#1149 1.8 Merge Github #1019 - add Fortran developer flags #1090
  MANIFEST
  config/cmake/HDFFortranCompilerFlags.cmake
  config/gnu-warnings/developer-gfort-5
  configure.ac
Labels: merge

#1160 1.12 Merge Fix Java VOL tests #1158
  MANIFEST
  config/cmake/jrunTest.cmake
  config/cmake/jvolTest.cmake
  config/cmake/scripts/HDF5config.cmake
  java/test/CMakeLists.txt
Labels: merge

#470 Assume C99 fixed sized ints exist, use them
  c++/src/H5PredType.cpp
  fortran/src/H5_f.c
  hl/fortran/src/H5LTfc.c
  hl/src/H5LT.c
  java/src/jni/h5util.c
  src/H5HGprivate.h
  src/H5Rint.c
  src/H5Rpkg.h
  src/H5T.c
  src/H5Tconv.c
  src/H5Tnative.c
  src/H5Tpkg.h
  src/H5Tpublic.h
  src/H5Tref.c
  src/H5Ztrans.c
  src/H5detect.c
  src/H5trace.c
  test/dt_arith.c
  test/dtransform.c
  test/dtypes.c
  test/tconfig.c
  tools/lib/h5diff_array.c
  tools/lib/h5diff_util.c
  tools/lib/h5tools_str.c
  tools/src/h5import/h5import.c
  tools/test/h5diff/h5diffgentest.c
  tools/test/h5import/h5importtest.c
Labels: WIP

#1174 Re-enable collective metadata reads after disabling for chunk lookup (1.12 merge)
  release_docs/RELEASE.txt
  src/H5Dchunk.c
Labels: merge

#1175 Re-enable collective metadata reads after disabling for chunk lookup (1.10 merge)
  release_docs/RELEASE.txt
  src/H5Dchunk.c
Labels: merge

#1193 1.12 TRILAB-266: Remove clang warnings.
  src/H5FDcore.c
  src/H5Zscaleoffset.c
  src/H5private.h
  src/uthash.h
  test/cork.c
  test/swmr.c
  test/testmeta.c
  test/tvlstr.c
Labels: merge

#1200 1.10 TRILAB-266: Remove clang warnings.
  src/H5FDcore.c
  src/H5Zscaleoffset.c
  src/H5private.h
  src/uthash.h
  test/cork.c
  test/swmr.c
  test/tvlstr.c
Labels: merge

#1197 Add javadoc to packages - HDFFV-11285
  MANIFEST
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/callbacks/package-info.java
  java/src/hdf/hdf5lib/exceptions/package-info.java
  java/src/hdf/hdf5lib/package-info.java
  java/src/hdf/hdf5lib/structs/package-info.java
Labels: documentation

#1198 1.12 Merge Add javadoc to packages - HDFFV-11285
  MANIFEST
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/callbacks/package-info.java
  java/src/hdf/hdf5lib/exceptions/package-info.java
  java/src/hdf/hdf5lib/package-info.java
  java/src/hdf/hdf5lib/structs/package-info.java
Labels: documentation, merge

#1204 1.12 Merge Github #969 Use stdout instead of file for configure check #1089
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDF5UseFortran.cmake
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
Labels: merge

#1199 1.10 Merge Add javadoc to packages - HDFFV-11285
  MANIFEST
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/callbacks/package-info.java
  java/src/hdf/hdf5lib/exceptions/package-info.java
  java/src/hdf/hdf5lib/package-info.java
  java/src/hdf/hdf5lib/structs/package-info.java
Labels: documentation, merge

#1205 1.10 Merge Github #969 Use stdout instead of file for configure check #1089
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDF5UseFortran.cmake
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
Labels: merge

#1180 Next batch of Doxygen updates.
  MANIFEST
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/FTS.dox
  doxygen/dox/FileFormatSpec.dox
  doxygen/dox/OtherSpecs.dox
  doxygen/dox/RFC.dox
  doxygen/dox/Specifications.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/DebuggingHDF5Applications.html
  doxygen/examples/FileFormat.html
  doxygen/examples/Filters.html
  doxygen/examples/IOFlow.html
  doxygen/hdf5doxy_layout.xml
  doxygen/img/IOFlow.gif
  doxygen/img/IOFlow2.gif
  doxygen/img/IOFlow3.gif
Labels: documentation

#1223 Closes #1221
  doxygen/aliases
  doxygen/dox/TechnicalNotes.dox
  src/H5Ppublic.h
Labels: documentation

#1230 Merge multiple PRs to 1.8
  CMakeFilters.cmake
  CMakeLists.txt
  c++/test/CMakeVFDTests.cmake
  config/cmake/HDF5Macros.cmake
  config/cmake/HDF5UseFortran.cmake
  config/cmake/README.txt.cmake.in
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
  test/CMakeVFDTests.cmake
  testpar/CMakeVFDTests.cmake
  tools/h5diff/CMakeTests.cmake
  tools/h5dump/CMakeVFDTests.cmake
  tools/h5repack/CMakeVFDTests.cmake
  tools/h5stat/CMakeTests.cmake
Labels: merge
