Repository HDFGroup/hdf5, pull requests merged in 2021-03, with the labels that each got.

#402 A fresh look for our dox
  configure.ac
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/Cookbook.dox
  doxygen/dox/DDLBNF110.dox
  doxygen/dox/DDLBNF112.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/MetadataCachingInHDF5.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/Specifications.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/mainpage.dox
  doxygen/hdf5_footer.html
  doxygen/hdf5_header.html
  doxygen/hdf5_navtree_hacks.js
  doxygen/hdf5doxy.css
  doxygen/hdf5doxy_layout.xml
  doxygen/img/HDFG-logo.png
  doxygen/img/ftv2node.png
  doxygen/img/ftv2pnode.png
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5Fpublic.h
  src/H5Gpublic.h
  src/H5Lpublic.h
  src/H5Opublic.h
  src/H5Rpublic.h
  src/H5VLmodule.h
Labels: documentation

#415 Doxygen2
  src/H5ACpublic.h
  src/H5Cpublic.h
  src/H5FDpublic.h
  src/H5Ppublic.h
Labels: documentation

#439 1 10 Merge #380 from develop
  release_docs/RELEASE.txt
  src/H5Epublic.h
  src/H5FDmulti.c
  src/H5FDstdio.c
Labels: merge

#438 1 12 Merge #380 from develop
  release_docs/RELEASE.txt
  src/H5Epublic.h
  src/H5FDmulti.c
  src/H5FDstdio.c
  src/H5Spkg.h
  tools/lib/h5tools_utils.c
Labels: merge

#457 Replaces checks for fork, etc. with checks for unistd.h
  test/accum.c
  test/dt_arith.c
  test/swmr.c
  test/twriteorder.c
  test/use_append_chunk.c
  test/use_append_chunk_mirror.c
  test/use_append_mchunks.c
  test/use_common.c
  test/use_disable_mdc_flushes.c
Labels: cleanup

#407 Add my assigned Doxygen documentation.
  doxygen/examples/H5Pget_metadata_read_attempts.1.c
  doxygen/examples/H5Pget_metadata_read_attempts.2.c
  doxygen/examples/H5Pget_metadata_read_attempts.3.c
  doxygen/examples/H5Pget_object_flush_cb.c
  src/H5Ppublic.h
Labels: documentation

#506 develop - Javadoc warning fixes
  java/src/hdf/hdf5lib/exceptions/HDF5LibraryException.java
  java/src/hdf/hdf5lib/structs/H5AC_cache_config_t.java
  java/src/hdf/hdf5lib/structs/H5E_error2_t.java
  java/src/hdf/hdf5lib/structs/H5FD_hdfs_fapl_t.java
  java/src/hdf/hdf5lib/structs/H5FD_ros3_fapl_t.java
  java/src/hdf/hdf5lib/structs/H5F_info2_t.java
  java/src/hdf/hdf5lib/structs/H5G_info_t.java
  java/src/hdf/hdf5lib/structs/H5L_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_hdr_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_native_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_token_t.java
Labels: documentation

#507 1 12 - javadoc warning fixes
  java/src/hdf/hdf5lib/exceptions/HDF5LibraryException.java
  java/src/hdf/hdf5lib/structs/H5AC_cache_config_t.java
  java/src/hdf/hdf5lib/structs/H5E_error2_t.java
  java/src/hdf/hdf5lib/structs/H5FD_hdfs_fapl_t.java
  java/src/hdf/hdf5lib/structs/H5FD_ros3_fapl_t.java
  java/src/hdf/hdf5lib/structs/H5F_info2_t.java
  java/src/hdf/hdf5lib/structs/H5G_info_t.java
  java/src/hdf/hdf5lib/structs/H5L_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_hdr_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_native_info_t.java
  java/src/hdf/hdf5lib/structs/H5O_token_t.java
Labels: documentation
