Repository HDFGroup/hdf5, pull requests merged in 2022-02, with the labels that each got.

#1417 (1.12 Merge) Unify handling of collective metadata reads status (#1206)
  release_docs/RELEASE.txt
  src/H5C.c
  src/H5CX.c
  src/H5Dchunk.c
  src/H5Dmpio.c
  src/H5Fmpi.c
  src/H5Fprivate.h
  src/H5Pfapl.c
  src/H5Z.c
  testpar/t_cache.c
  testpar/t_coll_md_read.c
Labels: merge

#1418 (1.10 Merge) Unify handling of collective metadata reads status (#1206)
  release_docs/RELEASE.txt
  src/H5C.c
  src/H5CX.c
  src/H5Dchunk.c
  src/H5Dmpio.c
  src/H5Fmpi.c
  src/H5Fprivate.h
  src/H5Pfapl.c
  src/H5Z.c
  testpar/t_cache.c
  testpar/t_coll_md_read.c
Labels: merge

#1442 Updated reference for Multi Dataset RFC.
  doxygen/aliases
Labels: documentation

#1398 Enable creation of RPM/DEB binaries GH#1394
  CMakeInstallation.cmake
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: enhancement
