Repository HDFGroup/hdf5, pull requests merged in 2022-04, with the labels that each got.

#1551 1.12 Update command format, avoid policy warning
  config/cmake_ext_mod/runTest.cmake
Labels: merge

#1566 1.12 Move error-stack text to top of usage display #1564
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5stat/h5stat.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
  tools/test/h5repack/testfiles/h5repack-help.txt
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
  tools/testfiles/h5dump-help.txt
  tools/testfiles/pbits/tnofilename-with-packed-bits.ddl
  tools/testfiles/pbits/tpbitsIncomplete.ddl
  tools/testfiles/pbits/tpbitsLengthExceeded.ddl
  tools/testfiles/pbits/tpbitsLengthPositive.ddl
  tools/testfiles/pbits/tpbitsMaxExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetNegative.ddl
Labels: merge

#1575 1.12 Add option for h5repack timing #1142
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack.h
  tools/src/h5repack/h5repack_copy.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_refs.c
  tools/test/h5repack/testfiles/h5repack-help.txt
Labels: merge

#1596 1.10: Brings MANIFEST removal from develop
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  MANIFEST
  bin/bbrelease
  bin/chkmanifest
  bin/locate_sw
  bin/release
  bin/runtest
  bin/snapshot
  bin/snapshot_version
  bin/timekeeper
Labels: merge

#1594 1.12: Brings release timeline and github action changes from develop
  .github/workflows/main.yml
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: merge

#1608 1.12: Brings bin/restore.sh src/H5config.h.in cleanup from develop
  bin/restore.sh
Labels: merge

#1610 1.12: Removes unused H5HP and H5MP packages
  src/CMakeLists.txt
  src/H5HP.c
  src/H5HPprivate.h
  src/H5MP.c
  src/H5MPmodule.h
  src/H5MPpkg.h
  src/H5MPprivate.h
  src/H5MPtest.c
  src/Makefile.am
  test/CMakeLists.txt
  test/CMakeTests.cmake
  test/Makefile.am
  test/pool.c
  test/testhdf5.c
  test/testhdf5.h
  test/theap.c
Labels: merge

#1612 1.12: Brings skip list try_free_safe changes from develop
  src/H5SL.c
  src/H5SLprivate.h
  test/tskiplist.c
Labels: merge

#1609 1.12: Normalization of HL library with develop
  hl/examples/ex_image1.c
  hl/src/H5DO.c
  hl/src/H5DS.c
  hl/src/H5LT.c
  hl/src/H5LTpublic.h
  hl/test/test_ds.c
  hl/test/test_file_image.c
  hl/test/test_h5do_compat.c
  hl/test/test_image.c
  hl/test/test_ld.c
  hl/test/test_lite.c
  hl/test/test_packet_vlen.c
  hl/test/test_table.c
  hl/tools/gif2h5/decompress.c
  hl/tools/gif2h5/gif2mem.c
  hl/tools/gif2h5/gifread.c
  hl/tools/gif2h5/h52giftest.sh.in
  hl/tools/gif2h5/hdfgifwr.c
  hl/tools/gif2h5/writehdf.c
  hl/tools/h5watch/extend_dset.c
Labels: merge

#1592 1.12 Fix these Doxygen warnings #1581
  src/H5Opublic.h
  src/H5Tmodule.h
  src/H5Tpublic.h
Labels: documentation, merge

#1611 1.12: Brings 1.12 compiler options in line with develop
  config/BlankForm
  config/clang-warnings/developer-general
  config/clang-warnings/general
  config/cmake/libh5cc.in
  config/cmake_ext_mod/ConfigureChecks.cmake
  config/gnu-warnings/cxx-general
  config/gnu-warnings/developer-general
  config/gnu-warnings/error-5
  config/gnu-warnings/error-general
  config/gnu-warnings/general
  src/H5private.h
  src/H5public.h
Labels: merge

#1615 1.12: Brings free list debugging changes from develop
  src/H5FL.c
  src/H5FLprivate.h
Labels: merge

#1618 1.12: Brings minor changes from headers in develop
  src/H5ACpublic.h
  src/H5CSprivate.h
  src/H5CXprivate.h
  src/H5Cpublic.h
  src/H5EAprivate.h
  src/H5FAprivate.h
  src/H5PBprivate.h
Labels: merge

#1617 1.12: Minor doxygen changes from develop
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
Labels: merge

#1621 1.12: Last round of normalizations for 1.12.2
  bin/README
  src/H5.c
  src/H5A.c
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dint.c
  src/H5M.c
  src/H5VMprivate.h
  src/H5system.c
  src/H5timer.c
  test/AtomicWriterReader.txt
  test/cork.c
  test/dangle.c
  test/direct_chunk.c
  test/fheap.c
  test/titerate.c
  test/tselect.c
  tools/lib/h5tools.c
  tools/lib/h5tools_utils.c
  tools/test/perform/chunk.c
  tools/test/perform/overhead.c
  tools/test/perform/pio_standalone.c
  tools/test/perform/pio_standalone.h
  tools/test/perform/sio_standalone.c
  tools/test/perform/sio_standalone.h
  tools/test/perform/zip_perf.c
Labels: merge

#1589 Fix these Doxygen warnings #1581
  src/H5Opublic.h
  src/H5Tmodule.h
  src/H5Tpublic.h
Labels: documentation

#1567 1.10 Move error-stack text to top of usage display #1564
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5stat/h5stat.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
  tools/test/h5repack/testfiles/h5repack-help.txt
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
  tools/testfiles/h5dump-help.txt
  tools/testfiles/pbits/tnofilename-with-packed-bits.ddl
  tools/testfiles/pbits/tpbitsIncomplete.ddl
  tools/testfiles/pbits/tpbitsLengthExceeded.ddl
  tools/testfiles/pbits/tpbitsLengthPositive.ddl
  tools/testfiles/pbits/tpbitsMaxExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetNegative.ddl
Labels: merge

#1591 1.10 Fix these Doxygen warnings #1581
  src/H5Tmodule.h
  src/H5Tpublic.h
Labels: documentation, merge

#1576 1.10 Add option for h5repack timing #1142
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack.h
  tools/src/h5repack/h5repack_copy.c
  tools/src/h5repack/h5repack_filters.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_refs.c
  tools/src/h5repack/h5repack_verify.c
  tools/test/h5repack/testfiles/h5repack-help.txt
Labels: merge

#1593 1.8 Fix these Doxygen warnings #1581
  src/H5Tpublic.h
Labels: documentation, merge

#1644 Hdf5 1 10 parallel comp
  CMakeLists.txt
  config/cmake/H5pubconf.h.in
  config/gnu-warnings/error-8
  configure.ac
  examples/CMakeLists.txt
  examples/CMakeTests.cmake
  examples/Makefile.am
  examples/ph5_filtered_writes.c
  examples/ph5_filtered_writes_no_sel.c
  release_docs/RELEASE.txt
  src/H5AC.c
  src/H5Dchunk.c
  src/H5Dint.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dpkg.h
  src/H5Dselect.c
  src/H5FDmpio.c
  src/H5Fmpi.c
  src/H5Fprivate.h
  src/H5mpi.c
  src/H5private.h
  src/H5public.h
  testpar/t_dset.c
  testpar/t_filters_parallel.c
  testpar/t_filters_parallel.h
  testpar/testphdf5.h
Labels: merge
