Repository HDFGroup/hdf5, pull requests merged in 2022-10, with the labels that each got.

#2110 1.8 Update examples reference to single-source version 2.0.1
  bin/release
  config/cmake/HDF518_Examples.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/README_HDF5_CMake
Labels: merge

#2109 1.10 Update examples reference to single-source version 2.0.1
  bin/release
  config/cmake/HDF5_Examples.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/README_HDF5_CMake
Labels: merge

#2143 Subfiling Fortran wrapper work.
  CMakeLists.txt
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90global.F90
  fortran/src/H5f90proto.h
  fortran/src/hdf5_fortrandll.def.in
  fortran/testpar/CMakeLists.txt
  fortran/testpar/CMakeTests.cmake
  fortran/testpar/Makefile.am
  fortran/testpar/hyper.F90
  fortran/testpar/mdset.F90
  fortran/testpar/ptest.F90
  fortran/testpar/subfiling.F90
  src/H5FDsubfiling/H5FDsubfiling.h
Labels: enhancement

#2146 1.12 Fix some Java warnings
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/hdf/hdf5lib/exceptions/HDF5LibraryException.java
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5util.c
  java/test/TestH5Fparams.java
  java/test/TestH5Ocreate.java
  java/test/TestH5Oparams.java
Labels: merge

#2147 1.10 Fix some Java warnings
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5util.c
  java/test/TestH5Ocreate.java
  java/test/TestH5Oparams.java
Labels: merge

#2148 Fixed fortran parallel testing with cmake
  CMakeLists.txt
  fortran/testpar/CMakeLists.txt
Labels: merge to 1.12, merge to 1.10, merge to 1.8, merge

#2175 Implement option for using CMake GNUInstallDirs
  CMakeInstallation.cmake
  c++/src/CMakeLists.txt
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5options.cmake
  doxygen/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  java/src/hdf/hdf5lib/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: merge to 1.12, merge to 1.10, merge to 1.8

#2165 Port VOL User Guide to doxygen
  doxygen/dox/UsersGuide.dox
  doxygen/examples/tables/volAPIs.dox
  src/H5VLmodule.h
Labels: documentation

#2156 JNI: Improve varlen datatype handling in H5A/H5D read/write functions
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5fImp.c
  java/src/jni/h5tImp.c
  java/src/jni/h5util.c
  java/src/jni/h5util.h
  java/test/TestH5A.java
  java/test/TestH5D.java
  java/test/TestH5R.java
  java/test/testfiles/JUnit-TestH5A.txt
  java/test/testfiles/JUnit-TestH5D.txt
  release_docs/RELEASE.txt
Labels: enhancement, merge to 1.12, merge to 1.10

#2188 Fix for documentation misunderstanding on m1 Intel builds
  src/H5Dmodule.h
Labels: documentation, merge to 1.12, merge to 1.10
