Repository HDFGroup/hdf5, pull requests merged in 2022-08, with the labels that each got.

#1957 Removes (void *) cast from memset on Windows
  src/H5win32defs.h
Labels: cleanup, merge to 1.12, merge to 1.10

#1958 Removes Windows getlogin() equivalent
  bin/checkposix
  src/H5private.h
  src/H5system.c
  src/H5win32defs.h
Labels: cleanup, merge to 1.12, merge to 1.10

#1960 Removes the Win32 macro for strdup
  src/H5win32defs.h
Labels: cleanup, merge to 1.12, merge to 1.10

#1953 Onion VFD
  bin/trace
  src/CMakeLists.txt
  src/H5FDonion.c
  src/H5FDonion.h
  src/H5FDonion_header.c
  src/H5FDonion_header.h
  src/H5FDonion_history.c
  src/H5FDonion_history.h
  src/H5FDonion_index.c
  src/H5FDonion_index.h
  src/H5FDonion_priv.h
  src/H5FDpublic.h
  src/H5private.h
  src/H5trace.c
  src/Makefile.am
  src/hdf5.h
  test/CMakeLists.txt
  test/Makefile.am
  test/onion.c
  tools/lib/h5diff.c
  tools/lib/h5tools.c
  tools/lib/h5tools.h
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5repack/h5repack_main.c
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5diff/h5diffgentest.c
  tools/test/h5diff/testfiles/h5diff_900.txt
  tools/test/h5diff/testfiles/h5diff_901.txt
  tools/test/h5diff/testfiles/h5diff_902.txt
  tools/test/h5diff/testfiles/h5diff_onion_dset_1d.h5
  tools/test/h5diff/testfiles/h5diff_onion_dset_1d.h5.onion
  tools/test/h5diff/testfiles/h5diff_onion_dset_ext.h5
  tools/test/h5diff/testfiles/h5diff_onion_dset_ext.h5.onion
  tools/test/h5diff/testfiles/h5diff_onion_objs.h5
  tools/test/h5diff/testfiles/h5diff_onion_objs.h5.onion
  tools/test/h5diff/testh5diff.sh.in
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5dump/testh5dump.sh.in
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/h5repack.sh.in
  tools/test/h5repack/testfiles/onion.tst_onion_dset_1d.h5.ddl
  tools/test/h5repack/testfiles/onion.tst_onion_dset_ext.h5.ddl
  tools/test/h5repack/testfiles/onion.tst_onion_objs.h5.ddl
  tools/testfiles/tst_onion_dset_1d.ddl
  tools/testfiles/tst_onion_dset_1d.h5
  tools/testfiles/tst_onion_dset_1d.h5.onion
  tools/testfiles/tst_onion_dset_ext.ddl
  tools/testfiles/tst_onion_dset_ext.h5
  tools/testfiles/tst_onion_dset_ext.h5.onion
  tools/testfiles/tst_onion_objs.ddl
  tools/testfiles/tst_onion_objs.h5
  tools/testfiles/tst_onion_objs.h5.onion
  tools/testfiles/tst_onion_revision_count.ddl
Labels: enhancement

#1964 Corrects some bad format strings in the tools
  tools/lib/h5tools_dump.c
  tools/src/h5ls/h5ls.c
Labels: cleanup, merge to 1.12, merge to 1.10

#1986 Fix4 readme
  README.md
Labels: documentation

#1997 Fix Error examples
  src/H5Emodule.h
Labels: documentation

#2000 Correct target name for szaec lib
  config/cmake/CTestCustom.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
Labels: merge to 1.12, merge to 1.10, merge to 1.8

#2012 [1.12 Merge] Hdf5 1 12 develop merges
  doc/parallel-compression.md
  release_docs/RELEASE.txt
  src/H5Dio.c
  src/H5Fint.c
  src/H5Fsuper.c
Labels: merge

#2013 [1.10 Merge] Hdf5 1 10 develop merges
  doc/parallel-compression.md
  release_docs/RELEASE.txt
  src/H5Dio.c
  src/H5Fint.c
  src/H5Fsuper.c
Labels: merge

#2001 1.12 Correct target name for szaec lib - merge #2000
  config/cmake/CTestCustom.cmake
  config/cmake/scripts/HDF5options.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
Labels: merge

#2003 1.10 Correct target name for szaec lib - merge #2000
  config/cmake/CTestCustom.cmake
  config/cmake/scripts/HDF5options.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
  config/sanitizer/code-coverage.cmake
Labels: merge

#2002 1.8 Correct target name for szaec lib - merge #2000
  config/cmake/CTestCustom.cmake
  config/cmake/scripts/HDF5options.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
  config/sanitizer/code-coverage.cmake
Labels: merge

#2045 Removes ST from the list of debug packages (Autotools only)
  configure.ac
Labels: merge to 1.12, merge to 1.10

#2051 Quiets Automake rules in src directory
  src/H5detect.c
  src/Makefile.am
Labels: merge to 1.12, merge to 1.10

#2052 Quiets Fortran Autotools builds
  config/conclude_fc.am
Labels: merge to 1.12, merge to 1.10

#2047 GitHub workflow cleanup
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  test/mirror_vfd.c
Labels: merge to 1.12, merge to 1.10
