Repository HDFGroup/hdf5, pull requests merged in 2022-01, with the labels that each got.

#1335 Clarified H5Lexists documentation about changing behavior between 1.8 and 1.10
  src/H5Lpublic.h
Labels: documentation

#1345 fixed off-by-one error in h5fget_name_f, HDFFV-11290
  fortran/src/H5Ff.c
  fortran/test/tH5F.F90
Labels: bug

#1321 Documentation fixes right in time for the holidays
  MANIFEST
  doxygen/dox/About.dox
  doxygen/dox/Glossary.dox
  doxygen/dox/Overview.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/hdf5doxy_layout.xml
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5FDmpio.h
  src/H5Fpublic.h
  src/H5Pmodule.h
  src/H5Ppublic.h
Labels: documentation

#1360 1.12 Merge cmake custom command changes
  src/CMakeLists.txt
Labels: merge

#1371 Merge Update the java slf4j logging jars to latest 1.7.33
  .gitattributes
  CMakeLists.txt
  MANIFEST
  config/cmake/hdf5-config.cmake.in
  java/examples/datasets/JavaDatasetExample.sh.in
  java/examples/datasets/Makefile.am
  java/examples/datatypes/JavaDatatypeExample.sh.in
  java/examples/datatypes/Makefile.am
  java/examples/groups/JavaGroupExample.sh.in
  java/examples/groups/Makefile.am
  java/examples/intro/JavaIntroExample.sh.in
  java/examples/intro/Makefile.am
  java/lib/ext/slf4j-nop-1.7.25.jar
  java/lib/ext/slf4j-nop-1.7.33.jar
  java/lib/ext/slf4j-simple-1.7.25.jar
  java/lib/ext/slf4j-simple-1.7.33.jar
  java/lib/slf4j-api-1.7.25.jar
  java/lib/slf4j-api-1.7.33.jar
  java/src/Makefile.am
  java/test/Makefile.am
  java/test/junit.sh.in
Labels: merge

#1362 1.8 Merge cmake custom command changes
  src/CMakeLists.txt
Labels: merge

#1361 1.10 Merge cmake custom command changes
  src/CMakeLists.txt
Labels: merge

#1364 1.10 Merge various cleanup java test, test files, comments
  java/examples/datasets/H5Ex_D_Sofloat.java
  java/examples/datasets/H5Ex_D_UnlimitedMod.java
  java/examples/groups/H5Ex_G_Corder.java
  java/examples/testfiles/examples.datasets.H5Ex_D_Sofloat.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/exceptions/HDF5LibraryException.java
  java/src/hdf/hdf5lib/package-info.java
  java/src/hdf/hdf5lib/structs/H5F_info2_t.java
  java/test/TestH5P.java
  java/test/TestH5Pfapl.java
  java/test/TestH5Plist.java
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
Labels: merge

#1377 1.10 Fix cmake dynamic analysis on windows
  config/sanitizer/code-coverage.cmake
  config/sanitizer/sanitizers.cmake
Labels: merge

#1378 1.8 Fix cmake dynamic analysis on windows
  config/sanitizer/code-coverage.cmake
  config/sanitizer/sanitizers.cmake
Labels: merge

#1374 1.12 Fix cmake dynamic analysis on windows
  config/sanitizer/code-coverage.cmake
  config/sanitizer/sanitizers.cmake
Labels: merge

#1407 1.12 Merge Update code owners file with more names #1386
  .github/CODEOWNERS
Labels: merge

#1404 1 12 Remove const from the argv tools/tests main sig. #1390
  hl/tools/h5watch/extend_dset.c
  hl/tools/h5watch/h5watch.c
  src/H5private.h
  src/H5system.c
  test/flushrefresh.c
  test/swmr_addrem_writer.c
  test/swmr_generator.c
  test/swmr_reader.c
  test/swmr_remove_reader.c
  test/swmr_remove_writer.c
  test/swmr_sparse_reader.c
  test/swmr_sparse_writer.c
  test/swmr_start_write.c
  test/swmr_writer.c
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5diff/h5diff_common.h
  tools/src/h5diff/h5diff_main.c
  tools/src/h5diff/ph5diff_main.c
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump_ddl.c
  tools/src/h5format_convert/h5format_convert.c
  tools/src/h5import/h5import.c
  tools/src/h5jam/h5jam.c
  tools/src/h5jam/h5unjam.c
  tools/src/h5ls/h5ls.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5clear.c
  tools/src/misc/h5debug.c
  tools/src/misc/h5mkgrp.c
  tools/test/h5dump/binread.c
  tools/test/h5jam/getub.c
  tools/test/h5jam/tellub.c
  tools/test/perform/pio_standalone.c
  tools/test/perform/pio_standalone.h
  tools/test/perform/sio_standalone.c
  tools/test/perform/sio_standalone.h
  tools/test/perform/zip_perf.c
Labels: merge

#1406 1 8 Remove const from the argv tools/tests main sig. #1390
  tools/h5copy/h5copy.c
  tools/h5diff/h5diff_common.c
  tools/h5diff/h5diff_common.h
  tools/h5diff/h5diff_main.c
  tools/h5diff/ph5diff_main.c
  tools/h5dump/binread.c
  tools/h5dump/h5dump.c
  tools/h5jam/getub.c
  tools/h5jam/h5jam.c
  tools/h5jam/h5unjam.c
  tools/h5jam/tellub.c
  tools/h5ls/h5ls.c
  tools/h5repack/h5repack_main.c
  tools/h5stat/h5stat.c
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/misc/h5mkgrp.c
  tools/perform/pio_perf.c
  tools/perform/pio_standalone.c
  tools/perform/pio_standalone.h
  tools/perform/sio_perf.c
  tools/perform/sio_standalone.c
  tools/perform/sio_standalone.h
Labels: merge

#1409 1.8 Merge Update code owners file with more names #1386
  .github/CODEOWNERS
Labels: merge

#1408 1.10 Merge Update code owners file with more names #1386
  .github/CODEOWNERS
Labels: merge

#1405 1 10 Remove const from the argv tools/tests main sig. #1390
  hl/tools/h5watch/extend_dset.c
  hl/tools/h5watch/h5watch.c
  src/H5private.h
  src/H5system.c
  test/flushrefresh.c
  test/swmr_addrem_writer.c
  test/swmr_generator.c
  test/swmr_reader.c
  test/swmr_remove_reader.c
  test/swmr_remove_writer.c
  test/swmr_sparse_reader.c
  test/swmr_sparse_writer.c
  test/swmr_start_write.c
  test/swmr_writer.c
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5diff/h5diff_common.h
  tools/src/h5diff/h5diff_main.c
  tools/src/h5diff/ph5diff_main.c
  tools/src/h5dump/h5dump.c
  tools/src/h5format_convert/h5format_convert.c
  tools/src/h5import/h5import.c
  tools/src/h5jam/h5jam.c
  tools/src/h5jam/h5unjam.c
  tools/src/h5ls/h5ls.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5clear.c
  tools/src/misc/h5debug.c
  tools/src/misc/h5mkgrp.c
  tools/test/h5dump/binread.c
  tools/test/h5jam/getub.c
  tools/test/h5jam/tellub.c
  tools/test/perform/pio_standalone.c
  tools/test/perform/pio_standalone.h
  tools/test/perform/sio_standalone.c
  tools/test/perform/sio_standalone.h
  tools/test/perform/zip_perf.c
Labels: merge
