Repository HDFGroup/hdf5, pull requests merged in 2022-07, with the labels that each got.

#1841 Add datasets UG chapter, plus fix doxygen refs
  doxygen/dox/Specifications.dox
  doxygen/img/Dsets_NbitFloating1.gif
  doxygen/img/Dsets_NbitFloating2.gif
  doxygen/img/Dsets_NbitInteger1.gif
  doxygen/img/Dsets_NbitInteger2.gif
  doxygen/img/Dsets_fig1.gif
  doxygen/img/Dsets_fig10.gif
  doxygen/img/Dsets_fig11.gif
  doxygen/img/Dsets_fig12.gif
  doxygen/img/Dsets_fig2.gif
  doxygen/img/Dsets_fig21.GIF
  doxygen/img/Dsets_fig3.gif
  doxygen/img/Dsets_fig4.gif
  doxygen/img/Dsets_fig5.gif
  doxygen/img/Dsets_fig6.gif
  doxygen/img/Dsets_fig7.gif
  doxygen/img/Dsets_fig8.gif
  doxygen/img/Dsets_fig9.gif
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/hdf/hdf5lib/HDF5GroupInfo.java
  src/H5Dmodule.h
  src/H5Gpublic.h
  src/H5Tmodule.h
  src/H5Zpublic.h
Labels: documentation

#1854 Updated vfd swmr and reference rfcs
  doxygen/aliases
  doxygen/dox/RFC.dox
Labels: documentation

#1856 1.12 HDFFV-11310 implement JNI VL support for primitive types
  config/sanitizer/code-coverage.cmake
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/jni/h5aImp.c
  java/src/jni/h5aImp.h
  java/src/jni/h5dImp.c
  java/src/jni/h5dImp.h
  java/src/jni/h5util.c
  java/src/jni/h5util.h
  java/src/jni/nativeData.c
  java/test/TestH5A.java
  java/test/TestH5D.java
  java/test/TestH5R.java
  java/test/testfiles/JUnit-TestH5A.txt
  java/test/testfiles/JUnit-TestH5D.txt
  java/test/testfiles/JUnit-TestH5R.txt
  release_docs/RELEASE.txt
  tools/lib/h5tools_str.c
  tools/lib/h5tools_str.h
Labels: merge

#1858 1 10 HDFFV-11310 implement JNI VL support for primitive types
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/jni/h5aImp.c
  java/src/jni/h5aImp.h
  java/src/jni/h5dImp.c
  java/src/jni/h5dImp.h
  java/src/jni/h5util.c
  java/src/jni/h5util.h
  java/test/TestH5A.java
  java/test/TestH5D.java
  java/test/TestH5R.java
  java/test/testfiles/JUnit-TestH5A.txt
  java/test/testfiles/JUnit-TestH5D.txt
  java/test/testfiles/JUnit-TestH5R.txt
  release_docs/RELEASE.txt
Labels: merge

#1893 Cherry-pick of Autotools updates from develop (#1885)
  autogen.sh
  configure.ac
Labels: merge

#1890 1 10 Add utility JNI function for 1.10 style references
  java/src/hdf/hdf5lib/H5.java
  java/src/jni/h5rImp.c
  java/src/jni/h5rImp.h
  release_docs/RELEASE.txt
Labels: merge

#1897 Removes the ability to build h5perf and h5perf_serial in standalone mode
  release_docs/RELEASE.txt
  tools/lib/io_timer.h
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/pio_perf.h
  tools/src/h5perf/sio_perf.c
  tools/src/h5perf/sio_perf.h
  tools/test/perform/CMakeLists.txt
  tools/test/perform/CMakeTests.cmake
  tools/test/perform/build_h5perf_alone.sh
  tools/test/perform/build_h5perf_serial_alone.sh
  tools/test/perform/pio_standalone.c
  tools/test/perform/pio_standalone.h
  tools/test/perform/sio_standalone.c
  tools/test/perform/sio_standalone.h
Labels: WIP

#1920 Fixes an incorrect brief description for H5Dopen2()
  src/H5Dpublic.h
Labels: merge to 1.12, merge to 1.10

#1921 Port UG chapter 2 and fix LD bad ref warning
  doxygen/img/Pmodel_fig2.gif
  doxygen/img/Pmodel_fig3.gif
  doxygen/img/Pmodel_fig5_a.gif
  doxygen/img/Pmodel_fig5_b.gif
  doxygen/img/Pmodel_fig5_c.gif
  doxygen/img/Pmodel_fig5_d.gif
  doxygen/img/Pmodel_fig5_e.gif
  doxygen/img/Pmodel_fig6.gif
  hl/src/H5LDpublic.h
  src/H5module.h
Labels: documentation

#1924 Port UG chapter 1 and some cleanup
  doxygen/img/Dmodel_fig1.gif
  doxygen/img/Dmodel_fig10.gif
  doxygen/img/Dmodel_fig11_b.gif
  doxygen/img/Dmodel_fig12_a.gif
  doxygen/img/Dmodel_fig12_b.gif
  doxygen/img/Dmodel_fig14_a.gif
  doxygen/img/Dmodel_fig14_b.gif
  doxygen/img/Dmodel_fig14_c.gif
  doxygen/img/Dmodel_fig14_d.gif
  doxygen/img/Dmodel_fig2.gif
  doxygen/img/Dmodel_fig3_a.gif
  doxygen/img/Dmodel_fig3_c.gif
  doxygen/img/Dmodel_fig4_a.gif
  doxygen/img/Dmodel_fig4_b.gif
  doxygen/img/Dmodel_fig5.gif
  doxygen/img/Dmodel_fig6.gif
  doxygen/img/Dmodel_fig7_b.gif
  doxygen/img/Dmodel_fig8.gif
  doxygen/img/Dmodel_fig9.gif
  doxygen/img/Dsets_fig21.GIF
  doxygen/img/ftv2node.png
  doxygen/img/ftv2pnode.png
  src/H5Fmodule.h
  src/H5Pmodule.h
  src/H5module.h
Labels: documentation

#1925 Switches the tagged metadata list from a skip list to a hash table
  src/H5C.c
  src/H5Cpkg.h
  src/H5Ctag.c
  src/H5Ipkg.h
  src/H5private.h
Labels: merge to 1.12, merge to 1.10

#1928 Updates uthash and makes some tweaks
  src/H5Dmpio.c
  src/H5private.h
  src/uthash.h
Labels: merge to 1.12, merge to 1.10

#1930 Merge changes between branches
  doxygen/dox/RFC.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/UsersGuide.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  hl/src/H5LTpublic.h
  hl/src/H5PTpublic.h
Labels: documentation

#1922 Implement improved CMake fortran module folder from GH#1411
  config/cmake_ext_mod/HDFMacros.cmake
  config/libhdf5.fpc.in
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/Makefile.am
  fortran/src/h5fc.in
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/Makefile.am
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge to 1.12, merge to 1.10, merge to 1.8

#1934 Removes padding-right from Doxygen href tags
  doxygen/hdf5doxy.css
Labels: merge to 1.12, merge to 1.10

#1937 eliminate unnecessary errors in the error stack
  tools/lib/h5tools_str.c
  tools/lib/h5tools_str.h
Labels: merge

#1932 Misc clang production warning fixes
  src/H5Cimage.c
  src/H5FDmulti.c
  src/H5HLcache.c
  src/H5Tref.c
  src/uthash.h
  test/objcopy.c
  test/objcopy_ref.c
Labels: merge to 1.12, merge to 1.10

#1942 1.12 fortran module folder from GH#1411 #1922
  config/cmake_ext_mod/HDFMacros.cmake
  config/libhdf5.fpc.in
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/Makefile.am
  fortran/src/h5fc.in
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/Makefile.am
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#1944 1.8 fortran module folder from GH#1411 #1922
  MANIFEST
  config/cmake_ext_mod/HDFMacros.cmake
  config/libhdf5.fpc.in
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/Makefile.am
  fortran/src/h5fc.in
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/Makefile.am
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#1943 1.10 fortran module folder from GH#1411 #1922
  config/cmake_ext_mod/HDFMacros.cmake
  config/libhdf5.fpc.in
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/Makefile.am
  fortran/src/h5fc.in
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/Makefile.am
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#1949 Cleanup of mirror VFD test code
  test/mirror_vfd.c
  test/use_append_chunk_mirror.c
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_writer.c
Labels: cleanup, merge to 1.12, merge to 1.10

#1955 Fixes format string warnings in tselect w/ clang 14
  test/tselect.c
Labels: merge to 1.12, merge to 1.10

#1956 Fixes clang warnings in H5Tconv.c (long) double macros
  src/H5Tconv.c
Labels: merge to 1.12, merge to 1.10, merge to 1.8
