Repository HDFGroup/hdf5, pull requests merged in 2022-12, with the labels that each got.

#2273 Output should only be printed if verbose.
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack_copy.c
Labels: bug, merge to 1.12, merge to 1.10

#2246 Add text about release notes
  CONTRIBUTING.md
Labels: documentation

#2280 Correct requires setting for pkgconfig files
  c++/src/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
Labels: bug, merge to 1.12, merge to 1.10, merge to 1.8

#2285 1.8 Correct requires setting for pkgconfig files #2280
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  c++/src/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
  tools/h5dump/CMakeTests.cmake
Labels: merge

#2283 1.12 Correct requires setting for pkgconfig files #2280
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  c++/src/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
Labels: merge

#2293 Updated H5ES documentation
  src/H5ESpublic.h
Labels: documentation, merge to 1.12, merge to 1.14

#2286 Update windows worker compilers
  .github/workflows/main.yml
  bin/h5vers
  bin/release
  release_docs/RELEASE.txt
Labels: documentation

#2304 Update hdf5_header.html
  doxygen/hdf5_header.html
Labels: documentation

#2312 1.10: Brings the updated CI in from develop
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  test/mirror_vfd.c
Labels: merge

#2311 1.12: Brings the updated CI in from develop
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  test/mirror_vfd.c
Labels: merge

#2316 1.14: Fixes duplicated build mode in -Werror GitHub action names
  .github/workflows/main.yml
Labels: merge

#2317 1.14.0: Fixes duplicated build mode in -Werror GitHub action names
  .github/workflows/main.yml
Labels: merge

#2321 moved onion VFD to FAPL group
  src/H5FDonion.h
Labels: documentation

#2319 Only document Fortran functions
  doxygen/Doxyfile.in
Labels: documentation

#2320 Removed idioms and misc. text clean-up
  doxygen/dox/ReferenceManual.dox
Labels: documentation

#2074 Align arg types of H5D_chunk_iter_op_t with H5Dget_chunk_info
  src/H5D.c
  src/H5Dchunk.c
  src/H5Dpublic.h
  test/chunk_info.c
Labels: merge to 1.12, merge to 1.10, merge to 1.14

#2324 Fix doxygen warnings and remove javadocs
  doxygen/Doxyfile.in
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Accessibility.dox
  doxygen/dox/cookbook/Attributes.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/cookbook/Performance.dox
  doxygen/hdf5doxy_layout.xml
  fortran/src/H5Pff.F90
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  release_docs/RELEASE.txt
  src/H5Amodule.h
  src/H5Gmodule.h
  src/H5Lpublic.h
  src/H5Tpublic.h
  src/H5VLconnector_passthru.h
Labels: documentation

#2328 1.14: Brings the following changesets over from develop:
  doxygen/Doxyfile.in
  doxygen/dox/ReferenceManual.dox
  doxygen/hdf5_header.html
  release_docs/RELEASE.txt
  src/H5D.c
  src/H5Dchunk.c
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5FDonion.h
  src/H5Fint.c
  src/H5Lpublic.h
  src/H5VLnative_file.c
  test/CMakeTests.cmake
  test/chunk_info.c
  test/cve_2020_10812.h5
  test/tmisc.c
  tools/src/misc/h5debug.c
Labels: merge

#2330 1.14.0: Brings the following changesets over from develop:
  configure.ac
  doxygen/Doxyfile.in
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Accessibility.dox
  doxygen/dox/cookbook/Attributes.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/cookbook/Performance.dox
  doxygen/hdf5_header.html
  doxygen/hdf5doxy_layout.xml
  fortran/src/H5Pff.F90
  hl/tools/CMakeLists.txt
  hl/tools/Makefile.am
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5Amodule.h
  src/H5D.c
  src/H5Dchunk.c
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5FDonion.h
  src/H5Fint.c
  src/H5Gmodule.h
  src/H5Lpublic.h
  src/H5Tpublic.h
  src/H5VLconnector_passthru.h
  src/H5VLnative_file.c
  test/CMakeTests.cmake
  test/chunk_info.c
  test/cve_2020_10812.h5
  test/tmisc.c
  tools/src/misc/h5debug.c
Labels: merge

#2323 1.14 Fix some doxygen warnings
  doxygen/Doxyfile.in
  doxygen/dox/Overview.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Accessibility.dox
  doxygen/dox/cookbook/Attributes.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/cookbook/Performance.dox
  doxygen/hdf5doxy_layout.xml
  fortran/src/H5Pff.F90
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  release_docs/RELEASE.txt
  src/H5Amodule.h
  src/H5Gmodule.h
  src/H5Lpublic.h
  src/H5Tpublic.h
  src/H5VLconnector_passthru.h
Labels: documentation

#2335 1.14: Fix up the H5Pencode2 test for virtual layout. (#2325)
  test/enc_dec_plist.c
Labels: merge

#2336 1.14.0: Fix up the H5Pencode2 test for virtual layout. (#2325)
  test/enc_dec_plist.c
Labels: merge

#2338 1.14: Onion VFD header cleanup (#2337)
  src/H5FDonion.c
  src/H5FDonion.h
  src/H5FDonion_header.h
Labels: merge

#2339 1.14.0: Onion VFD header cleanup (#2337)
  src/H5FDonion.c
  src/H5FDonion.h
  src/H5FDonion_header.h
Labels: merge

#2341 1.14: Adds Doxygen VOL flag markup (#2340)
  src/H5VLpublic.h
Labels: merge

#2342 1.14.0: Adds Doxygen VOL flag markup (#2340)
  src/H5VLpublic.h
Labels: merge
