Repository HDFGroup/hdf5, pull requests merged in 2022-09, with the labels that each got.

#2093 1.10 Port "learn HDF5" tutorial to doxygen
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/ViewTools2.dox
  doxygen/dox/ViewToolsJPSS.dox
  doxygen/examples/high_level_menu.md
  doxygen/img/LBDsetSubRWProg.png
  doxygen/img/imgLBDsetCreate.gif
  doxygen/img/imgLBDsetSubRW11.png
  doxygen/img/imgLBDsetSubRW12.png
  doxygen/img/imgLBDsetSubRW31.png
  doxygen/img/imgLBDsetSubRW32.png
  doxygen/img/imgLBDsetSubRW33.png
  doxygen/img/imgLBFile.gif
  doxygen/img/imggrpcreate.gif
  doxygen/img/imggrpdsets.gif
  doxygen/img/imggrps.gif
  doxygen/img/tutr-lochk.png
  doxygen/img/tutr-lochks.png
  doxygen/img/tutr-locons.png
  hl/src/H5DOpublic.h
  hl/src/H5DSpublic.h
  hl/src/H5IMpublic.h
  hl/src/H5LTpublic.h
  hl/src/H5PTpublic.h
  hl/src/H5TBpublic.h
Labels: documentation

#2098 [1.12 Merge] Cleanup some warnings in Java JNI code (#2034)
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5util.c
Labels: merge

#2099 [1.10 Merge] Cleanup some warnings in Java JNI code (#2034)
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5util.c
Labels: merge

#2104 Use doxygen snippets for common tables
  doxygen/examples/tables/fileDriverLists.dox
  doxygen/examples/tables/propertyLists.dox
  src/H5Dmodule.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5Pmodule.h
  src/H5Ppublic.h
Labels: documentation, merge to 1.12, merge to 1.10

#2107 Update examples reference to single-source version 2.0.1
  bin/release
  config/cmake/HDF5_Examples.cmake.in
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/README_HDF5_CMake
Labels: merge to 1.12, merge to 1.10, merge to 1.8

#2114 Add missing windows include/lib configure for StrStrIA
  config/cmake/ConfigureChecks.cmake
Labels: bug

#2108 1.12 Update examples reference to single-source version 2.0.1
  bin/release
  config/cmake/HDF5_Examples.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/README_HDF5_CMake
Labels: merge

#2123 Restructure ref manual presentation
  configure.ac
  doxygen/Doxyfile.in
  doxygen/dox/PredefinedDatatypeTables.dox
  doxygen/dox/RFC.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/examples/menus/core_menu.md
  doxygen/examples/menus/fortran_menu.md
  doxygen/examples/menus/high_level_menu.md
  doxygen/examples/menus/java_menu.md
  doxygen/examples/tables/predefinedDatatypes.dox
  doxygen/hdf5doxy_layout.xml
  src/H5Tmodule.h
Labels: documentation

#2122 Fixed an issue that could occur when combining hyperslab selections
  release_docs/RELEASE.txt
  src/H5Shyper.c
  test/th5s.c
Labels: merge to 1.12, merge to 1.10
