Repository HDFGroup/hdf5, pull requests merged in 2023-08, with the labels that each got.

#3317 Update release schedule
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Task

#3318 Update README.md w/ 1.4.3 info
  README.md
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Task

#3245 Switch parallel compression to use vector I/O
  src/H5Dmpio.c
  src/H5Fio.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Improvement

#3312 Fix incorrect error check in H5Ofill.c for undefined fill values
  release_docs/RELEASE.txt
  src/H5Ofill.c
  test/fillval.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#3314 Fix H5Otoken_to_str call in h5dump and other minor cleanup
  src/H5Dint.c
  tools/lib/h5tools_dump.c
  tools/lib/h5tools_str.c
  tools/src/h5dump/h5dump_ddl.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Type - Bug

#3315 Fix loading plugin fails with missing directory GH issue #3248
  release_docs/RELEASE.txt
  src/H5PLpath.c
  test/filter_plugin.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#3321 Update files to skip list and ignore_words_list
  .github/workflows/codespell.yml
  test/API/tfile.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Build

#3324 Fix loading plugin fails with missing directory GH issue #3248
  release_docs/RELEASE.txt
  src/H5PLint.c
  src/H5PLpath.c
  src/H5PLplugin_cache.c
  src/H5PLpublic.h
  test/filter_plugin.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Improvement, Branch - 1.12

#3325 Fix loading plugin fails with missing directory GH issue #3248
  release_docs/RELEASE.txt
  src/H5PLint.c
  src/H5PLpath.c
  src/H5PLplugin_cache.c
  src/H5PLpublic.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Improvement, Branch - 1.10

#3320 Windows runtime items go into the bin folder
  java/src/jni/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Java, Component - Build, Type - Bug

#3327 Switch parallel compression to use vector I/O (#3245)
  src/H5Dmpio.c
  src/H5Fio.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Branch - 1.14

#3328 Fix incorrect error check in H5Ofill.c for undefined fill values (#3312)
  release_docs/RELEASE.txt
  src/H5Ofill.c
  test/fillval.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.14

#3329 Fix H5Otoken_to_str call in h5dump and other minor cleanup (#3314)
  src/H5Dint.c
  tools/lib/h5tools_dump.c
  tools/lib/h5tools_str.c
  tools/src/h5dump/h5dump_ddl.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Tools, Type - Improvement, Branch - 1.14

#3332 A couple of documentation items to fix
  .clang-format
  doc/getting-started-with-hdf5-development.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3331 Fix h5repack for variable-length datatyped datasets
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack_copy.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#3330 Fix CVE-2018-11202
  release_docs/RELEASE.txt
  src/H5Dchunk.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#3336 Fix CVE-2018-13867
  release_docs/RELEASE.txt
  src/H5HLcache.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#3333 Fix h5repack for variable-length datatyped datasets (#3331)
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack_copy.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug, Branch - 1.14

#3340 Fix assertion failure in H5D__mpio_collective_filtered_vec_io
  src/H5Dmpio.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#3350 Fix assertion failure in H5D__mpio_collective_filtered_vec_io (#3340)
  src/H5Dmpio.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.14

#3354 Merges from develop Aug 2-4
  java/src/jni/CMakeLists.txt
  release_docs/RELEASE.txt
  src/H5Dchunk.c
  src/H5HLcache.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Branch - 1.14

#3352 Make h5dump spacing consistent when printing VLEN datatype (#3351)
  tools/lib/h5tools_dump.c
  tools/testfiles/tarray6.ddl
  tools/testfiles/tarray7.ddl
  tools/testfiles/tempty.ddl
  tools/testfiles/tfill.ddl
  tools/testfiles/tmultifile.ddl
  tools/testfiles/treference.ddl
  tools/testfiles/tvldtypes1.ddl
  tools/testfiles/tvldtypes2.ddl
  tools/testfiles/tvldtypes3.ddl
  tools/testfiles/tvldtypes4.ddl
  tools/testfiles/tvldtypes5.ddl
Labels: Merge, Priority - 3. Low 🔽, Component - Tools, Type - Task, Branch - 1.14

#3319 Fix for the bug exposed from running test/set_extent.c when selection…
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Defl.c
  src/H5Dscatgath.c
  src/H5Ppublic.h
  test/set_extent.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Testing

#3341 Add Fortran ES module to deploy list
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#3342 Add Fortran H5ES module to deploy list
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Fortran, Branch - 1.14

#3359 Merge 1 14 post0804
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Defl.c
  src/H5Dscatgath.c
  src/H5Ppublic.h
  test/set_extent.c
  testpar/t_file.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Component - Testing, Branch - 1.14

#3222 Implementation of the mpio driver with selection I/O.
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5FD.c
  src/H5FDdevelop.h
  src/H5FDint.c
  src/H5FDmpio.c
  src/H5FDprivate.h
  test/select_io_dset.c
  testpar/t_coll_chunk.c
  testpar/t_dset.c
  testpar/t_select_io_dset.c
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Improvement

#3361 Work around a testphdf5 failure on Cray MPICH machines
  release_docs/RELEASE.txt
  testpar/t_file.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#3362 Work around a testphdf5 failure on Cray MPICH machines (#3361)
  release_docs/RELEASE.txt
  testpar/t_file.c
Labels: Component - Parallel, Component - Testing, Branch - 1.14

#3365 set H5_PAC_C_MAX_REAL_PRECISION default to 0 when cross compiling with
  config/cmake/ConfigureChecks.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Branch - 1.14

#3364 set H5_PAC_C_MAX_REAL_PRECISION default to 0 when cross compiling with
  config/cmake/ConfigureChecks.cmake
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build

#3366 Merges from 1.14 Aug 4-9
  config/cmake/ConfigureChecks.cmake
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  release_docs/RELEASE.txt
  release_docs/USING_HDF5_VS.txt
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Defl.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dscatgath.c
  src/H5FD.c
  src/H5FDdevelop.h
  src/H5FDint.c
  src/H5FDmpio.c
  src/H5FDprivate.h
  src/H5Ppublic.h
  test/select_io_dset.c
  test/set_extent.c
  testpar/t_coll_chunk.c
  testpar/t_dset.c
  testpar/t_file.c
  testpar/t_select_io_dset.c
  testpar/t_vfd.c
  tools/lib/h5tools_dump.c
  tools/testfiles/tarray6.ddl
  tools/testfiles/tarray7.ddl
  tools/testfiles/tempty.ddl
  tools/testfiles/tfill.ddl
  tools/testfiles/tmultifile.ddl
  tools/testfiles/treference.ddl
  tools/testfiles/tvldtypes1.ddl
  tools/testfiles/tvldtypes2.ddl
  tools/testfiles/tvldtypes3.ddl
  tools/testfiles/tvldtypes4.ddl
  tools/testfiles/tvldtypes5.ddl
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Component - Testing, Component - Build

#3369 Add the 1.14 CVE matrix file
  CVE_list_1_14.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - New Feature, Branch - 1.14

#3370 Add CVE matrix
  CVE_list_1_14.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - New Feature, Branch - 1.14

#3371 Add a 1.14.3 column to the CVE matrix
  CVE_list_1_14.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement, Branch - 1.14

#3378 Correct cmake script
  config/cmake/examples/HDF5_Examples.cmake.in
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#3383 Clear RELEASE.txt and copy 1.14.2 RELEASE.txt to HISTORY-1.14.txt after
  release_docs/HISTORY-1_14.txt
  release_docs/RELEASE.txt
Labels: Component - Documentation, Branch - 1.14

#3377 Correct script
  config/cmake/examples/HDF5_Examples.cmake.in
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#3384 Correct CI settings
  .github/workflows/tarball.yml
  CMakePresets.json
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3385 restore CI tarball name prefix to match bin/release
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3386 Use plugins master with overrides
  CMakePresets.json
  bin/release
  config/cmake/cacheinit.cmake
  doxygen/dox/LearnBasics.dox
Labels: Merge, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Improvement, Branch - 1.14

#3387 Fix assertion failure during file close on error
  release_docs/RELEASE.txt
  src/H5C.c
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3388 Fix compile failures with H5C_DO_MEMORY_SANITY_CHECKS enabled
  src/H5Centry.c
  src/H5Cimage.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Task

#3389 Fix valgrind warning about write of uninitialized bytes
  src/H5FScache.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Task

#3390 Fix valgrind warning about write of uninitialized bytes in ScaleOffse…
  src/H5Zscaleoffset.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Task

#3391 Update presets, examples uncompress, szip cache
  .gitattributes
  CMakeInstallation.cmake
  CMakePresets.json
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Component - Misc

#3394 Fix serial to parallel chunked dataset file space allocation bug
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug

#3406 Fix for CVE-2016-4332
  release_docs/RELEASE.txt
  src/H5Omessage.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#3407 Fix ph5diff tests for MPIEXEC_MAX_NUMPROCS=1
  examples/CMakeTests.cmake
  tools/src/h5diff/ph5diff_main.c
  tools/test/h5diff/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Component - Parallel, Type - Bug

#3409 Update build script to match change in presets
  .github/workflows/cmake-ctest.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Branch - 1.12

#3392 Update presets, examples uncompress, szip cache
  .gitattributes
  .github/workflows/cmake-ctest.yml
  CMakeInstallation.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/ConfigureChecks.cmake
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Improvement, Branch - 1.14, Component - Misc

#3410 Fix another build folder name
  .github/workflows/cmake-ctest.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Branch - 1.14

#3411 Fix another build folder name
  .github/workflows/cmake-ctest.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Branch - 1.12

#3412 Enable szip by default in Autotools
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3414 Re-enable SZIP default to ON
  CMakeFilters.cmake
  CMakePresets.json
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3368 Fix Heap-buffer-overflow WRITE in H5MM_memcpy
  release_docs/RELEASE.txt
  src/H5Oalloc.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2977 Add Intel oneAPI actions (#2949)
  .github/workflows/linux-icx-auto.yml
  .github/workflows/linux-icx.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3416 Add RELEASE.txt entry for compound performance regression fix (#3376)
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#3420 Remove gubbins comment
  testpar/API/t_chunk_alloc.c
  testpar/t_chunk_alloc.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3353 Add other types and full type to enum/str/vlen dataformat for structblock[begin/end]
  tools/lib/h5tools.h
  tools/lib/h5tools_dump.c
Labels: Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#3419 Avoid H5Ocopy in h5repack for variable-length string types
  tools/src/h5repack/h5repack_copy.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#3422 Fix an issue with use of uninitialized memory in trefer_deprec.c test
  test/trefer_deprec.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#3358 Add other types and full type to enum/str/vlen dataformat for structblock[begin/end]
  tools/lib/h5tools.h
  tools/lib/h5tools_dump.c
Labels: Merge, Priority - 3. Low 🔽, Component - Tools, Type - Improvement, Branch - 1.14

#3413 Add parallel examples in doxygen
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/img/pchunk_figa.gif
  doxygen/img/pchunk_figb.gif
  doxygen/img/pchunk_figc.gif
  doxygen/img/pchunk_figd.gif
  doxygen/img/pcont_hy_figa.gif
  doxygen/img/pcont_hy_figb.gif
  doxygen/img/pcont_hy_figc.gif
  doxygen/img/pcont_hy_figd.gif
  doxygen/img/ppatt_figa.gif
  doxygen/img/ppatt_figb.gif
  doxygen/img/ppatt_figc.gif
  doxygen/img/ppatt_figd.gif
  doxygen/img/preg_figa.gif
  doxygen/img/preg_figb.gif
  doxygen/img/preg_figc.gif
  doxygen/img/preg_figd.gif
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement, Type - New Feature

#3425 Remove extraneous "33" in RELEASE.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#3424 Fix possible performance regression introduced with in-place type conversion in 1.14.2
  release_docs/RELEASE.txt
  src/H5Dscatgath.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.14

#3418 Revise file close assertion failure fix
  src/H5C.c
  src/H5Cimage.c
  src/H5Fint.c
  src/H5Fsuper.c
  src/H5MF.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Bug

#3426 Remove intel oneapi warning
  src/H5Dio.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3427 Fix for CVE-2018-15671
  src/H5Gint.c
  tools/src/h5dump/h5dump_ddl.c
  tools/testfiles/tgroup-2.ddl
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Type - Bug

#3428 Match function call and VRFY() output
  testpar/t_file.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Parallel, Type - Improvement

#3430 Fix the Fortran extension used in example links
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
Labels: Priority - 0. Blocker ⛔, Component - Documentation

#3432 Put H5T_CONV_ab macros in do..while loops
  .clang-format
  src/H5Tconv.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2382 Convert some H5MM calls to standard C equivalents
  config/cmake/HDFCompilerFlags.cmake
  configure.ac
  src/H5CS.c
  src/H5Dchunk.c
  src/H5Dmpio.c
  src/H5Dscatgath.c
  src/H5FDonion.c
  src/H5FDonion_header.c
  src/H5FDonion_history.c
  src/H5FDonion_index.c
  src/H5FDros3.c
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FL.c
  src/H5MM.c
  src/H5MMprivate.h
  src/H5Olayout.c
  src/H5RS.c
  src/H5Tinit_float.c
  src/H5Tref.c
  src/H5Tvlen.c
  src/H5encode.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3434 Add 1.14.4 to the release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Task

#3431 Output stderr file in CMake testing on failure
  config/cmake/runTest.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3436 Misc normalization with develop
  .clang-format
  .github/CODEOWNERS
  .github/workflows/codespell.yml
  .github/workflows/main.yml
  Makefile.am
  bin/genparser
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/libhdf5.settings.cmake.in
  config/gnu-warnings/developer-general
  config/intel-warnings/developer-general
  config/sanitizer/README.md
  configure.ac
  hl/src/H5LTanalyze.c
  hl/src/H5LTparse.c
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_8_0-1_10_0.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - High-Level Library, Component - Build, Type - Task, Branch - 1.10

#3438 sync cmake and examples changes
  .gitattributes
  .github/workflows/cmake-ctest.yml
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePresets.json
  bin/release
  config/cmake-presets/hidden-presets.json
  config/cmake/cacheinit.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  java/examples/datasets/CMakeLists.txt
  java/examples/datasets/JavaDatasetExample.sh.in
  java/examples/datasets/Makefile.am
  java/examples/datatypes/JavaDatatypeExample.sh.in
  java/examples/datatypes/Makefile.am
  java/examples/groups/JavaGroupExample.sh.in
  java/examples/groups/Makefile.am
  java/examples/intro/JavaIntroExample.sh.in
  java/examples/intro/Makefile.am
  java/lib/ext/slf4j-nop-1.7.33.jar
  java/lib/ext/slf4j-nop-2.0.6.jar
  java/lib/ext/slf4j-simple-1.7.33.jar
  java/lib/ext/slf4j-simple-2.0.6.jar
  java/lib/slf4j-api-1.7.33.jar
  java/lib/slf4j-api-2.0.6.jar
  java/src/Makefile.am
  java/src/hdf/hdf5lib/H5.java
  java/src/jni/CMakeLists.txt
  java/test/Makefile.am
  java/test/junit.sh.in
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Branch - 1.10

#3433 Add Intel oneAPI badges
  README.md
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3442 Sync Java changes - particularly VL handling
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5util.c
  java/src/jni/h5util.h
  java/test/TestH5A.java
  java/test/TestH5D.java
  java/test/testfiles/JUnit-TestH5A.txt
  java/test/testfiles/JUnit-TestH5D.txt
Labels: Priority - 2. Medium ⏹, Component - Java, Type - Improvement, Branch - 1.10

#3443 Correct GIF option notes
  config/cmake/libhdf5.settings.cmake.in
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug, Branch - 1.10

#3445 Add a CVE regression test action
  .github/workflows/cve.yml
  README.md
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - New Feature

#3444 Add HDF5 1.10 CVE vulnerability matrix
  CVE_list_1_10.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task, Branch - 1.10

#3448 Reverts the CVE fixes
  release_docs/RELEASE.txt
  src/H5Dbtree.c
  src/H5Dchunk.c
  src/H5Fsuper_cache.c
  src/H5Gint.c
  src/H5HLcache.c
  src/H5Omessage.c
  tools/src/h5dump/h5dump_ddl.c
  tools/testfiles/tgroup-2.ddl
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Branch - 1.10

#3451 Fix CVE-2016-4332
  release_docs/RELEASE.txt
  src/H5Omessage.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.10

#3449 Disable SZIP for Intel oneAPI Action
  .github/workflows/linux-icx-auto.yml
  .github/workflows/linux-icx.yml
Labels: Component - Testing

#3450 Update VOL CMake for REST VOL
  CMakeVOL.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3452 Fix CVE-2018-11202
  release_docs/RELEASE.txt
  src/H5Dchunk.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.10

#3478 Revert "Fix CVE-2018-11202 (#3452)"
  release_docs/RELEASE.txt
  src/H5Dchunk.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.10
