Repository HDFGroup/hdf5, pull requests merged in 2023-03, with the labels that each got.

#2492 1.14 Add fetchcontent for compression libs and fix cmake config #2487
  .github/workflows/codespell.yml
  .github/workflows/main.yml
  CMakeFilters.cmake
  CMakeLists.txt
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/LIBAEC/CPack.Info.plist.in
  config/cmake/LIBAEC/config.h.in
  config/cmake/LIBAEC/libaec-config-version.cmake.in
  config/cmake/LIBAEC/libaec-config.cmake.in
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIB/CPack.Info.plist.in
  config/cmake/ZLIB/zconf.h.in
  config/cmake/ZLIB/zlib-config-version.cmake.in
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/toolchain/GCC.cmake
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#2493 1.12 Add fetchcontent for compression libs and fix cmake config #2487
  .github/workflows/codespell.yml
  .github/workflows/main.yml
  CMakeFilters.cmake
  CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/LIBAEC/CPack.Info.plist.in
  config/cmake/LIBAEC/config.h.in
  config/cmake/LIBAEC/libaec-config-version.cmake.in
  config/cmake/LIBAEC/libaec-config.cmake.in
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIB/CPack.Info.plist.in
  config/cmake/ZLIB/zconf.h.in
  config/cmake/ZLIB/zlib-config-version.cmake.in
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
  config/cmake_ext_mod/HDFMacros.cmake
  config/sanitizer/tools.cmake
  config/toolchain/GCC.cmake
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#2503 1.14 Merge doxygen plist tables changes #2470 from develop
  doxygen/dox/VOLConnGuide.dox
  doxygen/examples/tables/propertyLists.dox
  doxygen/hdf5doxy_layout.xml
  java/src/hdf/hdf5lib/callbacks/package-info.java
  release_docs/RELEASE.txt
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5FDhdfs.h
  src/H5Gpublic.h
  src/H5Lpublic.h
  src/H5Mpublic.h
  src/H5Pmodule.h
Labels: merge

#2505 1.12 Merge doxygen plist tables changes #2470 from develop
  doc/branches-explained.md
  doxygen/Doxyfile.in
  doxygen/dox/MetadataCachingInHDF5.dox
  doxygen/dox/Overview.dox
  doxygen/dox/PredefinedDatatypeTables.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Accessibility.dox
  doxygen/dox/cookbook/Attributes.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/cookbook/Performance.dox
  doxygen/dox/high_level/extension.dox
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
  doxygen/examples/H5R_examples.c
  doxygen/examples/VFL.html
  doxygen/examples/menus/core_menu.md
  doxygen/examples/menus/fortran_menu.md
  doxygen/examples/menus/high_level_menu.md
  doxygen/examples/menus/java_menu.md
  doxygen/examples/tables/fileDriverLists.dox
  doxygen/examples/tables/predefinedDatatypes.dox
  doxygen/examples/tables/propertyLists.dox
  doxygen/examples/tables/volAPIs.dox
  doxygen/hdf5_header.html
  doxygen/hdf5doxy_layout.xml
  src/H5Amodule.h
  src/H5Dmodule.h
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5FDmpio.h
  src/H5FDpublic.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5Gpublic.h
  src/H5Lpublic.h
  src/H5MMpublic.h
  src/H5Mpublic.h
  src/H5Opublic.h
  src/H5PLextern.h
  src/H5PLmodule.h
  src/H5PLpublic.h
  src/H5Pmodule.h
  src/H5Ppublic.h
  src/H5Tmodule.h
  src/H5Tpublic.h
  src/H5VLmodule.h
Labels: merge

#2506 1.10 Merge doxygen plist tables changes #2470 from develop
  doxygen/Doxyfile.in
  doxygen/dox/MetadataCachingInHDF5.dox
  doxygen/dox/Overview.dox
  doxygen/dox/PredefinedDatatypeTables.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Accessibility.dox
  doxygen/dox/cookbook/Attributes.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/cookbook/Performance.dox
  doxygen/dox/high_level/extension.dox
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
  doxygen/examples/VFL.html
  doxygen/examples/menus/core_menu.md
  doxygen/examples/menus/fortran_menu.md
  doxygen/examples/menus/high_level_menu.md
  doxygen/examples/menus/java_menu.md
  doxygen/examples/tables/fileDriverLists.dox
  doxygen/examples/tables/predefinedDatatypes.dox
  doxygen/examples/tables/propertyLists.dox
  doxygen/hdf5_header.html
  doxygen/hdf5doxy_layout.xml
  src/H5ACpublic.h
  src/H5Dmodule.h
  src/H5Dpublic.h
  src/H5Emodule.h
  src/H5FDmpio.h
  src/H5FDpublic.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5Gpublic.h
  src/H5MMpublic.h
  src/H5Pmodule.h
  src/H5Ppublic.h
  src/H5Tmodule.h
Labels: merge

#2472 Missing or misplaced entries in API reference tables #2470
  doxygen/dox/Overview.dox
  doxygen/examples/tables/propertyLists.dox
  src/H5Pmodule.h
Labels: documentation

#2511 Fix an errant bracket that confused formatter
  src/H5C.c
Labels: Component - C Library

#2513 Remove redundant and flawed documentation of H5D_chunk_iter_op_t from…
  src/H5D.c
Labels: Merge, Branch - 1.10

#2521 Fix new codespell issues
  .github/workflows/codespell.yml
  config/toolchain/aarch64.cmake
  configure.ac
  doxygen/dox/LearnBasics2.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/IOFlow.html
  fortran/src/H5Pf.c
  fortran/test/tH5O_F03.F90
  src/H5FScache.c
  src/H5PLpath.c
  src/H5S.c
  testpar/t_bigio.c
Labels: Type - Improvement

#2512 Remove redundant and flawed documentation of H5D_chunk_iter_op_t from…
  src/H5D.c
Labels: Merge - To 1.10, Merge - To 1.14

#2519 Fix H5Dchunk_iter doxygen example, cherry-pick of ef3bed6
  doxygen/examples/H5D_examples.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Component - Documentation

#2517 docs: Replace idiom in ReferenceManual
  doxygen/dox/ReferenceManual.dox
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Component - Documentation

#2516 docs: in -> out (#2514)
  src/H5Ppublic.h
Labels: Merge - To 1.10, Merge - To 1.14, Component - Documentation

#2522 Elaborate how cd_values get stored
  src/H5Ppublic.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#2525 Fix 1.10 new codespell issues (#2521)
  .github/workflows/codespell.yml
  bin/genparser
  config/toolchain/aarch64.cmake
  configure.ac
  doxygen/dox/LearnBasics2.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/IOFlow.html
  fortran/src/H5Pf.c
  fortran/test/tH5O_F03.F90
  src/H5FScache.c
  src/H5PLpath.c
  src/H5S.c
  testpar/t_bigio.c
Labels: Branch - 1.10

#2520 Fix H5Dchunk_iter doxygen example, hdf5_1_10
  doxygen/examples/H5D_examples.c
Labels: Merge, Component - Documentation, Branch - 1.10

#2530 Fix new codespell issues (#2521)
  .github/workflows/codespell.yml
  bin/genparser
  config/toolchain/aarch64.cmake
  configure.ac
  doxygen/dox/LearnBasics2.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/IOFlow.html
  fortran/src/H5Pf.c
  fortran/test/tH5O_F03.F90
  src/H5FScache.c
  src/H5PLpath.c
  src/H5S.c
  testpar/t_bigio.c
Labels: Merge, Component - Documentation, Branch - 1.12

#2533 Fix new codespell issues (#2521)
  .github/workflows/codespell.yml
  config/toolchain/aarch64.cmake
  configure.ac
  doxygen/dox/LearnBasics2.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/IOFlow.html
  fortran/src/H5Pf.c
  fortran/test/tH5O_F03.F90
  src/H5FScache.c
  src/H5PLpath.c
  src/H5S.c
  testpar/t_bigio.c
Labels: Merge, Component - Documentation, Branch - 1.14

#2532 docs: in->out (#2514)
  src/H5Ppublic.h
Labels: Merge, Component - Documentation, Branch - 1.10

#2524 Addressed various Doxygen grammar issues.
  doxygen/aliases
  doxygen/examples/H5Pget_metadata_read_attempts.2.c
  doxygen/examples/H5Pget_metadata_read_attempts.3.c
  doxygen/examples/H5Pset_metadata_read_attempts.c
  src/H5ACpublic.h
  src/H5Apublic.h
  src/H5C.c
  src/H5Cpkg.h
  src/H5Cprivate.h
  src/H5Dint.c
  src/H5Doh.c
  src/H5Dpublic.h
  src/H5ESmodule.h
  src/H5Epublic.h
  src/H5FDhdfs.c
  src/H5FDmulti.h
  src/H5FDros3.c
  src/H5Fpublic.h
  src/H5Gmodule.h
  src/H5Goh.c
  src/H5Gpublic.h
  src/H5HFcache.c
  src/H5Ipublic.h
  src/H5Lpublic.h
  src/H5MF.c
  src/H5Mpublic.h
  src/H5Oalloc.c
  src/H5Omodule.h
  src/H5Opublic.h
  src/H5Oshared.h
  src/H5PLpublic.h
  src/H5Pfapl.c
  src/H5Ppublic.h
  src/H5Rpublic.h
  src/H5Sall.c
  src/H5Shyper.c
  src/H5Spublic.h
  src/H5Tenum.c
  src/H5Tpublic.h
  src/H5Zdevelop.h
  src/H5Zmodule.h
  src/H5Zpublic.h
  src/H5public.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Component - Documentation

#2540 GH issue #2538, print must have verbose on first
  tools/src/h5repack/h5repack.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#2539 Add concurrency option to cancel in-progress jobs
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Component - Testing, Type - Improvement

#2544 Make sure that ONLY_SHARED_LIBS option is correctly set
  CMakeLists.txt
  c++/src/CMakeLists.txt
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  hl/test/CMakeLists.txt
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/CMakeTests.cmake
  tools/lib/CMakeLists.txt
  tools/libtest/CMakeLists.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5import/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5stat/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
  tools/test/misc/vds/CMakeLists.txt
  utils/tools/h5dwalk/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#2356 Fix up the H5Pencode2 test for virtual layout. (#2325)
  test/enc_dec_plist.c
Labels: Merge, Branch - 1.12

#2542 GH issue #2538, print must have verbose on first
  tools/src/h5repack/h5repack.c
Labels: Merge, Component - Tools, Branch - 1.12

#2546 Make sure that ONLY_SHARED_LIBS option is correctly set
  CMakeLists.txt
  c++/src/CMakeLists.txt
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  hl/test/CMakeLists.txt
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/CMakeTests.cmake
  tools/lib/CMakeLists.txt
  tools/libtest/CMakeLists.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5import/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5stat/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
  tools/test/misc/vds/CMakeLists.txt
Labels: Merge, Component - Build, Branch - 1.12

#2549 1.12 Fix H5Dchunk_iter doxygen example, cherry-pick of 04682f2 (#2519)
  doxygen/examples/H5D_examples.c
Labels: Merge, Component - Documentation, Branch - 1.12

#2551 Add Glenn Song to the CODEOWNERS file
  .github/CODEOWNERS
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#2547 Make sure that ONLY_SHARED_LIBS option is correctly set
  CMakeLists.txt
  c++/src/CMakeLists.txt
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  hl/test/CMakeLists.txt
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/CMakeTests.cmake
  tools/lib/CMakeLists.txt
  tools/libtest/CMakeLists.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5import/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5stat/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
  tools/test/misc/vds/CMakeLists.txt
Labels: Merge, Component - Build, Branch - 1.10

#2543 GH issue #2538, print must have verbose on first
  tools/src/h5repack/h5repack.c
Labels: Merge, Component - Tools, Branch - 1.10

#2541 GH issue #2538, print must have verbose on first
  tools/src/h5repack/h5repack.c
Labels: Merge, Component - Tools, Branch - 1.14

#2560 Change libaec URL to actively maintained repo GH#2552
  config/cmake/README.md.cmake.in
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Component - Documentation, Branch - 1.14

#2564 Update cross compile checks and files #2497
  config/cmake/ConfigureChecks.cmake
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Component - Build, Type - Improvement, Branch - 1.14

#2566 Remove redundant and flawed documentation of H5D_chunk_iter_op_t from…
  src/H5D.c
Labels: Branch - 1.14

#2568 docs: in -> out (#2514) (#2516)
  src/H5Ppublic.h
Labels: Branch - 1.14

#2569 Update ReferenceManual.dox (#2517)
  doxygen/dox/ReferenceManual.dox
Labels: Branch - 1.14

#2570 [1.14 Merge] Subfiling VFD - add option to specify config file prefix (#2495)
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5FDsubfiling.h
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
  testpar/t_subfiling_vfd.c
Labels: Merge, Component - C Library, Type - Improvement, Branch - 1.14

#2559 Change libaec URL to actively maintained repo GH#2552
  config/cmake/README.md.cmake.in
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation

#2548 1.14 Fix H5Dchunk_iter doxygen example, cherry-pick of 04682f2 (#2519)
  doxygen/examples/H5D_examples.c
Labels: Merge, Component - Documentation, Branch - 1.14

#2562 Change libaec URL to actively maintained repo GH#2552
  config/cmake/README.md.cmake.in
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Component - Documentation, Branch - 1.10

#2567 Update cross compile checks and files #2497
  config/cmake/ConfigureChecks.cmake
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Component - Build, Type - Improvement, Branch - 1.10

#2535 Fix 2nd argument of Java H5Fis_accessible
  java/src/hdf/hdf5lib/H5.java
  java/src/jni/h5fImp.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Java, Type - Bug

#2578 Remove an obsolete comment from the MDS test
  testpar/t_pmulti_dset.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#2577 Add a clang-format comment about permissions
  .github/workflows/clang-format-fix.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Type - Improvement, Component - Misc

#2580 Merge MD cache tag slist --> hash table change
  src/H5C.c
  src/H5Cpkg.h
  src/H5Ctag.c
  src/H5Ipkg.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Improvement, Branch - 1.10

#2583 Merge minor configure.ac changes from develop
  configure.ac
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Improvement, Branch - 1.10

#2579 Minor merges to 1.10
  .github/workflows/clang-format-fix.yml
  release_docs/RELEASE.txt
  src/H5Oattr.c
  src/H5Ppublic.h
  testpar/testpar.h
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/testh5dump.sh.in
  tools/testfiles/tCVE-2021-37501_attr_decode.h5
Labels: Branch - 1.10

#2561 Change libaec URL to actively maintained repo GH#2552
  config/cmake/README.md.cmake.in
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Component - Documentation, Branch - 1.12

#2584 Allow parallel thread-safe builds
  CMakeLists.txt
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Component - Parallel, Type - Improvement, Branch - 1.10

#2585 Use new scheme in release_docs
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_8.txt
  release_docs/NEWSLETTER.txt
  release_docs/README.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement, Branch - 1.10

#2586 Align compiler flags with develop
  config/README.md
  config/clang-warnings/developer-general
  config/clang-warnings/general
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/conclude_fc.am
  config/gnu-fflags
  config/gnu-warnings/4.8
  config/gnu-warnings/cxx-4.8
  config/gnu-warnings/cxx-developer-4.8
  config/gnu-warnings/developer-12
  config/gnu-warnings/developer-4.8
  config/gnu-warnings/gfort-4.8
  config/gnu-warnings/gfort-developer-4.8
  config/gnu-warnings/gfort-developer-5
  config/gnu-warnings/gfort-developer-general
  config/gnu-warnings/gfort-no-developer-4.8
  config/gnu-warnings/gfort-no-developer-general
  config/gnu-warnings/no-cxx-developer-4.8
  config/gnu-warnings/no-developer-4.8
  config/ibm-aix
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Improvement, Branch - 1.10

#2588 Bring 'default' API value over from develop
  .github/workflows/main.yml
  configure.ac
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Improvement, Branch - 1.10

#2587 Remove dmalloc support (#2239)
  CMakeLists.txt
  config/cmake/H5pubconf.h.in
  config/cmake/libhdf5.settings.cmake.in
  configure.ac
  release_docs/RELEASE.txt
  src/H5private.h
  src/libhdf5.settings.in
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal, Branch - 1.10

#2589 Rename test scripts like develop
  configure.ac
  test/CMakeTests.cmake
  test/Makefile.am
  test/ShellTests.cmake
  test/test_abort_fail.sh.in
  test/test_check_version.sh.in
  test/test_error.sh.in
  test/test_external_env.sh.in
  test/test_flush_refresh.sh.in
  test/test_libinfo.sh.in
  test/test_links_env.sh.in
  test/test_plugin.sh.in
  test/test_swmr.sh.in
  test/test_use_cases.sh.in
  test/test_vds_env.sh.in
  test/test_vds_swmr.sh.in
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Component - Build, Type - Improvement, Branch - 1.10

#2591 Remove unused H5MP and H5HP packages
  src/CMakeLists.txt
  src/H5HP.c
  src/H5HPprivate.h
  src/H5MP.c
  src/H5MPmodule.h
  src/H5MPpkg.h
  src/H5MPprivate.h
  src/H5MPtest.c
  src/Makefile.am
  test/CMakeLists.txt
  test/CMakeTests.cmake
  test/Makefile.am
  test/pool.c
  test/testhdf5.c
  test/testhdf5.h
  test/theap.c
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Type - Deprecation / Removal, Branch - 1.10

#2592 Move Autotools VFD list to conclude.am
  c++/Makefile.am
  config/conclude.am
  fortran/Makefile.am
  fortran/src/Makefile.am
  test/Makefile.am
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Component - Build, Type - Improvement, Branch - 1.10

#2593 Remove bin/mkdirs and bin/newer
  bin/mkdirs
  bin/newer
  config/conclude.am
  config/examples.am
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal, Branch - 1.10

#2595 Bring bin/ changes from develop
  bin/README.md
  bin/checkposix
  bin/chkconfigure
  bin/chkcopyright
  bin/dependencies
  bin/deploy
  bin/distdep
  bin/errors
  bin/format_source_patch
  bin/gcov_script
  bin/genparser
  bin/output_filter.sh
  bin/release
  bin/restore.sh
  bin/trace
  bin/warnhist
Labels: Merge, Priority - 2. Medium ⏹, Type - Improvement, Type - Deprecation / Removal, Branch - 1.10, Component - Misc

#2596 Unify cmake and cmake_ext_mod like develop
  CMakeInstallation.cmake
  CMakeLists.txt
  c++/examples/CMakeTests.cmake
  c++/test/CMakeTests.cmake
  c++/test/CMakeVFDTests.cmake
  config/cmake/CTestCustom.cmake
  config/cmake/ConfigureChecks.cmake
  config/cmake/FindSZIP.cmake
  config/cmake/GetTimeOfDayTest.cpp
  config/cmake/HDFCXXTests.cpp
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/HDFTests.c
  config/cmake/HDFUseCXX.cmake
  config/cmake/HDFUseFortran.cmake
  config/cmake/NSIS.InstallOptions.ini.in
  config/cmake/NSIS.template.in
  config/cmake/grepTest.cmake
  config/cmake/hdf.bmp
  config/cmake/hdf.icns
  config/cmake/hdf.ico
  config/cmake/runTest.cmake
  config/cmake/version.plist.in
  config/cmake_ext_mod/CTestCustom.cmake
  config/cmake_ext_mod/ConfigureChecks.cmake
  examples/CMakeTests.cmake
  fortran/examples/CMakeTests.cmake
  fortran/test/CMakeTests.cmake
  hl/c++/examples/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/examples/CMakeTests.cmake
  hl/fortran/examples/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  hl/tools/h5watch/CMakeTests.cmake
  java/CMakeLists.txt
  m4/aclocal_cxx.m4
  test/CMakeTests.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/perform/CMakeTests.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Improvement, Branch - 1.10

#2594 Bring warning macro changes from develop
  src/H5private.h
  src/H5public.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Improvement, Branch - 1.10

#2597 Bring mirror VFD test improvements from develop
  src/H5FDmirror.c
  test/mirror_vfd.c
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_writer.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Branch - 1.10

#2608 Bring warning fixes from develop
  src/H5FDdirect.c
  src/H5Gname.c
  src/H5Gnode.c
  src/H5Gobj.c
  src/H5Gtraverse.c
  src/H5HF.c
  src/H5HFcache.c
  src/H5HFman.c
  src/H5Idbg.c
  src/H5L.c
  src/H5Ocache.c
  src/H5make_libsettings.c
  test/objcopy.c
  test/use_append_chunk_mirror.c
  tools/test/h5dump/h5dumpgentest.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Testing, Type - Improvement, Branch - 1.10

#2590 Fix test script names in cleanup code
  test/Makefile.am
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#2612 Bring release_docs scheme from develop
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_10.txt
  release_docs/HISTORY-1_8.txt
  release_docs/NEWSLETTER.txt
  release_docs/README.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement, Branch - 1.12

#2617 [1.10 Merge] Add Developer build mode to CMake
  CMakeLists.txt
  config/cmake/HDF5DeveloperBuild.cmake
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFMacros.cmake
  java/examples/datasets/CMakeLists.txt
  java/examples/datatypes/CMakeLists.txt
  java/examples/groups/CMakeLists.txt
  java/examples/intro/CMakeLists.txt
  java/test/CMakeLists.txt
  src/CMakeLists.txt
  src/H5AC.c
  src/H5ACmpio.c
  src/H5ACpkg.h
  src/H5ACprivate.h
  src/H5C.c
  src/H5Cmpio.c
  src/H5Cpkg.h
  src/H5Cprivate.h
  src/H5Ctag.c
  src/H5EAprivate.h
  test/CMakeLists.txt
  test/cache_tagging.c
  test/tmisc.c
  testpar/CMakeLists.txt
Labels: Merge, Component - Build, Type - New Feature, Branch - 1.10

#2616 Add missing items for hpc/scripts and release versions of extra
  bin/release
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5config.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
  src/CMakeLists.txt
  src/H5win32defs.h
Labels: Component - Build, Branch - 1.10

#2611 Add Option to not build gif tools and remove javadoc option
  configure.ac
  hl/CMakeLists.txt
  hl/Makefile.am
  hl/tools/CMakeLists.txt
  hl/tools/Makefile.am
  hl/tools/h5watch/CMakeTests.cmake
  java/src/hdf/hdf5lib/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Component - Build, Type - Task, Branch - 1.10

#2619 Remove perf tool and standalone h5perf builds
  release_docs/RELEASE.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5perf/Makefile.am
  tools/src/h5perf/perf.c
  tools/src/h5perf/pio_engine.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/pio_perf.h
  tools/src/h5perf/sio_engine.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5perf/sio_perf.h
  tools/test/perform/CMakeLists.txt
  tools/test/perform/CMakeTests.cmake
  tools/test/perform/build_h5perf_alone.sh
  tools/test/perform/build_h5perf_serial_alone.sh
  tools/test/perform/chunk.c
  tools/test/perform/direct_write_perf.c
  tools/test/perform/iopipe.c
  tools/test/perform/overhead.c
  tools/test/perform/perf_meta.c
  tools/test/perform/pio_standalone.c
  tools/test/perform/pio_standalone.h
  tools/test/perform/sio_standalone.c
  tools/test/perform/sio_standalone.h
  tools/test/perform/zip_perf.c
Labels: Merge, Priority - 1. High 🔼, Component - Tools, Component - Testing, Type - Deprecation / Removal, Branch - 1.10

#2620 Remove getlogin work-arounds
  bin/checkposix
  src/H5private.h
  src/H5system.c
  src/H5win32defs.h
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Branch - 1.10

#2614 Bring new release_docs scheme from 1.14
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_10.txt
  release_docs/HISTORY-1_12.txt
  release_docs/HISTORY-1_12_0-1_14_0.txt
  release_docs/HISTORY-1_8.txt
  release_docs/NEWSLETTER.txt
  release_docs/README.md
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#2610 Fix minor things noted when doing 1.10 merges
  CMakeLists.txt
  bin/checkposix
  java/CMakeLists.txt
  release_docs/INSTALL_Cygwin.txt
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement, Component - Misc

#2626 Fix a memory corruption issue in H5S__point_project_simple
  release_docs/RELEASE.txt
  src/H5Spoint.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#2627 [1.10 Merge] Fix a memory corruption issue in H5S__point_project_simple
  release_docs/RELEASE.txt
  src/H5Spoint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2629 1 10 revert 2615
  README.md
  c++/src/cpp_doc_config
  config/cmake/scripts/HDF5config.cmake
  config/lt_vers.am
  configure.ac
  release_docs/RELEASE.txt
  src/H5Defl.c
  src/H5FDfamily.c
  src/H5MM.c
  src/H5VM.c
  src/H5private.h
  src/H5public.h
  src/H5system.c
  src/H5win32defs.h
  src/libhdf5.settings.in
  test/h5test.h
  test/testframe.c
  test/testhdf5.h
  testpar/t_bigio.c
  testpar/t_filters_parallel.c
  testpar/t_mpi.c
Labels: Branch - 1.10

#2638 Undo revert 2615
  config/lt_vers.am
  release_docs/RELEASE.txt
  src/H5Defl.c
  src/H5FDfamily.c
  src/H5MM.c
  src/H5VM.c
  src/H5private.h
  src/H5system.c
  src/H5win32defs.h
  src/libhdf5.settings.in
  test/h5test.h
  test/testframe.c
  test/testhdf5.h
  testpar/t_bigio.c
  testpar/t_filters_parallel.c
  testpar/t_mpi.c
Labels: Branch - 1.10

#2636 Revert the removal of HDF5GroupInfo class and deprecate.
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/hdf/hdf5lib/HDF5GroupInfo.java
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Java, Type - Deprecation / Removal, Branch - 1.10

#2637 Revert the removal of HDF5GroupInfo class and deprecate.
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/HDF5GroupInfo.java
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Java, Type - Deprecation / Removal, Branch - 1.12

#2581 Minor cherry-pick merges to 1.12
  .github/CODEOWNERS
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  doxygen/examples/tables/propertyLists.dox
  release_docs/RELEASE.txt
  src/H5Oattr.c
  src/H5Ppublic.h
  testpar/testpar.h
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/testh5dump.sh.in
  tools/testfiles/tCVE-2021-37501_attr_decode.h5
Labels: Branch - 1.12

#2650 Check CMake version for correct option
  config/cmake/scripts/CTestScript.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.10

#2651 Fix CMake for version less then 3.18
  bin/batch/ctest.qsub.in.cmake
  bin/batch/ctestP.lsf.in.cmake
  bin/batch/ctestP.sl.in.cmake
  bin/batch/ctestS.lsf.in.cmake
  bin/batch/ctestS.sl.in.cmake
  bin/batch/ctest_parallel.cmake.in
  bin/batch/ctest_serial.cmake.in
  bin/batch/knl_ctestP.sl.in.cmake
  bin/batch/knl_ctestS.sl.in.cmake
  bin/batch/ray_ctestP.lsf.in.cmake
  bin/batch/ray_ctestS.lsf.in.cmake
  config/cmake/UseJavaSymlinks.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5config.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.12
