Repository HDFGroup/hdf5, pull requests merged in 2023-10, with the labels that each got.

#3623 Add HPC CDash to README.md
  README.md
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#3622 Disable static + thread-safe on Windows w/ CMake
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#3628 Remove unused member from H5D_shared_t struct.
  src/H5Dpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3633 Fix spelling
  CMakeInstallation.cmake
  config/cmake/UseJava.cmake
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
  fortran/src/H5Pff.F90
  hl/fortran/src/H5IMff.F90
  hl/src/H5IM.c
  hl/src/H5IMpublic.h
  java/src/hdf/hdf5lib/H5.java
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_10_0-1_12_0.txt
  release_docs/HISTORY-1_8_0-1_10_0.txt
  src/H5ACmpio.c
  src/H5ACprivate.h
  src/H5Cimage.c
  src/H5Cprivate.h
  src/H5FDhdfs.c
  src/H5FDmpio.c
  src/H5FDpublic.h
  src/H5FDros3.c
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  src/H5FLprivate.h
  src/H5Gpublic.h
  src/H5HFcache.c
  src/H5MFaggr.c
  src/H5Oalloc.c
  src/H5Oefl.c
  src/H5Pfapl.c
  src/H5Tcommit.c
  src/H5Tnative.c
  src/H5WB.c
  src/H5Zfletcher32.c
  src/H5detect.c
  src/H5private.h
  test/cache_api.c
  test/direct_chunk.c
  test/external.c
  test/mf.c
  test/swmr.c
  test/tfile.c
  test/tselect.c
  test/ttsafe_rec_rw_lock.c
  testpar/t_2Gio.c
  testpar/t_cache_image.c
  testpar/t_dset.c
  testpar/t_shapesame.c
  testpar/t_span_tree.c
  testpar/testphdf5.c
  tools/src/h5perf/perf.c
  tools/src/h5repack/h5repack_copy.c
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5repack/h5repackgentest.c
  tools/test/h5stat/CMakeTests.cmake
  tools/test/h5stat/testh5stat.sh.in
  utils/mirror_vfd/mirror_writer.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Component - High-Level Library, Component - Java, Component - Fortran, Component - Parallel, Component - Testing, Type - Improvement, Branch - 1.12

#3630 Disable static + thread-safe on Windows w/ CMake (#3622)
  .github/workflows/main.yml
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Improvement, Branch - 1.14

#3631 Disable static + thread-safe on Windows w/ CMake (#3622)
  .github/workflows/main.yml
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Improvement, Branch - 1.12

#3624 Remove old EXTERNALPROJECT_ADD in favor of FETCH_CONTENT
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#3636 Fail CMake on Windows when sub-filing VFD is enabled
  CMakeLists.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Parallel, Component - Build, Type - Improvement

#3638 Improve consistency in past tense usage
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3639 Split out test logic to separate file
  CMakeLists.txt
  CMakeTests.cmake
Labels: Priority - 3. Low 🔽, Component - Build, Type - Improvement

#3643 dropping MPI-2 support
  CMakeLists.txt
  configure.ac
  release_docs/RELEASE.txt
  src/H5Dmpio.c
  src/H5FDmpio.c
  src/H5FDmpio.h
  src/H5Fmodule.h
  src/H5Smpio.c
  src/H5mpi.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Component - Build, Type - Deprecation / Removal

#3645 Add CVE action for 1.12
  .github/workflows/cve.yml
  CVE_list-1_12.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Component - Testing, Type - Improvement, Branch - 1.12

#3644 Switch IEEE flags for NAG Fortran
  config/linux-gnulibc1
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Improvement

#3646 Remove 1.10.11 info from README.md
  README.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3648 Bring the H5detect removal change from develop
  .clang-format
  CMakeLists.txt
  bin/batch/knl_H5detect.sl.in.cmake
  configure.ac
  release_docs/INSTALL_CMake.txt
  release_docs/README_HPC
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5.c
  src/H5T.c
  src/H5Tconv.c
  src/H5Tinit_float.c
  src/H5Tpkg.h
  src/H5build_settings.autotools.c.in
  src/H5build_settings.cmake.c.in
  src/H5build_settings.off.c.in
  src/H5detect.c
  src/H5make_libsettings.c
  src/H5private.h
  src/Makefile.am
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Component - Build, Branch - 1.14

#3654 Fixes GH#1027 compilation error
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Component - Build, Type - Bug

#3650 Remove 1.10 badge
  README.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3651 Use real URLs and updated names for plugins
  CMakeFilters.cmake
  CMakePlugins.cmake
  CMakePresets.json
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  release_docs/INSTALL_CMake.txt
  test/API/driver/CMakeLists.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Component - Misc

#3591 Update parallel compression feature to support multi-dataset I/O
  doc/parallel-compression.md
  release_docs/RELEASE.txt
  src/H5Dchunk.c
  src/H5Dcontig.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dpkg.h
  src/H5FDmpio.c
  src/H5Fmpi.c
  src/H5Fprivate.h
  src/H5Fquery.c
  src/H5Pint.c
  src/H5VLnative_dataset.c
  testpar/t_filters_parallel.c
  testpar/t_filters_parallel.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Improvement

#3528 Add more tests for selection I/O.
  src/H5Dscatgath.c
  test/cmpd_dset.c
  test/select_io_dset.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Parallel, Component - Testing, Type - Improvement

#3658 Address nagfor exceptions stoppage.
  config/cmake/HDFFortranCompilerFlags.cmake
  config/linux-gnulibc1
  fortran/examples/CMakeLists.txt
  fortran/src/H5Dff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5_buildiface.F90
  fortran/test/tH5D.F90
  fortran/test/tH5G_1_8.F90
  hl/fortran/examples/CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Testing

#3665 Add expedited testing support to t_filters_parallel
  testpar/t_filters_parallel.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3667 Correct use of set() command with options
  CMakeFilters.cmake
  CMakePlugins.cmake
  config/cmake/HDF5PluginMacros.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.14

#3668 Update RELEASE.txt
  release_docs/RELEASE.txt
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Branch - 1.12

#3656 Remove clang warnings
  src/H5FDsubfiling/H5FDsubfiling.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3662 Fixes test failure for gfortran -O2 and -O3, -fdefault-real-16
  fortran/test/tH5P_F03.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - Bug

#3671 Fix link error on clang17/gfortran13/macOS-13 (#3666)
  fortran/examples/ph5example.f90
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3673 sync a couple of misses from merge
  doxygen/examples/tables/propertyLists.dox
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Branch - 1.14

#3670 Correct fortran CMake generator expressions
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  fortran/testpar/CMakeLists.txt
  hl/fortran/examples/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/fortran/test/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#3653 Remove callable action badges.
  README.md
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Documentation, Component - Build

#3657 Add AOCC GitHub Action (#3504)
  .github/workflows/linux-auto-aocc-ompi.yml
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3675 Fix uninitialized subfiling test variable
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3674 Add support for AOCC & Flang w/ the Autotools
  config/clang-cxxflags
  config/clang-fflags
  config/linux-gnulibc1
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Component - Parallel, Component - Build, Type - Improvement

#3677 Fix a strncpy call to use dest size not src
  src/H5system.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3678 Remove CANBE_UNUSED() from subfiling VFD
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfile_int.c
  src/H5FDsubfiling/H5FDsubfiling_priv.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Improvement

#3680 Suppress MPI_Waitall warnings w/ MPICH
  src/H5FDsubfiling/H5FDioc_int.c
  src/H5FDsubfiling/H5FDsubfile_int.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Improvement

#3681 Fix invalid memory access in S3 comms
  src/H5FDs3comms.c
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#3685 Add Doxygen for H5Pset_fapl_sec2()
  src/H5FDsec2.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Documentation, Type - Improvement

#3694 Remove scorecard workflow from 1.14 branch
  .github/workflows/scorecard.yml
Labels: Priority - 3. Low 🔽, Type - Task, Branch - 1.14, Component - Misc

#3690 switch to using the "time" function instead of the "date" function for h5fuse.sh timing
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Priority - 2. Medium ⏹, Component - Tools, Component - Parallel, Type - Improvement

#3696 Add test info output to t_filters_parallel
  testpar/t_filters_parallel.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3699 Suppress format string warnings in subfiling test
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3700 Fix unused variable warning in H5F_sfile_assert_num
  src/H5Fsfile.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3698 Restore floating-point suffixes in tests
  hl/test/test_table.c
  test/dt_arith.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3703 Correct use of set() command with options (#3667)
  CMakeFilters.cmake
  CMakePlugins.cmake
  config/cmake/HDF5PluginMacros.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3704 Sync changes that are only in 1.14 branch
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/ConfigureChecks.cmake
  config/cmake/runTest.cmake
  config/sanitizer/README.md
  doxygen/examples/H5D_examples.c
  fortran/src/H5Fff.F90
  fortran/src/H5Lff.F90
  src/H5Olayout.c
  tools/test/misc/talign.c
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - C Library, Type - Task

#3705 Sync 1.14 branch with develop
  .github/workflows/linux-auto-aocc-ompi.yml
  CMakeFilters.cmake
  config/clang-cxxflags
  config/clang-fflags
  config/cmake/HDFFortranCompilerFlags.cmake
  config/linux-gnulibc1
  configure.ac
  fortran/examples/CMakeLists.txt
  fortran/examples/ph5example.f90
  fortran/src/CMakeLists.txt
  fortran/src/H5Dff.F90
  fortran/src/H5Pff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5_buildiface.F90
  fortran/test/CMakeLists.txt
  fortran/test/tH5D.F90
  fortran/test/tH5G_1_8.F90
  fortran/test/tH5P_F03.F90
  fortran/testpar/CMakeLists.txt
  hl/fortran/examples/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/fortran/test/CMakeLists.txt
  hl/test/test_table.c
  java/src/jni/h5aImp.c
  release_docs/RELEASE.txt
  src/H5CX.c
  src/H5FDs3comms.c
  src/H5FDsec2.h
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDioc_int.c
  src/H5FDsubfiling/H5FDsubfile_int.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5FDsubfiling_priv.h
  src/H5Fsfile.c
  src/H5system.c
  test/dt_arith.c
  test/dtypes.c
  test/tselect.c
  testpar/t_filters_parallel.c
  testpar/t_mpi.c
  testpar/t_subfiling_vfd.c
  tools/test/misc/talign.c
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - High-Level Library, Component - Documentation, Component - Fortran, Component - Parallel, Component - Testing, Component - Build, Type - Task, Branch - 1.14, Component - Misc

#3695 Clean up comments.
  src/H5Dio.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3686 Convert nv workflow to callable
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/linux-nvhpc-auto.yml
  .github/workflows/linux-nvhpc.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/linux-gnulibc1
  config/nvidia-cxxflags
  config/nvidia-fflags
  config/nvidia-flags
  fortran/src/CMakeLists.txt
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3706 Cache variables req FORCE to change
  CMakeFilters.cmake
  CMakePlugins.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3707 Cache variables req FORCE to change
  CMakeFilters.cmake
  CMakePlugins.cmake
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.14

#3711 Add NV flags and update CI
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/linux-nvhpc-auto.yml
  .github/workflows/linux-nvhpc.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  CTestConfig.cmake
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/cmake/scripts/CTestScript.cmake
  config/linux-gnulibc1
  config/nvidia-cxxflags
  config/nvidia-fflags
  config/nvidia-flags
Labels: Merge, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Improvement, Branch - 1.14

#3712 Some corrections and fix for plugins
  CMakeLists.txt
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/scripts/CTestScript.cmake
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Type - Improvement

#3719 Fix issue with unmatched messages in ph5diff
  release_docs/RELEASE.txt
  tools/lib/h5diff.c
  tools/src/h5diff/ph5diff_main.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Component - Parallel, Type - Bug

#3717 provide an alternative to mapfile for older bash shells
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Parallel, Type - Improvement

#3724 Attempt to quiet some warnings with cray compilers.
  fortran/test/tH5D.F90
  fortran/test/tH5E_F03.F90
  fortran/test/tH5F.F90
  fortran/test/tH5G.F90
  fortran/test/tH5O_F03.F90
  fortran/test/tH5P_F03.F90
  fortran/test/tH5Sselect.F90
  fortran/test/tH5T.F90
  fortran/test/tH5T_F03.F90
  fortran/test/tH5Z.F90
  fortran/test/vol_connector.F90
  fortran/testpar/async.F90
Labels: Priority - 2. Medium ⏹, Component - Fortran, Component - Build, Type - Improvement

#3708 GH issue 3398 - option to disable doxygen warn as error
  CMakeLists.txt
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Improvement

#3721 Fix CMake VOL passthrough tests by copying files to correct directory
  test/CMakePassthroughVOLTests.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#3722 Develop intel split
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/gnu-warnings/developer-general
  config/intel-cxxflags
  config/intel-fflags
  config/intel-flags
  config/intel-warnings/classic/15
  config/intel-warnings/classic/18
  config/intel-warnings/classic/developer-general
  config/intel-warnings/classic/general
  config/intel-warnings/classic/ifort-general
  config/intel-warnings/classic/win-developer-general
  config/intel-warnings/classic/win-general
  config/intel-warnings/classic/win-ifort-general
  config/intel-warnings/developer-general
  config/intel-warnings/oneapi/developer-general
  config/intel-warnings/oneapi/general
  config/intel-warnings/oneapi/ifort-general
  config/intel-warnings/oneapi/win-developer-general
  config/intel-warnings/oneapi/win-general
  config/intel-warnings/oneapi/win-ifort-general
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Improvement

#3714 Fixes and adjustments to t_filters_parallel
  testpar/t_filters_parallel.c
  testpar/t_filters_parallel.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Parallel, Component - Testing, Type - Improvement

#3725 Organize CMake config features like libsettings
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 3. Low 🔽, Component - Build, Type - Improvement

#3709 GH issue 3398 - option to disable doxygen warn as error
  CMakeLists.txt
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Component - Build, Branch - 1.14

#3728 Suppress cast-qual warning in H5TB Fortran wrapper
  hl/fortran/src/H5TBfc.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Fortran, Type - Improvement

#3727 Organize CMake config features like libsettings
  config/cmake/hdf5-config.cmake.in
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Improvement, Branch - 1.14

#2974 Add new API function H5Pget_actual_select_io_mode()
  doxygen/examples/tables/propertyLists.dox
  release_docs/RELEASE.txt
  src/H5CX.c
  src/H5CXprivate.h
  src/H5Dprivate.h
  src/H5FDint.c
  src/H5M.c
  src/H5Pdxpl.c
  src/H5Ppublic.h
  test/select_io_dset.c
  testpar/t_filters_parallel.c
  testpar/t_select_io_dset.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - New Feature

#3723 Test scripts now execute in-source with creation of tmp dir
  CMakeInstallation.cmake
  CMakePresets.json
  tools/test/h5copy/testh5copy.sh.in
  tools/test/h5diff/h5diff_plugin.sh.in
  tools/test/h5diff/testh5diff.sh.in
  tools/test/h5dump/h5dump_plugin.sh.in
  tools/test/h5dump/testh5dump.sh.in
  tools/test/h5dump/testh5dumppbits.sh.in
  tools/test/h5dump/testh5dumpvds.sh.in
  tools/test/h5dump/testh5dumpxml.sh.in
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5format_convert/expected/h5fc_ext1_f.ddl
  tools/test/h5format_convert/expected/h5fc_ext1_i.ddl
  tools/test/h5format_convert/expected/h5fc_ext1_s.ddl
  tools/test/h5format_convert/expected/h5fc_ext2_if.ddl
  tools/test/h5format_convert/expected/h5fc_ext2_is.ddl
  tools/test/h5format_convert/expected/h5fc_ext2_sf.ddl
  tools/test/h5format_convert/expected/h5fc_ext3_isf.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext1_f.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext1_i.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext1_s.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext2_if.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext2_is.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext2_sf.ddl
  tools/test/h5format_convert/expected/old_h5fc_ext3_isf.ddl
  tools/test/h5format_convert/testh5fc.sh.in
  tools/test/h5import/h5importtestutil.sh.in
  tools/test/h5jam/testh5jam.sh.in
  tools/test/h5ls/h5ls_plugin.sh.in
  tools/test/h5ls/testh5ls.sh.in
  tools/test/h5ls/testh5lsvds.sh.in
  tools/test/h5repack/h5repack.sh.in
  tools/test/h5repack/h5repack_plugin.sh.in
  tools/test/h5stat/testh5stat.sh.in
  tools/test/misc/testh5clear.sh.in
  tools/test/misc/testh5mkgrp.sh.in
  tools/test/misc/testh5repart.sh.in
  utils/tools/test/h5dwalk/copy_demo_files.sh.in
  utils/tools/test/h5dwalk/testh5dwalk.sh.in
Labels: Priority - 0. Blocker ⛔, Component - Tools, Component - Build, Type - Bug

#3729 Add -h and --help as flags for help message
  bin/h5cc.in
  fortran/src/h5fc.in
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#3702 Update the library version matrix for H5Pset_libver_bounds()
  src/H5Ppublic.h
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#3734 Add missing test files to distclean target
  test/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3735 Add tools/libtest to Autotools builds
  hl/test/Makefile.am
  tools/Makefile.am
  tools/libtest/Makefile.am
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Component - Testing, Type - Improvement

#3739 Clean up onion VFD files in tools `make clean`
  tools/test/h5diff/Makefile.am
  tools/test/h5dump/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Component - Testing, Type - Improvement

#3740 Clean Java test files on Autotools
  java/test/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Java, Component - Testing

#3741 Clean the flushrefresh test dir on Autotools
  test/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3743 Fix file names in tfile.c
  test/Makefile.am
  test/tfile.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3744 Clean Autotools files in parallel tests
  fortran/testpar/Makefile.am
  testpar/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Component - Testing, Type - Improvement

#3647 Add native VOL checks to deprecated functions
  src/H5Odeprec.c
  src/H5Rdeprec.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3691 Fix buffer overflow in cache debugging code
  src/H5Cmpio.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Bug

#3726 update stat arg for apple
  fortran/src/H5Fff.F90
  fortran/src/H5Off.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90global.F90
  fortran/testpar/CMakeTests.cmake
  fortran/testpar/subfiling.F90
Labels: Component - Fortran, Type - Improvement

#3747 Fix windows cpack error in WiX package.
  doxygen/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc

#3753 Add a simple cache to the ros3 VFD
  release_docs/RELEASE.txt
  src/H5FDros3.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#3754 Improve the usage of h5clear
  tools/src/misc/h5clear.c
  tools/test/misc/expected/h5clear_missing_file.ddl
  tools/test/misc/expected/h5clear_usage.ddl
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#3751 Update Autotools to correctly configure oneAPI
  config/apple
  config/freebsd
  config/linux-gnulibc1
  config/netbsd
  config/oneapi-cxxflags
  config/oneapi-fflags
  config/oneapi-flags
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Improvement

#3746 Add h5pget_actual_selection_io_mode fortran wrapper
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/test/tH5P.F90
  fortran/testpar/hyper.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - New Feature

#3748 Update fortran action step
  .github/workflows/cmake-ctest.yml
Labels: Priority - 0. Blocker ⛔, Type - Deprecation / Removal, Component - Misc

#3759 Bump the ros3 VFD cache to 16 MiB
  release_docs/RELEASE.txt
  src/H5FDros3.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#3693 Fix hangs during collective I/O with independent metadata writes
  release_docs/RELEASE.txt
  src/H5Cmpio.c
  src/H5Pfapl.c
  testpar/t_coll_md.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug

#3716 Fix some issues with collective metadata reads for chunked datasets
  release_docs/RELEASE.txt
  src/H5Dbtree.c
  src/H5Dbtree2.c
  src/H5Dchunk.c
  src/H5Dearray.c
  src/H5Dfarray.c
  src/H5Dmpio.c
  src/H5Dnone.c
  src/H5Dpkg.h
  src/H5Dsingle.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Bug

#3758 Fix failure in t_select_io_dset when run with more than 10 ranks
  testpar/t_select_io_dset.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Parallel, Component - Testing, Type - Improvement

#3750 Fix windows cpack error in WiX package.
  doxygen/CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Branch - 1.14

#3749 Update fortran action step
  .github/workflows/cmake-ctest.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Deprecation / Removal, Branch - 1.14, Component - Misc

#3761 Fix H5Pevict_on_close failing regardless of actual parallel use
  src/H5Fint.c
  src/H5Pfapl.c
  test/evict_on_close.c
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Component - Testing, Type - Improvement

#3765 Add release note for H5Pset_evict_on_close change for parallel HDF5
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3767 Add release note for H5Pset_evict_on_close change for parallel HDF5 (#3765)
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Type - Task, Branch - 1.14

#3755 Preserve MPI-I/O file hints when fapl is closed
  src/H5Fint.c
  src/H5Fpkg.h
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3769 Add compression tests for subfiling
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Parallel, Component - Testing, Type - Improvement

#3763 Update CMake to use plugins and compression fetchcontent
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CTestConfig.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  config/cmake/scripts/CTestScript.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Type - Improvement, Type - Deprecation / Removal, Branch - 1.12, Component - Misc

#3774 Cache installation of OpenMPI for AOCC action
  .github/workflows/linux-auto-aocc-ompi.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#3777 Cache installation of OpenMPI for AOCC action (#3774)
  .github/workflows/linux-auto-aocc-ompi.yml
Labels: Merge, Priority - 3. Low 🔽, Type - Task, Branch - 1.14, Component - Misc

#3775 Fix typo in comment
  src/H5Tvlen.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3779 Fix a file handle leak in the core VFD
  release_docs/RELEASE.txt
  src/H5FDcore.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#3776 Fix a format string warning in the C++ examples
  hl/c++/examples/ptExampleFL.cpp
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C++, Type - Improvement

#3785 Print some messages in parallel tests on MPI rank 0 only
  test/h5test.c
  test/testframe.c
  testpar/t_2Gio.c
  testpar/t_mpi.c
  testpar/t_shapesame.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Task

#3786 Avoid attempted use of NULL pointer in parallel compression code
  src/H5Dmpio.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Bug

#3793 Don't install h5tools_test_utils test program on system
  release_docs/RELEASE.txt
  tools/libtest/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3794 Add Doxygen to H5FDsplitter.h
  src/H5FDsplitter.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#3795 Update Doxygen initializers & identifiers in VFDs
  src/H5FDcore.h
  src/H5FDdirect.h
  src/H5FDfamily.h
  src/H5FDhdfs.h
  src/H5FDlog.h
  src/H5FDmirror.h
  src/H5FDmpio.h
  src/H5FDmulti.h
  src/H5FDonion.h
  src/H5FDros3.h
  src/H5FDsec2.h
  src/H5FDsplitter.h
  src/H5FDstdio.h
  src/H5FDwindows.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Documentation, Type - Improvement

#3796 Remove CDASH_LOCAL variable reference
  CMakeInstallation.cmake
  CTestConfig.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/examples/HDF5_Examples.cmake.in
Labels: Priority - 1. High 🔼, Component - Build, Type - Bug, Type - Improvement, Type - Deprecation / Removal

#3806 Fix memory corruption in 'MPI I/O FAPL preserve' test
  testpar/t_file.c
Labels: Priority - 0. Blocker ⛔, Component - Parallel, Component - Testing, Type - Bug

#3807 Fix usage of h5_clean_files in t_pflush2.c
  testpar/t_pflush2.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Task

#3808 Fix parallel driver check in h5_fixname_real
  test/h5test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3802 Drop MPI-2 support (#3643)
  CMakeLists.txt
  configure.ac
  release_docs/RELEASE.txt
  src/H5Dmpio.c
  src/H5FDmpio.c
  src/H5FDmpio.h
  src/H5Fmodule.h
  src/H5Smpio.c
  src/H5mpi.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Component - Build, Type - Task, Branch - 1.14
