Repository HDFGroup/hdf5, pull requests merged in 2023-09, with the labels that each got.

#3477 Add an h5py badge to README.md
  README.md
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Testing, Type - Task

#3459 [1.10 Merge] Fix valgrind warning about write of uninitialized bytes in ScaleOffse…
  src/H5Zscaleoffset.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.10

#3462 [1.12 Merge] Fix valgrind warning about write of uninitialized bytes in ScaleOffse…
  src/H5Zscaleoffset.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.12

#3465 [1.14 Merge] Fix valgrind warning about write of uninitialized bytes (#3389)
  src/H5FScache.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.14

#3461 [1.12 Merge] Fix assertion failure during file close on error
  release_docs/RELEASE.txt
  src/H5Cimage.c
  src/H5Fint.c
  src/H5Fsuper.c
  src/H5MF.c
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.12

#3463 [1.14 Merge] Fix assertion failure during file close on error
  release_docs/RELEASE.txt
  src/H5Cimage.c
  src/H5Fint.c
  src/H5Fsuper.c
  src/H5MF.c
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.14

#3460 [1.10 Merge] Fix assertion failure during file close on error
  release_docs/RELEASE.txt
  src/H5Cimage.c
  src/H5F.c
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5Fsuper.c
  src/H5MF.c
  testpar/t_file.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.10

#3457 Avoid having all the ranks printing out testing information
  test/h5test.h
  test/testframe.c
  testpar/t_2Gio.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3464 [1.14 Merge] Fix compile failures with H5C_DO_MEMORY_SANITY_CHECKS enabled (#3388)
  src/H5Centry.c
  src/H5Cimage.c
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Type - Task, Branch - 1.14

#3466 [1.14 Merge] Fix valgrind warning about write of uninitialized bytes in ScaleOffse…
  src/H5Zscaleoffset.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.14

#3475 [1.10 Merge] Fix serial to parallel chunked dataset file space allocation bug (#3394)
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug, Branch - 1.10

#3476 [1.12 Merge] Fix serial to parallel chunked dataset file space allocation bug (#3394)
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug, Branch - 1.12

#3474 [1.14 Merge] Update VOL CMake for REST VOL
  CMakeVOL.cmake
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Branch - 1.14

#3467 [1.14 Merge] Fix serial to parallel chunked dataset file space allocation bug (#3394)
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.14

#3479 Revert "[1.10 Merge] Fix serial to parallel chunked dataset file spac…
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.10

#3468 [1.14 Merge] Fix ph5diff tests for MPIEXEC_MAX_NUMPROCS=1 (#3407)
  examples/CMakeTests.cmake
  tools/src/h5diff/ph5diff_main.c
  tools/test/h5diff/CMakeTests.cmake
Labels: Merge, Priority - 2. Medium ⏹, Component - Tools, Component - Testing, Type - Bug, Branch - 1.14

#3469 [1.14 Merge] Avoid H5Ocopy in h5repack for variable-length string types (#3419)
  tools/src/h5repack/h5repack_copy.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Tools, Type - Bug, Branch - 1.14

#3470 [1.14 Merge] Skip atomicity tests for OpenMPI major versions < 5 (#3421)
  release_docs/RELEASE.txt
  testpar/t_2Gio.c
  testpar/testphdf5.c
Labels: Merge, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Task, Branch - 1.14

#3456 Fix Subfiling VFD IOC assignment bug
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDsubfiling_priv.h
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Bug

#3471 [1.14 Merge] Fix an issue with use of uninitialized memory in trefer_deprec.c test…
  test/trefer_deprec.c
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Type - Bug, Branch - 1.14

#3482 Correct java test dimension
  java/test/TestH5Arw.java
  java/test/TestH5Drw.java
Labels: Priority - 0. Blocker ⛔, Component - Java, Component - Testing, Type - Bug

#3483 Correct dimensions in java test
  java/test/TestH5Arw.java
  java/test/TestH5Drw.java
Labels: Merge, Priority - 0. Blocker ⛔, Component - Java, Component - Testing, Type - Bug, Branch - 1.10

#3484 Correct dimensions in java test
  java/src/jni/h5aImp.c
  java/test/TestH5Arw.java
  java/test/TestH5Drw.java
Labels: Merge, Priority - 0. Blocker ⛔, Component - Java, Component - Testing, Type - Bug, Branch - 1.14

#3485 Correct dimensions in java test
  java/test/TestH5Arw.java
  java/test/TestH5Drw.java
Labels: Merge, Priority - 0. Blocker ⛔, Component - Java, Component - Testing, Type - Bug, Branch - 1.12

#3472 [1.14 Merge] Fix use of uninitialized value in testpar/t_dset.c test (#3423)
  testpar/t_dset.c
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Type - Bug, Branch - 1.14

#3473 [1.14 Merge] Output stderr file in CMake testing on failure (#3431)
  config/cmake/runTest.cmake
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Type - Improvement, Branch - 1.14

#3455 Support CMake VOL builds with FetchContent from local directory
  CMakeVOL.cmake
  doc/cmake-vols-fetchcontent.md
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3486 Revert "Revert "[1.10 Merge] Fix serial to parallel chunked dataset f…
  release_docs/RELEASE.txt
  src/H5Dint.c
  testpar/t_chunk_alloc.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Branch - 1.10

#3488 Prettify the CVE matrix
  CVE_list_1_14.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task, Branch - 1.14

#3487 Revert "Reverts the CVE fixes (#3448)"
  release_docs/RELEASE.txt
  src/H5Dbtree.c
  src/H5Dchunk.c
  src/H5Fsuper_cache.c
  src/H5Gint.c
  src/H5HLcache.c
  tools/src/h5dump/h5dump_ddl.c
  tools/testfiles/tgroup-2.ddl
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Type - Bug, Branch - 1.10

#3454 Fix the Fortran include dir in install config files
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3489 Add footnotes to CVE table
  CVE_list_1_14.md
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Type - Task, Branch - 1.14

#3498 Fix links in RELEASE.txt
  release_docs/RELEASE.txt
Labels: Component - Documentation, Branch - 1.12

#3490 Cherry-pick of CVE fixes from 1.10
  release_docs/RELEASE.txt
  src/H5Dbtree.c
  src/H5Dchunk.c
  src/H5Fsuper_cache.c
  src/H5Gint.c
  src/H5HLcache.c
  src/H5Omessage.c
  tools/src/h5dump/h5dump_ddl.c
  tools/testfiles/tgroup-2.ddl
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Type - Bug, Branch - 1.12

#3492 Convert hbool_t --> bool in examples
  examples/ph5_filtered_writes.c
  examples/ph5_filtered_writes_no_sel.c
  examples/ph5_subfiling.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3499 Fix some minor formatting for consistency
  config/toolchain/build32.cmake
  config/toolchain/clang.cmake
  config/toolchain/crayle.cmake
  config/toolchain/gcc.cmake
  config/toolchain/mingw64.cmake
  config/toolchain/pgi.cmake
Labels: Priority - 3. Low 🔽, Type - Task, Component - Misc

#3508 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Testing, Type - New Feature

#3495 Convert hbool_t --> bool in testpar
  testpar/API/H5_api_async_test_parallel.c
  testpar/API/H5_api_dataset_test_parallel.c
  testpar/API/H5_api_file_test_parallel.c
  testpar/API/H5_api_test_parallel.c
  testpar/API/H5_api_test_parallel.h
  testpar/API/t_bigio.c
  testpar/API/t_coll_chunk.c
  testpar/API/t_dset.c
  testpar/API/t_file.c
  testpar/API/t_file_image.c
  testpar/API/t_filter_read.c
  testpar/API/t_mdset.c
  testpar/API/t_prop.c
  testpar/API/t_shapesame.c
  testpar/API/t_span_tree.c
  testpar/API/testphdf5.c
  testpar/API/testphdf5.h
  testpar/t_2Gio.c
  testpar/t_bigio.c
  testpar/t_cache.c
  testpar/t_cache_image.c
  testpar/t_dset.c
  testpar/t_file.c
  testpar/t_file_image.c
  testpar/t_filter_read.c
  testpar/t_filters_parallel.c
  testpar/t_mdset.c
  testpar/t_pmulti_dset.c
  testpar/t_pread.c
  testpar/t_prop.c
  testpar/t_select_io_dset.c
  testpar/t_shapesame.c
  testpar/t_span_tree.c
  testpar/t_subfiling_vfd.c
  testpar/t_vfd.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3491 Convert hbool_t --> bool in tools
  tools/lib/h5diff.c
  tools/lib/h5diff.h
  tools/lib/h5diff_array.c
  tools/lib/h5diff_attr.c
  tools/lib/h5diff_dset.c
  tools/lib/h5tools.c
  tools/lib/h5tools.h
  tools/lib/h5tools_dump.c
  tools/lib/h5tools_dump.h
  tools/lib/h5tools_error.h
  tools/lib/h5tools_ref.c
  tools/lib/h5tools_str.c
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/lib/h5trav.c
  tools/lib/h5trav.h
  tools/libtest/h5tools_test_utils.c
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump.h
  tools/src/h5dump/h5dump_ddl.c
  tools/src/h5dump/h5dump_extern.h
  tools/src/h5dump/h5dump_xml.c
  tools/src/h5format_convert/h5format_convert.c
  tools/src/h5import/h5import.c
  tools/src/h5jam/h5jam.c
  tools/src/h5jam/h5unjam.c
  tools/src/h5ls/h5ls.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_engine.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack.h
  tools/src/h5repack/h5repack_copy.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_opttable.c
  tools/src/h5repack/h5repack_refs.c
  tools/src/h5repack/h5repack_verify.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5clear.c
  tools/src/misc/h5debug.c
  tools/src/misc/h5delete.c
  tools/src/misc/h5mkgrp.c
  tools/src/misc/h5repart.c
  tools/test/h5copy/h5copygentest.c
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5format_convert/h5fc_chk_idx.c
  tools/test/h5format_convert/h5fc_gentest.c
  tools/test/h5repack/h5repackgentest.c
  tools/test/h5repack/h5repacktst.c
  tools/test/misc/clear_open_chk.c
  tools/test/misc/h5clear_gentest.c
  tools/test/misc/vds/UC_common.h
  tools/test/perform/overhead.c
  tools/test/perform/perf_meta.c
  tools/test/perform/zip_perf.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#3518 [1.14 Merge] Fix Subfiling VFD IOC assignment bug (#3456)
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDsubfiling_priv.h
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#3511 Added new Fortran API wrappers
  fortran/src/H5Dff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5_buildiface.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/H5f90proto.h
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/CMakeLists.txt
  fortran/test/Makefile.am
  fortran/test/fortranlib_test.F90
  fortran/test/fortranlib_test_1_8.F90
  fortran/test/fortranlib_test_F03.F90
  fortran/test/tH5D.F90
  fortran/test/tH5F.F90
  fortran/test/tH5F_F03.F90
  fortran/test/tH5L_F03.F90
  fortran/test/tH5MISC_1_8.F90
  fortran/test/tH5P_F03.F90
  fortran/test/tH5Sselect.F90
  fortran/test/tHDF5_F03.F90
  fortran/testpar/hyper.F90
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/H5DOff.F90
  hl/fortran/src/Makefile.am
  hl/fortran/src/hdf5_hl_fortrandll.def.in
  release_docs/RELEASE.txt
  src/H5Spublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - Improvement

#3519 [1.14 Merge] Support CMake VOL FetchContent builds from local directory
  CMakeVOL.cmake
  doc/cmake-vols-fetchcontent.md
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Branch - 1.14

#3523 misc. fortran fixes for failing CI dailty tests
  fortran/src/H5Fff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Off.F90
  fortran/src/H5Pff.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5D.F90
  fortran/test/tH5L_F03.F90
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#3517 Add missing row for the ROS3 VFD in table #3415
  doxygen/examples/tables/fileDriverLists.dox
  doxygen/examples/tables/propertyLists.dox
  src/H5Fmodule.h
  src/H5Fpublic.h
  src/H5Ppublic.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Bug, Type - Improvement

#3527 fixed nvidia compiler issue
  fortran/test/tH5L_F03.F90
Labels: Priority - 1. High 🔼, Component - Fortran, Type - Bug

#3535 Fix unmatched TAG in H5Dchunk.c macro
  src/H5Dchunk.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#3534 quiet warning on Sunspot (gcc 11.2.0)
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Task

#3500 Add API examples doxygen page
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/IntroHDF5.dox
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#3537 removed C_INT32_T from Fortran APIs
  fortran/src/H5Dff.F90
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/test/tH5D.F90
  fortran/testpar/hyper.F90
  test/chunk_info.c
  test/direct_chunk.c
Labels: Priority - 2. Medium ⏹, Component - Fortran, Component - Testing, Type - Task

#3509 Add NVHPC 23.7 GitHub Actions
  .github/workflows/linux-nvhpc-auto.yml
  .github/workflows/linux-nvhpc.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3538 Remove HD prefix from math functions
  src/H5Bcache.c
  src/H5FDonion.c
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5Fint.c
  src/H5Tconv.c
  src/H5VLnative_token.c
  src/H5Zdeflate.c
  src/H5Zscaleoffset.c
  src/H5private.h
  src/H5system.c
  src/H5timer.c
  test/direct_chunk.c
  test/dsets.c
  test/dt_arith.c
  test/mtime.c
  test/swmr.c
  tools/lib/h5diff_array.c
  tools/test/h5diff/h5diffgentest.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement

#3539 Remove HD prefix from HDlog10 calls
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Parallel, Component - Testing, Type - Bug

#3541 fixed arg to C H5Dwrite_chunk
  fortran/src/H5Dff.F90
Labels: Priority - 2. Medium ⏹, Component - Fortran, Type - Task

#3529 Convert main.yml CI into callable workflows
  .github/workflows/autotools.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/codespell.yml
  .github/workflows/cve.yml
  .github/workflows/h5py.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/linux-icx-auto.yml
  .github/workflows/linux-icx.yml
  .github/workflows/main-auto-par.yml
  .github/workflows/main-auto-spc.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake.yml
  .github/workflows/main.yml
  .github/workflows/netcdf.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement, Component - Misc

#3543 Sync CMake and doxygen changes with develop
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/mccacheinit.cmake
  config/cmake/patch.xml.in
  config/cmake/runTest.cmake
  config/toolchain/build32.cmake
  config/toolchain/clang.cmake
  config/toolchain/crayle.cmake
  config/toolchain/gcc.cmake
  config/toolchain/mingw64.cmake
  config/toolchain/pgi.cmake
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/dox/UsersGuide.dox
  doxygen/img/pchunk_figa.gif
  doxygen/img/pchunk_figb.gif
  doxygen/img/pchunk_figc.gif
  doxygen/img/pchunk_figd.gif
  doxygen/img/pcont_hy_figa.gif
  doxygen/img/pcont_hy_figb.gif
  doxygen/img/pcont_hy_figc.gif
  doxygen/img/pcont_hy_figd.gif
  doxygen/img/ppatt_figa.gif
  doxygen/img/ppatt_figb.gif
  doxygen/img/ppatt_figc.gif
  doxygen/img/ppatt_figd.gif
  doxygen/img/preg_figa.gif
  doxygen/img/preg_figb.gif
  doxygen/img/preg_figc.gif
  doxygen/img/preg_figd.gif
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  java/examples/datasets/CMakeLists.txt
  java/test/TestH5.java
  src/CMakeLists.txt
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Improvement, Branch - 1.10

#3549 Correct names of examples tgz
  bin/release
Labels: Priority - 0. Blocker ⛔, Component - Build, Branch - 1.10, Component - Misc

#3550 Update so numbers for 1.10.11 release.
  config/lt_vers.am
Labels: Branch - 1.10

#3562 Disable warnings as errors
  doxygen/Doxyfile.in
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Branch - 1.10

#3573 Check config on windows for correct wix name
  CMakeInstallation.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.10

#3557 Adds link to h5fuse.sh in testpar for autotools
  .github/workflows/linux-nvhpc.yml
  .github/workflows/main-auto-par.yml
  configure.ac
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfile_int.c
  src/H5FDsubfiling/H5FDsubfiling_priv.h
  src/H5FDsubfiling/H5subfiling_common.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Task

#3563 Some minor formatting and text changes
  doxygen/Doxyfile.in
  doxygen/dox/ExamplesAPI.dox
  fortran/testpar/CMakeTests.cmake
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#3572 Correct comments about H5Z_FILTER_NONE
  c++/src/H5DcreatProp.cpp
  java/src/hdf/hdf5lib/H5.java
  src/H5Pocpl.c
  src/H5Z.c
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3579 fixed function declaration in h5fuse.sh
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#3584 Fixed GH-3554
  src/H5FDs3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Type - Improvement

#3575 Switched from UNTESTED to UNT
  CVE_list_1_14.md
Labels: Branch - 1.14

#3548 Revert the removal of java class H5GroupInfo
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/HDF5GroupInfo.java
Labels: Priority - 0. Blocker ⛔, Component - Java, Branch - 1.12

#3589 Remove h5dwalk.1 man page.
  utils/tools/h5dwalk/h5dwalk.1
Labels: Priority - 3. Low 🔽, Component - Documentation

#3592 Use variable for ignore-eol usage.
  tools/test/h5dump/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.10

#3581 Removed the use of -commons linking option on Darwin
  configure.ac
  fortran/src/H5_ff.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#3594 Fix docs for H5Pset_dxpl_mpio_collective_opt()
  src/H5FDmpio.c
  src/H5FDmpio.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3595 Just print status on CMake below 3.14
  config/cmake/fileCompareTest.cmake
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Branch - 1.10

#3578 Merge CMake,doxygen changes from develop,1.10 branches
  .github/workflows/main.yml
  .github/workflows/netcdf.yml
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/fileCompareTest.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/patch.xml.in
  config/cmake/runTest.cmake
  config/cmake/scripts/HDF5options.cmake
  config/sanitizer/README.md
  config/toolchain/build32.cmake
  config/toolchain/clang.cmake
  config/toolchain/crayle.cmake
  config/toolchain/gcc.cmake
  config/toolchain/mingw64.cmake
  config/toolchain/pgi.cmake
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/img/pchunk_figa.gif
  doxygen/img/pchunk_figb.gif
  doxygen/img/pchunk_figc.gif
  doxygen/img/pchunk_figd.gif
  doxygen/img/pcont_hy_figa.gif
  doxygen/img/pcont_hy_figb.gif
  doxygen/img/pcont_hy_figc.gif
  doxygen/img/pcont_hy_figd.gif
  doxygen/img/ppatt_figa.gif
  doxygen/img/ppatt_figb.gif
  doxygen/img/ppatt_figc.gif
  doxygen/img/ppatt_figd.gif
  doxygen/img/preg_figa.gif
  doxygen/img/preg_figb.gif
  doxygen/img/preg_figc.gif
  doxygen/img/preg_figd.gif
  examples/CMakeTests.cmake
  java/examples/datasets/CMakeLists.txt
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Improvement, Branch - 1.12, Component - Misc

#3593 Sync CMake and doxygen
  CMakeInstallation.cmake
  config/cmake/fileCompareTest.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/patch.xml.in
  config/sanitizer/README.md
  config/toolchain/build32.cmake
  config/toolchain/clang.cmake
  config/toolchain/crayle.cmake
  config/toolchain/gcc.cmake
  config/toolchain/mingw64.cmake
  config/toolchain/pgi.cmake
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/img/pchunk_figa.gif
  doxygen/img/pchunk_figb.gif
  doxygen/img/pchunk_figc.gif
  doxygen/img/pchunk_figd.gif
  doxygen/img/pcont_hy_figa.gif
  doxygen/img/pcont_hy_figb.gif
  doxygen/img/pcont_hy_figc.gif
  doxygen/img/pcont_hy_figd.gif
  doxygen/img/ppatt_figa.gif
  doxygen/img/ppatt_figb.gif
  doxygen/img/ppatt_figc.gif
  doxygen/img/ppatt_figd.gif
  doxygen/img/preg_figa.gif
  doxygen/img/preg_figb.gif
  doxygen/img/preg_figc.gif
  doxygen/img/preg_figd.gif
  fortran/testpar/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Bug, Type - Improvement, Branch - 1.14

#3597 Fix typo: `arange`->`arrange` in src/H5Cmpio.c.
  src/H5Cmpio.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3598 Fix docs for H5Acreate2 and H5Acreate_by_name
  src/H5A.c
  src/H5Apublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3600 Use HDoff_t with lseek consistently
  src/H5FDcore.c
  test/atomic_reader.c
  test/atomic_writer.c
  test/big.c
  test/dsets.c
  test/file_image.c
  test/istore.c
  tools/src/h5jam/h5jam.c
  tools/test/misc/h5clear_gentest.c
  tools/test/perform/iopipe.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Tools, Component - Testing, Type - Improvement

#3601 Clean up Subfiling VFD header doxygen formatting
  src/H5FDsubfiling/H5FDsubfiling.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3590 Remove `sh` to run bash script.
  testpar/t_subfiling_vfd.c
Labels: Priority - 3. Low 🔽, Component - Testing

#3602 Fix potential uninitialized variable
  tools/src/h5perf/sio_engine.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement

#3603 Remove unnecessary assignment in test generator
  tools/test/h5format_convert/h5fc_gentest.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement

#3608 Update bin release
  bin/release
Labels: Component - Build

#3609 Fix typo `proceeses`.
  src/H5FDmpio.c
  testpar/API/t_span_tree.c
  testpar/t_span_tree.c
Labels: Priority - 3. Low 🔽, Component - C Library

#3610 Hard edit on release.txt for consistency.
  release_docs/RELEASE.txt
Labels: Component - Documentation, Branch - 1.12

#3611 Added RELEASE.txt from HDF5 1.10.11 release to HISTORY-1_10.txt.
  release_docs/HISTORY-1_10.txt
Labels: Component - Documentation, Branch - 1.10

#3612 Fixed unused variable in H5CS.c (#3552)
  src/H5CS.c
Labels: Priority - 3. Low 🔽, Component - C Library

#3614 Fix grammar
  src/H5FDmpio.c
Labels: Priority - 3. Low 🔽, Component - C Library

#3616 Removed the use of -commons linking option on Darwin (#3581)
  configure.ac
  fortran/src/H5_ff.F90
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug, Branch - 1.14

#3617 Cleanup unused statements (#3553)
  src/H5Cimage.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#3618 Removed the use of -commons linking option on Darwin (#3581)
  configure.ac
  fortran/src/H5f90global.F90
  release_docs/RELEASE.txt
Labels: Component - Fortran, Component - Build, Branch - 1.12
