Repository HDFGroup/hdf5, pull requests merged in 2023-04, with the labels that each got.

#2632 Avoid suppressing error output for non-tentative file opens
  src/H5Fint.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#2654 chore: make comment consistent
  test/h5test.c
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#2648 CMake - Match Autotools behavior for library instrumentation
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#2628 Synchronize HDF5 tests with VOL tests
  test/tarray.c
  test/tattr.c
  test/tcoords.c
  test/tfile.c
  test/tgenprop.c
  test/th5o.c
  test/th5s.c
  test/titerate.c
  test/tmisc.c
  test/trefer.c
  test/tselect.c
  test/ttime.c
  test/tunicode.c
  test/tvlstr.c
  test/tvltypes.c
  testpar/t_bigio.c
  testpar/t_file.c
  testpar/t_shapesame.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Task

#2643 Update java logger version
  .gitattributes
  CMakeLists.txt
  config/cmake/hdf5-config.cmake.in
  java/examples/datasets/JavaDatasetExample.sh.in
  java/examples/datasets/Makefile.am
  java/examples/datatypes/JavaDatatypeExample.sh.in
  java/examples/datatypes/Makefile.am
  java/examples/groups/JavaGroupExample.sh.in
  java/examples/groups/Makefile.am
  java/examples/intro/JavaIntroExample.sh.in
  java/examples/intro/Makefile.am
  java/lib/ext/slf4j-nop-1.7.33.jar
  java/lib/ext/slf4j-nop-2.0.6.jar
  java/lib/ext/slf4j-simple-1.7.33.jar
  java/lib/ext/slf4j-simple-2.0.6.jar
  java/lib/slf4j-api-1.7.33.jar
  java/lib/slf4j-api-2.0.6.jar
  java/src/Makefile.am
  java/src/hdf/hdf5lib/H5.java
  java/test/Makefile.am
  java/test/junit.sh.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Java, Type - Improvement

#2631 [1.14 Merge] Fix a memory corruption issue in H5S__point_project_simple (#2626)
  release_docs/RELEASE.txt
  src/H5Spoint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2545 Make sure that ONLY_SHARED_LIBS option is correctly set
  CMakeLists.txt
  c++/src/CMakeLists.txt
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  hl/test/CMakeLists.txt
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/CMakeTests.cmake
  tools/lib/CMakeLists.txt
  tools/libtest/CMakeLists.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5import/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5stat/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
  tools/test/misc/vds/CMakeLists.txt
  utils/tools/h5dwalk/CMakeLists.txt
Labels: Merge, Component - Build, Branch - 1.14

#2618 [1.14 Merge] Fix issues with Subfiling VFD IOC selection strategies
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5subfiling_common.c
  testpar/t_subfiling_vfd.c
Labels: Merge, Component - C Library, Component - Testing, Type - Bug, Branch - 1.14

#2681 Update HDF5 version after 1.10.10 release.
  README.md
  c++/src/cpp_doc_config
  config/cmake/scripts/HDF5config.cmake
  config/lt_vers.am
  configure.ac
  java/test/TestH5.java
  release_docs/HISTORY-1_10.txt
  release_docs/RELEASE.txt
  src/H5public.h
  tools/test/h5repack/testfiles/h5repack_layout.h5-plugin_version_test.ddl
Labels: Component - Documentation, Branch - 1.10

#2660 Fix #2598 sanitize leak
  release_docs/RELEASE.txt
  tools/lib/h5trav.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#2672 [1.10 Merge] CMake - Match Autotools behavior for library instrumentation (#2648)
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Branch - 1.10

#2668 [1.10 Merge] Avoid suppressing error output for non-tentative file opens (#2632)
  src/H5Fint.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Branch - 1.10

#2686 Remove dead code hidden behind #ifdef LATER
  src/H5FLprivate.h
  src/H5FOprivate.h
  src/H5RSprivate.h
  src/H5SLprivate.h
  src/H5Sselect.c
  src/H5UCprivate.h
  src/H5VM.c
  test/tattr.c
  test/tfile.c
  testpar/t_dset.c
  tools/lib/h5tools_str.c
  tools/test/perform/zip_perf.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement, Type - Deprecation / Removal

#2661 Remove -Wunused-but-set-variable warnings in tests
  test/dt_arith.c
  test/tattr.c
  test/twriteorder.c
Labels: Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Deprecation / Removal

#2664 Fix a heap buffer overflow during H5D__compact_readvv (GitHub #2606)
  release_docs/RELEASE.txt
  src/H5Dint.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2667 Fix improper include of build directory (#2422, #2621)
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#2679 Add buffer overrun checks to H5O__layout_decode and H5O__sdspace_decode
  release_docs/RELEASE.txt
  src/H5Olayout.c
  src/H5Osdspace.c
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2663 Fix invalid memory access in H5O__ginfo_decode
  release_docs/RELEASE.txt
  src/H5Oginfo.c
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2693 Cache tidy
  src/H5AC.c
  src/H5ACmpio.c
  src/H5C.c
  src/H5Cdbg.c
  src/H5Cimage.c
  src/H5Cmpio.c
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2695 Use additional CPUs in GitHub actions
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#2665 Fix for github issue #2599:
  release_docs/RELEASE.txt
  src/H5Oint.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2701 Change name of test file to avoid conflict
  java/test/TestH5OcopyOld.java
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 1. High 🔼, Component - Java, Type - Improvement

#2708 Fix memory leaks and aborts in H5O EFL decode
  src/H5Oefl.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2707 Fix memory leaks and aborts in H5O EFL decode
  src/H5Oefl.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2711 Refactor cache mark flush dep
  src/H5C.c
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2710 Update HDF-EOS5 workflow to mirror main.yml
  .github/workflows/hdfeos5.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#2709 Fix memory leaks and aborts in H5O EFL decode
  src/H5Oefl.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2675 Fix #2598 sanitize leak
  release_docs/RELEASE.txt
  tools/lib/h5trav.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug, Branch - 1.14

#2673 [1.12 Merge] CMake - Match Autotools behavior for library instrumentation (#2648)
  CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Branch - 1.12

#2717 Identify some options as advanced
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/UserMacros/Windows_MT.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#2703 Change name of test file to avoid conflict
  java/test/TestH5OcopyOld.java
Labels: Merge, Priority - 1. High 🔼, Component - Java, Type - Improvement, Branch - 1.14

#2719 Refactor H5C_entry_in_skip_list
  src/H5C.c
  src/H5Cpkg.h
  src/H5Cprivate.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2720 Fix java depends and pdb lib install
  config/cmake/HDFMacros.cmake
  java/examples/datasets/CMakeLists.txt
  java/examples/datatypes/CMakeLists.txt
  java/examples/groups/CMakeLists.txt
  java/examples/intro/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Java, Component - Build, Type - Bug

#2722 Remove unused macros
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2724 Add a RELEASE.txt note for GH #2605
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Type - Task, Component - Misc

#2697 Fixed GH-2603, heap-buffer-overflow in H5O__linfo_decode
  release_docs/RELEASE.txt
  src/H5Olinfo.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2706 Fix for github issue #2599: (#2665)
  release_docs/RELEASE.txt
  src/H5Oint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2691 Fix out of bounds in `hdf5/src/H5Fint.c:2859`
  release_docs/RELEASE.txt
  src/H5Fsuper_cache.c
  src/H5Gent.c
  src/H5Gprivate.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2725 [1.14 Merge] Fix a heap buffer overflow during H5D__compact_readvv (GitHub #2606) …
  release_docs/RELEASE.txt
  src/H5Dint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2735 Fix for github issue #2599: (#2665)
  release_docs/RELEASE.txt
  src/H5Oint.c
Labels: Branch - 1.12

#2745 Remove 1.10 release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.10, Component - Misc

#2744 Remove 1.12 release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.12, Component - Misc

#2743 Remove 1.14 release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.14, Component - Misc

#2742 Merge "Use additional CPUs" and related fixes
  .github/workflows/main.yml
  config/cmake/HDFMacros.cmake
  java/examples/datasets/CMakeLists.txt
  java/examples/datatypes/CMakeLists.txt
  java/examples/groups/CMakeLists.txt
  java/examples/intro/CMakeLists.txt
Labels: Merge, Priority - 1. High 🔼, Component - Java, Component - Testing, Type - Improvement, Component - Misc

#2736 Fix for github issue #2599: (#2665)
  release_docs/RELEASE.txt
  src/H5Oint.c
Labels: Branch - 1.10

#2723 Fix memory leaks when processing OH cont messages
  release_docs/RELEASE.txt
  src/H5Ocache.c
  src/H5Ocont.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2734 [1.10 Merge] H5O__pline_decode() Make more resilient to out-of-bounds read (#2210)
  release_docs/RELEASE.txt
  src/H5Opline.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2733 [1.12 Merge] H5O__pline_decode() Make more resilient to out-of-bounds read (#2210)
  release_docs/RELEASE.txt
  src/H5Opline.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2728 [1.14 Merge] Add buffer overrun checks to H5O__layout_decode and H5O__sdspace_deco…
  release_docs/RELEASE.txt
  src/H5Olayout.c
  src/H5Osdspace.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2726 [1.12 Merge] Fix a heap buffer overflow during H5D__compact_readvv (GitHub #2606) …
  release_docs/RELEASE.txt
  src/H5Dint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2727 [1.10 Merge] Fix a heap buffer overflow during H5D__compact_readvv (GitHub #2606) …
  release_docs/RELEASE.txt
  src/H5Dint.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2729 [1.12 Merge] Add buffer overrun checks to H5O__layout_decode and H5O__sdspace_deco…
  release_docs/RELEASE.txt
  src/H5Olayout.c
  src/H5Osdspace.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2730 [1.10 Merge] Add buffer overrun checks to H5O__layout_decode and H5O__sdspace_deco…
  release_docs/RELEASE.txt
  src/H5Olayout.c
  src/H5Osdspace.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2751 Remove author and date from RELEASE.txt entries
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.14, Component - Misc

#2752 Remove author and date from RELEASE.txt entries
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.12, Component - Misc

#2753 Remove author and date from RELEASE.txt entries
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Type - Improvement, Branch - 1.10, Component - Misc

#2750 H5Spoint.c: Fix mistake in comment
  src/H5Spoint.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2748 Sanitize the attribute info message decode fxn
  src/H5Oainfo.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2754 Sanitize B-tree k ohdr message decode call
  src/H5Obtreek.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2712 Check for invalid AAPL in H5Aopen
  src/H5VLnative_attr.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#2768 Update concurrency group for main CI workflow
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Type - Improvement

#2770 [1.14 Merge] Check for invalid AAPL in H5Aopen (#2712)
  src/H5VLnative_attr.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.14

#2771 [1.12 Merge] Check for invalid AAPL in H5Aopen (#2712)
  src/H5VLnative_attr.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.12

#2769 Clean up memory allocated when reading messages in H5Dlayout on error
  release_docs/RELEASE.txt
  src/H5Dlayout.c
Labels: Merge - To 1.14, Type - Bug, Branch - 1.14

#2756 Add no subsets option to h5diff like h5dump
  release_docs/RELEASE.txt
  tools/lib/h5diff.h
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#2759 Add no subsets option to h5diff like h5dump
  release_docs/RELEASE.txt
  tools/lib/h5diff.h
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
Labels: Merge, Priority - 1. High 🔼, Component - Tools, Type - Bug, Branch - 1.14

#2763 Fixed heap-buffer-overflow in H5O__linfo_decode
  release_docs/RELEASE.txt
  src/H5Olinfo.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2758 Fixed heap-buffer-overflow in H5O__linfo_decode
  release_docs/RELEASE.txt
  src/H5Olinfo.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2755 Clean up H5Oefl decode function
  src/H5Oefl.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2773 Add new version of COPYING_LBNL_HDF5.
  COPYING_LBNL_HDF5
Labels: Merge - To 1.12, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task

#2775 Add new version of COPYING_LBNL_HDF5.
  COPYING_LBNL_HDF5
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task, Branch - 1.14

#2776 Add new version of COPYING_LBNL_HDF5.
  COPYING_LBNL_HDF5
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task, Branch - 1.12

#2762 Sanitize the ohdr modification time decode fxns
  src/H5Omtime.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2760 Add no subsets option to h5diff like h5dump
  release_docs/RELEASE.txt
  tools/lib/h5diff.c
  tools/lib/h5diff.h
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
Labels: Merge, Component - Tools, Type - Bug, Branch - 1.12

#2749 Sanitize the attribute object header msg code
  src/H5Oattr.c
  test/titerate.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2715 Added Fortran Async APIs
  doxygen/aliases
  fortran/src/CMakeLists.txt
  fortran/src/H5Af.c
  fortran/src/H5Aff.F90
  fortran/src/H5Df.c
  fortran/src/H5Dff.F90
  fortran/src/H5ESff.F90
  fortran/src/H5Eff.F90
  fortran/src/H5Ff.c
  fortran/src/H5Fff.F90
  fortran/src/H5Gf.c
  fortran/src/H5Gff.F90
  fortran/src/H5Lf.c
  fortran/src/H5Lff.F90
  fortran/src/H5Of.c
  fortran/src/H5Off.F90
  fortran/src/H5Pff.F90
  fortran/src/H5Rff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5Tff.F90
  fortran/src/H5VLff.F90
  fortran/src/H5_buildiface.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90global.F90
  fortran/src/H5f90proto.h
  fortran/src/HDF5.F90
  fortran/src/Makefile.am
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/Makefile.am
  fortran/test/tH5A_1_8.F90
  fortran/test/tH5G_1_8.F90
  fortran/test/tf.F90
  fortran/testpar/CMakeLists.txt
  fortran/testpar/Makefile.am
  fortran/testpar/async.F90
  fortran/testpar/ptest.F90
  fortran/testpar/subfiling.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - New Feature

#2792 Add new version of COPYING_LBNL_HDF5. (#2773)
  COPYING_LBNL_HDF5
Labels: Branch - 1.10

#2794 docs: change Powershell to PowerShell
  doc/getting-started-with-hdf5-development.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#2788 Add bug note to H5Dget_space_status documentation
  src/H5Dpublic.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Task

#2784 docs: remove signature requirement from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#2778 Correct CMake option defaults - deprecate szip for libaec
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/mccacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Improvement, Type - Deprecation / Removal

#2796 2my feature select io tconv
  src/H5CX.c
  src/H5CXprivate.h
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dcontig.c
  src/H5Defl.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dpkg.h
  src/H5Dprivate.h
  src/H5Dvirtual.c
  src/H5Pdxpl.c
  src/H5Ppublic.h
  test/select_io_dset.c
  testpar/t_2Gio.c
  testpar/t_dset.c
  testpar/t_select_io_dset.c
Labels: Component - C Library

#2798 Fix ROS3 VFD anonymous credential usage with h5dump and h5ls
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#2786 Correct CMake option defaults - deprecate szip for libaec
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/mccacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Improvement, Type - Deprecation / Removal, Branch - 1.14

#2801 Add release note for ROS3 VFD anonymous credential fix
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#2804 Fix hdfeos5 workflow concurrency conflicts
  .github/workflows/hdfeos5.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#2795 Sanitize object header message decode functions
  src/H5Obogus.c
  src/H5Ocache_image.c
  src/H5Odrvinfo.c
  src/H5Ofill.c
  src/H5Ofsinfo.c
  src/H5Oginfo.c
  src/H5Olayout.c
  src/H5Olinfo.c
  src/H5Olink.c
  src/H5Opline.c
  src/H5Orefcount.c
  src/H5Osdspace.c
  src/H5Oshmesg.c
  src/H5Ostab.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2797 H5Odtype.c decode cleanup
  src/H5Odtype.c
  test/dtypes.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2808 Sanitize H5HG cache deserialization code
  src/H5HGcache.c
  src/H5HGpkg.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2807 Allow H5P_DEFAULT in H5Pget_vol_cap_flags and H5Pget_vol_id
  release_docs/RELEASE.txt
  src/H5Pfapl.c
  test/vol.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#2826 Fix hdfeos5 workflow concurrency conflicts (#2804)
  .github/workflows/hdfeos5.yml
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Type - Task, Branch - 1.14

#2810 Harden H5G cache deserialization
  src/H5Gcache.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2806 H5fuse.sh optimization updates
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Parallel, Type - Improvement

#2817 Add support for CMakePresets and fix example download
  .gitignore
  CMakeInstallation.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/ConfigureChecks.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Component - Build, Type - Improvement, Type - New Feature

#2785 Fix v1 object header gap bug in H5Ocopy
  release_docs/RELEASE.txt
  src/H5Ocopy.c
  test/objcopy.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2809 Harden superblock cache deserialization
  src/H5Fsuper_cache.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2683 Subfiling VFD - check if MPI is finalized during VFD termination
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#2838 Correct compression install files
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Bug

#2839 Update H5Dget_space_status bug note to reference 1.14.0
  src/H5Dpublic.h
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#2849 Sync with develop
  .gitignore
  CMakeInstallation.cmake
  CMakePresets.json
  CONTRIBUTING.md
  config/cmake-presets/hidden-presets.json
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  doc/getting-started-with-hdf5-development.md
  fortran/test/tH5T_F03.F90
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5Bcache.c
  src/H5Bpkg.h
  src/H5Bprivate.h
  src/H5Dpublic.h
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5Fsuper_cache.c
  src/H5Gcache.c
  src/H5HGcache.c
  src/H5HGpkg.h
  src/H5HLcache.c
  src/H5Obogus.c
  src/H5Ocache_image.c
  src/H5Ocopy.c
  src/H5Odrvinfo.c
  src/H5Odtype.c
  src/H5Ofill.c
  src/H5Ofsinfo.c
  src/H5Oginfo.c
  src/H5Olayout.c
  src/H5Olinfo.c
  src/H5Olink.c
  src/H5Opline.c
  src/H5Orefcount.c
  src/H5Osdspace.c
  src/H5Oshmesg.c
  src/H5Ostab.c
  src/H5Pfapl.c
  test/dtypes.c
  test/objcopy.c
  test/vol.c
  testpar/t_subfiling_vfd.c
  utils/subfiling_vfd/h5fuse.sh.in
Labels: Merge, Priority - 0. Blocker ⛔, Type - Task, Branch - 1.14

#2823 Implement selection I/O with type conversion
  bin/trace
  doxygen/examples/tables/propertyLists.dox
  release_docs/RELEASE.txt
  src/H5.c
  src/H5CX.c
  src/H5CXprivate.h
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dcontig.c
  src/H5Defl.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dpkg.h
  src/H5Dprivate.h
  src/H5Dscatgath.c
  src/H5Dvirtual.c
  src/H5FDint.c
  src/H5Fprivate.h
  src/H5Fquery.c
  src/H5Pdxpl.c
  src/H5Ppublic.h
  src/H5Sprivate.h
  src/H5Spublic.h
  src/H5Sselect.c
  src/H5private.h
  src/H5trace.c
  test/CMakeLists.txt
  test/Makefile.am
  test/enc_dec_plist.c
  test/gen_plist.c
  test/select_io_dset.c
  test/testfiles/plist_files/def_dxpl_32be
  test/testfiles/plist_files/def_dxpl_32le
  test/testfiles/plist_files/def_dxpl_64be
  test/testfiles/plist_files/def_dxpl_64le
  test/testfiles/plist_files/dxpl_32be
  test/testfiles/plist_files/dxpl_32le
  test/testfiles/plist_files/dxpl_64be
  test/testfiles/plist_files/dxpl_64le
  testpar/CMakeLists.txt
  testpar/Makefile.am
  testpar/t_2Gio.c
  testpar/t_coll_chunk.c
  testpar/t_dset.c
  testpar/t_select_io_dset.c
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Component - C Library, Component - Documentation, Component - Parallel, Component - Testing, Type - New Feature

#2842 Convert H5D asserts to normal error checking
  src/H5Dbtree.c
  src/H5Dchunk.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2855 Don't use strnlen when len is not known
  src/H5Odtype.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#2843 Add DT workflow for creating daily binaries
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  CMakePresets.json
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Component - Build, Type - Improvement, Type - New Feature

#2853 Add Fortran Selection IO APIs
  doxygen/aliases
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/H5_test_buildiface.F90
  fortran/test/fortranlib_test.F90
  fortran/test/tH5P.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - New Feature

#2857 Fix TRACE macros in selection I/O plist calls
  src/H5Pdxpl.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Improvement

#2833 Fix v1 object header gap bug in H5Ocopy (#2785)
  release_docs/RELEASE.txt
  src/H5Ocopy.c
  test/objcopy.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.12

#2834 Fix v1 object header gap bug in H5Ocopy (#2785)
  release_docs/RELEASE.txt
  src/H5Ocopy.c
  test/objcopy.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.10

#2860 Remove selection I/O test from testphdf5 in CMake
  testpar/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#2859 Fix memory leaks in H5Dwrite w/ selection I/O
  src/H5Dio.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug

#2858 Use powershell shell to copy files
  .github/workflows/cmake-ctest.yml
Labels: Priority - 3. Low 🔽, Component - Build, Type - Bug

#2761 Add no subsets option to h5diff like h5dump
  release_docs/RELEASE.txt
  tools/lib/h5diff.h
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
Labels: Merge, Priority - 1. High 🔼, Component - Tools, Type - Bug, Branch - 1.10

#2811 Clean up memory allocated when reading messages in H5Dlayout on error
  release_docs/RELEASE.txt
  src/H5Dlayout.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.12

#2819 Add support for CMakePresets and fix example download
  .gitignore
  CMakeInstallation.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Component - Build, Type - Improvement, Type - New Feature, Branch - 1.12

#2836 Add bug note to H5Dget_space_status documentation (#2788)
  src/H5Dpublic.h
Labels: Merge, Priority - 2. Medium ⏹, Component - Documentation, Type - Task, Branch - 1.12

#2837 Add bug note to H5Dget_space_status documentation (#2788)
  src/H5Dpublic.h
Labels: Merge, Priority - 2. Medium ⏹, Component - Documentation, Type - Task, Branch - 1.10

#2847 Correct compression install files
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Build, Type - Bug, Branch - 1.12

#2813 Clean up memory allocated when reading messages in H5Dlayout on error
  release_docs/RELEASE.txt
  src/H5Dlayout.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.10
