Repository HDFGroup/hdf5, pull requests merged in 2023-06, with the labels that each got.

#3038 Add casts to type conversion to fix long dbl bug
  src/H5Tconv.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#3016 Print out the VOL connector being used in the ASYNC test
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/H5f90proto.h
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tf.F90
  fortran/testpar/async.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Component - Fortran, Component - Testing, Type - Improvement

#3051 Fix multiConfig variable usage and remove unused CMake vars
  CMakeLists.txt
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDF5_Examples.cmake.in
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/grepTest.cmake
  config/cmake/jrunTest.cmake
  config/cmake/runTest.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Bug, Branch - 1.10

#3045 Remove most unused options which are defaulted #2998
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/examples/tables/propertyLists.dox
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Type - Bug, Branch - 1.14

#3046 Remove most unused options which are defaulted #2998
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/H5Pget_metadata_read_attempts.2.c
  doxygen/examples/H5Pget_metadata_read_attempts.3.c
  doxygen/examples/H5Pset_metadata_read_attempts.c
  doxygen/examples/ImageSpec.html
  doxygen/examples/tables/propertyLists.dox
  doxygen/hdf5_navtree_hacks.js
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Type - Bug, Branch - 1.12

#3042 Update actions and change defaults of compression (fix vars)
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePresets.json
  config/cmake/CTestCustom.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Type - Improvement, Type - Task, Branch - 1.14

#3043 Update actions and change defaults of compression (fix vars)
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePresets.json
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake_ext_mod/HDFMacros.cmake
  configure.ac
  release_docs/INSTALL_CMake.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Branch - 1.12

#3047 Remove most unused options which are defaulted #2998
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/ImageSpec.html
  doxygen/examples/tables/propertyLists.dox
  doxygen/hdf5_navtree_hacks.js
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Type - Bug, Branch - 1.10

#3041 Develop gh doxy
  .github/workflows/cmake-ctest.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Improvement

#3052 Bring key merges from develop
  .github/workflows/main.yml
  config/cmake/HDF5_Examples.cmake.in
  config/cmake/jrunTest.cmake
  config/cmake_ext_mod/grepTest.cmake
  config/cmake_ext_mod/runTest.cmake
  configure.ac
  java/src/jni/h5lImp.c
  release_docs/RELEASE.txt
  src/H5FDtest.c
  src/H5Tconv.c
  test/accum_swmr_reader.c
  test/swmr.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Java, Component - Testing, Component - Build, Type - Task, Branch - 1.12

#3044 Update actions and change defaults of compression (fix vars)
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  CMakeFilters.cmake
  CMakePresets.json
  config/cmake/HDF5PluginCache.cmake
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Improvement, Branch - 1.10

#3040 Move encode/decode macros to a new header
  src/CMakeLists.txt
  src/H5B2cache.c
  src/H5B2test.c
  src/H5Cepoch.c
  src/H5Cprefetched.c
  src/H5Ctag.c
  src/H5D.c
  src/H5Dint.c
  src/H5Dselect.c
  src/H5FDint.c
  src/H5FDonion_header.c
  src/H5FDonion_history.c
  src/H5FDonion_index.c
  src/H5Fprivate.h
  src/H5Gnode.c
  src/H5HFbtree2.c
  src/H5HFcache.c
  src/H5HFhuge.c
  src/H5HGcache.c
  src/H5HL.c
  src/H5HLcache.c
  src/H5Ocopy_ref.c
  src/H5Odeprec.c
  src/H5Ofsinfo.c
  src/H5Olayout.c
  src/H5Pdapl.c
  src/H5Pdxpl.c
  src/H5Plapl.c
  src/H5Pocpl.c
  src/H5Rdeprec.c
  src/H5Tref.c
  src/H5VLnative_dataset.c
  src/H5encode.h
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3053 CMake build is missing H5FDsubfiling.h #3037
  src/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Type - Bug

#3060 HDF5Array arrayify is missing break statement #3056
  java/src/hdf/hdf5lib/HDFArray.java
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Java, Type - Bug

#3059 Fix doxygen comments in structure and enable FAIL_ON_WARNINGS
  doxygen/Doxyfile.in
  src/H5FDpublic.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Testing, Component - Build, Type - Improvement

#3055 Correct path for doxygen files
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Component - Testing, Component - Build, Type - Bug

#2981 ci: add netcdf action (#2934)
  .github/workflows/netcdf.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3065 Add netCDF and HDF-EOS5 badges to README.md
  README.md
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3066 Update the release schedule for 1.12.3
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - Develop Only, Priority - 1. High 🔼, Type - Task, Component - Misc

#3062 Move config/cmake_ext_mod content to config/cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  c++/examples/CMakeTests.cmake
  c++/test/CMakeTests.cmake
  config/cmake/CTestCustom.cmake
  config/cmake/ConfigureChecks.cmake
  config/cmake/FindSZIP.cmake
  config/cmake/GetTimeOfDayTest.cpp
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/HDFTests.c
  config/cmake/HDFUseFortran.cmake
  config/cmake/NSIS.InstallOptions.ini.in
  config/cmake/NSIS.template.in
  config/cmake/grepTest.cmake
  config/cmake/hdf.bmp
  config/cmake/hdf.icns
  config/cmake/hdf.ico
  config/cmake/runTest.cmake
  config/cmake/version.plist.in
  config/cmake_ext_mod/CTestCustom.cmake
  config/cmake_ext_mod/ConfigureChecks.cmake
  examples/CMakeTests.cmake
  fortran/examples/CMakeTests.cmake
  fortran/test/CMakeTests.cmake
  hl/c++/examples/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/examples/CMakeTests.cmake
  hl/fortran/examples/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  hl/tools/h5watch/CMakeTests.cmake
  java/CMakeLists.txt
  test/CMakeTests.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/perform/CMakeTests.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Task, Branch - 1.12

#3063 Bring gcc/clang attribute and warning macros over
  src/H5private.h
  src/H5public.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Task, Branch - 1.12

#3069 Update README.md
  README.md
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Documentation, Type - Task

#3067 Fix MSVC 32/64 bit shift conversion warnings
  src/H5SL.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3068 Remove Win32 POSIX redefinitions
  src/H5win32defs.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3072 Remove ref to format_source_patch
  bin/format_source
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Type - Improvement, Component - Misc

#3075 add autotools generated files for codespell to skip
  .github/workflows/codespell.yml
Labels: Priority - 2. Medium ⏹, Type - Improvement, Branch - 1.12, Component - Misc

#3073 Minor normalization w/ develop
  Makefile.am
  autogen.sh
  bin/checkposix
  bin/chkcopyright
  bin/genparser
  bin/h5vers
  bin/release
  bin/restore.sh
  bin/warnhist
  configure.ac
  hl/src/H5LTanalyze.c
  hl/src/H5LTparse.c
Labels: Merge, Priority - 1. High 🔼, Component - High-Level Library, Component - Build, Type - Task, Branch - 1.12, Component - Misc

#3079 Don't use -fstdarg-opt with clang-tidy
  config/cmake/HDFCompilerFlags.cmake
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3028 ci: add h5py action (#2986)
  .github/workflows/h5py.yml
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Fortran, Component - Parallel, Component - Testing, Component - Build, Type - Task

#3085 Added new HDF5 logo and minor text and link changes to README.md
  README.md
  doxygen/img/HDF5.png
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3081 Minor cleanup of H5detect.c
  src/H5detect.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3093 Remove template title text ([BUG], etc.)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Type - Task, Component - Misc

#3092 Adds a release note for Autoconf 2.71 bump
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Type - Task, Branch - 1.12

#3090 Build the ros3 VFD in GitHub actions
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3095 Add cross-compile defaults to Autotools
  configure.ac
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3094 Fix misc warnings on Windows
  src/H5Iint.c
  src/H5T.c
  src/H5system.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3101 Fixed typo: hdf5-examples should be hdf5_examples in a link
  doxygen/dox/LearnBasics3.dox
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#3096 Make some changes to configure.ac to support MinGW
  config/cmake/H5pubconf.h.in
  configure.ac
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3099 Bring MD cache uthash tag list from develop
  src/H5C.c
  src/H5Cpkg.h
  src/H5Ctag.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Improvement, Branch - 1.12

#3098 Remove code paths where `long long` < 8 bytes
  test/big.c
  test/ntypes.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3097 Remove long double conversion work-arounds
  config/cmake/ConfigureChecks.cmake
  config/cmake/ConversionTests.c
  config/cmake/H5pubconf.h.in
  configure.ac
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tconv.c
  src/H5Tpkg.h
  test/dt_arith.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Deprecation / Removal

#3111 Add Mark Kittisopikul to CODEOWNERS
  .github/CODEOWNERS
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Type - Task

#3107 Fix the default for API_VERSION to only allow one default
  CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Type - Bug

#3108 Fix the default for API_VERSION to only allow one default
  CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Type - Bug, Branch - 1.14

#3109 Fix doxygen and actions - merge from develop
  .github/workflows/cmake-ctest.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/LearnBasics3.dox
  fortran/src/H5Aff.F90
  fortran/src/H5Dff.F90
  fortran/src/H5ESff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Gff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Off.F90
  fortran/src/H5Pff.F90
  fortran/src/H5Tff.F90
  fortran/src/H5VLff.F90
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/HDFArray.java
  java/src/jni/h5Constants.c
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5lImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5util.c
  src/H5FDpublic.h
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Component - Fortran, Type - Bug, Branch - 1.14

#3110 Rework tools.cmake and add C flags
  config/sanitizer/tools.cmake
Labels: WIP, Priority - 3. Low 🔽, Component - Testing, Component - Build, Type - New Feature

#3102 Fix gh pages so that the doxygen files are uploaded
  .github/workflows/release.yml
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Testing, Component - Build, Type - Bug, Type - Improvement

#3112 Fix a misc warning in test/vol.c
  test/vol.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3104 Remove H5detect and H5make_libsettings
  CMakeLists.txt
  bin/batch/knl_H5detect.sl.in.cmake
  bin/checkposix
  config/cmake/libhdf5.settings.cmake.in
  configure.ac
  release_docs/INSTALL_CMake.txt
  release_docs/README_HPC
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5.c
  src/H5T.c
  src/H5Tinit_float.c
  src/H5Tmodule.h
  src/H5Tpkg.h
  src/H5Tpublic.h
  src/H5build_settings.autotools.c.in
  src/H5build_settings.cmake.c.in
  src/H5build_settings.off.c.in
  src/H5detect.c
  src/H5make_libsettings.c
  src/H5private.h
  src/Makefile.am
  src/libhdf5.settings.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Improvement

#3113 clang-tidy clang-analyzer-core issues addressed
  src/H5system.c
  src/H5trace.c
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3117 Add note for issue 3056
  release_docs/RELEASE.txt
Labels: Priority - 1. High 🔼, Component - Documentation

#3116 Use 1.14 toolchain
  config/toolchain/aarch64.cmake
Labels: Component - Build, Type - Improvement

#3115 merges from develop
  .github/workflows/release.yml
  config/cmake/HDFCompilerFlags.cmake
  config/sanitizer/tools.cmake
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  tools/test/h5copy/testh5copy.sh.in
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Branch - 1.14

#3120 Remove unused HD macros
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  configure.ac
  src/H5private.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Build, Type - Deprecation / Removal

#3119 Adds an optional version arg to bin/format_source
  bin/format_source
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Type - Improvement, Component - Misc

#3121 Clean up mirror VFD code in utils dir
  utils/mirror_vfd/mirror_remote.c
  utils/mirror_vfd/mirror_remote.h
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_server_stop.c
  utils/mirror_vfd/mirror_writer.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3126 Sync fortran src files with develop
  fortran/src/H5Of.c
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/H5f90proto.h
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5G_1_8.F90
  fortran/test/tH5I.F90
  fortran/test/tH5P_F03.F90
  fortran/test/tH5T_F03.F90
  fortran/test/tf.F90
  fortran/testpar/async.F90
  src/H5Fpublic.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug, Branch - 1.14

#3130 Fix spelling issues flagged by codespell
  test/dt_arith.c
  test/onion.c
  test/test_error.sh.in
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3129 chore: add Python for HDF-EOS zoo description
  doxygen/dox/IntroHDF5.dox
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3131 chore: match documentation and function name
  test/s3comms.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Documentation, Type - Improvement

#3133 Revert long double checks
  config/cmake/ConfigureChecks.cmake
  config/cmake/ConversionTests.c
  config/cmake/H5pubconf.h.in
  configure.ac
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tconv.c
  src/H5Tpkg.h
  test/dt_arith.c
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#3127 Add java options to build scripts
  bin/buildhdf5
  bin/cmakehdf5
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3136 Add java options to build scripts
  bin/buildhdf5
  bin/cmakehdf5
  test/dt_arith.c
  test/onion.c
  test/test_error.sh.in
Labels: Priority - 2. Medium ⏹, Component - Build, Branch - 1.14

#3137 Add java options to build scripts
  bin/buildhdf5
  bin/cmakehdf5
  test/dt_arith.c
  test/testerror.sh.in
Labels: Priority - 2. Medium ⏹, Component - Build, Branch - 1.12

#3138 Add java options to build scripts
  bin/buildhdf5
  bin/cmakehdf5
  test/dt_arith.c
  test/test_error.sh.in
Labels: Priority - 2. Medium ⏹, Component - Build, Branch - 1.10

#3134 Some minor version text changes
  .github/workflows/release.yml
  config/cmake/runTest.cmake
  config/cmake/scripts/HDF5config.cmake
  test/onion.c
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Testing, Branch - 1.14

#3143 Removed .lnt linter files
  src/hdf5-lin.lnt
  src/hdf5-win.lnt
  src/hdf5.lnt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Deprecation / Removal, Component - Misc

#3140 Fix path to libhdf5.settings in cmakehdf5
  bin/cmakehdf5
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3142 Remove HD prefix from network calls
  src/H5FDmirror.c
  src/H5private.h
  test/mirror_vfd.c
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_server_stop.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Deprecation / Removal

#3145 Remove hbool_t/TRUE/FALSE from java
  java/src/jni/h5Constants.c
  java/src/jni/h5Imp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5fImp.c
  java/src/jni/h5iImp.c
  java/src/jni/h5jni.h
  java/src/jni/h5lImp.c
  java/src/jni/h5oImp.c
  java/src/jni/h5pDCPLImp.c
  java/src/jni/h5pDXPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5pFCPLImp.c
  java/src/jni/h5pOCPLImp.c
  java/src/jni/h5util.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Java, Type - Improvement

#3146 CMake: (feature) ROS3 and cmake config file.
  config/cmake/hdf5-config.cmake.in
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#3147 Define minimal permissions for new GitHub workflows
  .github/workflows/daily-build.yml
  .github/workflows/h5py.yml
  .github/workflows/netcdf.yml
  .github/workflows/release.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Type - Improvement, Component - Misc

#3139 Track s3 i/o when S3COMMS_DEBUG enabled
  src/H5FDs3comms.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3148 Fix the snapshots workflow
  .github/workflows/cmake-ctest.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#3149 Removes the HD prefix from java C99 calls
  java/src/jni/exceptionImp.c
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5eImp.c
  java/src/jni/h5fImp.c
  java/src/jni/h5iImp.c
  java/src/jni/h5jni.h
  java/src/jni/h5lImp.c
  java/src/jni/h5oImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pDCPLImp.c
  java/src/jni/h5pDXPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5pLAPLImp.c
  java/src/jni/h5plImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5sImp.c
  java/src/jni/h5tImp.c
  java/src/jni/h5util.c
  java/src/jni/h5vlImp.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Java, Type - Improvement

#3153 Correct the zip usage
  .github/workflows/release.yml
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc

#3152 Create Security Policy
  SECURITY.md
Labels: Priority - 1. High 🔼, Type - Improvement, Type - New Feature, Component - Misc

#3135 Various merges from develop
  .github/workflows/cmake-ctest.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  CMakeFilters.cmake
  config/cmake/ConfigureChecks.cmake
  config/cmake/FindSZIP.cmake
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFTests.c
  config/cmake/UserMacros/Windows_MT.cmake
  config/cmake/scripts/HDF5options.cmake
  config/sanitizer/tools.cmake
  configure.ac
  doc/branches-explained.md
  doxygen/Doxyfile.in
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/examples/menus/core_menu.md
  doxygen/examples/tables/predefinedDatatypes.dox
  fortran/src/H5Lff.F90
  java/examples/datasets/CMakeLists.txt
  java/examples/datatypes/CMakeLists.txt
  java/examples/groups/CMakeLists.txt
  java/examples/intro/CMakeLists.txt
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/HDF5GroupInfo.java
  java/src/hdf/hdf5lib/HDFArray.java
  java/src/jni/h5fImp.c
  java/src/jni/h5lImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5tImp.c
  m4/aclocal_fc.f90
  release_docs/RELEASE.txt
  src/H5Dpublic.h
  src/H5Fpublic.h
  src/H5Tmodule.h
  src/H5Tpublic.h
Labels: Component - C Library, Component - Documentation, Component - Java, Component - Fortran, Component - Build, Branch - 1.10

#3154 Update github files/workflow from develop
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Merge, Priority - 1. High 🔼, Branch - 1.14, Component - Misc

#3156 Update github files/workflow from develop
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
Labels: Merge, Priority - 1. High 🔼, Type - Improvement, Branch - 1.10, Component - Misc

#3161 Remove duplicate code
  fortran/src/H5Pff.F90
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Bug, Branch - 1.12

#3162 Fix #1978 h5vers usage message and update Platforms Tested in RELEASE.txt
  bin/h5vers
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Task

#3087 speed-up building HDF5
  .github/workflows/hdfeos5.yml
  .github/workflows/netcdf.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3163 Remove dead code behind #ifdef OLD_WAY
  src/H5B2.c
  src/H5Dio.c
  src/H5HG.c
  test/h5test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Deprecation / Removal

#3165 Remove H5F_evict_tagged_metadata()
  src/H5AC.c
  src/H5Fio.c
  src/H5Fprivate.h
  src/H5Fsuper.c
  src/H5Oflush.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3167 Add missing space in zip command
  .github/workflows/release.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#3168 Add missing space in zip command
  .github/workflows/release.yml
Labels: Merge, Branch - 1.14, Component - Misc

#3170 Add missing space in zip command
  .github/workflows/release.yml
Labels: Merge, Branch - 1.10, Component - Misc

#3164 Fixed check for a VOL's async compatibility
  fortran/testpar/async.F90
Labels: Component - Fortran, Component - Testing

#3173 Update Linux workflows
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#3175 Add gh-pages doxygen link
  README.md
Labels: Merge - Develop Only, Component - Documentation

#3176 Fix the doxygen to gh pages and artifact creation
  .github/workflows/release.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#3181 Tidy the list of options in main.yml
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3182 Remove HD/hbool_t from fortran
  fortran/src/H5Af.c
  fortran/src/H5Df.c
  fortran/src/H5Ef.c
  fortran/src/H5Ff.c
  fortran/src/H5Gf.c
  fortran/src/H5If.c
  fortran/src/H5Lf.c
  fortran/src/H5Lff.F90
  fortran/src/H5Of.c
  fortran/src/H5Pf.c
  fortran/src/H5Rf.c
  fortran/src/H5Sf.c
  fortran/src/H5Tf.c
  fortran/src/H5f90kit.c
  fortran/test/t.c
  fortran/test/tH5A_1_8.F90
  fortran/test/tH5G_1_8.F90
  fortran/test/tH5Sselect.F90
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Fortran, Type - Improvement

#3183 Remove HD/hbool_t from high-level lib
  hl/fortran/src/H5DSfc.c
  hl/fortran/src/H5IMcc.c
  hl/fortran/src/H5IMfc.c
  hl/fortran/src/H5LTfc.c
  hl/fortran/src/H5TBfc.c
  hl/src/H5DO.c
  hl/src/H5DS.c
  hl/src/H5IM.c
  hl/src/H5LD.c
  hl/src/H5LT.c
  hl/src/H5LTanalyze.c
  hl/src/H5LTanalyze.l
  hl/src/H5LTparse.c
  hl/src/H5LTparse.h
  hl/src/H5LTparse.y
  hl/src/H5LTprivate.h
  hl/src/H5PT.c
  hl/src/H5TB.c
  hl/test/gen_test_ds.c
  hl/test/gen_test_ld.c
  hl/test/h5hltest.h
  hl/test/test_ds.c
  hl/test/test_dset_append.c
  hl/test/test_file_image.c
  hl/test/test_h5do_compat.c
  hl/test/test_image.c
  hl/test/test_ld.c
  hl/test/test_lite.c
  hl/test/test_packet.c
  hl/test/test_packet_vlen.c
  hl/test/test_table.c
  hl/tools/gif2h5/hdf2gif.c
  hl/tools/h5watch/extend_dset.c
  hl/tools/h5watch/h5watch.c
  hl/tools/h5watch/h5watchgentest.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - High-Level Library, Component - Fortran, Type - Improvement

#3184 Remove HDva_(arg|copy|end|start)
  src/H5E.c
  src/H5ESint.c
  src/H5Eint.c
  src/H5RS.c
  src/H5private.h
  src/H5system.c
  src/H5trace.c
  test/API/testhdf5.c
  test/h5test.c
  test/testframe.c
  test/thread_id.c
  tools/lib/h5tools_str.c
  tools/lib/h5tools_utils.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_perf.c
  utils/mirror_vfd/mirror_remote.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Testing, Type - Improvement

#3180 Drop HD prefix & hbool_t from H5TS
  src/H5TS.c
  src/H5TSdevelop.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3190 Remove HD from fork/exec*/wait*
  src/H5private.h
  test/accum.c
  test/dt_arith.c
  test/swmr.c
  test/twriteorder.c
  test/use_append_chunk.c
  test/use_append_chunk_mirror.c
  test/use_append_mchunks.c
  testpar/t_subfiling_vfd.c
  utils/mirror_vfd/mirror_server.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Improvement

#3187 Fix assertion failure when attempting to use IOC VFD directly
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDioc.c
  testpar/CMakeTests.cmake
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Bug

#3193 Rename HDqsort() to qsort()
  src/H5Aint.c
  src/H5Cimage.c
  src/H5Dchunk.c
  src/H5Dmpio.c
  src/H5FDint.c
  src/H5FDonion_index.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5Glink.c
  src/H5private.h
  test/API/titerate.c
  test/API/tselect.c
  test/titerate.c
  test/tselect.c
  test/tskiplist.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Improvement

#3159 Add note about HDF5_VOL_CONNECTOR to tools usage
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/misc/h5mkgrp.c
  tools/test/h5diff/testfiles/h5diff_10.txt
  tools/test/h5diff/testfiles/h5diff_600.txt
  tools/test/h5diff/testfiles/h5diff_603.txt
  tools/test/h5diff/testfiles/h5diff_606.txt
  tools/test/h5diff/testfiles/h5diff_612.txt
  tools/test/h5diff/testfiles/h5diff_615.txt
  tools/test/h5diff/testfiles/h5diff_621.txt
  tools/test/h5diff/testfiles/h5diff_622.txt
  tools/test/h5diff/testfiles/h5diff_623.txt
  tools/test/h5diff/testfiles/h5diff_624.txt
  tools/test/misc/testfiles/h5mkgrp_help.txt
  tools/testfiles/h5dump-help.txt
  tools/testfiles/help-1.ls
  tools/testfiles/help-2.ls
  tools/testfiles/help-3.ls
  tools/testfiles/pbits/tnofilename-with-packed-bits.ddl
  tools/testfiles/pbits/tpbitsIncomplete.ddl
  tools/testfiles/pbits/tpbitsLengthExceeded.ddl
  tools/testfiles/pbits/tpbitsLengthPositive.ddl
  tools/testfiles/pbits/tpbitsMaxExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetExceeded.ddl
  tools/testfiles/pbits/tpbitsOffsetNegative.ddl
  tools/testfiles/textlinksrc-nodangle-1.ls
  tools/testfiles/tgroup-1.ls
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#3205 Remove checks for setsysinfo, which is unused
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  configure.ac
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal

#3203 Remove HD from protected POSIX calls
  src/H5private.h
  src/H5system.c
  src/H5timer.c
  test/h5test.c
  test/links.c
  test/testframe.c
  testpar/t_mpi.c
  tools/lib/h5diff.c
  tools/test/perform/iopipe.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement

#3201 Rename HDato*() to ato*()
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5private.h
  test/mirror_vfd.c
  test/swmr_addrem_writer.c
  test/swmr_generator.c
  test/swmr_reader.c
  test/swmr_remove_reader.c
  test/swmr_remove_writer.c
  test/swmr_sparse_reader.c
  test/swmr_sparse_writer.c
  test/swmr_start_write.c
  test/swmr_writer.c
  test/testframe.c
  test/twriteorder.c
  test/use_common.c
  test/use_disable_mdc_flushes.c
  test/vds_swmr_writer.c
  testpar/t_subfiling_vfd.c
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_parse.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5clear.c
  tools/src/misc/h5mkgrp.c
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_server_stop.c
  utils/tools/h5dwalk/h5dwalk.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Testing, Type - Improvement

#3209 Remove some "Programmer" comments
  src/H5B2stat.c
  src/H5B2test.c
  src/H5Dearray.c
  src/H5Dfarray.c
  src/H5Dnone.c
  src/H5Dselect.c
  src/H5Dsingle.c
  src/H5Dtest.c
  src/H5EAtest.c
  src/H5FDstdio.c
  src/H5Fdbg.c
  src/H5Gstab.c
  src/H5Gtest.c
  src/H5HFstat.c
  src/H5HFtest.c
  src/H5HGdbg.c
  src/H5HLdbg.c
  src/H5Obtreek.c
  src/H5Odrvinfo.c
  src/H5Oshmesg.c
  src/H5Otest.c
  src/H5P.c
  src/H5Pencdec.c
  src/H5Pint.c
  src/H5Ptest.c
  src/H5Sselect.c
  src/H5Stest.c
  test/accum.c
  test/btree2.c
  test/cache.c
  test/cache_api.c
  test/cache_common.c
  test/cache_common.h
  test/cache_image.c
  test/cache_tagging.c
  test/cork.c
  test/earray.c
  test/efc.c
  test/fheap.c
  test/genall5.c
  test/genall5.h
  test/hyperslab.c
  test/istore.c
  test/ohdr.c
  testpar/t_cache_image.c
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Parallel, Component - Testing, Type - Deprecation / Removal

#3204 Remove HD from strto* calls
  hl/tools/h5watch/h5watch.c
  src/H5.c
  src/H5AC.c
  src/H5FDmpio.c
  src/H5FDonion.c
  src/H5FDs3comms.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5private.h
  src/H5trace.c
  test/big.c
  test/testframe.c
  test/use_common.c
  testpar/t_subfiling_vfd.c
  tools/lib/h5tools_utils.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5import/h5import.c
  tools/src/h5ls/h5ls.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_engine.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_parse.c
  tools/src/misc/h5debug.c
  tools/src/misc/h5repart.c
  tools/test/perform/zip_perf.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - High-Level Library, Component - Testing, Type - Improvement

#3212 Remove HD from HDis* (e.g., isalpha)
  src/H5.c
  src/H5AC.c
  src/H5FDmpio.c
  src/H5FDs3comms.c
  src/H5Omtime.c
  src/H5Ztrans.c
  src/H5dbg.c
  src/H5private.h
  src/H5trace.c
  tools/lib/h5tools_utils.c
  tools/src/h5dump/h5dump.c
  tools/src/h5perf/pio_perf.c
  tools/src/h5perf/sio_perf.c
  tools/src/h5repack/h5repack_parse.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Type - Improvement

#3185 Update actions for release option, fix branch for daily build
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  README.md
  bin/bbrelease
Labels: Priority - 2. Medium ⏹, Type - Bug, Type - Improvement, Component - Misc

#3198 Hdf5 1 14 release action
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/main.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  README.md
Labels: Merge, Priority - 2. Medium ⏹, Type - Bug, Type - Improvement, Branch - 1.14, Component - Misc

#3199 Hdf5 1 12 release action
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/main.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  README.md
Labels: Merge, Priority - 2. Medium ⏹, Type - Bug, Type - Improvement, Branch - 1.12, Component - Misc

#3200 Hdf5 1 10 release action
  .github/workflows/daily-build.yml
  .github/workflows/main.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  README.md
Labels: Merge, Priority - 2. Medium ⏹, Type - Bug, Type - Improvement, Branch - 1.10, Component - Misc

#3213 fix gh action if statements
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#3215 Adjust presets timeout and fix build script VS versions
  config/cmake-presets/hidden-presets.json
  config/cmake/scripts/HDF5config.cmake
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Bug, Component - Misc

#3216 Adjust presets timeout and fix build script VS versions
  config/cmake-presets/hidden-presets.json
  config/cmake/scripts/HDF5config.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Branch - 1.14

#3217 Adjust presets timeout and fix build script VS versions
  config/cmake-presets/hidden-presets.json
  config/cmake/scripts/HDF5config.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Type - Improvement, Branch - 1.12, Component - Misc

#3218 Adjust presets timeout and fix build script VS versions
  config/cmake-presets/hidden-presets.json
  config/cmake/scripts/HDF5config.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Type - Improvement, Branch - 1.10, Component - Misc
