Repository HDFGroup/hdf5, pull requests merged in 2023-07, with the labels that each got.

#3226 Several ros3vfd logging improvements
  src/H5FDs3comms.c
Labels: Type - Improvement

#3231 Update COPYING
  COPYING
Labels: Priority - 2. Medium ⏹, Component - Documentation

#3236 addresses compilation fortran warnings on Frontier
  fortran/src/H5Aff.F90
  fortran/src/H5Dff.F90
  fortran/src/H5ESff.F90
  fortran/src/H5Eff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Gff.F90
  fortran/src/H5Iff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Off.F90
  fortran/src/H5Pff.F90
  fortran/src/H5Rff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5Tff.F90
  fortran/src/H5VLff.F90
  fortran/src/H5Zff.F90
  fortran/src/H5_ff.F90
Labels: Priority - 1. High 🔼, Component - Fortran, Type - Improvement

#3240 Fix doc for H5allocate_memory
  src/H5public.h
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Bug

#3232 merge bbrelease to release
  .github/workflows/release.yml
  bin/bbrelease
  bin/release
Labels: Type - Improvement, Component - Misc

#3228 Replace support.hdfgroup.org URLs for alternative COPYING file
  bin/chkcopyright
  test/API/H5_api_async_test.c
  test/API/H5_api_async_test.h
  test/API/H5_api_attribute_test.c
  test/API/H5_api_attribute_test.h
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
  test/API/H5_api_datatype_test.c
  test/API/H5_api_datatype_test.h
  test/API/H5_api_file_test.c
  test/API/H5_api_file_test.h
  test/API/H5_api_group_test.c
  test/API/H5_api_group_test.h
  test/API/H5_api_link_test.c
  test/API/H5_api_link_test.h
  test/API/H5_api_misc_test.c
  test/API/H5_api_misc_test.h
  test/API/H5_api_object_test.c
  test/API/H5_api_object_test.h
  test/API/H5_api_test.c
  test/API/H5_api_test.h
  test/API/H5_api_test_config.h.in
  test/API/H5_api_test_util.c
  test/API/H5_api_test_util.h
  test/API/driver/h5_api_test_driver.cxx
  test/API/driver/h5_api_test_driver.hxx
  testpar/API/H5_api_async_test_parallel.c
  testpar/API/H5_api_async_test_parallel.h
  testpar/API/H5_api_attribute_test_parallel.c
  testpar/API/H5_api_attribute_test_parallel.h
  testpar/API/H5_api_dataset_test_parallel.c
  testpar/API/H5_api_dataset_test_parallel.h
  testpar/API/H5_api_datatype_test_parallel.c
  testpar/API/H5_api_datatype_test_parallel.h
  testpar/API/H5_api_file_test_parallel.c
  testpar/API/H5_api_file_test_parallel.h
  testpar/API/H5_api_group_test_parallel.c
  testpar/API/H5_api_group_test_parallel.h
  testpar/API/H5_api_link_test_parallel.c
  testpar/API/H5_api_link_test_parallel.h
  testpar/API/H5_api_misc_test_parallel.c
  testpar/API/H5_api_misc_test_parallel.h
  testpar/API/H5_api_object_test_parallel.c
  testpar/API/H5_api_object_test_parallel.h
  testpar/API/H5_api_test_parallel.c
  testpar/API/H5_api_test_parallel.h
  testpar/API/t_bigio.c
Labels: Priority - 2. Medium ⏹, Component - Documentation

#3227 Replace 1_10 reference with develop branch
  doxygen/dox/LearnBasics.dox
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#3242 Switch CI to use release script
  .gitattributes
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  bin/release
Labels: Priority - 0. Blocker ⛔, Type - Deprecation / Removal, Component - Misc

#3241 Subfiling VFD source cleanup
  CMakeLists.txt
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  configure.ac
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5FDsubfiling/CMakeLists.txt
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/mercury/LICENSE.txt
  src/H5FDsubfiling/mercury/README.md
  src/H5FDsubfiling/mercury/src/util/mercury_atomic.h
  src/H5FDsubfiling/mercury/src/util/mercury_compiler_attributes.h
  src/H5FDsubfiling/mercury/src/util/mercury_dlog.c
  src/H5FDsubfiling/mercury/src/util/mercury_dlog.h
  src/H5FDsubfiling/mercury/src/util/mercury_list.h
  src/H5FDsubfiling/mercury/src/util/mercury_log.c
  src/H5FDsubfiling/mercury/src/util/mercury_log.h
  src/H5FDsubfiling/mercury/src/util/mercury_queue.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_annotation.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_condition.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_condition.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_mutex.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_mutex.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_pool.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_pool.h
  src/H5FDsubfiling/mercury/src/util/mercury_time.h
  src/H5FDsubfiling/mercury/src/util/mercury_util.c
  src/H5FDsubfiling/mercury/src/util/mercury_util.h
  src/H5FDsubfiling/mercury/src/util/mercury_util_config.h
  src/H5FDsubfiling/mercury/src/util/mercury_util_config.h.in
  src/H5FDsubfiling/mercury/src/util/mercury_util_error.h
  src/H5FDsubfiling/mercury/src/util/version.txt
  src/H5FDsubfiling/mercury/version.txt
  src/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Build, Type - Bug

#3244 install h5fuse.sh into the bin directory for autotools
  utils/Makefile.am
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Parallel

#3243 Disable h5py until fixed properly without spack
  .github/workflows/h5py.yml
Labels: Priority - 3. Low 🔽, Type - Bug, Type - Deprecation / Removal, Component - Misc

#3030 ROS3: (feature) Temporary security credentials
  release_docs/RELEASE.txt
  src/H5FDros3.c
  src/H5FDros3.h
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
  tools/lib/h5tools.c
  tools/lib/h5tools_utils.c
  tools/lib/h5tools_utils.h
  tools/libtest/h5tools_test_utils.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5stat/h5stat.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#3083 Avoid truncating at null byte when copying to std::string
  c++/src/H5DataSet.cpp
  c++/test/dsets.cpp
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C++, Type - Improvement

#3237 Merge changes from develop
  .gitattributes
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  bin/bbrelease
  bin/release
Labels: Merge, Priority - 1. High 🔼, Type - Improvement, Branch - 1.14, Component - Misc

#3250 Fix CMake builds when Subfiling VFD isn't enabled
  config/cmake/hdf5-config.cmake.in
  src/CMakeLists.txt
  src/H5FDsubfiling/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3247 Fix some warnings in developer builds
  config/cmake/HDFCompilerFlags.cmake
  config/gnu-warnings/developer-general
  config/intel-warnings/developer-general
  src/H5.c
  src/H5Dmpio.c
  src/H5FDmpio.c
  src/H5FDonion.c
  src/H5MMprivate.h
  src/H5Spoint.c
  src/H5Tref.c
  src/H5mpi.c
  test/chunk_info.c
  test/h5test.c
  test/onion.c
  test/stab.c
  testpar/API/t_coll_md_read.c
  testpar/t_bigio.c
  testpar/t_coll_chunk.c
  testpar/t_coll_md.c
  testpar/t_filters_parallel.c
  tools/lib/h5tools.h
  tools/lib/h5tools_str.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Testing, Component - Build, Type - Task

#3238 Merge changes from develop
  .gitattributes
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  bin/bbrelease
  bin/release
Labels: Merge, Priority - 1. High 🔼, Type - Improvement, Branch - 1.12, Component - Misc

#3239 Merge changes from develop
  .gitattributes
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  bin/bbrelease
  bin/release
Labels: Merge, Priority - 1. High 🔼, Type - Improvement, Branch - 1.10, Component - Misc

#3259 Fix warning in H5C__UPDATE_STATS_FOR_DIRTY_PIN macro
  src/H5Cpkg.h
Labels: Priority - 0. Blocker ⛔, Component - C Library, Type - Task

#3255 Update DEFAULT_API_VERSION documentation for CMake
  CMakeLists.txt
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug

#3254 changed the scope of #ifdef DOXYGEN to now include H5D multi-functions
  fortran/src/H5Dff.F90
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation

#3252 Option changed but not all references
  config/cmake/hdf5-config.cmake.in
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug

#3263 Move 1.12.3 release to October
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Component - Documentation, Type - Task

#3260 Fixed some -Wunused-variable warnings and one Wsometimes-uninitialize…
  examples/ph5_filtered_writes.c
  examples/ph5_filtered_writes_no_sel.c
  testpar/t_vfd.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Improvement

#3256 Duplicate function removed
  fortran/src/H5Pff.F90
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Fortran, Component - Build, Type - Bug, Branch - 1.10

#3268 chore: make VRFY output consistent
  testpar/t_coll_chunk.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3267 CMake: (fix) Threads dependency
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 1. High 🔼, Component - Build, Type - Bug

#3272 chore: fix grammar - get hang -> get hung
  testpar/API/t_bigio.c
  testpar/API/t_shapesame.c
  testpar/API/testphdf5.c
  testpar/t_bigio.c
  testpar/t_cache.c
  testpar/t_cache_image.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
Labels: Priority - 2. Medium ⏹, Component - Parallel, Type - Improvement

#3269 sync bin dir with develop
  COPYING
  bin/buildhdf5
  bin/chkcopyright
  bin/cmakehdf5
  bin/format_source
  bin/h5vers
  bin/make_err
  bin/make_overflow
  bin/make_vers
  bin/output_filter.sh
  bin/release
  bin/switch_maint_mode
  bin/warnhist
Labels: Priority - 2. Medium ⏹, Type - Task, Branch - 1.14, Component - Misc

#3271 sync bin with develop
  COPYING
  README.md
  bin/buildhdf5
  bin/chkcopyright
  bin/cmakehdf5
  bin/format_source
  bin/h5vers
  bin/make_err
  bin/make_overflow
  bin/make_vers
  bin/output_filter.sh
  bin/pkgscrpts/makeInternalREADME.pl
  bin/pkgscrpts/makeOuterREADME.pl
  bin/switch_maint_mode
  bin/warnhist
Labels: Merge, Priority - 2. Medium ⏹, Type - Task, Branch - 1.10, Component - Misc

#3273 Fix typo - persent -> present
  testpar/API/t_shapesame.c
  testpar/API/testphdf5.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#3276 Remove unused files
  bin/README.md
  bin/checkposix
  src/.indent.pro
  src/hdf5-lin.lnt
  src/hdf5-win.lnt
  src/hdf5.lnt
Labels: Merge, Branch - 1.14

#3277 Sync .github directory
  .github/CODEOWNERS
  .github/workflows/hdfeos5.yml
  .github/workflows/main.yml
  .github/workflows/netcdf.yml
  SECURITY.md
Labels: Merge, Branch - 1.14

#3278 Brings over some H5F changes
  src/H5Fefc.c
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5Fprivate.h
  test/efc.c
Labels: Merge, Branch - 1.14

#3280 Bump Autoconf to 2.71
  configure.ac
Labels: Merge, Branch - 1.14

#3282 Normalize examples w/ develop
  examples/h5_cmprss.c
  examples/h5_crtatt.c
  examples/h5_crtdat.c
  examples/h5_crtgrp.c
  examples/h5_crtgrpar.c
  examples/h5_crtgrpd.c
  examples/h5_elink_unix2win.c
  examples/h5_extlink.c
  examples/h5_rdwt.c
  examples/h5_vds-exc.c
  examples/h5_vds-exclim.c
  examples/h5_vds.c
  examples/ph5_filtered_writes.c
  examples/ph5_filtered_writes_no_sel.c
  examples/ph5example.c
  examples/testh5cc.sh.in
Labels: Merge, Branch - 1.14

#3284 Fix warning in cache_common.c (#2952)
  test/cache_common.c
Labels: Merge, Priority - 3. Low 🔽, Component - Testing, Type - Task, Branch - 1.14

#3285 Add test for HDstrcasestr macro (#2115)
  src/H5system.c
  src/H5win32defs.h
  test/th5_system.c
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Type - Task, Branch - 1.14

#3289 Normalize mirror server code
  utils/mirror_vfd/mirror_remote.c
  utils/mirror_vfd/mirror_remote.h
  utils/mirror_vfd/mirror_server.c
  utils/mirror_vfd/mirror_server_stop.c
  utils/mirror_vfd/mirror_writer.c
Labels: Merge, Branch - 1.14

#3283 Normalize java w/ develop
  java/src/jni/exceptionImp.c
  java/src/jni/h5Constants.c
  java/src/jni/h5Imp.c
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5eImp.c
  java/src/jni/h5fImp.c
  java/src/jni/h5iImp.c
  java/src/jni/h5jni.h
  java/src/jni/h5lImp.c
  java/src/jni/h5oImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pDCPLImp.c
  java/src/jni/h5pDXPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5pFCPLImp.c
  java/src/jni/h5pLAPLImp.c
  java/src/jni/h5pOCPLImp.c
  java/src/jni/h5plImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5sImp.c
  java/src/jni/h5tImp.c
  java/src/jni/h5util.c
  java/src/jni/h5vlImp.c
Labels: Merge, Branch - 1.14

#3286 Fix release version for some H5Pfapl routines (#3023)
  src/H5Ppublic.h
Labels: Merge, Priority - 3. Low 🔽, Component - Documentation, Type - Task, Branch - 1.14

#3279 Normalize C++ w/ develop
  c++/examples/h5tutr_extend.cpp
  c++/examples/readdata.cpp
  c++/examples/testh5c++.sh.in
  c++/src/H5AbstractDs.cpp
  c++/src/H5ArrayType.cpp
  c++/src/H5AtomType.cpp
  c++/src/H5Attribute.cpp
  c++/src/H5CommonFG.cpp
  c++/src/H5CompType.cpp
  c++/src/H5DaccProp.cpp
  c++/src/H5DataSet.cpp
  c++/src/H5DataSpace.cpp
  c++/src/H5DataType.cpp
  c++/src/H5DcreatProp.cpp
  c++/src/H5DxferProp.cpp
  c++/src/H5EnumType.cpp
  c++/src/H5Exception.cpp
  c++/src/H5FaccProp.cpp
  c++/src/H5FcreatProp.cpp
  c++/src/H5File.cpp
  c++/src/H5FloatType.cpp
  c++/src/H5Group.cpp
  c++/src/H5IdComponent.cpp
  c++/src/H5IntType.cpp
  c++/src/H5LaccProp.cpp
  c++/src/H5Library.cpp
  c++/src/H5Location.cpp
  c++/src/H5Object.cpp
  c++/src/H5OcreatProp.cpp
  c++/src/H5PredType.cpp
  c++/src/H5PropList.cpp
  c++/src/H5StrType.cpp
  c++/src/H5VarLenType.cpp
  c++/test/dsets.cpp
  c++/test/h5cpputil.cpp
  c++/test/h5cpputil.h
  c++/test/tarray.cpp
  c++/test/tattr.cpp
  c++/test/tcompound.cpp
  c++/test/tdspl.cpp
  c++/test/tfile.cpp
  c++/test/tfilter.cpp
  c++/test/th5s.cpp
  c++/test/titerate.cpp
  c++/test/tlinks.cpp
  c++/test/tobject.cpp
  c++/test/trefer.cpp
  c++/test/ttypes.cpp
  c++/test/tvlstr.cpp
Labels: Merge, Branch - 1.14

#3287 API test updates (#3018)
  CMakeLists.txt
  CMakeVOL.cmake
  doc/cmake-vols-fetchcontent.md
  release_docs/RELEASE.txt
  src/H5VLnative_attr.c
  test/API/CMakeLists.txt
  test/API/H5_api_async_test.c
  test/API/H5_api_attribute_test.c
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
  test/API/H5_api_datatype_test.c
  test/API/H5_api_file_test.c
  test/API/H5_api_group_test.c
  test/API/H5_api_link_test.c
  test/API/H5_api_object_test.c
  test/API/H5_api_test.c
  test/API/H5_api_test.h
  test/API/H5_api_test_util.c
  test/API/H5_api_tests_disabled.h
  test/API/tattr.c
  test/API/testhdf5.c
  test/API/testhdf5.h
  test/API/tfile.c
  test/API/th5s.c
  test/API/titerate.c
  test/API/tmisc.c
  test/API/trefer.c
  test/API/tvlstr.c
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/API/H5_api_async_test_parallel.c
  testpar/API/H5_api_test_parallel.c
  testpar/API/t_dset.c
  testpar/API/t_file.c
  testpar/API/t_file_image.c
  testpar/API/t_mdset.c
  testpar/API/testphdf5.h
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Branch - 1.14

#3290 Subfiling VFD source cleanup (#3241)
  CMakeLists.txt
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/hdf5-config.cmake.in
  configure.ac
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5FDsubfiling/CMakeLists.txt
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/mercury/LICENSE.txt
  src/H5FDsubfiling/mercury/README.md
  src/H5FDsubfiling/mercury/src/util/mercury_atomic.h
  src/H5FDsubfiling/mercury/src/util/mercury_compiler_attributes.h
  src/H5FDsubfiling/mercury/src/util/mercury_dlog.c
  src/H5FDsubfiling/mercury/src/util/mercury_dlog.h
  src/H5FDsubfiling/mercury/src/util/mercury_list.h
  src/H5FDsubfiling/mercury/src/util/mercury_log.c
  src/H5FDsubfiling/mercury/src/util/mercury_log.h
  src/H5FDsubfiling/mercury/src/util/mercury_queue.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_annotation.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_condition.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_condition.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_mutex.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_mutex.h
  src/H5FDsubfiling/mercury/src/util/mercury_thread_pool.c
  src/H5FDsubfiling/mercury/src/util/mercury_thread_pool.h
  src/H5FDsubfiling/mercury/src/util/mercury_time.h
  src/H5FDsubfiling/mercury/src/util/mercury_util.c
  src/H5FDsubfiling/mercury/src/util/mercury_util.h
  src/H5FDsubfiling/mercury/src/util/mercury_util_config.h
  src/H5FDsubfiling/mercury/src/util/mercury_util_config.h.in
  src/H5FDsubfiling/mercury/src/util/mercury_util_error.h
  src/H5FDsubfiling/mercury/src/util/version.txt
  src/H5FDsubfiling/mercury/version.txt
  src/Makefile.am
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug, Type - Improvement, Branch - 1.14

#3291 Fix some warnings in developer builds (#3247)
  config/cmake/HDFCompilerFlags.cmake
  config/gnu-warnings/developer-general
  config/intel-warnings/developer-general
  src/H5.c
  src/H5Dmpio.c
  src/H5FDmpio.c
  src/H5FDonion.c
  src/H5MMprivate.h
  src/H5Spoint.c
  src/H5Tref.c
  src/H5mpi.c
  test/chunk_info.c
  test/h5test.c
  test/onion.c
  test/stab.c
  testpar/API/t_coll_md_read.c
  testpar/t_bigio.c
  testpar/t_coll_chunk.c
  testpar/t_coll_md.c
  testpar/t_filters_parallel.c
  tools/lib/h5tools.h
  tools/lib/h5tools_str.c
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Task, Branch - 1.14

#3288 Fix assertion failure when attempting to use IOC VFD directly (#3187)
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDioc.c
  testpar/CMakeTests.cmake
  testpar/t_subfiling_vfd.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#3281 Misc warnings and cross-compile improvements
  config/cmake/H5pubconf.h.in
  configure.ac
  src/H5Iint.c
  src/H5SL.c
  src/H5T.c
  src/H5Tconv.c
  src/H5system.c
  test/big.c
  test/ntypes.c
  test/vol.c
Labels: Merge, Branch - 1.14

#3296 Sync Fortran w/ develop
  fortran/src/H5Af.c
  fortran/src/H5Aff.F90
  fortran/src/H5Dff.F90
  fortran/src/H5ESff.F90
  fortran/src/H5Ef.c
  fortran/src/H5Eff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Gff.F90
  fortran/src/H5Iff.F90
  fortran/src/H5Lf.c
  fortran/src/H5Lff.F90
  fortran/src/H5Of.c
  fortran/src/H5Off.F90
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5Rf.c
  fortran/src/H5Rff.F90
  fortran/src/H5Sf.c
  fortran/src/H5Sff.F90
  fortran/src/H5Tf.c
  fortran/src/H5Tff.F90
  fortran/src/H5VLff.F90
  fortran/src/H5Zff.F90
  fortran/src/H5_ff.F90
  fortran/src/H5f90kit.c
  fortran/test/t.c
  fortran/test/tH5A_1_8.F90
  fortran/test/tH5G_1_8.F90
  fortran/test/tH5Sselect.F90
  hl/fortran/src/H5DSfc.c
  hl/fortran/src/H5IMfc.c
  hl/fortran/src/H5LTfc.c
  hl/fortran/src/H5TBfc.c
Labels: Merge, Branch - 1.14

#3298 Sync high-level library with develop
  hl/src/H5DO.c
  hl/src/H5DS.c
  hl/src/H5IM.c
  hl/src/H5LD.c
  hl/src/H5LT.c
  hl/src/H5LTanalyze.c
  hl/src/H5LTanalyze.l
  hl/src/H5LTparse.c
  hl/src/H5LTparse.h
  hl/src/H5LTparse.y
  hl/src/H5LTprivate.h
  hl/src/H5TB.c
  hl/test/gen_test_ds.c
  hl/test/gen_test_ld.c
  hl/test/h5hltest.h
  hl/test/test_ds.c
  hl/test/test_dset_append.c
  hl/test/test_file_image.c
  hl/test/test_h5do_compat.c
  hl/test/test_image.c
  hl/test/test_ld.c
  hl/test/test_lite.c
  hl/test/test_packet.c
  hl/test/test_packet_vlen.c
  hl/test/test_table.c
  hl/tools/gif2h5/decompress.c
  hl/tools/gif2h5/hdf2gif.c
  hl/tools/h5watch/extend_dset.c
  hl/tools/h5watch/h5watch.c
  hl/tools/h5watch/h5watchgentest.c
Labels: Merge, Branch - 1.14

#3299 Sync ros3 VFD w/ develop
  src/H5FDros3.c
  src/H5FDros3.h
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/ros3.c
  test/s3comms.c
Labels: Merge, Branch - 1.14

#3300 Sync testhdf5 files w/ develop
  test/tarray.c
  test/tattr.c
  test/tcheck_version.c
  test/tcoords.c
  test/testframe.c
  test/testhdf5.h
  test/tfile.c
  test/tgenprop.c
  test/th5_system.c
  test/th5o.c
  test/th5s.c
  test/tid.c
  test/titerate.c
  test/tmeta.c
  test/tmisc.c
  test/trefer.c
  test/trefer_deprec.c
  test/tselect.c
  test/tsohm.c
  test/tvltypes.c
  test/twriteorder.c
Labels: Merge, Branch - 1.14

#3304 Brings an enum fix from develop
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tcompound.c
  test/enum.c
Labels: Merge, Branch - 1.14

#3305 Bring clang-format changes from develop
  .clang-format
  src/H5Iint.c
  test/ros3.c
Labels: Merge, Branch - 1.14
