Repository HDFGroup/hdf5, pull requests merged in 2023-12, with the labels that each got.

#3882 Updating funding.yml with a shorter URL
  .github/FUNDING.yml
Labels: Priority - 3. Low 🔽, Type - Improvement, Component - Misc

#3883 Fix build error on freebsd
  config/freebsd
Labels: Priority - 1. High 🔼, Component - Fortran, Type - Bug

#3888 Correct CMake command and example packaging
  CMakeInstallation.cmake
  tools/test/h5copy/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3890 Correct urls and handling of external git repos
  CMakeFilters.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Type - Improvement, Component - Misc

#3893 Some changes to portal links when they could be found on docs.hdfgroup.org, and changed the helpdesk link to help.hdfgroup.org
  README.md
  release_docs/INSTALL_Cygwin.txt
  test/API/README.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3895 Add intel binaries to daily-build/release workflows
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement, Type - New Feature, Component - Misc

#3900 Disable doxygen as errors for netcdf
  .github/workflows/netcdf.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Task

#3898 Add VDS examples and fix non-standalone build
  CMakeInstallation.cmake
  HDF5Examples/C/CMakeLists.txt
  HDF5Examples/C/H5D/CMakeLists.txt
  HDF5Examples/C/H5D/C_sourcefiles.cmake
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5G/C_sourcefiles.cmake
  HDF5Examples/C/H5PAR/CMakeLists.txt
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/C/H5VDS/CMakeLists.txt
  HDF5Examples/C/H5VDS/C_sourcefiles.cmake
  HDF5Examples/C/H5VDS/Makefile.am
  HDF5Examples/C/H5VDS/h5ex_vds-eiger.c
  HDF5Examples/C/H5VDS/h5ex_vds-exc.c
  HDF5Examples/C/H5VDS/h5ex_vds-exclim.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim-maxmin.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival.c
  HDF5Examples/C/H5VDS/h5ex_vds-simpleIO.c
  HDF5Examples/C/H5VDS/h5ex_vds.c
  HDF5Examples/C/H5VDS/test.sh.in
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-eiger.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-eiger.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-exc.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-exc.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-exclim.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-exclim.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival-unlim-maxmin.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival-unlim-maxmin.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival-unlim.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival-unlim.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-percival.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-simpleIO.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds-simpleIO.tst
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds.ddl
  HDF5Examples/C/H5VDS/tfiles/110/h5ex_vds.tst
  HDF5Examples/C/Perf/CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
  HDF5Examples/JAVA/H5D/CMakeLists.txt
  HDF5Examples/JAVA/H5G/CMakeLists.txt
  HDF5Examples/JAVA/H5G/Java_sourcefiles.cmake
  HDF5Examples/JAVA/H5J/CMakeLists.txt
  HDF5Examples/JAVA/H5J/Java_sourcefiles.cmake
  HDF5Examples/JAVA/H5T/CMakeLists.txt
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  HDF5Examples/config/cmake/UseJava.cmake
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/UseJava.cmake
  config/cmake/javaTargets.cmake.in
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/hdf5doxy_layout.xml
Labels: Priority - 0. Blocker ⛔, Component - Java, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Type - New Feature

#3903 Doc versions
  src/H5Dpublic.h
  src/H5Epublic.h
  src/H5Fpublic.h
  src/H5Gpublic.h
  src/H5Idevelop.h
  src/H5Ipublic.h
  src/H5Ppublic.h
  src/H5Rpublic.h
  src/H5Tpublic.h
  src/H5Zdevelop.h
  src/H5Zpublic.h
  src/H5public.h
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#3905 Change Trouble Shooting to Troubleshooting
  doxygen/dox/MetadataCachingInHDF5.dox
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3907 Add CMake api checks to test the new Examples folder.
  .github/workflows/cmake.yml
  .github/workflows/main-cmake-spc.yml
  CMakeLists.txt
  HDF5Examples/C/H5D/16/h5ex_d_alloc.c
  HDF5Examples/C/H5D/16/h5ex_d_checksum.c
  HDF5Examples/C/H5D/16/h5ex_d_chunk.c
  HDF5Examples/C/H5D/16/h5ex_d_compact.c
  HDF5Examples/C/H5D/16/h5ex_d_extern.c
  HDF5Examples/C/H5D/16/h5ex_d_fillval.c
  HDF5Examples/C/H5D/16/h5ex_d_gzip.c
  HDF5Examples/C/H5D/16/h5ex_d_hyper.c
  HDF5Examples/C/H5D/16/h5ex_d_rdwr.c
  HDF5Examples/C/H5D/16/h5ex_d_shuffle.c
  HDF5Examples/C/H5D/16/h5ex_d_szip.c
  HDF5Examples/C/H5D/16/h5ex_d_unlimadd.c
  HDF5Examples/C/H5D/16/h5ex_d_unlimgzip.c
  HDF5Examples/C/H5D/16/h5ex_d_unlimmod.c
  HDF5Examples/C/H5D/CMakeLists.txt
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/JAVA/H5J/Java_sourcefiles.cmake
  config/cmake/HDF5ExampleCache.cmake
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Type - New Feature, Component - Misc

#3908 Added new H5G Fortran HDF5examples
  HDF5Examples/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/Fortran_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5G/h5_version.h.in
  HDF5Examples/FORTRAN/H5G/h5ex_g_intermediate.F90
  HDF5Examples/FORTRAN/H5G/h5ex_g_iterate.F90
  HDF5Examples/FORTRAN/H5G/h5ex_g_iterate.h5
  HDF5Examples/FORTRAN/H5G/h5ex_g_traverse.F90
  HDF5Examples/FORTRAN/H5G/h5ex_g_traverse.h5
  HDF5Examples/FORTRAN/H5G/h5ex_g_visit.F90
  HDF5Examples/FORTRAN/H5G/h5ex_g_visit.h5
  HDF5Examples/FORTRAN/H5G/tfiles/18/F03/h5ex_g_iterate_F03.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/F03/h5ex_g_traverse_F03.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/F03/h5ex_g_visit_F03.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_intermediate.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_iterate.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_iterate_F03.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_traverse.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_visit.tst
  HDF5Examples/FORTRAN/H5G/tfiles/18/h5ex_g_visit_F03.tst
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_dataset.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_file_create.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_chunk.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_col.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_pattern.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_row.F90
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - Task

#3896 Implement optimized support for vector I/O in Subfiling VFD
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDioc_int.c
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Component - Testing, Type - Improvement

#3912 Added H5Fdelete_f with test
  fortran/src/H5Fff.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5F.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - New Feature
