Repository HDFGroup/hdf5, pull requests merged in 2023-02, with the labels that each got.

#2427 Update and fix compiler flags
  .github/workflows/main.yml
  .github/workflows/pr-check.yml
  MANIFEST
  config/BlankForm
  config/apple
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/cmake_ext_mod/ConfigureChecks.cmake
  config/cmake_ext_mod/HDFMacros.cmake
  config/cmake_ext_mod/NSIS.template.in
  config/gnu-fflags
  config/gnu-warnings/general
  config/ibm-aix
  config/sanitizer/tools.cmake
  config/solaris
  config/toolchain/aarch64.cmake
  config/toolchain/gcc.cmake
  config/toolchain/intel.cmake
  config/toolchain/pgi.cmake
  src/libhdf5.settings.in
Labels: merge

#2438 Add szip/libaec to GitHub CI and fix warnings
  .github/workflows/main.yml
  src/H5Z.c
  src/H5Zszip.c
  test/dsets.c
  test/tmisc.c
Labels: merge to 1.12, merge to 1.10, merge to 1.14

#2425 corrected/added note about closing creation property list identifier
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5Gpublic.h
  src/H5Lpublic.h
  src/H5Mpublic.h
Labels: documentation

#2445 1.10: Drop non-1.10 branches in main.yml
  .github/workflows/main.yml
Labels: merge

#2448 1.14: Drop non-1.14 branches in main.yml
  .github/workflows/main.yml
Labels: merge

#2449 1.10: Bring `make install` GitHub action from develop
  .github/workflows/main.yml
Labels: merge

#2452 1.10: Fixes an incorrect brief description for H5Dopen2
  src/H5Dpublic.h
Labels: merge

#2450 1.10: Add szip/libaec to GitHub CI and fix warnings (#2438)
  .github/workflows/main.yml
  src/H5Z.c
  src/H5Zszip.c
  test/dsets.c
  test/tmisc.c
Labels: merge

#2451 1.10: Bring generated file tidying from develop
  src/H5detect.c
  src/Makefile.am
Labels: merge

#2447 1.12: Drop non-1.12 branches in main.yml
  .github/workflows/main.yml
Labels: merge

#2275 1.10 h5repack should only print if verbose
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack_copy.c
  tools/test/h5dump/CMakeTests.cmake
Labels: bug, merge

#2284 1.10 Correct requires setting for pkgconfig files #2280
  c++/src/CMakeLists.txt
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
Labels: merge

#2462 Add build options for CMake packaging #2347
  CMakeInstallation.cmake
Labels: merge to 1.12, merge to 1.10, merge to 1.14

#2466 1.10 Merge Add build options for CMake packaging #2347
  CMakeInstallation.cmake
Labels: merge

#2464 1.14 Merge Add build options for CMake packaging #2347
  CMakeInstallation.cmake
Labels: merge

#2476 CMake generated pkg-config file is incorrect #2259
  c++/src/CMakeLists.txt
  config/libhdf5.fpc.in
  config/libhdf5.pc.in
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: merge to 1.12, merge to 1.10, merge to 1.14

#2477 1.14 Merge Correct pkgconfig variables and libraries #2259
  c++/src/CMakeLists.txt
  config/libhdf5.fpc.in
  config/libhdf5.pc.in
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: merge

#2478 1.12 Merge Correct pkgconfig variables and libraries #2259
  c++/src/CMakeLists.txt
  config/libhdf5.fpc.in
  config/libhdf5.pc.in
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: merge

#2479 1.10 Merge Merge CMake generated pkg-config file is incorrect #2259
  c++/src/CMakeLists.txt
  config/libhdf5.fpc.in
  config/libhdf5.pc.in
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: merge

#2465 1.12 Merge Add build options for CMake packaging #2347
  CMakeInstallation.cmake
Labels: merge

#2480 Fix issue with collective metadata writes of global heap data
  release_docs/RELEASE.txt
  src/H5Cmpio.c
  testpar/CMakeLists.txt
  testpar/Makefile.am
  testpar/t_coll_md.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: bug, merge to 1.14

#2484 1.12 Remove space from toolchain name #2482
  config/toolchain/icc.cmake
Labels: merge

#2485 1.10 Remove space from toolchain name #2482
  config/toolchain/icc.cmake
Labels: merge

#2486 [1.14 Merge] Fix issue with collective metadata writes of global heap data (#2480)
  release_docs/RELEASE.txt
  src/H5Cmpio.c
  testpar/CMakeLists.txt
  testpar/Makefile.am
  testpar/t_coll_md.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: merge to 1.14

#2494 1.10 Add fetchcontent for compression libs and fix cmake config #2487
  .github/workflows/codespell.yml
  .github/workflows/main.yml
  CMakeFilters.cmake
  CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/LIBAEC/CPack.Info.plist.in
  config/cmake/LIBAEC/config.h.in
  config/cmake/LIBAEC/libaec-config-version.cmake.in
  config/cmake/LIBAEC/libaec-config.cmake.in
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIB/CPack.Info.plist.in
  config/cmake/ZLIB/zconf.h.in
  config/cmake/ZLIB/zlib-config-version.cmake.in
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake_ext_mod/HDFLibMacros.cmake
  config/cmake_ext_mod/HDFMacros.cmake
  config/sanitizer/tools.cmake
  config/toolchain/intel_classic.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge

#2500 Use LINK_COMP_LIBS instead of STATIC_LIBRARY for depends
  CMakeFilters.cmake
  CMakeLists.txt
  config/toolchain/aarch64.cmake
Labels: merge

#2487 Add fetchcontent for compression libs and fix cmake config
  .github/workflows/codespell.yml
  .github/workflows/main.yml
  CMakeFilters.cmake
  CMakeLists.txt
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/LIBAEC/CPack.Info.plist.in
  config/cmake/LIBAEC/config.h.in
  config/cmake/LIBAEC/libaec-config-version.cmake.in
  config/cmake/LIBAEC/libaec-config.cmake.in
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIB/CPack.Info.plist.in
  config/cmake/ZLIB/zconf.h.in
  config/cmake/ZLIB/zlib-config-version.cmake.in
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: merge to 1.12, merge to 1.10, merge to 1.14
