Repository HDFGroup/hdf5, pull requests merged in 2023-11, with the labels that each got.

#3804 Add processing of NVHPC flags in linux-gnulibc1 file
  .github/workflows/nvhpc-auto.yml
  config/linux-gnulibc1
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Task

#3810 Use the current toolchain for examples as default
  CMakeInstallation.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/scripts/HDF5options.cmake
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Bug, Type - Improvement

#3787 Fix misc. warnings from GCC when compiling with -fsanitize=undefined
  src/H5Dmpio.c
  src/H5FDfamily.c
  src/H5FDlog.c
  src/H5FDsec2.c
  src/H5T.c
  tools/src/misc/h5repart.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Task

#3818 Force compression cache variables and update presets
  CMakePlugins.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Type - Improvement, Branch - 1.12

#3819 Add missing comma
  CMakePresets.json
Labels: Priority - 0. Blocker ⛔, Branch - 1.12

#3817 Update hdf5_1_12 branch version after creation of hdf5_1_12_3
  README.md
  c++/src/cpp_doc_config
  config/cmake/scripts/HDF5config.cmake
  configure.ac
  java/src/hdf/hdf5lib/H5.java
  java/test/TestH5.java
  release_docs/RELEASE.txt
  src/H5public.h
  tools/test/h5repack/testfiles/h5repack_layout.h5-plugin_version_test.ddl
Labels: Component - Build, Branch - 1.12, Component - Misc

#3821 Merge CMake updates from 1.12 development branch
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  CMakePresets.json
  CTestConfig.cmake
  config/cmake-presets/hidden-presets.json
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  config/cmake/scripts/CTestScript.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Component - Misc

#3800 Set NVHPC maximum optimization level to -O1 for now
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  config/cmake/HDFCompilerFlags.cmake
  config/nvidia-flags
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Task

#3822 Correct name of szip variable for install file
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.12

#3736 Update NVHPC version from 23.7 to 23.9.
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3811 Sync CMake changes from develop
  CMakeInstallation.cmake
  CTestConfig.cmake
  c++/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/scripts/HDF5options.cmake
  config/sanitizer/README.md
  fortran/CMakeLists.txt
  hl/CMakeLists.txt
  java/CMakeLists.txt
  tools/CMakeLists.txt
  utils/CMakeLists.txt
Labels: Merge, Priority - 3. Low 🔽, Component - Build, Type - Improvement, Branch - 1.14

#3813 Update doxygen links and add v1_14 to gh-pages
  .github/workflows/release-files.yml
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/ViewTools2.dox
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Branch - 1.14, Component - Misc

#3814 Update some doxygen links to local refs
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/ViewTools2.dox
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Improvement, Component - Misc

#3782 Rework MPI Info FAPL preserve PR to use VFD 'ctl' operations
  src/H5FDmpi.c
  src/H5FDmpio.c
  src/H5FDprivate.h
  src/H5FDpublic.h
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5Fint.c
  src/H5Fmpi.c
  src/H5Fpkg.h
  src/H5Fprivate.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Parallel, Type - Task

#3824 Removed the use of C wrappers from H5P APIs.
  fortran/src/H5Off.F90
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5f90proto.h
  fortran/src/hdf5_fortrandll.def.in
  fortran/testpar/Makefile.am
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - Improvement

#3828 Adjust some CMake settings
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/scripts/HDF5options.cmake
  doxygen/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.12

#3801 Fortran Wrappers H5VLnative_addr_to_token_f and H5VLnative_token_to_address_f
  fortran/src/H5VLff.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5O_F03.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - New Feature

#3830 Adjust some CMake settings
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/scripts/HDF5options.cmake
  doxygen/CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Branch - 1.12

#3825 Create test for H5Pget_dxpl_mpio
  testpar/t_ph5basic.c
  testpar/testphdf5.c
  testpar/testphdf5.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#3834 Renamed h5fuse.sh to h5fuse
  configure.ac
  release_docs/RELEASE.txt
  testpar/t_subfiling_vfd.c
  utils/Makefile.am
  utils/subfiling_vfd/CMakeLists.txt
  utils/subfiling_vfd/h5fuse.in
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#3837 Disable FP exceptions in H5T init code
  config/linux-gnulibc1
  release_docs/RELEASE.txt
  src/H5Tinit_float.c
  src/H5private.h
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Fortran, Type - Improvement

#3836 Add intel oneapi windows build to CI CMake
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  config/cmake-presets/hidden-presets.json
  fortran/examples/ph5example.f90
  fortran/src/CMakeLists.txt
  fortran/src/H5Pff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5T_F03.F90
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/H5LTff.F90
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Component - Testing, Component - Build, Type - Improvement, Type - New Feature

#3838 Remove printf() format warning on Windows oneAPI.
  test/accum.c
Labels: Merge - To 1.14, Component - C Library, Type - Improvement

#3829 Test and document path handling of H5Lcreate_* API
  src/H5Lpublic.h
  test/links.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Component - Testing, Type - Bug

#3841 Correct ENV variables
  config/cmake/examples/HDF5_Examples.cmake.in
Labels: Component - Java, Component - Build, Type - Bug

#3847 Remove 1.12 from README.md
  README.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3848 Remove Autotools sed hack
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3845 cmakedefine macro uses C comments with "#undef"
  fortran/src/CMakeLists.txt
  fortran/src/H5_ff.F90
  fortran/src/H5config_f.inc.cmake
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#3629 Make filter unregister callbacks safe for VOL connectors
  src/H5Z.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3852 Add extra space in comments for consistency
  tools/test/h5dump/CMakeTests.cmake
Labels: Component - Documentation

#3683 Add CMake long double cross-compile defaults
  config/cmake/ConfigureChecks.cmake
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#3846 Test and document path handling of H5Lcreate_* API
  src/H5Lpublic.h
  test/links.c
Labels: Priority - 3. Low 🔽, Component - Documentation, Component - Testing, Type - Improvement, Branch - 1.14

#3849 Add GitHub actions for testing VOL connectors
  .github/workflows/vol.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_log.yml
  .github/workflows/vol_rest.yml
  CMakeVOL.cmake
  README.md
  doc/cmake-vols-fetchcontent.md
  test/API/CMakeLists.txt
  test/API/H5_api_test.c
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/CMakeLists.txt
  testpar/t_bigio.c
  testpar/t_pshutdown.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Parallel, Component - Testing, Component - Build, Type - Improvement, Component - Misc

#3853 Fixes for CI and presets
  .github/workflows/linux-auto-aocc-ompi.yml
  .github/workflows/netcdf.yml
  config/cmake-presets/hidden-presets.json
  config/cmake/grepTest.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#3856 Change dest for doxygen
  .github/workflows/release-files.yml
  CONTRIBUTING.md
  doc/branches-explained.md
  doxygen/dox/Overview.dox
  doxygen/examples/FileFormat.html
  src/H5Fmodule.h
  src/H5module.h
Labels: Priority - 0. Blocker ⛔, Component - Documentation

#3855 Sync fixes for CI and presets
  .github/workflows/hdfeos5.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/linux-auto-aocc-ompi.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  CONTRIBUTING.md
  config/cmake-presets/hidden-presets.json
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/grepTest.cmake
  config/linux-gnulibc1
  config/nvidia-flags
  doxygen/dox/Overview.dox
  doxygen/examples/FileFormat.html
  fortran/examples/ph5example.f90
  fortran/src/CMakeLists.txt
  fortran/src/H5_ff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5T_F03.F90
  hl/fortran/src/CMakeLists.txt
  hl/fortran/src/H5LTff.F90
  src/H5Fmodule.h
  src/H5module.h
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Branch - 1.14

#3826 Implement selection vector I/O with collective chunk filling
  src/H5Dchunk.c
  src/H5FDmpio.c
  testpar/t_filters_parallel.c
  testpar/t_vfd.c
Labels: Component - C Library, Type - Improvement

#3865 Do not publish compression headers or docs
  CMakeInstallation.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Bug, Component - Misc

#3866 Fix typo: look -> loop
  tools/src/h5dump/h5dump.c
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Bug

#3862 Expanded README for Fortran API development
  fortran/src/FortBuildFlow.fig
  fortran/src/FortBuildFlow.svg
  fortran/src/README
  fortran/src/README.md
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#3859 Add HDF5_DISABLE_TESTS_REGEX option to skip tests
  CMakeTests.cmake
  c++/test/CMakeTests.cmake
  c++/test/CMakeVFDTests.cmake
  config/cmake/scripts/CTestScript.cmake
  fortran/test/CMakeTests.cmake
  fortran/testpar/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  hl/tools/h5watch/CMakeTests.cmake
  java/test/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  test/API/CMakeLists.txt
  test/CMakeLists.txt
  test/CMakePassthroughVOLTests.cmake
  test/CMakeTests.cmake
  test/CMakeVFDTests.cmake
  test/ShellTests.cmake
  testpar/CMakeTests.cmake
  testpar/CMakeVFDTests.cmake
  tools/libtest/CMakeTests.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/CMakeVFDTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/misc/CMakeTestsRepart.cmake
  tools/test/perform/CMakeTests.cmake
  utils/mirror_vfd/CMakeLists.txt
  utils/subfiling_vfd/CMakeLists.txt
Labels: Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Improvement, Type - New Feature

#3842 Fix segfault on user compound dtype conversion callback
  src/H5T.c
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#3867 Fix typo in error message for `MPI_Type_dup`.
  src/H5Smpio.c
Labels: Priority - 1. High 🔼, Component - Parallel, Type - Bug

#3868 Complete the `if command line option` sentence.
  tools/src/h5dump/h5dump.c
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3869 Fix configuration issue due to possibly empty CMake variable
  test/API/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3870 Fix segfault on user compound conversion callback
  src/H5T.c
  test/dtypes.c
Labels: Merge, Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Branch - 1.14

#3874 Update examples with 1.6 api and static libs
  HDF5Examples/C/H5D/C_sourcefiles.cmake
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5G/C_sourcefiles.cmake
  HDF5Examples/C/H5T/16/h5ex_t_objrefatt.c
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/C/H5T/tfiles/16/114/h5ex_t_vlenatt.ddl
  HDF5Examples/CMakeLists.txt
  config/cmake/HDF5ExampleCache.cmake
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug
