Repository HDFGroup/hdf5, pull requests merged in 2023-05, with the labels that each got.

#2861 add new presets
  CMakePresets.json
Labels: Merge, Component - Build, Branch - 1.14

#2865 Remove "the the" from comments and docs
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/ImageSpec.html
  doxygen/examples/tables/propertyLists.dox
  doxygen/hdf5_navtree_hacks.js
  fortran/src/H5Af.c
  fortran/src/H5Lf.c
  fortran/src/H5Sf.c
  fortran/src/H5Tf.c
  fortran/test/tH5A_1_8.F90
  hl/test/test_ds.c
  hl/test/test_dset_append.c
  release_docs/HISTORY-1_0-1_8_0.txt
  release_docs/HISTORY-1_8_0-1_10_0.txt
  test/tselect.c
  tools/lib/h5tools_dump.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#2863 Correct usage of CMAKE_BUILD_TYPE
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/libhdf5.settings.cmake.in
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#2870 Remove duplicate variable for configuration use
  config/cmake/HDFMacros.cmake
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#2864 Add Fortran Selection IO APIs
  doxygen/aliases
  fortran/src/H5Pff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/H5_test_buildiface.F90
  fortran/test/fortranlib_test.F90
  fortran/test/tH5P.F90
  release_docs/RELEASE.txt
  testpar/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - New Feature

#2856 Harden H5O cache deserialize calls
  src/H5Ocache.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#2872 Add bin directory to make distclean
  Makefile.am
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#2873 Fixed test failure for when REAL is promoted via a compiler flag
  fortran/test/fortranlib_test.F90
  fortran/test/tH5P.F90
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Testing, Type - Bug

#2869 Correct usage of CMAKE_BUILD_TYPE
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/libhdf5.settings.cmake.in
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Branch - 1.10

#2868 Correct usage of CMAKE_BUILD_TYPE
  config/cmake/libhdf5.settings.cmake.in
  config/cmake_ext_mod/HDFLibMacros.cmake
  config/cmake_ext_mod/HDFMacros.cmake
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Branch - 1.12

#2882 Add configure_file commands for batch
  src/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.12

#2881 Update so numbers for hdf5 1.14.1 release.
  config/lt_vers.am
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Task, Branch - 1.14

#2884 Redo remove selection I/O test from testphdf5 in CMake #2860. (#2874)
  testpar/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.14

#2888 Add missing terminator
  doxygen/dox/Overview.dox
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#2889 Add RELEASE.txt entry for API tests
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Task, Component - Misc

#2891 Force lowercase Fortran module file names
  config/cmake/HDF5UseFortran.cmake
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Component - Build, Type - Bug

#2895 Remove 1.8 badge from README.md
  README.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#2901 remove obsolete SZIP find module
  config/cmake/FindSZIP.cmake
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Deprecation / Removal

#2898 Move the 1.10.11 release to September
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - Develop Only, Priority - 1. High 🔼, Type - Task, Component - Misc

#2907 remove obsolete SZIP find module
  config/cmake/FindSZIP.cmake
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Deprecation / Removal, Branch - 1.14

#2908 Added summary report to test big IO
  testpar/t_bigio.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#2913 Fix some compile failures in API tests
  testpar/API/t_dset.c
  testpar/API/t_filter_read.c
  testpar/API/t_shapesame.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#2915 Fix mirror VFD test timeouts
  test/mirror_vfd.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#2904 Add h5copy help test and verify consistency
  tools/src/h5import/h5import.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5delete.c
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5copy/testfiles/h5copy_help1.ddl
  tools/test/h5copy/testfiles/h5copy_help2.ddl
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
Labels: Merge, Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement, Branch - 1.14

#2910 Fix CMake generator expression syntax
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  config/cmake/HDFMacros.cmake
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  test/API/CMakeLists.txt
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.14

#2909 Fix CMake generator expression syntax
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  config/cmake/HDFMacros.cmake
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  test/API/CMakeLists.txt
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/CMakeLists.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#2918 CMake fix gen. exprs. and add h5copy help
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  config/cmake/FindSZIP.cmake
  config/cmake/HDFMacros.cmake
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  test/API/CMakeLists.txt
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/CMakeLists.txt
  tools/src/h5import/h5import.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5delete.c
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5copy/testfiles/h5copy_help1.ddl
  tools/test/h5copy/testfiles/h5copy_help2.ddl
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build

#2919 Fix some compile failures in API tests (#2913)
  testpar/API/t_dset.c
  testpar/API/t_filter_read.c
  testpar/API/t_shapesame.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#2921 Add Doxygen for H5S_ALL, _PLIST, and _BLOCK
  src/H5Spublic.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#2922 Add Doxygen for H5ES_NONE _WAIT_NONE/FOREVER
  src/H5ESpublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#2923 Public header cleanup
  src/H5ACpublic.h
  src/H5Apublic.h
  src/H5Cpublic.h
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5Epublic.h
  src/H5FDpublic.h
  src/H5Fpublic.h
  src/H5Gpublic.h
  src/H5Ipublic.h
  src/H5Lpublic.h
  src/H5MMpublic.h
  src/H5Mpublic.h
  src/H5Opublic.h
  src/H5PLpublic.h
  src/H5Ppublic.h
  src/H5Rpublic.h
  src/H5Spublic.h
  src/H5Tpublic.h
  src/H5VLpublic.h
  src/H5Zpublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2914 Reduce code duplication in macros
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2844 Remove unused variable warning in H5C.c
  src/H5C.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2930 More code duplication reduction
  src/H5C.c
  src/H5Cimage.c
  src/H5Cmpio.c
  src/H5Cpkg.h
  test/cache_common.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2937 Update action uses version
  .github/workflows/clang-format-fix.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement

#2938 Update action uses version
  .github/workflows/clang-format-fix.yml
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement, Branch - 1.14

#2932 New 1 10 hdffv 11052
  release_docs/RELEASE.txt
  src/H5Fint.c
  test/CMakeTests.cmake
  test/cve_2020_10812.h5
  test/tmisc.c
  tools/src/misc/h5debug.c
Labels: Component - C Library, Branch - 1.10

#2944 Bump Autoconf version to 2.71
  configure.ac
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Improvement

#2942 Update action uses version
  .github/workflows/clang-format-fix.yml
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement, Branch - 1.10

#2940 Fix CMake generator expression syntax
  CMakePresets.json
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  config/cmake_ext_mod/HDFMacros.cmake
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  testpar/CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.12

#2939 Update action uses version
  .github/workflows/clang-format-fix.yml
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement, Branch - 1.12

#2941 Fix CMake generator expression syntax
  .gitignore
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  config/cmake/HDFMacros.cmake
  fortran/examples/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  testpar/CMakeLists.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.10

#2936 Move functions into more focused source code modules
  src/CMakeLists.txt
  src/H5C.c
  src/H5Cdbg.c
  src/H5Centry.c
  src/H5Cimage.c
  src/H5Cint.c
  src/H5Clog.c
  src/H5Clog.h
  src/H5Clog_json.c
  src/H5Clog_trace.c
  src/H5Cmpio.c
  src/H5Cpkg.h
  src/H5Cprivate.h
  src/H5Cquery.c
  src/H5Ctag.c
  src/Makefile.am
  test/cache_image.c
  testpar/t_cache_image.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2931 Prevent buffer overrun in H5S_select_deserialize
  src/H5Odtype.c
  src/H5Olayout.c
  src/H5Rint.c
  src/H5S.c
  src/H5Sall.c
  src/H5Shyper.c
  src/H5Snone.c
  src/H5Spkg.h
  src/H5Spoint.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5private.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#2950 Warn about changing collections during iteration
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5Gpublic.h
  src/H5Ipublic.h
  src/H5Lpublic.h
  src/H5Mpublic.h
  src/H5Ppublic.h
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#2952 Fix warning in cache_common.c
  test/cache_common.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Task

#2957 addresses gfortran >= 13 issue optimization causing segfault/corrupted memory
  fortran/src/H5Aff.F90
  fortran/src/H5Pff.F90
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#2951 Remove unnecessary fields from cache structs
  src/H5AC.c
  src/H5ACmpio.c
  src/H5ACpkg.h
  src/H5C.c
  src/H5Cdbg.c
  src/H5Centry.c
  src/H5Cimage.c
  src/H5Cint.c
  src/H5Cmpio.c
  src/H5Cpkg.h
  src/H5Cprefetched.c
  src/H5Cprivate.h
  src/H5Cquery.c
  src/H5Ctag.c
  src/H5EAcache.c
  src/H5FAcache.c
  src/H5FScache.c
  src/H5Fsuper.c
  src/H5Fsuper_cache.c
  src/H5Gcache.c
  src/H5HFcache.c
  src/H5HGcache.c
  src/H5HLcache.c
  src/H5Oalloc.c
  src/H5Ocache.c
  src/H5SMcache.c
  test/cache.c
  test/cache_api.c
  test/cache_common.c
  test/cache_image.c
  testpar/t_cache.c
  testpar/t_file.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#2953 Prevent buffer overrun in H5S_select_deserialize
  src/H5Odtype.c
  src/H5Olayout.c
  src/H5Rint.c
  src/H5S.c
  src/H5Sall.c
  src/H5Shyper.c
  src/H5Snone.c
  src/H5Spkg.h
  src/H5Spoint.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.14

#2962 Warn about changing collections during iteration
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5Gpublic.h
  src/H5Ipublic.h
  src/H5Lpublic.h
  src/H5Mpublic.h
  src/H5Ppublic.h
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Type - Improvement, Branch - 1.14

#2966 Update name of DT action and install text
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge, Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Bug, Branch - 1.14

#2902 Add h5copy help test and verify consistency
  tools/src/h5import/h5import.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5delete.c
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5copy/testfiles/h5copy_help1.ddl
  tools/test/h5copy/testfiles/h5copy_help2.ddl
  tools/test/h5copy/testh5copy.sh.in
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement

#2975 Remove version specific examples from README_HPC. (#2613)
  release_docs/README_HPC
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation

#2956 Prevent buffer overrun in H5S_select_deserialize
  src/H5Odtype.c
  src/H5Olayout.c
  src/H5Rint.c
  src/H5S.c
  src/H5Sall.c
  src/H5Shyper.c
  src/H5Snone.c
  src/H5Spkg.h
  src/H5Spoint.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5private.h
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.12

#2903 Add h5copy help test and verify consistency
  tools/src/h5copy/h5copy.c
  tools/src/h5import/h5import.c
  tools/src/h5stat/h5stat.c
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5copy/testfiles/h5copy_help1.ddl
  tools/test/h5copy/testfiles/h5copy_help2.ddl
  tools/test/h5stat/testfiles/h5stat_help1.ddl
  tools/test/h5stat/testfiles/h5stat_help2.ddl
  tools/test/h5stat/testfiles/h5stat_nofile.ddl
Labels: Merge, Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement, Branch - 1.12

#2927 Change defaults of standard filters.
  .github/workflows/main.yml
  CMakeFilters.cmake
  CMakePresets.json
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Improvement

#2980 ci: set minimal permissions on GitHub Workflows
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/main.yml
  .github/workflows/tarball.yml
Labels: Component - Testing, Type - Improvement

#2971 Update version
  README.md
  c++/src/cpp_doc_config
  config/cmake/scripts/HDF5config.cmake
  configure.ac
  java/src/hdf/hdf5lib/H5.java
  java/test/TestH5.java
  release_docs/HISTORY-1_14.txt
  release_docs/README_HPC
  release_docs/RELEASE.txt
  src/H5public.h
  tools/test/h5repack/testfiles/h5repack_layout.h5-plugin_version_test.ddl
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Task, Branch - 1.14

#2967 Add DT workflows and update windows preset
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/toolchain/aarch64.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Bug, Branch - 1.10

#2963 Prevent buffer overrun in H5S_select_deserialize
  src/H5Odtype.c
  src/H5Olayout.c
  src/H5Rint.c
  src/H5S.c
  src/H5Sall.c
  src/H5Shyper.c
  src/H5Snone.c
  src/H5Spkg.h
  src/H5Spoint.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5private.h
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug, Branch - 1.10

#2988 Fix plugin cache variable name
  .github/workflows/main.yml
  config/cmake/HDF5PluginCache.cmake
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Bug

#2987 Updated H5Ovisit_f and H5Ovisit_by_name_f wrappers internals.
  fortran/src/H5Aff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Of.c
  fortran/src/H5Off.F90
  fortran/src/H5f90proto.h
  fortran/test/tH5T_F03.F90
  fortran/testpar/async.F90
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug, Type - Improvement

#2995 Put some vol capability checks in testpar tests and remove remaining warnings
  test/API/H5_api_link_test.c
  testpar/API/t_dset.c
  testpar/API/t_file.c
  testpar/API/t_file_image.c
  testpar/API/t_mdset.c
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3001 Fix missing/misplaced h5_reset calls
  src/H5FDtest.c
  test/accum_swmr_reader.c
  test/swmr.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#3009 Add release note for #2999
  release_docs/RELEASE.txt
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#3008 Remove src/.indent.pro
  src/.indent.pro
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Type - Deprecation / Removal, Component - Misc

#3002 Develop release workflow
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - New Feature

#3012 Fix assert in Debug Windows Java JNI
  .github/workflows/main.yml
  java/src/jni/h5lImp.c
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 1. High 🔼, Component - Java, Component - Testing, Type - Bug

#3013 Fix multiConfig variable usage and remove unused CMake vars
  CMakeLists.txt
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3014 Suppress vfd.c test warning
  test/vfd.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3015 Bump GitHub Autotools actions to gcc-12
  .github/workflows/main.yml
Labels: Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#3017 Fixed Fortran Doxygen warnings
  doxygen/aliases
  fortran/src/H5Aff.F90
  fortran/src/H5Dff.F90
  fortran/src/H5ESff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Gff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Off.F90
  fortran/src/H5VLff.F90
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Fortran, Type - Bug, Type - Improvement

#3019 Remove most unused options which are defaulted #2998
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/examples/tables/propertyLists.dox
Labels: Component - Documentation, Type - Deprecation / Removal

#3020 Correct name of fetch content variable name
  config/cmake/HDFLibMacros.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#3023 Fix release version for some H5Pfapl routines
  src/H5Ppublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3021 correct warning ignore match for zlib
  config/cmake/CTestCustom.cmake
Labels: Priority - 3. Low 🔽, Component - Build, Type - Bug

#3018 API test updates
  CMakeLists.txt
  CMakeVOL.cmake
  doc/cmake-vols-fetchcontent.md
  release_docs/RELEASE.txt
  src/H5VLnative_attr.c
  test/API/CMakeLists.txt
  test/API/H5_api_async_test.c
  test/API/H5_api_attribute_test.c
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
  test/API/H5_api_datatype_test.c
  test/API/H5_api_file_test.c
  test/API/H5_api_group_test.c
  test/API/H5_api_link_test.c
  test/API/H5_api_object_test.c
  test/API/H5_api_test.c
  test/API/H5_api_test.h
  test/API/H5_api_test_util.c
  test/API/H5_api_tests_disabled.h
  test/API/tattr.c
  test/API/testhdf5.c
  test/API/testhdf5.h
  test/API/tfile.c
  test/API/th5s.c
  test/API/titerate.c
  test/API/tmisc.c
  test/API/trefer.c
  test/API/tvlstr.c
  test/CMakeLists.txt
  testpar/API/CMakeLists.txt
  testpar/API/H5_api_async_test_parallel.c
  testpar/API/H5_api_test_parallel.c
  testpar/API/t_dset.c
  testpar/API/t_file.c
  testpar/API/t_file_image.c
  testpar/API/t_mdset.c
  testpar/API/testphdf5.h
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#2383 Cleans up Java JNI warnings and add java to -Werror checks
  .github/workflows/main.yml
  java/src/jni/h5Constants.c
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5lImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5util.c
Labels: WIP, Merge - To 1.12, Merge - To 1.10, Merge - To 1.14, Priority - 3. Low 🔽, Component - Java, Type - Improvement

#3026 Only pass efc pointer to H5F__efc_open
  src/H5Fefc.c
  src/H5Fint.c
  src/H5Fpkg.h
  test/efc.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement
