Repository HDFGroup/hdf5, pull requests merged in 2024-08, with the labels that each got.

#4682 Warning fix
  tools/lib/h5diff.c
Labels: Priority - 3. Low 🔽, Component - Build, Type - Bug

#4686 Add file name argument to publish workflow
  .github/workflows/publish-release.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4685 CMake link line needs to use new HDF5_ENABLE_THREADS
  test/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#4690 Correct the properties for using THREADS library
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Testing, Component - Build, Type - Bug

#4687 doxygen file is a zipfile
  .github/workflows/publish-release.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4691 Use filename in directory sync
  .github/workflows/publish-release.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4683 Fix segfault when closing datatype during failure in H5Topen2
  src/H5Tcommit.c
  src/H5VLint.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4692 unzip does not create extra dir
  .github/workflows/publish-release.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4693 Remove racey start condition for ping thread
  test/ttsafe_semaphore.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#4681 Rework Dynamic Analysis and sanitize testing
  HDF5Examples/C/H5D/CMakeLists.txt
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/C/H5VDS/CMakeLists.txt
  HDF5Examples/C/TUTR/CMakeLists.txt
  HDF5Examples/CXX/H5D/CMakeLists.txt
  HDF5Examples/CXX/TUTR/CMakeLists.txt
  c++/test/CMakeTests.cmake
  c++/test/CMakeVFDTests.cmake
  config/cmake/CTestCustom.cmake
  fortran/test/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  test/CMakeTests.cmake
  testpar/CMakeVFDTests.cmake
  tools/lib/h5diff_array.c
  tools/lib/h5tools_str.c
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/CMakeVFDTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/perform/CMakeTests.cmake
  utils/tools/test/h5dwalk/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#4675 Remove another H5E_BEGIN/END_TRY within the library
  src/H5Gdeprec.c
  src/H5Gname.c
  test/links.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4694 Remove last H5E_BEGIN/END_TRY from library code
  src/H5Iint.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4702 Add check of returned value from API calls.
  test/links.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4699 Add mac dmg binary and remove old macos-13 workflows
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  CMakeInstallation.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Component - Misc

#4701 Add Windows SHLWAPI lib to public interface
  config/cmake/ConfigureChecks.cmake
  src/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Type - Bug

#4679 Use local variable in btree2 and print value
  test/btree2.c
  test/earray.c
  test/farray.c
  test/fheap.c
  test/objcopy.c
  test/objcopy_ref.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#4703 Add windows signing
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Improvement, Component - Misc

#4657 Add tests for H5R get name APIs
  fortran/src/H5Rff.F90
  release_docs/RELEASE.txt
  src/H5Rint.c
  src/H5Rpublic.h
  test/trefer.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Fortran

#4711 Change logic for checking secrets exists
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4707 Change osx refs to macos
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  CMakePresets.json
  HDF5Examples/CMakePresets.json
  bin/cmakehdf5
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Bug, Type - Improvement, Component - Misc

#4714 Replace alias \Code with \TText
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/H5AC_cache_config_t.dox
  doxygen/dox/MetadataCachingInHDF5.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/api-compat-macros.dox
  doxygen/dox/cookbook/Files.dox
  doxygen/dox/rm-template.dox
  src/H5Dpublic.h
  src/H5Emodule.h
  src/H5FDlog.h
  src/H5FDmulti.h
  src/H5Fpublic.h
  src/H5Gpublic.h
  src/H5Lpublic.h
  src/H5Ppublic.h
  src/H5Tmodule.h
  src/H5Tpublic.h
  src/H5public.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation

#4713 Correct signing names and variables
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4717 Add missing blosc2 info
  CMakePresets.json
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Component - Misc

#4722 Fix error return types in H5Rdeprec.c
  src/H5Rdeprec.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4721 Fix the reference file for the ABI workflow
  .github/workflows/release.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4720 Test opening unseekable file
  test/tfile.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4724 Clean up tests
  test/trefer.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4725 Fix semaphore test
  src/H5TSsemaphore.h
  test/ttsafe.c
  test/ttsafe.h
  test/ttsafe_semaphore.c
Labels: Priority - 1. High 🔼, Component - Testing, Type - Bug

#4734 Fix snapshot CI failure by adding arch name to dmg file
  .github/workflows/release-files.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4733 Fix incorrect VOL vs. non-VOL calls partially
  src/H5L.c
  test/th5o.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4739 Use gfortran 14 for cmake-ctest.yml on mac
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-cmake.yml
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#4744 Fix `HDopen macro redefined` warnings
  tools/src/h5perf/pio_engine.c
  tools/src/h5perf/sio_engine.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4738 Return basic HTTP range GET logging to ROS3
  src/H5FDs3comms.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4745 Replace non-VOL calls with VOL calls - part 1
  src/H5A.c
  src/H5D.c
  src/H5Ddeprec.c
  src/H5VLint.c
  src/H5VLprivate.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4715 Fix inconsistent documentation of get_name functions
  src/H5A.c
  src/H5Apublic.h
  src/H5Epublic.h
  src/H5Gdeprec.c
  src/H5Gpublic.h
  src/H5Lpublic.h
  test/error_test.c
  test/links.c
  test/tfile.c
  test/th5o.c
  test/tmisc.c
  test/trefer.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Testing, Type - Improvement

#4750 Remove HDF-EOS5 CI action
  .github/workflows/hdfeos5.yml
  README.md
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4748 Replace non-VOL calls with VOL calls - part 2
  src/H5F.c
  src/H5Fdeprec.c
  src/H5Fpublic.h
  test/mount.c
  test/tfile.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Documentation, Component - Testing, Type - Improvement

#4749 Restore rand_r in a few parallel tests
  test/h5test.c
  test/h5test.h
  testpar/t_pmulti_dset.c
  testpar/t_select_io_dset.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Parallel, Component - Testing, Type - Improvement

#4752 Don't run AOCC parallel tests with -j2
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Parallel, Component - Testing, Type - Improvement

#4756 Replace non-VOL calls with VOL calls - part 3
  src/H5G.c
  src/H5L.c
  src/H5Ldeprec.c
  test/th5o.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Improvement

#4573 Turn on parallel CI tests in Autotools & CMake
  .github/workflows/main-auto-par.yml
  .github/workflows/main-cmake-par.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4762 Fix typo in H5Centry.c
  src/H5Centry.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4759 Set/Unset VOL wrapping context in H5VL_attr_close
  src/H5VLcallback.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4761 Add missing C++ and Fortran to Intel oneAPI CI
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement

#4757 Remove early test exit
  test/tfile.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4763 Restore Julia CI
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - New Feature

#4760 Add testing to NVHPC CI actions (CMake & Autotools)
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement

#4772 Move 1.14.6 and 1.16.0 to correct date
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4773 Fix typo in H5T_order_t enum
  src/H5Tpublic.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Documentation, Type - Bug

#4775 Remove dummy comments that repeat function names.
  test/vol.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Testing, Type - Task

#4774 Sync develop changes August 21 - 27 to hdf5_1_14
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/main-auto-par.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  src/H5A.c
  src/H5Apublic.h
  src/H5Centry.c
  src/H5D.c
  src/H5Ddeprec.c
  src/H5Epublic.h
  src/H5F.c
  src/H5FDs3comms.c
  src/H5Fdeprec.c
  src/H5Fpublic.h
  src/H5G.c
  src/H5Gdeprec.c
  src/H5Gpublic.h
  src/H5L.c
  src/H5Ldeprec.c
  src/H5Lpublic.h
  src/H5Tpublic.h
  src/H5VLcallback.c
  src/H5VLint.c
  src/H5VLpassthru.c
  src/H5VLprivate.h
  src/H5public.h
  test/error_test.c
  test/h5test.c
  test/h5test.h
  test/links.c
  test/mount.c
  test/tfile.c
  test/th5o.c
  test/tmisc.c
  test/trefer.c
  testpar/t_pmulti_dset.c
  testpar/t_select_io_dset.c
  tools/src/h5perf/pio_engine.c
  tools/src/h5perf/sio_engine.c
Labels: Priority - 1. High 🔼, Type - Task, Branch - 1.14

#4777 Fix grammar in H5Odtype.c comment block
  src/H5Odtype.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4776 Add subfiling checks to the gcc action
  .github/workflows/main-auto-par.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4771 Replace non-VOL calls with VOL calls - part 4
  src/H5Gdeprec.c
  src/H5O.c
  src/H5Odeprec.c
  src/H5Tcommit.c
  src/H5Tdeprec.c
  src/H5VLnative.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4778 Add subfiling to CI everywhere we test parallel
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/main-cmake-par.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4779 Convert Collective Calls html file to doxygen
  doxygen/dox/CollectiveCalls.dox
  doxygen/dox/IntroParHDF5.dox
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4787 Correct issues in workflows due to mis-merges
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-auto-par.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/publish-release.yml
  release_docs/INSTALL_CMake.txt
  src/H5Ppublic.h
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4789 Fixes Fortran parallel build race condition for tests
  hl/fortran/test/Makefile.am
Labels: Priority - 2. Medium ⏹, Component - Fortran, Type - Bug

#4791 Correct build paths for binaries
  .github/workflows/cmake-ctest.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4790 Fix grammar and simplify comment in H5Fint.c
  src/H5Fint.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4793 Fix char-subscripts warnings in H5private.h
  src/H5private.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement
