Repository HDFGroup/hdf5, pull requests merged in 2024-10, with the labels that each got.

#4903 fixed washed-out table text in documentation
  doxygen/dox/CollectiveCalls.dox
Labels: Merge - To 1.14, Component - Documentation

#4881 Split H5TS termination into threadlocal/thread-global parts
  src/H5TSint.c
  src/H5TSprivate.h
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4875 Remove a call to H5E_clear_stack() in H5O code
  src/H5Eint.c
  src/H5Oint.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4871 Remove H5E_clear_stack() from library
  src/H5Gloc.c
  src/H5Ocopy.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4852 Clean up thread-local error stacks in all threads
  src/H5E.c
  src/H5Eint.c
  src/H5Epkg.h
  src/H5TSint.c
  test/CMakeLists.txt
  test/Makefile.am
  test/ttsafe.c
  test/ttsafe.h
  test/ttsafe_error_stacks.c
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4902 Enable HDF-EOS5 Action again
  .github/workflows/hdfeos5.yml
  README.md
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Task

#4908 Add Fortran H5ES reference to RM table
  doxygen/dox/ReferenceManual.dox
Labels: Component - Documentation

#4913 Update CI and CMake to new branch
  .github/workflows/abi-report.yml
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cmake.yml
  .github/workflows/cve.yml
  .github/workflows/cygwin-auto.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/daily-build.yml
  .github/workflows/h5py.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/main-auto-par-spc.yml
  .github/workflows/main-auto-par.yml
  .github/workflows/main-auto-spc.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/scorecard.yml
  .github/workflows/tarball.yml
  .github/workflows/vfd-main.yml
  .github/workflows/vfd-subfiling.yml
  .github/workflows/vfd.yml
  .github/workflows/vol.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_log.yml
  .github/workflows/vol_rest.yml
  CMakePresets.json
  CTestConfig.cmake
  config/cmake-presets/hidden-presets.json
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5config.cmake
  config/lt_vers.am
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - New Feature, Type - Task, Type - Deprecation / Removal, Component - Misc, Branch - 1.16

#4909 add Fortran H5DO reference to RM table
  doxygen/dox/ReferenceManual.dox
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Merge - To 1.16

#4861 Remove H5E_clear_stack() from H5SM code
  src/H5Adense.c
  src/H5B2.c
  src/H5B2private.h
  src/H5SM.c
  src/H5SMpkg.h
  test/btree2.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4917 Correct remaining 1.16 update versions
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  CMakePresets.json
  HDF5Examples/README.md
  README.md
  config/cmake/cacheinit.cmake
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/dox/ExamplesAPI.dox
  doxygen/examples/H5.format.1.1.html
  doxygen/hdf5doxy_layout.xml
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_Cygwin.txt
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Component - Misc, Branch - 1.16

#4919 Update version usage
  .github/workflows/daily-build.yml
  .github/workflows/h5py.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  config/cmake/scripts/HDF5config.cmake
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_Cygwin.txt
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Bug, Component - Misc

#4920 Cleanup sync issues
  .github/workflows/daily-build.yml
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug, Branch - 1.14

#4922 Create HISTORY file and clear RELEASE
  release_docs/HISTORY-1_14_0-1_16_0.txt
  release_docs/HISTORY-1_16.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Deprecation / Removal, Branch - 1.16

#4923 Add HISTORY and clean RELEASE
  release_docs/HISTORY-1_14_0-1_16_0.txt
  release_docs/RELEASE.txt
  release_docs/RELEASE_PROCESS.md
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Component - Documentation, Type - Deprecation / Removal

#4929 Use H5VLcmp_connector_cls to compare VOL connector IDs in API tests
  test/API/H5_api_test.c
Labels: Priority - 1. High 🔼, Component - Testing, Type - Task

#4927 Adding missing Fortran examples and fixed broken links for Fortran
  doxygen/dox/ExamplesAPI.dox
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Fortran, Type - Improvement, Merge - To 1.16

#4930 Minor refactoring of testframe.c testing framework
  c++/test/testhdf5.cpp
  test/testframe.c
  test/testframe.h
  test/testhdf5.c
  test/ttsafe.c
  testpar/t_2Gio.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Task, Merge - To 1.16

#4936 Use H5VLcmp_connector_cls to compare VOL connector IDs in parallel API tests
  testpar/API/H5_api_test_parallel.c
Labels: Priority - 1. High 🔼, Component - Testing, Type - Task

#4945 Remove old RELEASE.txt note
  release_docs/RELEASE.txt
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task, Merge - To 1.16

#4938 add analysis and coverage to CDash reports
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/daily-schedule.yml
  CMakeLists.txt
  config/cmake/ConfigureChecks.cmake
  config/sanitizer/code-coverage.cmake
  config/toolchain/intel.cmake
  src/H5VLpassthru.c
  src/H5system.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement, Component - Misc, Merge - To 1.16

#4939 Fix for issue #4849 that settings in fapl libver bounds causes unexpe…
  c++/test/tfile.cpp
  src/H5Fint.c
  src/H5Fsuper.c
  src/H5Oint.c
  src/H5Oprivate.h
  test/swmr.c
  test/tfile.c
  test/tmisc.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug, Merge - To 1.16

#4950 Announce 1.16.0 --> 2.0.0
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Priority - 1. High 🔼, Type - Task, Component - Misc, Merge - To 2.0

#4947 Fixed data typing errors discovered by promoting integers and reals.
  fortran/src/H5Rff.F90
  fortran/src/H5VLff.F90
Labels: Priority - 1. High 🔼, Component - Fortran, Type - Bug, Merge - To 2.0

#4954 Only clear FE_INVALID when that symbol is present on the system
  release_docs/RELEASE.txt
  src/H5Tinit_float.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Bug, Merge - To 2.0

#4955 Remove duplicate and unneeded dmg step in workflow - correct ABI version compare
  .github/workflows/main-cmake.yml
  .github/workflows/release.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4962 Fix h5py GitHub Action
  .github/workflows/h5py.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Task

#4963 Do not package debug builds
  .github/workflows/main-cmake.yml
Labels: Priority - 1. High 🔼, Type - Bug, Component - Misc, Merge - To 2.0

#4965 Updated hyperslab documentation
  fortran/src/H5Sff.F90
  src/H5Spublic.h
Labels: Component - Documentation, Type - Improvement, Merge - To 2.0

#4957 Fix linker flag in pkg-config file for system zlib
  CMakeFilters.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Merge - To 2.0

#4966 Incorporate remaining parts of the filters.html file
  doxygen/dox/ExamplesAPI.dox
  src/H5Dmodule.h
  src/H5PLmodule.h
  src/H5Zmodule.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement, Merge - To 2.0

#4969 Remove TRUE and FALSE from H5private.h
  c++/test/tattr.cpp
  c++/test/tfile.cpp
  c++/test/tlinks.cpp
  c++/test/tobject.cpp
  hl/test/test_lite.c
  src/H5Eint.c
  src/H5TSmutex.c
  src/H5TSwin.c
  src/H5VLint.c
  src/H5VLtest.c
  src/H5private.h
  test/cmpd_dset.c
  test/error_test.c
  test/h5test.c
  test/select_io_dset.c
  test/trefer.c
  test/ttsafe_rec_rwlock.c
  test/vol.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - High-Level Library, Component - C++, Component - Testing, Type - Improvement, Merge - To 2.0

#4970 Moved timer functionality to (new) H5timer.h
  src/CMakeLists.txt
  src/H5private.h
  src/H5timer.c
  src/H5timer.h
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement, Merge - To 2.0

#4967 The h5(p)*c parser retains escaped whitespace character
  bin/h5cc.in
  c++/src/h5c++.in
  fortran/src/h5fc.in
Labels: Priority - 1. High 🔼, Component - Tools, Type - Bug, Merge - To 2.0

#4972 Move warning suppression macros to H5warnings.h
  src/CMakeLists.txt
  src/H5FDmulti.c
  src/H5private.h
  src/H5warnings.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Merge - To 2.0

#4973 Switch HDoff_t from __int64 to int64_t on Windows
  release_docs/RELEASE.txt
  src/H5public.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Merge - To 2.0

#4977 Remove FALSE from some API tests
  test/API/H5_api_link_test.c
  test/API/H5_api_object_test.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Task, Merge - To 2.0

#4975 Set the C standard to 11
  config/clang-flags
  config/cmake/HDFCompilerFlags.cmake
  config/gnu-flags
  config/nvidia-flags
  config/oneapi-flags
  release_docs/RELEASE.txt
  src/H5win32defs.h
Labels: Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Improvement, Merge - To 2.0

#4976 Remove the high-level GIF tools
  configure.ac
  hl/tools/CMakeLists.txt
  hl/tools/Makefile.am
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/gif2h5/CMakeTests.cmake
  hl/tools/gif2h5/Makefile.am
  hl/tools/gif2h5/decompress.c
  hl/tools/gif2h5/gif.h
  hl/tools/gif2h5/gif2hdf.c
  hl/tools/gif2h5/gif2mem.c
  hl/tools/gif2h5/gifread.c
  hl/tools/gif2h5/h52gifgentst.c
  hl/tools/gif2h5/h52giftest.sh.in
  hl/tools/gif2h5/hdf2gif.c
  hl/tools/gif2h5/hdfgifwr.c
  hl/tools/gif2h5/testfiles/README
  hl/tools/gif2h5/testfiles/ex_image2.h5
  hl/tools/gif2h5/testfiles/h52giftst.h5
  hl/tools/gif2h5/testfiles/image1.gif
  hl/tools/gif2h5/writehdf.c
  release_docs/INSTALL_Autotools.txt
  release_docs/RELEASE.txt
  src/H5build_settings.autotools.c.in
  src/libhdf5.settings.autotools.in
Labels: Priority - 1. High 🔼, Component - Tools, Component - High-Level Library, Type - Deprecation / Removal, Merge - To 2.0

#4980 Always check for __attribute__() in CMake
  config/cmake/ConfigureChecks.cmake
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Merge - To 2.0

#4979 Remove some Solaris Studio work-arounds
  bin/genparser
  config/cmake/ConfigureChecks.cmake
  hl/src/H5LTanalyze.c
  hl/src/H5LTparse.c
  release_docs/RELEASE.txt
  src/H5private.h
  tools/test/perform/chunk.c
  tools/test/perform/overhead.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - High-Level Library, Component - Build, Type - Deprecation / Removal, Merge - To 2.0

#4981 Check in generated files in src
  .gitignore
  release_docs/RELEASE.txt
  src/H5Edefin.h
  src/H5Einit.h
  src/H5Emajdef.h
  src/H5Emindef.h
  src/H5Epubgen.h
  src/H5Eterm.h
  src/H5overflow.h
  src/H5version.h
Labels: Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Improvement, Merge - To 2.0

#4988 Move h5_test_init() calls after MPI_Init
  testpar/t_pmulti_dset.c
  testpar/t_select_io_dset.c
Labels: Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement, Merge - To 2.0

#4995 Remove bin/cmakehdf5
  bin/README.md
  bin/cmakehdf5
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Deprecation / Removal

#4989 Replace COPYING with LICENSE in workflows
  .autom4te.cfg
  .gitattributes
  .github/workflows/autotools.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/cve.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/netcdf.yml
  .h5chkright.ini
Labels: Priority - 0. Blocker ⛔, Type - Bug, Component - Misc, Merge - To 2.0

#4990 Prefix remaining CMake options except for CMake BUILD* variables
  .github/workflows/cmake-analysis.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_log.yml
  .github/workflows/vol_rest.yml
  CMakeLists.txt
  config/cmake-presets/hidden-presets.json
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/scripts/HDF5options.cmake
  config/sanitizer/README.md
  config/sanitizer/sanitizers.cmake
  doc/cmake-vols-fetchcontent.md
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5build_settings.cmake.c.in
  src/libhdf5.settings.cmake.in
  test/CMakeTests.cmake
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Deprecation / Removal, Component - Misc, Merge - To 2.0

#4999 Disable Julia CI
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Deprecation / Removal, Merge - To 2.0

#4968 Remove another couple of H5E_clear_stack calls
  release_docs/RELEASE.txt
  src/H5Dvirtual.c
  src/H5Gloc.c
  src/H5Gtraverse.c
  test/links.c
Labels: Component - C Library, Component - Testing, Type - Improvement, Merge - To 2.0

#4935 Add support for native zlib-ng in the library and compression references
  CMakeFilters.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDFLibMacros.cmake
  config/cmake/ZLIBNG/CMakeLists.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5Zdeflate.c
  test/CMakeLists.txt
  test/chunk_info.c
  test/direct_chunk.c
  tools/test/perform/CMakeLists.txt
  tools/test/perform/direct_write_perf.c
  tools/test/perform/zip_perf.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Build, Type - Improvement, Merge - To 2.0

#5001 Patch Julia CI
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/julia_ci.patch
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement, Merge - To 2.0

#4953 Updated zlib and libaec compression versions
  CMakePresets.json
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIBNG/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Merge - To 2.0

#4997 Add szip documentation to dataset section of user guide
  src/H5Dmodule.h
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement, Merge - To 2.0

#4942 Refactor allocation of API context
  release_docs/RELEASE.txt
  src/H5.c
  src/H5Atest.c
  src/H5CX.c
  src/H5CXprivate.h
  src/H5FDprivate.h
  src/H5Fprivate.h
  src/H5Ftest.c
  src/H5Gtest.c
  src/H5Itest.c
  src/H5Otest.c
  src/H5TSmutex.h
  src/H5TSprivate.h
  src/H5Tconv_array.c
  src/H5Tconv_bitfield.c
  src/H5Tconv_compound.c
  src/H5Tconv_enum.c
  src/H5Tconv_float.c
  src/H5Tconv_integer.c
  src/H5Tconv_reference.c
  src/H5Tconv_string.c
  src/H5Tconv_vlen.c
  src/H5VL.c
  src/H5VLconnector_passthru.h
  src/H5VLint.c
  src/H5VLprivate.h
  src/H5Zprivate.h
  src/H5private.h
  test/accum.c
  test/accum_swmr_reader.c
  test/btree2.c
  test/cache.c
  test/cache_common.h
  test/cache_tagging.c
  test/chunk_info.c
  test/cmpd_dset.c
  test/dsets.c
  test/earray.c
  test/efc.c
  test/farray.c
  test/fheap.c
  test/freespace.c
  test/gheap.c
  test/lheap.c
  test/mf.c
  test/ntypes.c
  test/ohdr.c
  test/page_buffer.c
  test/titerate.c
  test/trefer.c
  test/trefer_deprec.c
  test/tselect.c
  test/unregister.c
  test/vol.c
  testpar/t_cache.c
  testpar/t_file.c
  testpar/t_shapesame.c
  tools/src/misc/h5debug.c
Labels: Merge - Develop Only, Component - C Library, Component - Testing, Type - Improvement

#5003 Update the README
  README.md
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Task, Merge - To 2.0

#5000 Certain versions of VS produce rounding errors in tfloatsattr
  tools/test/h5dump/CMakeTests.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug, Merge - To 2.0

#4974 Split out compiler flags into specific compiler files
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-script.yml
  CMakeLists.txt
  config/cmake/HDFCXXCompilerFlags.cmake
  config/cmake/HDFClangCXXFlags.cmake
  config/cmake/HDFClangFlags.cmake
  config/cmake/HDFCompilerCXXFlags.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFCompilerFortranFlags.cmake
  config/cmake/HDFFortranCompilerFlags.cmake
  config/cmake/HDFGnuCXXFlags.cmake
  config/cmake/HDFGnuFlags.cmake
  config/cmake/HDFGnuFortranFlags.cmake
  config/cmake/HDFIntelCXXFlags.cmake
  config/cmake/HDFIntelFlags.cmake
  config/cmake/HDFIntelFortranFlags.cmake
  config/cmake/HDFMsvcCXXFlags.cmake
  config/cmake/HDFMsvcFlags.cmake
  config/cmake/HDFNvhpcCXXFlags.cmake
  config/cmake/HDFNvhpcFlags.cmake
  config/cmake/HDFNvhpcFortranFlags.cmake
  release_docs/RELEASE.txt
  src/H5build_settings.cmake.c.in
  src/libhdf5.settings.cmake.in
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Merge - To 2.0

#5009 Get the Autotools version number from H5public.h
  README.md
  configure.ac
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement

#5007 Fix h5py CI failure
  .github/workflows/h5py.yml
Labels: Component - Testing

#5004 Move cygwin workflow to cdash reports in daily-build
  .github/workflows/cmake.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/daily-build.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement, Component - Misc, Merge - To 2.0

#5013 Remove duplicate sec2 VFD ID variable
  src/H5FDwindows.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#5011 Remove version number from h5repack test plugin
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/dynlib_vrpk.c
  tools/test/h5repack/expected/h5repack_layout.h5-plugin_version_test.ddl
  tools/test/h5repack/expected/plugin_version_test.h5repack_layout.h5.tst
  tools/test/h5repack/h5repack_plugin.sh.in
Labels: Priority - 2. Medium ⏹, Component - Tools, Component - Testing, Type - Improvement

#5021 Fix minor Windows warnings
  src/H5HFhuge.c
  test/external_common.c
  test/h5test.c
  tools/lib/h5diff.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Testing, Type - Improvement

#5019 Clean up comments in FUNC_ENTER macros
  src/H5private.h
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#5017 Fix bin/restore to not delete checked-in files
  bin/restore.sh
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement

#5020 Fix bad private FUNC_ENTER macros
  src/H5.c
  src/H5Aint.c
  src/H5B2hdr.c
  src/H5B2int.c
  src/H5B2test.c
  src/H5Dchunk.c
  src/H5Dio.c
  src/H5Dlayout.c
  src/H5FDint.c
  src/H5FDmpio.c
  src/H5FDtest.c
  src/H5FL.c
  src/H5FScache.c
  src/H5FSint.c
  src/H5Faccum.c
  src/H5Fprivate.h
  src/H5Fquery.c
  src/H5Gstab.c
  src/H5HG.c
  src/H5Oattr.c
  src/H5Oattribute.c
  src/H5Oshared.h
  src/H5Pint.c
  src/H5Rint.c
  src/H5T.c
  src/H5TSc11.c
  src/H5TSint.c
  src/H5TSpthread.c
  src/H5TSrec_rwlock.c
  src/H5TSwin.c
  src/H5Tvlen.c
  src/H5VLnative.c
  src/H5private.h
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug

#5023 Add workflow step to test expected test failures
  .github/workflows/nvhpc-cmake.yml
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement, Component - Misc, Merge - To 2.0

#4991 Add msys2 workflow for CMake
  .github/workflows/cmake.yml
  .github/workflows/msys2-cmake.yml
  config/cmake/ConfigureChecks.cmake
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Component - Misc, Merge - To 2.0

#5002 Fix segfault in h5dump caused by corrupted btree node level
  src/H5B.c
  src/H5Bcache.c
  src/H5Bpkg.h
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement

#5024 Rework FUNC_ENTER macros
  src/H5.c
  src/H5private.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#5025 Add long double format option to h5dump
  hl/tools/h5watch/h5watch.c
  release_docs/RELEASE.txt
  tools/lib/h5tools.h
  tools/lib/h5tools_dump.c
  tools/lib/h5tools_str.c
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump.h
  tools/src/h5dump/h5dump_ddl.c
  tools/src/h5dump/h5dump_extern.h
  tools/src/h5dump/h5dump_xml.c
  tools/src/h5ls/h5ls.c
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
  tools/test/h5dump/expected/tfloatsattrs.ddl
  tools/test/h5dump/expected/tfloatsattrs.wddl
  tools/test/h5dump/testh5dump.sh.in
Labels: Priority - 0. Blocker ⛔, Component - Tools, Type - Bug, Type - Improvement, Merge - To 2.0

#5030 Remove Julia CI source patch
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/julia_ci.patch
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#5031 Remove Autotools Cygwin PR action
  .github/workflows/autotools.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Deprecation / Removal

#5035 Verify CMake workflows match autotools
  .github/workflows/main-cmake-par-spc.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
  .github/workflows/msys2-cmake.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/testxpr-cmake.yml
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement, Component - Misc, Merge - To 2.0

#5050 Add HDF5 2.0 planning link to README.md
  README.md
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Task

#5051 Add callable workflows for building OpenMPI and MPICH from source
  .github/workflows/build_mpich_source.yml
  .github/workflows/build_openmpi_source.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - New Feature

#5053 malloc --> calloc in H5B_t allocation
  src/H5B.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#5054 Make H5T__free more aggressive about cleanup
  src/H5T.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement
