Repository HDFGroup/hdf5, pull requests merged in 2024-07, with the labels that each got.

#4617 Update release info
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4619 Add H5F_LIBVER_V116 to internal library version structures
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/test/tH5P_F03.F90
  src/H5Aint.c
  src/H5Dlayout.c
  src/H5Dpkg.h
  src/H5Fsuper.c
  src/H5Ofill.c
  src/H5Ofsinfo.c
  src/H5Oint.c
  src/H5Opkg.h
  src/H5Opline.c
  src/H5S.c
  src/H5Shyper.c
  src/H5Spkg.h
  src/H5Spoint.c
  src/H5T.c
  src/H5Tpkg.h
  test/dtypes.c
  test/h5test.c
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Component - Fortran, Type - Improvement

#4609 Add 'try' parameter to H5Z_find, and remove calls to H5E_clear_stack()
  src/H5Opline.c
  src/H5Pocpl.c
  src/H5Z.c
  src/H5Zprivate.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4625 Fix a stack size warning in ros3 VFD code
  src/H5FDs3comms.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4626 Reworked cleaning up API test files
  test/API/H5_api_async_test.c
  test/API/H5_api_link_test.c
  test/API/H5_api_object_test.c
  test/API/H5_api_test.c
  test/API/H5_api_test_util.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Task

#4622 corrected offset type in C wrapper
  fortran/src/H5Pf.c
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#4624 Remove some internal use of API calls and H5E_BEGIN_TRY/H5E_END_TRY
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5VLcallback.c
  src/H5VLconnector.h
  src/H5VLmodule.h
  src/H5VLnative_file.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4646 Remove auto NSIS check because of issues with CI
  CMakeInstallation.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#4628 Add python testing for examples
  HDF5Examples/C/TUTR/CMakeTests.cmake
  HDF5Examples/CMakeLists.txt
  HDF5Examples/PYTHON/CMakeLists.txt
  HDF5Examples/PYTHON/Py_sourcefiles.cmake
  HDF5Examples/PYTHON/h5_vlstring.py
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
Labels: Component - Testing, Component - Build, Type - Improvement

#4649 Clean up Fortran __float128 configure-time checks
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFTests.c
  configure.ac
  fortran/test/tH5T_F03.F90
  m4/aclocal_fc.m4
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Improvement

#4604 Feature/awesome
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/Overview.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/UsersGuide.dox
  doxygen/doxygen-awesome.css
  doxygen/examples/DebuggingHDF5Applications.html
  doxygen/examples/FileFormat.html
  doxygen/examples/FileImageOps.html
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
  doxygen/hdf5_header.html
  doxygen/hdf5doxy.css
  doxygen/hdf5doxy_layout.xml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4639 Add temporary fix for ARM64 Mac _Float16 build failure
  .github/workflows/main-cmake.yml
  src/H5private.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Bug

#4640 Update doxygen Learn Basics / example refs. Add Reference sections
  HDF5Examples/JAVA/TUTR/HDF5GroupAbsoluteRelativeCreate.java
  HDF5Examples/JAVA/TUTR/Java_sourcefiles.cmake
  HDF5Examples/JAVA/TUTR/tfiles/110/HDF5GroupAbsoluteRelativeCreate.txt
  doxygen/aliases
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/ViewTools.dox
  fortran/src/H5Fff.F90
  hl/src/H5DOpublic.h
  hl/src/H5DSpublic.h
  hl/src/H5IMpublic.h
  hl/src/H5LTpublic.h
  hl/src/H5PTpublic.h
  hl/src/H5TBpublic.h
  src/H5Dmodule.h
  src/H5ESmodule.h
  src/H5Fmodule.h
  src/H5Imodule.h
  src/H5Lmodule.h
  src/H5Mmodule.h
  src/H5Omodule.h
  src/H5PLmodule.h
  src/H5Rmodule.h
  src/H5Smodule.h
  src/H5Tmodule.h
  src/H5VLmodule.h
  src/H5Zmodule.h
  src/H5module.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4653 Fixed messed up table captions.
  doxygen/examples/FileFormat.html
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
Labels: Merge - To 1.14, Component - Documentation

#4650 Fixed FetchContent usage for new CMake reqs.
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Deprecation / Removal

#4648 Eliminate more H5E_BEGIN/END_TRY macros and H5E_clear_stack() calls
  src/H5FDfamily.c
  src/H5Fsuper.c
  src/H5SM.c
  src/H5SMpkg.h
  src/H5SMtest.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4654 Make VOL CI run against current branch
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_log.yml
  .github/workflows/vol_rest.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Bug

#4658 Correct name of zlib_ng option
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake-spc.yml
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug, Component - Misc

#4660 Fix the examples for testing java with binaries
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/hdf5-config.cmake.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Java, Component - Testing, Component - Build, Type - Bug

#4663 publish msi binary
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Task, Component - Misc

#4664 Add publish from branch workflow
  .github/workflows/publish-branch.yml
  .github/workflows/publish-release.yml
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Type - Task, Component - Misc

#4669 Fix incorrect indentation for permissions in workflow yml files.
  .github/workflows/publish-branch.yml
  .github/workflows/publish-release.yml
Labels: Merge - To 1.14, Component - Misc

#4677 Cleanup conflict diff line from sync to hdf5_1_14
  doxygen/aliases
Labels: Priority - 3. Low 🔽, Component - Documentation, Branch - 1.14

#4676 Remove outdated line from Copyright header in new files.
  HDF5Examples/C/H5G/test-pc.sh
  HDF5Examples/C/H5T/test-pc.sh
  HDF5Examples/FORTRAN/H5G/test-pc.sh
  HDF5Examples/FORTRAN/H5T/test-pc.sh
  test/testframe.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Misc

#4666 Fix binary examples process
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-cmake.yml
  HDF5Examples/CMakePresets.json
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Java, Component - Build, Type - Bug
