Repository HDFGroup/hdf5, pull requests merged in 2024-01, with the labels that each got.

#3916 New Fortran Examples added
  HDF5Examples/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/h5_version.h.in
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/Fortran_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_dataset.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_file_create.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_filtered_writes_no_sel.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_chunk.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_col.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_pattern.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_row.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_subfiling.F90
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90global.F90
  fortran/src/Makefile.am
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - Task

#3917 Remove examples that have been moved to HDF5Examples folder
  HDF5Examples/C/H5PAR/ph5example.c
  HDF5Examples/CTestConfig.cmake
  examples/CMakeLists.txt
  examples/CMakeTests.cmake
  examples/Makefile.am
  examples/h5_vds-eiger.c
  examples/h5_vds-exc.c
  examples/h5_vds-exclim.c
  examples/h5_vds-percival-unlim-maxmin.c
  examples/h5_vds-percival-unlim.c
  examples/h5_vds-percival.c
  examples/h5_vds-simpleIO.c
  examples/h5_vds.c
  examples/ph5_filtered_writes.c
  examples/ph5_filtered_writes_no_sel.c
  examples/ph5_subfiling.c
  examples/run-c-ex.sh.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Component - Build, Component - Misc

#3920 Fix building VOLs under library with CMake <3.24
  CMakeVOL.cmake
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3921 Use props for includes and remove global includes
  CMakeFilters.cmake
  CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
  HDF5Examples/JAVA/CMakeLists.txt
  HDF5Examples/JAVA/H5D/CMakeLists.txt
  HDF5Examples/JAVA/H5G/CMakeLists.txt
  HDF5Examples/JAVA/H5J/CMakeLists.txt
  HDF5Examples/JAVA/H5T/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  src/CMakeLists.txt
  test/dsets.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Component - Misc

#3926 renamed defined H5_VERS* to avoid conflicts
  configure.ac
  fortran/src/H5config_f.inc.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Bug

#3919 Add H5Dread/write_multi to API tests
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3924 Fix building VOLs under library with CMake <3.24
  CMakeVOL.cmake
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Bug, Branch - 1.14

#3929 Update upload- artifact to match download version
  .github/workflows/cmake-ctest.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc

#3933 CMake compression and directory includes from develop
  CMakeFilters.cmake
  CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
  HDF5Examples/JAVA/CMakeLists.txt
  HDF5Examples/JAVA/H5D/CMakeLists.txt
  HDF5Examples/JAVA/H5G/CMakeLists.txt
  HDF5Examples/JAVA/H5J/CMakeLists.txt
  HDF5Examples/JAVA/H5T/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/mccacheinit.cmake
  src/CMakeLists.txt
  test/dsets.c
Labels: Merge, Priority - 1. High 🔼, Component - Build, Type - Bug, Type - Improvement, Branch - 1.14

#3931 Add H5Dread/write_multi to API tests
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Branch - 1.14

#3934 Reorg and update options for doc and cmake config
  CMakeLists.txt
  config/cmake/hdf5-config.cmake.in
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation

#3939 Remove incorrect include of sz header
  testpar/t_filter_read.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#3886 autogen.sh: check directly for libtoolize instead of libtool [as libtool is not used here]
  autogen.sh
Labels: Priority - 3. Low 🔽, Component - Build, Type - Improvement

#3943 Clean up Doxygen for szip functions and constants
  src/H5Ppublic.h
  src/H5Zpublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Documentation, Type - Improvement

#3944 Replace off_t with HDoff_t internally
  hl/tools/gif2h5/gif2hdf.c
  src/H5Pdcpl.c
  src/H5Ppublic.h
  src/H5win32defs.h
  test/h5test.c
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - High-Level Library, Component - Parallel, Component - Testing, Type - Improvement

#3948 Fix chid_t to hid_t
  src/H5Apublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Documentation, Type - Bug

#3932 Update H5Fget_obj_count/ids docs to reflect dtype behavior
  doxygen/aliases
  src/H5Fpublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3941 Fortran API work.
  fortran/src/H5Ff.c
  fortran/src/H5Fff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/fortranlib_test.F90
  fortran/test/tH5F.F90
  fortran/test/tH5Sselect.F90
  release_docs/RELEASE.txt
  src/H5Spublic.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Fortran, Type - New Feature, Type - Task

#3937 Add the user test program in HDFFV-9174 for committed types.
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#3949 Document H5Fget_obj_count/ids behavior for datatypes
  doxygen/aliases
  src/H5Fpublic.h
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Branch - 1.14

#3942 Remove cached datatype conversion path table entries on file close
  src/H5Fint.c
  src/H5T.c
  src/H5Tpkg.h
  src/H5Tprivate.h
  test/tmisc.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#3957 fixed BIND name
  fortran/src/H5Sff.F90
  fortran/test/tH5Sselect.F90
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#3960 Fix infinite loop on API test fail
  test/API/H5_api_dataset_test.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#3964 Change 'extensible' to 'fixed' in H5FA code
  src/H5FAcache.c
  src/H5FAhdr.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3958 RF: move codespell configuration into .codespellrc so could be used locally as well
  .codespellrc
  .github/workflows/codespell.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Improvement, Component - Misc

#3955 Add RELEASE.txt note for the fix for issue #1256
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3961 Fix infinite loop on API test fail
  test/API/H5_api_dataset_test.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug, Branch - 1.14

#3963 Document that fileno is same for all handles
  src/H5Fpublic.h
  src/H5Opublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3962 Fix doxygen errors
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release.yml
  CMakeLists.txt
  configure.ac
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/PredefinedDatatypeTables.dox
  doxygen/examples/tables/fileDriverLists.dox
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/callbacks/Callbacks.java
  java/src/hdf/hdf5lib/callbacks/H5A_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5D_append_cb.java
  java/src/hdf/hdf5lib/callbacks/H5D_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5E_walk_cb.java
  java/src/hdf/hdf5lib/callbacks/H5L_iterate_t.java
  java/src/hdf/hdf5lib/callbacks/H5O_iterate_t.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_close_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_copy_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_create_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_close_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_compare_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_copy_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_create_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_delete_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_get_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_set_func_cb.java
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/H5Dmodule.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5Pmodule.h
  src/H5Ppublic.h
  src/H5Tmodule.h
  src/H5VLmodule.h
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Component - Testing, Component - Build, Type - Bug, Component - Misc

#3959 Add API support for Fortran MPI_F08 module definitions.
  .github/workflows/nvhpc-cmake.yml
  CMakeLists.txt
  config/cmake/H5pubconf.h.in
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/H5Pff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/hdf5_fortrandll.def.in
  fortran/testpar/CMakeLists.txt
  fortran/testpar/Makefile.am
  fortran/testpar/mpi_param.F90
  fortran/testpar/ptest.F90
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - New Feature

#3965 Document that fileno is the same for all handles
  src/H5Fpublic.h
  src/H5Opublic.h
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Branch - 1.14

#3966 Added a GitHub Codespaces configuration.
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/noop.txt
Labels: Type - Improvement, Component - Misc

#3968 Fixed XL and gfortran errors
  fortran/src/H5Fff.F90
  fortran/src/H5Sff.F90
  fortran/test/tH5Sselect.F90
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#3954 h5 compiler wrappers now pass all arguments passed to it to the compile line
  bin/h5cc.in
  c++/examples/testh5c++.sh.in
  c++/src/h5c++.in
  examples/testh5cc.sh.in
  fortran/examples/testh5fc.sh.in
  fortran/src/h5fc.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Build, Type - Bug

#3974 Explicitly use PROJECT_BINARY_DIR in target copy location
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#3975 Fix space difference vs expected output for Fortran examples with compression filters
  HDF5Examples/FORTRAN/H5D/h5ex_d_checksum.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_gzip.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_nbit.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_soint.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_szip.F90
Labels: Merge - To 1.14, Component - Testing, Component - Misc

#3950 Clarify vlen string message documentation
  doxygen/examples/H5.format.html
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement
