Repository HDFGroup/hdf5, pull requests merged in 2024-05, with the labels that each got.

#4446 H5R Fortran wrappers and misc. H5R API/DOC updates
  doxygen/aliases
  fortran/src/H5Rff.F90
  fortran/src/H5Sff.F90
  fortran/src/H5_f.c
  fortran/src/H5_ff.F90
  fortran/src/H5f90global.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/fortranlib_test.F90
  fortran/test/tH5R.F90
  release_docs/RELEASE.txt
  src/H5Fpublic.h
  src/H5Ipublic.h
  src/H5Ppublic.h
  src/H5R.c
  src/H5Rpublic.h
  test/trefer.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Fortran, Component - Testing, Type - Bug, Type - Improvement, Type - New Feature, Type - Task

#4452 Fix grammar in VOL guide
  doxygen/dox/VOLConnGuide.dox
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4456 Fix bug in MPI-IO VFD
  src/H5FDmpio.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Bug

#4458 Fixed failures with xl compilers.
  fortran/src/H5Rff.F90
  fortran/test/tH5R.F90
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#4454 Removed "function/code stack" debugging configure option
  bin/trace
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDF5DeveloperBuild.cmake
  config/cmake/libhdf5.settings.cmake.in
  configure.ac
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5CS.c
  src/H5CSprivate.h
  src/H5FL.c
  src/H5FLprivate.h
  src/H5build_settings.autotools.c.in
  src/H5build_settings.cmake.c.in
  src/H5private.h
  src/Makefile.am
  src/libhdf5.settings.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Build, Type - Deprecation / Removal

#4457 Clean up memory leaks
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Parallel, Component - Testing, Type - Bug

#4463 Fix typo in H5Rget_obj_type
  doxygen/dox/APIVersions.dox
Labels: Merge - To 1.14, Component - Documentation, Type - Bug

#4464 Use ADD_H5_ERR_TEST to not compare output
  tools/test/h5stat/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Component - Testing, Type - Bug

#4467 win32defs: Fix Wundef warning
  src/H5win32defs.h
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4453 Refactor error handling code to eliminate internal ID calls
  .gitignore
  bin/h5vers
  bin/make_err
  src/CMakeLists.txt
  src/H5D.c
  src/H5Dint.c
  src/H5Dvirtual.c
  src/H5E.c
  src/H5Edeprec.c
  src/H5Eint.c
  src/H5Epkg.h
  src/H5Eprivate.h
  src/H5FDfamily.c
  src/H5FDonion.c
  src/H5Fint.c
  src/H5Gint.c
  src/H5Gloc.c
  src/H5Gnode.c
  src/H5Gstab.c
  src/H5Gtraverse.c
  src/H5Iint.c
  src/H5Iprivate.h
  src/H5Ocopy.c
  src/H5Oint.c
  src/H5SM.c
  src/H5T.c
  src/H5Tcommit.c
  src/H5VLcallback.c
  src/H5Z.c
  src/H5private.h
  src/H5public.h
  src/Makefile.am
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Improvement

#4466 CMake: Fix mingw/fortran build
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Component - Build, Type - Bug

#4468 Update for blosc2 in plugins and prefix hdf5 cmake varnames
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePresets.json
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5FLT/h5ex_d_blosc2.c
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_blosc2.ddl
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_blosc2.h5
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_blosc2.tst
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  java/lib/junit.jar
  java/test/junit.sh.in
  java/test/testfiles/JUnit-TestH5.txt
  java/test/testfiles/JUnit-TestH5A.txt
  java/test/testfiles/JUnit-TestH5Arw.txt
  java/test/testfiles/JUnit-TestH5D.txt
  java/test/testfiles/JUnit-TestH5Dparams.txt
  java/test/testfiles/JUnit-TestH5Dplist.txt
  java/test/testfiles/JUnit-TestH5Drw.txt
  java/test/testfiles/JUnit-TestH5E.txt
  java/test/testfiles/JUnit-TestH5Edefault.txt
  java/test/testfiles/JUnit-TestH5Eparams.txt
  java/test/testfiles/JUnit-TestH5Eregister.txt
  java/test/testfiles/JUnit-TestH5F.txt
  java/test/testfiles/JUnit-TestH5Fbasic.txt
  java/test/testfiles/JUnit-TestH5Fparams.txt
  java/test/testfiles/JUnit-TestH5Fswmr.txt
  java/test/testfiles/JUnit-TestH5G.txt
  java/test/testfiles/JUnit-TestH5Gbasic.txt
  java/test/testfiles/JUnit-TestH5Giterate.txt
  java/test/testfiles/JUnit-TestH5Lbasic.txt
  java/test/testfiles/JUnit-TestH5Lcreate.txt
  java/test/testfiles/JUnit-TestH5Lparams.txt
  java/test/testfiles/JUnit-TestH5Obasic.txt
  java/test/testfiles/JUnit-TestH5Ocopy.txt
  java/test/testfiles/JUnit-TestH5OcopyOld.txt
  java/test/testfiles/JUnit-TestH5Ocreate.txt
  java/test/testfiles/JUnit-TestH5Oparams.txt
  java/test/testfiles/JUnit-TestH5P.txt
  java/test/testfiles/JUnit-TestH5PData.txt
  java/test/testfiles/JUnit-TestH5PL.txt
  java/test/testfiles/JUnit-TestH5Pfapl.txt
  java/test/testfiles/JUnit-TestH5Pfaplhdfs.txt
  java/test/testfiles/JUnit-TestH5Pfapls3.txt
  java/test/testfiles/JUnit-TestH5Plist.txt
  java/test/testfiles/JUnit-TestH5Pvirtual.txt
  java/test/testfiles/JUnit-TestH5R.txt
  java/test/testfiles/JUnit-TestH5Rref.txt
  java/test/testfiles/JUnit-TestH5S.txt
  java/test/testfiles/JUnit-TestH5Sbasic.txt
  java/test/testfiles/JUnit-TestH5T.txt
  java/test/testfiles/JUnit-TestH5Tbasic.txt
  java/test/testfiles/JUnit-TestH5Tparams.txt
  java/test/testfiles/JUnit-TestH5VL.txt
  java/test/testfiles/JUnit-TestH5Z.txt
  release_docs/INSTALL_CMake.txt
  src/H5Dmodule.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Java, Component - Build, Type - Bug, Type - Improvement, Component - Misc

#4459 Fix leak of internal IDs registered during compound datatype conversion
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tconv_compound.c
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4474 Fix github issue #2523: doxygen -- fix grammatically incorrect senten…
  src/H5Apublic.h
  src/H5Opublic.h
  src/H5Ppublic.h
  src/H5Spublic.h
Labels: Component - Documentation

#4480 Point to HDFGroup repository for testing vol-log-based
  .github/workflows/vol_log.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4478 Update LT_VERS_AGE for libhdf5 and lib_fortran.
  config/lt_vers.am
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4476 Remove env step not used by CI in testing
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Bug, Component - Misc

#4483 Fix an issue where compound datatype member IDs can be leaked during conversion (#4459)
  release_docs/HISTORY-1_14.txt
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tconv_compound.c
  test/dtypes.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4485 Update versions for hdf5 1.14.4-3
  README.md
  c++/src/Makefile.in
  config/cmake/scripts/HDF5config.cmake
  config/lt_vers.am
  configure
  configure.ac
  fortran/src/Makefile.in
  hl/c++/src/Makefile.in
  hl/fortran/src/Makefile.in
  hl/src/Makefile.in
  java/src/jni/Makefile.in
  release_docs/INSTALL_CMake.txt
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
  src/Makefile.in
Labels: Component - Build

#4477 Properly clean up cache when failing to load an object header
  src/H5Gint.c
  src/H5Odbg.c
  src/H5Oint.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4490 Add a missing image from the original document
  doxygen/dox/IntroParHDF5.dox
  doxygen/img/pimplayer.gif
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Bug

#4489 Disable EOF checks for SWMR readers in more cases.
  src/H5Fsuper.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4498 Remove unnecessary fortran install
  .github/workflows/cmake-bintest.yml
  .github/workflows/h5py.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4496 Only one version of binaries is produced for platforms
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Component - Misc

#4497 Fix for github issue #2220.
  doxygen/dox/VOLConnGuide.dox
Labels: Component - Documentation

#4494 Release asset tarballs with no version filenames
  .github/workflows/release-files.yml
  .github/workflows/tarball.yml
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Task

#4462 Fix for github Issue #1388 can't delete renamed dense attribute with corder tracking enabled
  src/H5Adense.c
  test/tattr.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4501 Fix/revert a libtool sed hack
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4504 Fix daily-build CI and correct use of *_FOUND settings for filters
  .github/workflows/release-files.yml
  CMakeFilters.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc

#4506 Add fortkit dependency for H5Rff.F90 and fix for a libtool sed hack
  README.md
  configure
  configure.ac
  fortran/src/Makefile.am
  fortran/src/Makefile.in
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#4505 Correct examples tests to just run under dynamic analysis
  HDF5Examples/C/H5D/CMakeLists.txt
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/C/H5VDS/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug, Type - Improvement

#4509 Remove trailing extra whitespace in hyperlink
  doxygen/dox/Overview.dox
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4512 Set H5 specific vars immediately if legacy find
  CMakeFilters.cmake
  CMakePlugins.cmake
  config/cmake/HDF5PluginMacros.cmake
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4492 Don't update 'pos' and 'op' fields when using pread/pwrite
  src/H5FDlog.c
  src/H5FDsec2.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4522 Fix spelling
  .codespellrc
  CODE_OF_CONDUCT.md
  config/cmake/NSIS.template.in
  hl/src/H5TB.c
  release_docs/HISTORY-1_0-1_8_0.txt
  src/H5ACmpio.c
  src/H5CX.c
  src/H5Dchunk.c
  src/H5FApkg.h
  src/H5FDsubfiling/H5FDioc_priv.h
  src/H5Shyper.c
  src/H5VLint.c
  test/bittests.c
  test/fheap.c
  test/gen_old_group.c
  test/tsohm.c
  test/unlink.c
  tools/src/h5repack/h5repack_opttable.c
  tools/test/h5dump/h5dumpgentest.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#4520 Use old requests version in REST VOL workflow
  .github/workflows/vol_rest.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Task, Dependencies

#4523 Fix typo in DAPL callback documentation
  src/H5Pdapl.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4525 Move/rename libhdf5.settings input files
  CMakeInstallation.cmake
  configure.ac
  src/libhdf5.settings.autotools.in
  src/libhdf5.settings.cmake.in
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#4532 Fix typos in property callback documentation
  src/H5Pfapl.c
  src/H5Pfcpl.c
  src/H5Pgcpl.c
  src/H5Plapl.c
  src/H5Pocpypl.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4535 Point to HDFGroup repository
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  release_docs/RELEASE_PROCESS.md
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Task, Component - Misc

#4534 Fix wrong int type as some systems have int as 64-bit wide
  java/src/jni/h5Imp.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Java, Type - Bug

#4530 H5FDquery return value
  src/H5FD.c
  src/H5FDdevelop.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library

#4531 Refactor to reduce code duplication
  src/H5D.c
  src/H5Dint.c
  src/H5VLcallback.c
  src/H5VLprivate.h
  test/testfiles/error_test_1
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement
