Repository HDFGroup/hdf5, pull requests merged in 2024-04, with the labels that each got.

#4292 Add missing foreach for VFD and Pasthrough runs
  test/CMakePassthroughVOLTests.cmake
  test/CMakeVFDTests.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4283 Fixes for file format security issues
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dcontig.c
  src/H5Defl.c
  src/H5Dint.c
  src/H5Dpkg.h
  src/H5Gent.c
  src/H5Glink.c
  src/H5Gloc.c
  src/H5Gnode.c
  src/H5Gobj.c
  src/H5Gpkg.h
  src/H5Gprivate.h
  src/H5Gstab.c
  src/H5Gtest.c
  src/H5HG.c
  src/H5HL.c
  src/H5HLcache.c
  src/H5HLprivate.h
  src/H5Lint.c
  src/H5Ocache.c
  src/H5Ocopy.c
  src/H5Odtype.c
  src/H5Oefl.c
  src/H5Olayout.c
  src/H5Opkg.h
  src/H5Oprivate.h
  src/H5Osdspace.c
  src/H5Oshared.c
  src/H5Oshared.h
  src/H5Ostab.c
  src/H5S.c
  src/H5Spoint.c
  src/H5Sprivate.h
  src/H5T.c
  src/H5Tprivate.h
  src/H5VLnative_blob.c
  src/H5Znbit.c
  tools/lib/h5tools_utils.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Tools, Type - Bug

#4277 Add configure options for disabling extension features
  config/cmake/ConfigureChecks.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/libhdf5.settings.cmake.in
  configure.ac
  release_docs/RELEASE.txt
  src/H5build_settings.autotools.c.in
  src/H5build_settings.cmake.c.in
  src/libhdf5.settings.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Improvement

#4269 Add documentation (H5FD)
  src/H5FDdevelop.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4218 Fix problems with background buffers and array datatypes
  release_docs/RELEASE.txt
  src/H5Tconv.c
  test/dtypes.c
Labels: Merge - To 1.14

#4294 Synch workflows and require apt-get update
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/main-auto-par-spc.yml
  .github/workflows/main-auto-par.yml
  .github/workflows/main-auto-spc.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/testxpr.yml
  .github/workflows/vfd-subfiling.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_log.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4296 Fix divide-by-zero when page buf page size is 0
  release_docs/RELEASE.txt
  src/H5Fsuper.c
  src/H5MFsection.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4301 Fix typo - Cnversion
  src/H5Tconv.c
Labels: Component - Documentation, Type - Bug

#4305 Add build folder to path
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
Labels: Merge, Priority - 1. High 🔼, Component - Testing, Component - Build, Type - Bug, Branch - 1.14

#4311 Fix typo - differetly
  test/dt_arith.c
Labels: Component - Documentation

#4313 Fix README badges
  README.md
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#4314 Remove old wait_H5Tinit.cmake file
  config/cmake/wait_H5Tinit.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Task

#4317 Remove VS ptable error from Known Problems
  release_docs/RELEASE.txt
Labels: Component - Documentation, Type - Deprecation / Removal

#4318 Update .so numbers
  config/lt_vers.am
Labels: Component - C Library, Component - Fortran, Component - Build, Branch - 1.14

#4309 Simplify check for datatypes with unusual number of unused bits
  src/H5T.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4322 Fix issues with empty or uninitialized link names
  src/H5Gent.c
  src/H5Gloc.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4321 Fix h5py testing failure due to invalid datatype IDs
  src/H5T.c
  src/H5Tconv.c
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Testing, Type - Bug

#4323 Revise _Float16 configure checks
  config/cmake/ConfigureChecks.cmake
  config/cmake/ConversionTests.c
  configure.ac
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#4324 Sync develop changes April 3 - April4 to hdf5_1_14
  config/cmake/ConfigureChecks.cmake
  config/cmake/ConversionTests.c
  configure.ac
  release_docs/RELEASE.txt
  src/H5Gent.c
  src/H5Gloc.c
  src/H5T.c
  src/H5Tconv.c
  test/dtypes.c
Labels: Component - C Library, Component - Testing, Component - Build, Branch - 1.14

#4320 Update support branch version number to 1.14.5-1
  README.md
  c++/src/cpp_doc_config
  config/cmake/scripts/HDF5config.cmake
  configure.ac
  java/src/hdf/hdf5lib/H5.java
  java/test/TestH5.java
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
  tools/test/h5repack/expected/h5repack_layout.h5-plugin_version_test.ddl
Labels: Branch - 1.14

#4326 Sync change for allowing serial tools to use Subfiling VFD
  tools/lib/h5tools.c
Labels: Priority - 2. Medium ⏹, Component - Tools, Type - Improvement, Branch - 1.14

#4328 Correct test express cmake
  test/CMakeLists.txt
  test/CMakeTests.cmake
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4327 Sync change for allowing serial tools to use Subfiling VFD (#4326)
  tools/lib/h5tools.c
Labels: Merge, Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#4329 Merge Test Express changes.
  test/CMakeLists.txt
  test/CMakeTests.cmake
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Branch - 1.14

#4331 Remove unnecessary step from REST VOL workflow
  .github/workflows/vol_rest.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Deprecation / Removal

#4337 Remove HD macros for C time functions
  src/H5Clog_json.c
  src/H5Dmpio.c
  src/H5FDcore.c
  src/H5FDlog.c
  src/H5FDonion.c
  src/H5FDs3comms.c
  src/H5FDsec2.c
  src/H5Odbg.c
  src/H5Omtime.c
  src/H5private.h
  src/H5system.c
  src/H5timer.c
  test/API/H5_api_test.c
  test/accum.c
  test/app_ref.c
  test/big.c
  test/btree2.c
  test/cmpd_dset.c
  test/dsets.c
  test/dt_arith.c
  test/dtypes.c
  test/earray.c
  test/farray.c
  test/fheap.c
  test/h5test.c
  test/hyperslab.c
  test/istore.c
  test/links.c
  test/mdset.c
  test/mtime.c
  test/set_extent.c
  test/swmr_reader.c
  test/swmr_remove_reader.c
  test/swmr_sparse_reader.c
  test/tid.c
  test/tselect.c
  test/tskiplist.c
  test/ttime.c
  test/tunicode.c
  test/unlink.c
  test/vds_swmr_writer.c
  testpar/API/H5_api_test_parallel.c
  testpar/t_pmulti_dset.c
  tools/src/h5ls/h5ls.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement

#4340 Remove HD prefix from toupper/tolower
  src/H5FDs3comms.c
  src/H5private.h
  src/H5system.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4336 Add VDS and SWMR to documentation
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/intro_SWMR.html
  doxygen/examples/intro_VDS.html
  doxygen/img/tutr-swmr1.png
  doxygen/img/tutr-swmr2.png
  doxygen/img/tutr-swmr3.png
  doxygen/img/tutrvds-ex.png
  doxygen/img/tutrvds-map.png
  doxygen/img/tutrvds-multimgs.png
  doxygen/img/tutrvds-snglimg.png
Labels: Component - Documentation, Type - Improvement

#4338 Clean up random number generator code
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  configure.ac
  src/H5private.h
  src/H5system.c
  test/accum.c
  test/app_ref.c
  test/big.c
  test/bittests.c
  test/btree2.c
  test/cache_api.c
  test/cmpd_dset.c
  test/dsets.c
  test/dt_arith.c
  test/dtypes.c
  test/earray.c
  test/farray.c
  test/fheap.c
  test/fillval.c
  test/filter_plugin.c
  test/hyperslab.c
  test/istore.c
  test/mdset.c
  test/ntypes.c
  test/select_io_dset.c
  test/set_extent.c
  test/stab.c
  test/swmr_addrem_writer.c
  test/swmr_common.c
  test/swmr_generator.c
  test/swmr_reader.c
  test/swmr_remove_reader.c
  test/swmr_remove_writer.c
  test/swmr_sparse_reader.c
  test/swmr_sparse_writer.c
  test/swmr_start_write.c
  test/swmr_writer.c
  test/tid.c
  test/tselect.c
  test/tskiplist.c
  test/tunicode.c
  test/unlink.c
  test/vfd.c
  testpar/t_cache.c
  testpar/t_pmulti_dset.c
  testpar/t_select_io_dset.c
  tools/test/perform/overhead.c
  tools/test/perform/zip_perf.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement

#4339 Remove the getting started guide
  doc/getting-started-with-hdf5-development.md
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Deprecation / Removal

#4342 Remove noise comment from H5DO.c
  hl/src/H5DO.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - High-Level Library, Type - Improvement

#4345 Add note about H5Iregister_type hash_table param
  src/H5Ipublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4346 Remove `#undef ERR` from H5private.h
  src/H5private.h
  tools/src/h5import/h5import.c
  tools/src/h5import/h5import.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Type - Improvement

#4343 Add NAMECHECK_ONLY to macro list in .clang-format
  .clang-format
  src/H5TS.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4348 Remove HD from last non-win32 C89 functions
  hl/tools/h5watch/h5watch.c
  src/H5Clog_json.c
  src/H5Clog_trace.c
  src/H5private.h
  test/app_ref.c
  test/del_many_dense_attrs.c
  test/dt_arith.c
  test/filenotclosed.c
  test/h5test.c
  test/tcheck_version.c
  testpar/t_2Gio.c
  testpar/t_shapesame.c
  testpar/testphdf5.c
  tools/lib/h5tools_utils.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Improvement

#4349 Fix dead links cont.
  doxygen/aliases
  doxygen/examples/intro_SWMR.html
  doxygen/examples/intro_VDS.html
  doxygen/img/images_to_copy.dox
  src/H5Fmodule.h
Labels: Component - Documentation, Type - Improvement

#4354 Fix use of possibly uninitialized memory in h5repack
  tools/src/h5repack/h5repack.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#4355 Fix use of possibly uninitialized memory in h5repack (#4354)
  tools/src/h5repack/h5repack.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#4356 Fix use of possibly uninitialized memory in h5repack (#4354)
  tools/src/h5repack/h5repack.c
Labels: Merge, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#4357 Match content listing with content
  release_docs/INSTALL
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4361 Documentation updates from develop
  doxygen/aliases
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/intro_SWMR.html
  doxygen/examples/intro_VDS.html
  doxygen/img/images_to_copy.dox
  doxygen/img/tutr-swmr1.png
  doxygen/img/tutr-swmr2.png
  doxygen/img/tutr-swmr3.png
  doxygen/img/tutrvds-ex.png
  doxygen/img/tutrvds-map.png
  doxygen/img/tutrvds-multimgs.png
  doxygen/img/tutrvds-snglimg.png
  release_docs/INSTALL
  release_docs/RELEASE.txt
  src/H5Fmodule.h
Labels: Component - Documentation, Branch - 1.14

#4362 Documentation updates (hdf5_1_14_4) from develop
  doxygen/aliases
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/intro_SWMR.html
  doxygen/examples/intro_VDS.html
  doxygen/img/images_to_copy.dox
  doxygen/img/tutr-swmr1.png
  doxygen/img/tutr-swmr2.png
  doxygen/img/tutr-swmr3.png
  doxygen/img/tutrvds-ex.png
  doxygen/img/tutrvds-map.png
  doxygen/img/tutrvds-multimgs.png
  doxygen/img/tutrvds-snglimg.png
  release_docs/INSTALL
  release_docs/RELEASE.txt
  src/H5Fmodule.h
Labels: Component - Documentation

#4365 Update RELEASE.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#4364 Update RELEASE.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#4360 Removed duplicate entries in compile line for h5* compiler wrappers
  bin/h5cc.in
  c++/src/h5c++.in
  fortran/src/h5fc.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Type - Bug

#4367 Added CVE info to RELEASE.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#4371 Change doxygen version from 1.10.0 to 1.9.7
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4374 Add known issue for MacOS 14 _Float16 byte order detection issue
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4380 Added newsletter text for 1.14.4 release
  release_docs/NEWSLETTER.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#4379 Add known issue for MacOS 14 _Float16 byte order detection issue
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4378 Add known issue for MacOS 14 _Float16 byte order detection issue
  release_docs/RELEASE.txt
Labels: Merge, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4376 Fix doxygen interference and some documentation issues
  .github/workflows/cmake-ctest.yml
  bin/h5vers
  bin/release
  c++/src/RM_stylesheet.css
  c++/src/cpp_doc_config
  c++/src/footer.html
  c++/src/header.html
  doxygen/dox/ViewTools.dox
  release_docs/INSTALL_Cygwin.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Type - Improvement, Branch - 1.14

#4375 Fix doxygen interference and some documentation issues
  .github/workflows/cmake-ctest.yml
  bin/h5vers
  bin/release
  c++/src/RM_stylesheet.css
  c++/src/cpp_doc_config
  c++/src/footer.html
  c++/src/header.html
  doxygen/dox/ViewTools.dox
  release_docs/INSTALL_Cygwin.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug, Type - Improvement, perl

#4377 Fix all doxygen versions
  .github/workflows/cmake-ctest.yml
Labels: Priority - 1. High 🔼, Type - Bug, Component - Misc

#4382 Fix broken links and references in INSTALL_Auto.txt
  release_docs/INSTALL_Auto.txt
Labels: Component - Documentation

#4386 Added the new tag name scheme to NEWSLETTER.txt
  release_docs/NEWSLETTER.txt
Labels: Component - Documentation

#4387 Normalize 'known problems' in RELEASE.txt w/ 1.14
  release_docs/RELEASE.txt
Labels: Component - Documentation

#4388 Fix typos in NEWSLETTER.txt
  release_docs/NEWSLETTER.txt
Labels: Component - Documentation

#4366 Remove `--rpm` signature in comment
  src/H5Tconv.c
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4389 switched from \returns to more commonly used \return
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5ESpublic.h
  src/H5Fpublic.h
  src/H5Mpublic.h
  src/H5Tpublic.h
  src/H5public.h
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#4395 Correct doxygen GH pages folder for release
  .github/workflows/release-files.yml
  CONTRIBUTING.md
  README.md
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/GettingStarted.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/menus/high_level_menu.md
  fortran/src/README.md
  release_docs/NEWSLETTER.txt
  src/H5Fmodule.h
  src/H5Ppublic.h
  src/H5module.h
  test/API/README.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug

#4399 Correct the high-level link
  CONTRIBUTING.md
  doxygen/Doxyfile.in
  doxygen/dox/GettingStarted.dox
  doxygen/examples/menus/high_level_menu.md
  fortran/src/README.md
Labels: Merge, Priority - 1. High 🔼, Type - Bug, Branch - 1.14

#4359 Add CXX flags to sanitize
  config/sanitizer/sanitizers.cmake
  config/toolchain/clang.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Component - Testing, Component - Build, Type - Improvement

#4330 Set available CMake build types for non-multi-config generators
  config/cmake/HDFMacros.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#4398 Correct the high-level library link
  CONTRIBUTING.md
  doxygen/Doxyfile.in
  doxygen/dox/GettingStarted.dox
  doxygen/examples/menus/high_level_menu.md
  fortran/src/README.md
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Type - Improvement

#4405 Improve release workflow
  .github/workflows/release-files.yml
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4406 Improve release workflow
  .github/workflows/release-files.yml
  .github/workflows/tarball.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4412 Update Intel oneAPI version to 2024.1
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
Labels: Component - Build

#4403 Update documentation
  doxygen/dox/GettingStarted.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/FileImageOps.html
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4409 Use aliases for URLs
  CONTRIBUTING.md
  README.md
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics.dox
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/Overview.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/VOLConnGuide.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/ViewToolsJPSS.dox
  doxygen/dox/rm-template.dox
  doxygen/examples/FileFormat.html
  doxygen/examples/intro_SWMR.html
  doxygen/hdf5doxy_layout.xml
  hl/src/H5DOpublic.h
  hl/src/H5LTpublic.h
  release_docs/INSTALL_Auto.txt
  src/H5Fmodule.h
  src/H5Ppublic.h
  src/H5VLmodule.h
  src/H5module.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Improvement

#4415 Update documentation
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/FileImageOps.html
  doxygen/examples/H5.format.html
  doxygen/examples/LibraryReleaseVersionNumbers.html
  doxygen/img/images_to_copy.dox
  doxygen/img/trunk_branches.jpg
Labels: Merge - To 1.14, Component - Documentation

#4416 Remove obsolete file
  release_docs/README_HDF5_CMake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Deprecation / Removal, Component - Misc

#4422 Add training videos page
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/TrainingVideos.dox
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4312 Add release process markdown file
  release_docs/RELEASE_PROCESS.md
Labels: Component - Documentation, Type - Improvement

#4429 Allow clang-format to format H5Cpkg.h
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4393 Split H5Tconv.c into modules by type
  src/CMakeLists.txt
  src/H5T.c
  src/H5Tconv.c
  src/H5Tconv.h
  src/H5Tconv_array.c
  src/H5Tconv_array.h
  src/H5Tconv_bitfield.c
  src/H5Tconv_bitfield.h
  src/H5Tconv_compound.c
  src/H5Tconv_compound.h
  src/H5Tconv_enum.c
  src/H5Tconv_enum.h
  src/H5Tconv_float.c
  src/H5Tconv_float.h
  src/H5Tconv_integer.c
  src/H5Tconv_integer.h
  src/H5Tconv_macros.h
  src/H5Tconv_reference.c
  src/H5Tconv_reference.h
  src/H5Tconv_string.c
  src/H5Tconv_string.h
  src/H5Tconv_vlen.c
  src/H5Tconv_vlen.h
  src/H5Tdbg.c
  src/H5Tpkg.h
  src/H5Tprivate.h
  src/Makefile.am
  test/cmpd_dset.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4438 Fix Broken Links in VOL API Doxygen Table
  doxygen/examples/tables/volAPIs.dox
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation

#4428 Don't print thread ID when the library isn't multithreaded
  java/test/junit.sh.in
  src/H5CS.c
  src/H5Eint.c
  test/h5test.c
  test/test_error.sh.in
  test/testfiles/err_compat_1
  test/testfiles/error_test_1
  tools/test/h5dump/errfiles/tall-1.err
  tools/test/h5dump/errfiles/tall-2A.err
  tools/test/h5dump/errfiles/tall-2A0.err
  tools/test/h5dump/errfiles/tall-2B.err
  tools/test/h5dump/errfiles/tarray1_big.err
  tools/test/h5dump/errfiles/tattr-3.err
  tools/test/h5dump/errfiles/tattrregR.err
  tools/test/h5dump/errfiles/tcomp-3.err
  tools/test/h5dump/errfiles/tdataregR.err
  tools/test/h5dump/errfiles/tdset-2.err
  tools/test/h5dump/errfiles/textlink.err
  tools/test/h5dump/errfiles/textlinkfar.err
  tools/test/h5dump/errfiles/textlinksrc.err
  tools/test/h5dump/errfiles/tgroup-2.err
  tools/test/h5dump/errfiles/torderlinks1.err
  tools/test/h5dump/errfiles/torderlinks2.err
  tools/test/h5dump/errfiles/tperror.err
  tools/test/h5dump/errfiles/tqmarkfile.err
  tools/test/h5dump/errfiles/tslink-D.err
  tools/test/h5dump/testh5dump.sh.in
  tools/test/h5dump/testh5dumppbits.sh.in
  tools/test/h5dump/testh5dumpvds.sh.in
  tools/test/h5format_convert/testh5fc.sh.in
  tools/test/h5repack/expected/h5repack_layout.h5-dset2_chunk_20x10-errstk.tst
  tools/test/h5repack/h5repack.sh.in
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Tools, Type - Improvement

#4427 Start refactoring H5E code to avoid using IDs internally
  bin/make_err
  src/H5E.c
  src/H5Eint.c
  src/H5Epkg.h
  src/H5Eprivate.h
  src/H5private.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4425 Add support for builtin_expect compiler hint
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDFTests.c
  configure.ac
  src/H5private.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4444 sanitizer flags need set before compiler flags
  CMakeLists.txt
  config/sanitizer/sanitizers.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#4441 Add navigate chapters and use release_docs in Learn Basics
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/dox/LearnBasics1.dox
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/TrainingVideos.dox
  doxygen/examples/h5_attribute.c
  doxygen/examples/h5_extlink.c
Labels: Merge - To 1.14, Component - Documentation, Type - Improvement

#4445 Fix for github issue #3790: infinite loop closing library
  release_docs/RELEASE.txt
  src/H5Ocache.c
  src/H5Oint.c
  src/H5Opkg.h
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/errfiles/infinite_loop.err
  tools/test/h5dump/expected/infinite_loop.ddl
  tools/test/h5dump/testfiles/3790_infinite_loop.h5
  tools/test/h5dump/testh5dump.sh.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug
