Repository HDFGroup/hdf5, pull requests merged in 2024-02, with the labels that each got.

#3976 append '-WF,' when passing C preprocessor directives to the xlf compiler
  fortran/examples/testh5fc.sh.in
Labels: Priority - 1. High 🔼, Component - Fortran, Component - Testing, Type - Bug

#3979 Fixed spacing issues in example tests.
  HDF5Examples/FORTRAN/H5D/h5ex_d_checksum.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_gzip.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_nbit.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_soint.F90
  HDF5Examples/FORTRAN/H5D/h5ex_d_szip.F90
  HDF5Examples/FORTRAN/H5D/tfiles/18/h5ex_d_checksum.tst
  HDF5Examples/FORTRAN/H5D/tfiles/18/h5ex_d_gzip.tst
  HDF5Examples/FORTRAN/H5D/tfiles/18/h5ex_d_nbit.tst
  HDF5Examples/FORTRAN/H5D/tfiles/18/h5ex_d_soint.tst
  HDF5Examples/FORTRAN/H5D/tfiles/18/h5ex_d_szip.tst
Labels: Priority - 2. Medium ⏹, Component - Fortran, Type - Task

#3982 corrected -- warning: implicit conversion changes signedness
  src/H5FDsubfiling/H5FDsubfiling.c
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Task

#3983 Skip mac bintest until more reliable
  .github/workflows/cmake-bintest.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Task, Component - Misc

#3988 Make platform specific test presets for windows and macs
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  CMakePresets.json
  HDF5Examples/CMakePresets.json
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Component - Misc

#3986 Remove ADB signature from RELEASE.txt.
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Deprecation / Removal

#3992 Update release schedule
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Priority - 3. Low 🔽, Type - Task, Component - Misc

#3993 Update README with new release info
  README.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#3940 Sync API tests with vol-tests
  test/API/H5_api_attribute_test.c
  test/API/H5_api_attribute_test.h
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
  test/API/H5_api_object_test.c
  test/API/H5_api_object_test.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#3967 Fix for github issue #2414: segfault when copying dataset with attrib…
  src/H5Aint.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#3972 Updated INSTALL file
  release_docs/INSTALL
Labels: Merge - To 1.14, Component - Documentation, Type - Improvement

#3999 Fix incompatible pointer type warnings in object reference examples
  HDF5Examples/C/H5T/h5ex_t_objref.c
  HDF5Examples/C/H5T/h5ex_t_objrefatt.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Bug, Component - Misc

#3998 Fix build issue and some warnings in H5_api_dataset_test.c
  test/API/H5_api_dataset_test.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Task

#1830 Modern C++ dtor declarations
  c++/src/H5AbstractDs.cpp
  c++/src/H5AbstractDs.h
  c++/src/H5ArrayType.cpp
  c++/src/H5ArrayType.h
  c++/src/H5AtomType.cpp
  c++/src/H5AtomType.h
  c++/src/H5CommonFG.cpp
  c++/src/H5CommonFG.h
  c++/src/H5CompType.cpp
  c++/src/H5CompType.h
  c++/src/H5DaccProp.cpp
  c++/src/H5DaccProp.h
  c++/src/H5DcreatProp.cpp
  c++/src/H5DcreatProp.h
  c++/src/H5DxferProp.cpp
  c++/src/H5DxferProp.h
  c++/src/H5EnumType.cpp
  c++/src/H5EnumType.h
  c++/src/H5Exception.cpp
  c++/src/H5Exception.h
  c++/src/H5FaccProp.cpp
  c++/src/H5FaccProp.h
  c++/src/H5FcreatProp.cpp
  c++/src/H5FcreatProp.h
  c++/src/H5FloatType.cpp
  c++/src/H5FloatType.h
  c++/src/H5IdComponent.cpp
  c++/src/H5IdComponent.h
  c++/src/H5IntType.cpp
  c++/src/H5IntType.h
  c++/src/H5LaccProp.cpp
  c++/src/H5LaccProp.h
  c++/src/H5LcreatProp.cpp
  c++/src/H5LcreatProp.h
  c++/src/H5Library.cpp
  c++/src/H5Library.h
  c++/src/H5Location.cpp
  c++/src/H5Location.h
  c++/src/H5Object.cpp
  c++/src/H5Object.h
  c++/src/H5OcreatProp.cpp
  c++/src/H5OcreatProp.h
  c++/src/H5PredType.cpp
  c++/src/H5PredType.h
  c++/src/H5StrType.cpp
  c++/src/H5StrType.h
  c++/src/H5VarLenType.cpp
  c++/src/H5VarLenType.h
  c++/test/h5cpputil.cpp
  c++/test/h5cpputil.h
Labels: WIP, Merge - Develop Only, Priority - 3. Low 🔽, Component - C++, Type - Improvement

#4002 remove incorrect check for environ
  .github/workflows/abi-report.yml
  .github/workflows/cmake-bintest.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc

#4003 Issue #1824: Replaced most remaining sprintf with safer snprint
  java/src/jni/h5util.c
  src/H5FDfamily.c
  src/H5FDsplitter.c
  test/API/H5_api_async_test.c
  test/API/H5_api_attribute_test.c
  test/API/H5_api_dataset_test.c
  test/API/H5_api_file_test.c
  test/API/H5_api_group_test.c
  test/filter_plugin.c
  testpar/API/H5_api_async_test_parallel.c
  testpar/t_vfd.c
  tools/test/h5dump/h5dumpgentest.c
  utils/tools/h5dwalk/h5dwalk.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Java, Component - Testing, Type - Improvement

#4006 Add hl and cpp ABI reports to daily build
  .github/workflows/abi-report.yml
  .github/workflows/release-files.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Component - Misc

#4009 Don't add files and directories with names that begin with ., or that…
  bin/release
  config/cmake/runTest.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Improvement, Component - Misc

#4008 Fix some output issues with ph5diff
  tools/lib/h5diff.c
  tools/src/h5diff/ph5diff_main.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#4010 Update install texts
  HDF5Examples/config/cmake/HDFMacros.cmake
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDFMacros.cmake
  release_docs/INSTALL_Auto.txt
  release_docs/INSTALL_CMake.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4014 Add C in project line for CMake to fix #4012.
  HDF5Examples/C/CMakeLists.txt
  HDF5Examples/C/H5PAR/CMakeLists.txt
  HDF5Examples/C/Perf/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#4015 separate out individual checks for string removal
  config/cmake/runTest.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Testing, Type - Improvement

#4005 Add compound subset ops on attributes to API tests
  test/API/H5_api_attribute_test.c
  test/API/H5_api_attribute_test.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4020 Delete old snapshot binaries after new snapshots are created
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Improvement, Type - New Feature, Component - Misc

#4022 Correct String FIND for runTest and grepTest
  HDF5Examples/config/cmake/grepTest.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/HDF5UseFortran.cmake
  config/cmake/grepTest.cmake
  config/cmake/runTest.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4024 Grep for error messages instead of comparing files
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Type - Improvement

#4026 Fix paths to build artifacts when using presets
  .github/workflows/cmake-ctest.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Branch - 1.14, Component - Misc

#4028 Remove oneapi return value warning.
  test/dt_arith.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4007 Replaced last sprintf with snprintf
  src/H5Oainfo.c
  src/H5Oattr.c
  src/H5Obogus.c
  src/H5Obtreek.c
  src/H5Ocache_image.c
  src/H5Ocont.c
  src/H5Odrvinfo.c
  src/H5Oefl.c
  src/H5Ofsinfo.c
  src/H5Oginfo.c
  src/H5Olayout.c
  src/H5Olinfo.c
  src/H5Olink.c
  src/H5Omessage.c
  src/H5Omtime.c
  src/H5Oname.c
  src/H5Opkg.h
  src/H5Orefcount.c
  src/H5Oshared.h
  src/H5Oshmesg.c
  src/H5Ostab.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library

#4027 Test vlen sequence IO in API tests
  test/API/H5_api_dataset_test.c
  test/API/H5_api_dataset_test.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Improvement

#4030 Fix H5F_get_access_plist to copy file locking settings
  release_docs/RELEASE.txt
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5Ftest.c
  src/H5Pfapl.c
  test/links.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4036 Fix missing NOT from if check in HL folder
  hl/CMakeLists.txt
  hl/test/test_dset_append.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - High-Level Library, Component - Build, Type - Bug

#4033 Fix the datatype passed to H5*exists_async APIs in tests.
  config/cmake/H5pubconf.h.in
  config/cmake/HDF5UseFortran.cmake
  configure.ac
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/test/H5_test_buildiface.F90
  fortran/testpar/async.F90
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Testing, Type - Bug

#4016 Update and Add general INSTALL
  HDF5Examples/config/cmake/HDFMacros.cmake
  release_docs/INSTALL
  release_docs/INSTALL_Auto.txt
  release_docs/INSTALL_CMake.txt
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4017 Improve performance of flushing single objects
  src/H5AC.c
  src/H5ACprivate.h
  src/H5C.c
  src/H5Centry.c
  src/H5Cint.c
  src/H5Cpkg.h
  src/H5Cprivate.h
  src/H5Ctag.c
  test/cache.c
  test/cache_common.h
  test/cache_tagging.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library

#4021 Fix memory leak in H5LTopen_file_image when H5LT_FILE_IMAGE_DONT_COPY flag is used
  hl/src/H5LT.c
  release_docs/RELEASE.txt
  src/H5Pfapl.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - High-Level Library, Type - Bug

#4041 Allocate only necessary memory in dset API test
  test/API/H5_api_dataset_test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4043 Remove unused AIX cross-compile cache overrides
  config/BlankForm
  config/ibm-aix
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal

#4045 Remove check for gettimeofday + tz in CMake
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDFTests.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Deprecation / Removal

#4051 Remove limitations on preset generators
  HDF5Examples/config/cmake-presets/hidden-presets.json
  config/cmake-presets/hidden-presets.json
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Component - Misc
