Repository HDFGroup/hdf5, pull requests merged in 2024-06, with the labels that each got.

#4540 Remove julia CI actions
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/julia-auto.yml
  .github/workflows/julia-cmake.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#4536 correct plugin URL
  CMakePresets.json
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug, Branch - 1.14, Component - Misc

#4541 Fix various mistakes in doxygen docs
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/img/tutr-lodset.png
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Bug

#4542 Export HDF5 parallel status for CMake FetchContent'ed VOL connectors
  CMakeVOL.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#4543 Remove an unnecessary check for parallel and thread-safety from examples
  HDF5Examples/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Bug

#3505 Change type of `offset` arg in `H5Pset_external` to `HDoff_t`
  bin/trace
  release_docs/RELEASE.txt
  src/H5Pdcpl.c
  src/H5Ppublic.h
  src/H5private.h
  src/H5public.h
  src/H5win32defs.h
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4544 Adjust h5repack userblock option to allow reserve size
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack_copy.c
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/h5repack.sh.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Component - Testing, Type - Improvement

#4550 Fix typos in context/property documentation
  src/H5CX.c
  src/H5Ppublic.h
  test/tgenprop.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4556 Fix CI markdown link check http 500 errors
  .github/workflows/markdown-link-check.yml
  .github/workflows/markdown_config.json
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4551 Simplify property copying between lists internally
  src/H5P.c
  src/H5Pint.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4546 Add Python examples
  HDF5Examples/PYTHON/h5_compound.py
  HDF5Examples/PYTHON/h5_crtdat.py
  HDF5Examples/PYTHON/h5_gzip.py
  HDF5Examples/PYTHON/h5_hype.py
  HDF5Examples/PYTHON/h5_hypeb.py
  HDF5Examples/PYTHON/h5_links.py
  HDF5Examples/PYTHON/h5_objref.py
  HDF5Examples/PYTHON/h5_readtofloat.py
  HDF5Examples/PYTHON/h5_regref.py
  HDF5Examples/PYTHON/h5_selecelem.py
  HDF5Examples/PYTHON/h5_string.py
  HDF5Examples/PYTHON/h5_unlim.py
  HDF5Examples/PYTHON/h5_visit.py
  HDF5Examples/PYTHON/h5_visita.py
  HDF5Examples/PYTHON/h5_vlstring.py
  doxygen/aliases
Labels: Priority - 3. Low 🔽, Type - Task, Component - Misc

#4554 Correct property cb signatures in docs
  src/H5P.c
  src/H5Pdeprec.c
  src/H5Pint.c
  src/H5Ppublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4555 Clean up off_t --> HDoff_t stragglers
  c++/src/C2Cppfunction_map.htm
  c++/src/H5DcreatProp.cpp
  c++/src/H5DcreatProp.h
  configure.ac
  java/src/jni/h5pDCPLImp.c
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5Fmodule.h
  src/H5Fquery.c
  src/H5Pdcpl.c
  src/H5Ppublic.h
  test/dsets.c
  test/external.c
  test/external_env.c
  test/set_extent.c
  tools/lib/h5tools_dump.c
  tools/src/h5ls/h5ls.c
  tools/src/misc/h5repart.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Testing, Type - Improvement

#4561 Add compression includes to tests needing zlib support
  test/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug

#4568 Allow usage of page buffering for serial file access from parallel HDF5 builds
  release_docs/RELEASE.txt
  src/H5Fint.c
  test/page_buffer.c
  testpar/t_file.c
  testpar/testphdf5.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Component - Testing, Type - Bug

#4567 Remove old version of libaec
  CMakeFilters.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal

#4563 Add property names to context field docs
  src/H5CX.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4565 Document property shared name behavior
  src/H5Ppkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4569 Clarify H5CX macro documentation
  src/H5CX.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4570 Document H5Punregister modifying default properties
  src/H5P.c
  src/H5Ppkg.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4171 Update NVHPC to 24.5
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4572 Clean up comments in H5FDros3.c
  src/H5FDros3.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4575 Rename INSTALL_Auto.txt to INSTALL_Autotools.txt
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_Cygwin.txt
  release_docs/RELEASE_PROCESS.md
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4581 Turn off ros3 VFD stat collection by default
  src/H5FDros3.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4475 Pause recording errors instead of clearing the error stack
  bin/format_source
  release_docs/RELEASE.txt
  src/H5Dvirtual.c
  src/H5E.c
  src/H5Edeprec.c
  src/H5Eint.c
  src/H5Epkg.h
  src/H5Eprivate.h
  src/H5Epublic.h
  src/H5FD.c
  src/H5FDonion.c
  src/H5FDprivate.h
  src/H5FDsplitter.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5Fefc.c
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5Fprivate.h
  src/H5Lexternal.c
  src/H5VLnative_file.c
  test/efc.c
  test/error_test.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4562 Add page buffer cache command line option to tools
  release_docs/RELEASE.txt
  tools/lib/h5diff.c
  tools/lib/h5diff.h
  tools/lib/h5tools.c
  tools/lib/h5tools.h
  tools/libtest/h5tools_test_utils.c
  tools/src/h5diff/h5diff_common.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack.h
  tools/src/h5repack/h5repack_copy.c
  tools/src/h5repack/h5repack_main.c
  tools/src/h5repack/h5repack_verify.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5mkgrp.c
  tools/test/h5diff/expected/h5diff_10.txt
  tools/test/h5diff/expected/h5diff_600.txt
  tools/test/h5diff/expected/h5diff_603.txt
  tools/test/h5diff/expected/h5diff_606.txt
  tools/test/h5diff/expected/h5diff_612.txt
  tools/test/h5diff/expected/h5diff_615.txt
  tools/test/h5diff/expected/h5diff_621.txt
  tools/test/h5diff/expected/h5diff_622.txt
  tools/test/h5diff/expected/h5diff_623.txt
  tools/test/h5diff/expected/h5diff_624.txt
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/expected/file_space_cache.ddl
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
  tools/test/h5dump/testh5dump.sh.in
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/expected/help-1.ls
  tools/test/h5ls/expected/help-2.ls
  tools/test/h5ls/expected/help-3.ls
  tools/test/h5ls/expected/textlinksrc-nodangle-1.ls
  tools/test/h5ls/expected/tgroup-1.ls
  tools/test/h5repack/expected/h5repack-help.txt
  tools/test/h5repack/h5repacktst.c
  tools/test/h5stat/CMakeTests.cmake
  tools/test/h5stat/expected/h5stat_filters-cache.ddl
  tools/test/h5stat/expected/h5stat_help1.ddl
  tools/test/h5stat/expected/h5stat_help2.ddl
  tools/test/h5stat/expected/h5stat_nofile.ddl
  tools/test/h5stat/testh5stat.sh.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Component - Testing, Type - Improvement, Type - New Feature

#4580 Clarify documentation for H5CX_get_data_transform
  src/H5CX.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4583 Remove public API call from ros3 VFD
  src/H5FDros3.c
  src/H5Pfapl.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4584 Remove printf debugging from H5FDs3comms.c
  src/H5FDs3comms.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#4587 Cleanup of ros3 test
  test/ros3.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4588 Remove unused code from H5FDs3comms.c
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Deprecation / Removal

#4589 Remove magic fields from s3comms structs
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Deprecation / Removal

#4591 Remove dead H5FD_s3comms_percent_encode_char()
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Deprecation / Removal

#4594 Clean up s3comms test code
  test/s3comms.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4566 Add publish to bucket workflow
  .github/workflows/abi-report.yml
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/cve.yml
  .github/workflows/cygwin-auto.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/daily-build.yml
  .github/workflows/h5py.yml
  .github/workflows/hdfeos5.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/publish-release.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
  .github/workflows/vfd.yml
  .github/workflows/vol.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - New Feature, Component - Misc

#4596 Update abi report CI workflow for last release
  .github/workflows/abi-report.yml
  .github/workflows/daily-build.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug, Component - Misc

#4597 Document that ctx VOL property isn't drawn from the FAPL
  src/H5CX.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4603 Update macos workflow to 14 (keep 13 as alternate)
  .github/workflows/cmake-bintest.yml
  .github/workflows/main-cmake.yml
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#4606 Move markdown link check CI to once on Saturdays
  .github/workflows/markdown-link-check.yml
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Type - Task, Component - Misc

#4595 Bring subfiling VFD code closer to typical library code
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDioc_int.c
  src/H5FDsubfiling/H5FDioc_priv.h
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5FDsubfiling/H5FDsubfile_int.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5FDsubfiling_priv.h
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
  src/H5FDsubfiling/H5subfiling_err.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4598 Correct documentation for return-and-read fields
  src/H5CX.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4608 These two generators create strings without NUL for testing
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5repack/h5repacktst.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Testing, Type - Bug

#4593 Fix Fortran pkconfig to indicate full path of modules
  fortran/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Bug

#4615 Update release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4611 Document VOL object wrapping context
  doxygen/dox/VOLConnGuide.dox
  src/H5VLcallback.c
  src/H5VLconnector.h
  src/H5VLint.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement
