Repository HDFGroup/hdf5, pull requests merged in 2024-11, with the labels that each got.

#5032 Add parallel cdash script to daily-build workflow
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/daily-build.yml
  src/H5api_adpt.h
  testpar/CMakeLists.txt
  testpar/CMakeTests.cmake
  testpar/testpar.h
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - New Feature, Component - Misc, Merge - To 2.0

#5058 Update daily build action to build MPICH and OpenMPI from source
  .github/workflows/build_mpich_source.yml
  .github/workflows/build_openmpi_source.yml
  .github/workflows/cmake-par-source.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#5063 Remove top-level structure from MPI source build workflow tar artifacts
  .github/workflows/build_mpich_source.yml
  .github/workflows/build_openmpi_source.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#4993 Update nvhpc version to 24.9
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement

#5059 Add OSS-Fuzz badge
  README.md
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Task

#5064 Update stdio API calls
  src/H5FDstdio.c
  src/H5private.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Bug / Bugfix, Merge - To 1.14.6

#5022 Fixed H5Ovisit2() change of behavior between 1.10.11 and v1.14.4.3
  release_docs/RELEASE.txt
  src/H5Oint.c
  test/th5o.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug / Bugfix

#5066 Improve merge CI
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Component - Misc

#5071 Skip some additional dt_arith long double tests for ppc64le systems
  test/dt_arith.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Task

#5068 Remove ref to obsolete and removed option
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 3. Low 🔽, Type - Bug / Bugfix, Component - Misc

#5070 Renamed H5VLstart_lib_state and H5VLfinish_lib_state
  doxygen/aliases
  doxygen/dox/VOLConnGuide.dox
  release_docs/RELEASE.txt
  src/H5VL.c
  src/H5VLconnector_passthru.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Type - Deprecation / Removal

#5075 Restrict daily schedule to HDF repo
  .github/workflows/daily-schedule.yml
Labels: Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#5074 Rename HDF5_ENABLE_Z_LIB_SUPPORT to HDF5_ENABLE_ZLIB_SUPPORT
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/vol_rest.yml
  CMakeFilters.cmake
  CMakeLists.txt
  HDF5Examples/C/H5D/C_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5D/Fortran_sourcefiles.cmake
  HDF5Examples/JAVA/H5D/Java_sourcefiles.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/mccacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/HISTORY-1_14_0-2_0_0.txt
  release_docs/INSTALL_CMake.txt
  release_docs/README_HPC
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Build, Type - Improvement, Type - Deprecation / Removal, Component - Misc

#5079 Add CMake min version check to CI
  .github/workflows/main-cmake-spc.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Component - Misc

#5081 Add 32-bit workflow
  .github/workflows/cmake.yml
  .github/workflows/i386-cmake.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement, Component - Misc

#5084 Move overflow macros from VFDs to H5FDpkg.h
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDhdfs.c
  src/H5FDlog.c
  src/H5FDmirror.c
  src/H5FDonion.c
  src/H5FDpkg.h
  src/H5FDros3.c
  src/H5FDsec2.c
  src/H5FDsplitter.c
  src/H5FDstdio.c
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#5083 Make H5F_LIBVER_LATEST a real enum value
  java/src/hdf/hdf5lib/HDF5Constants.java
  java/src/jni/h5Constants.c
  release_docs/RELEASE.txt
  src/H5Fpublic.h
  src/H5Ppublic.h
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Java, Type - Improvement

#5092 fixed true/false definition and added missing h5_interm_group example
  HDF5Examples/C/TUTR/C_sourcefiles.cmake
  HDF5Examples/C/TUTR/h5_interm_group.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug / Bugfix, Branch - 2.0

#5093 Fix typo masquarading
  bin/h5cc.in
  c++/src/h5c++.in
Labels: Component - Tools

#5094 Add documentation to h5test testing framework
  test/h5test.c
  test/h5test.h
Labels: Priority - 3. Low 🔽, Component - Documentation, Component - Testing, Type - Improvement

#5127 Added note about leaving callback functions properly.
  doxygen/aliases
  src/H5Apublic.h
  src/H5Dpublic.h
  src/H5Gpublic.h
  src/H5Ipublic.h
  src/H5Lpublic.h
  src/H5Mpublic.h
  src/H5Opublic.h
  src/H5Ppublic.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5129 Update plugin version refs to match updated plugins repo
  CMakePresets.json
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement, Component - Misc

#5091 Remove CMake-3.31.0 warnings
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
Labels: Component - Build

#5130 Add check for PERL_FOUND around actual test
  test/ShellTests.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5131 Convert external chunking documentation to doxygen
  doxygen/dox/DSChunkingIssues.dox
  doxygen/dox/IntroParHDF5.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/chunking_in_hdf5.dox
  doxygen/img/Chunk_f1.gif
  doxygen/img/Chunk_f2.gif
  doxygen/img/Chunk_f3.gif
  doxygen/img/Chunk_f4.gif
  doxygen/img/Chunk_f5.gif
  doxygen/img/Chunk_f6.gif
  doxygen/img/chunking1and2.png
  doxygen/img/chunking3and4.png
  doxygen/img/chunking5.png
  doxygen/img/chunking6.png
  doxygen/img/chunking7.png
  doxygen/img/chunking8.png
  src/H5Gpublic.h
  src/H5Tmodule.h
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#5137 Temporary disable of julia workflow
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix, Type - Task, Component - Misc

#5140 Convert vfl html file to doxygen
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/VFL.html
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5141 Update zfp compression lib references
  CMakePresets.json
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_zfp.ddl
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_zfp.tst
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug / Bugfix, Component - Misc

#5134 Convert file image ops file to doxygen
  doxygen/aliases
  doxygen/dox/RFC.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/ViewTools.dox
  doxygen/examples/FileImageOps.html
  doxygen/img/DOChunks_fig1.png
  doxygen/img/DOChunks_fig2.png
  hl/src/H5DOpublic.h
  hl/src/H5LTpublic.h
  src/H5Dmodule.h
  src/H5Dpublic.h
  src/H5Fmodule.h
  src/H5Fpublic.h
  src/H5PLmodule.h
  src/H5Pmodule.h
  src/H5Ppublic.h
  src/H5module.h
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#5142 Clarified the description of the filter ID range.
  src/H5Zmodule.h
  src/H5Zpublic.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5143 Added a bin/process_source.sh script
  bin/process_source.sh
Labels: Priority - 2. Medium ⏹, Type - New Feature, Component - Misc

#5146 Correct some links in doxygen - not found
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_zfp.tst
  doxygen/aliases
  doxygen/dox/ExamplesAPI.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/hdf5_footer.html
  doxygen/hdf5_header.html
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug / Bugfix, Component - Misc

#5149 Convert HL table spec file to doxygen
  doxygen/dox/Specifications.dox
  doxygen/examples/TableSpec.html
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5150 Rename cdash site for daily MPI source builds
  .github/workflows/cmake-par-source.yml
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#5139 Convert Debugging HDF5 Applications to doxygen
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/DebuggingHDF5Applications.html
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5138 Add check for broken links in Doxygen generated html docs
  .github/workflows/linkchecker.yml
Labels: Priority - 1. High 🔼, Component - Documentation, Component - Testing, Type - Improvement, Component - Misc

#5151 Skip some parallel tests for OpenMPI version 5.0.5
  release_docs/RELEASE.txt
  testpar/testphdf5.c
Labels: Priority - 3. Low 🔽, Component - Parallel, Component - Testing, Type - Improvement

#5153 Allow link check to continue temporarily
  .github/workflows/linkchecker.yml
Labels: Type - Task, Component - Misc
