Repository HDFGroup/hdf5, pull requests merged in 2024-03, with the labels that each got.

#4053 Fix issue with FAPL file locking setting inheriting test
  test/h5test.c
  test/h5test.h
  test/links.c
  test/vol.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#4039 Fix VOL-compatibility issues in External Link API test
  test/API/H5_api_link_test.c
  test/API/H5_api_link_test.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4040 Add upddated cmake tools from source location
  config/sanitizer/README.md
  config/sanitizer/afl-fuzzing.cmake
  config/sanitizer/code-coverage.cmake
  config/sanitizer/dependency-graph.cmake
  config/sanitizer/formatting.cmake
  config/sanitizer/sanitizers.cmake
  config/sanitizer/tools.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Improvement

#4046 Add options to allow tools type selection and naming
  CMakeLists.txt
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/hdf5-config.cmake.in
  config/sanitizer/README.md
  hl/tools/gif2h5/CMakeLists.txt
  hl/tools/gif2h5/CMakeTests.cmake
  hl/tools/h5watch/CMakeLists.txt
  hl/tools/h5watch/CMakeTests.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/misc/CMakeTestsRepart.cmake
  utils/tools/h5dwalk/CMakeLists.txt
  utils/tools/test/h5dwalk/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Component - Build, Type - Improvement, Type - New Feature

#4047 Improve error messages when tools attempt to use non-enabled S3 and HDFS VFDs.
  tools/libtest/h5tools_test_utils.c
  tools/src/h5dump/h5dump.c
  tools/src/h5ls/h5ls.c
  tools/src/h5stat/h5stat.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#4057 Do not enable szip for sanitizer runs
  config/cmake/mccacheinit.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Component - Misc

#4059 Add note to H5Tset_fields about needing to set datatype precision first
  src/H5Tpublic.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4061 Fix issue where H5Tset_fields does not account for datatype offsets
  release_docs/RELEASE.txt
  src/H5Tfloat.c
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4066 Ignore UserPresets and Use only C compiler for sanitizers
  .gitignore
  HDF5Examples/CMakeUserPresets.json
  config/sanitizer/sanitizers.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug, Component - Misc

#4067 Rename incorrectly named option
  c++/examples/CMakeTests.cmake
  c++/test/CMakeTests.cmake
  c++/test/CMakeVFDTests.cmake
  config/cmake/mccacheinit.cmake
  examples/CMakeTests.cmake
  fortran/examples/CMakeTests.cmake
  fortran/test/CMakeTests.cmake
  hl/c++/examples/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/examples/CMakeTests.cmake
  hl/fortran/examples/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  hl/tools/h5watch/CMakeTests.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  test/CMakeTests.cmake
  testpar/CMakeVFDTests.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/CMakeVFDTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/perform/CMakeTests.cmake
  utils/tools/test/h5dwalk/CMakeTests.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Task

#4071 Fix a memory leak in the cmpd_dset test
  test/cmpd_dset.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4072 Fix uninitialized bytes in cmpd_dset test
  test/cmpd_dset.c
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4052 Update INSTALL files
  .github/workflows/cmake-ctest.yml
  config/cmake/HDFMacros.cmake
  config/cmake/README.md.cmake.in
  release_docs/INSTALL_CMake.txt
  release_docs/USING_HDF5_CMake.txt
  release_docs/USING_HDF5_VS.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4055 Add NEWSLETTER and merge abi reports and add sha256sums
  .github/workflows/abi-report.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
  config/cmake-presets/hidden-presets.json
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Component - Build, Type - Improvement, Component - Misc

#4073 Fix uninitialized bytes in selection I/O test
  test/select_io_dset.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#4049 Added new H5E with tests.
  README.md
  config/cmake/H5pubconf.h.in
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFUseFortran.cmake
  configure.ac
  doxygen/examples/H5E_examples.c
  fortran/src/CMakeLists.txt
  fortran/src/H5Aff.F90
  fortran/src/H5Ef.c
  fortran/src/H5Eff.F90
  fortran/src/H5Pff.F90
  fortran/src/H5VLff.F90
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90proto.h
  fortran/src/H5fortkit.F90
  fortran/src/Makefile.am
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/fortranlib_test_F03.F90
  fortran/test/tH5E.F90
  fortran/test/tH5E_F03.F90
  fortran/test/tH5I.F90
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
  release_docs/RELEASE.txt
  src/H5Epublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran

#4077 Don't load toolchain file in CMake workflows
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Task, Component - Misc

#4078 Add support for the new MSVC preprocessor
  release_docs/RELEASE.txt
  src/H5win32defs.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4064 Increased H5FD_ROS3_MAX_SECRET_TOK_LEN to 4096 to accommodate long AWS secret tokens
  src/H5FDros3.c
  src/H5FDros3.h
  src/H5FDs3comms.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4050 Prevent cache use instead of actual I/O in dset vlen API tests
  test/API/H5_api_dataset_test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4062 New option for building with static CRT in Windows
  config/cmake/HDFUseFortran.cmake
  config/cmake/UserMacros/Windows_MT.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Component - Build, Type - Deprecation / Removal

#4082 Addresses compilation errors with gfortran 4.8
  fortran/src/H5Eff.F90
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Fortran, Type - Improvement

#4074 Fix bin/trace script w/ out params
  bin/trace
  src/H5.c
  src/H5A.c
  src/H5D.c
  src/H5E.c
  src/H5ES.c
  src/H5Edeprec.c
  src/H5F.c
  src/H5FD.c
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDfamily.c
  src/H5FDhdfs.c
  src/H5FDmirror.c
  src/H5FDmpio.c
  src/H5FDonion.c
  src/H5FDros3.c
  src/H5FDsplitter.c
  src/H5Fdeprec.c
  src/H5Fmpi.c
  src/H5G.c
  src/H5Gdeprec.c
  src/H5I.c
  src/H5L.c
  src/H5Ldeprec.c
  src/H5M.c
  src/H5O.c
  src/H5Odeprec.c
  src/H5P.c
  src/H5PL.c
  src/H5Pdapl.c
  src/H5Pdcpl.c
  src/H5Pdeprec.c
  src/H5Pdxpl.c
  src/H5Pfapl.c
  src/H5Pfcpl.c
  src/H5Pgcpl.c
  src/H5Plapl.c
  src/H5Plcpl.c
  src/H5Pmapl.c
  src/H5Pocpl.c
  src/H5Pocpypl.c
  src/H5Pstrcpl.c
  src/H5R.c
  src/H5Rdeprec.c
  src/H5S.c
  src/H5Shyper.c
  src/H5Spoint.c
  src/H5Sselect.c
  src/H5T.c
  src/H5Tarray.c
  src/H5Tenum.c
  src/H5Tfloat.c
  src/H5Tpad.c
  src/H5VL.c
  src/H5VLcallback.c
  src/H5Z.c
  src/H5trace.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4070 Use H5T_STD_I32LE to create datatype in vds examples
  HDF5Examples/C/H5VDS/h5ex_vds-eiger.c
  HDF5Examples/C/H5VDS/h5ex_vds-exc.c
  HDF5Examples/C/H5VDS/h5ex_vds-exclim.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim-maxmin.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival.c
  HDF5Examples/C/H5VDS/h5ex_vds-simpleIO.c
  HDF5Examples/C/H5VDS/h5ex_vds.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Component - Misc

#4086 Remove printf debugging in H5HL code
  config/cmake/HDFCompilerFlags.cmake
  configure.ac
  src/H5HL.c
  src/H5HLprivate.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Deprecation / Removal

#4081 Fixed asserts due to H5Pset_est_link_info() values
  release_docs/RELEASE.txt
  src/H5Gobj.c
  test/tmisc.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4084 Added macOS support statement
  release_docs/RELEASE.txt
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#4090 fixes compilation failures due to H5E additions
  fortran/src/H5Eff.F90
  fortran/test/tH5E_F03.F90
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Type - Bug

#4091 Remove extra whitespaces from nvhpc-cmake action.
  .github/workflows/nvhpc-cmake.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4088 Remove printf debugging in H5I package
  config/cmake/HDFCompilerFlags.cmake
  configure.ac
  src/H5Iint.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#3878 Add subfiling for h5dump filedriver option help message
  tools/src/h5dump/h5dump.c
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
Labels: Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#4093 Merge HDF4 release workflow changes to hdf5
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Improvement, Component - Misc

#4060 Update long double test with correct values
  test/dsets.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4092 virtual creates must use the same datatype as the main file
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim-maxmin.c
  HDF5Examples/C/H5VDS/h5ex_vds-percival-unlim.c
  HDF5Examples/C/H5VDS/h5ex_vds-simpleIO.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#3306 Fixed -Wdeprecated-copy-dtor warnings by implementing a copy assignme…
  c++/src/H5Attribute.cpp
  c++/src/H5Attribute.h
  c++/src/H5Group.cpp
  c++/src/H5Group.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C++, Type - Improvement

#4085 Expand check for variable-length or reference types when clearing datatype conversion paths
  src/H5T.c
  test/tmisc.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Improvement

#4089 Remove H5B debug checks
  config/cmake/HDF5DeveloperBuild.cmake
  configure.ac
  release_docs/RELEASE.txt
  src/H5B.c
  src/H5Bdbg.c
  src/H5Bpkg.h
  src/H5Bprivate.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Deprecation / Removal

#4099 Fix the last C++ stack size warning
  c++/test/tfilter.cpp
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C++, Component - Testing, Type - Improvement

#4095 Clean up off_t usage
  HDF5Examples/FORTRAN/H5D/h5ex_d_extern.F90
  c++/src/H5DcreatProp.cpp
  fortran/src/H5Pff.F90
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDlog.c
  src/H5FDsec2.c
  test/big.c
  test/enc_dec_plist.c
  test/enc_dec_plist_cross_platform.c
  test/external.c
  test/file_image.c
  test/fillval.c
  test/gen_bad_offset.c
  test/gen_plist.c
  test/istore.c
  test/objcopy.c
  test/set_extent.c
  test/th5s.c
  test/twriteorder.c
  testpar/t_2Gio.c
  testpar/t_dset.c
  testpar/t_prop.c
  tools/src/h5import/h5import.c
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5repack/h5repacktst.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Tools, Component - Fortran, Component - C++, Component - Parallel, Component - Testing, Type - Improvement

#4100 Correct missing change of source path for S3 build
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4101 Remove leading / from relative path.
  README.md
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#3956 msvc: don't declare `HAVE_TIMEZONE` for older MSVC
  config/cmake/ConfigureChecks.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4096 Remove a few H5O printf debugging statements
  src/H5Oint.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Deprecation / Removal

#4103 Remove H5DEBUG() calls from H5Dmpio.c
  src/H5Dmpio.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Parallel, Type - Improvement

#4098 Remove printf debugging from H5Smpio.c
  config/cmake/HDFCompilerFlags.cmake
  configure.ac
  src/H5Smpio.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Parallel, Type - Deprecation / Removal

#4097 Change how stats are printed in H5Z
  src/H5Z.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4104 Refactor datatype conversion code to use pointers rather than IDs
  src/H5Aint.c
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dcontig.c
  src/H5Ddeprec.c
  src/H5Dfill.c
  src/H5Dint.c
  src/H5Dio.c
  src/H5Dmpio.c
  src/H5Dpkg.h
  src/H5Dscatgath.c
  src/H5Dvirtual.c
  src/H5Ocopy_ref.c
  src/H5Ofill.c
  src/H5Oprivate.h
  src/H5Pdcpl.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5T.c
  src/H5Tconv.c
  src/H5Tnative.c
  src/H5Tpkg.h
  src/H5Tprivate.h
  src/H5VLnative_dataset.c
  test/dt_arith.c
  tools/test/h5format_convert/h5fc_chk_idx.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Improvement

#4110 Minimize use of abort()
  src/H5.c
  src/H5Tbit.c
  src/H5private.h
  test/hyperslab.c
  test/tmisc.c
  tools/test/misc/talign.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Improvement

#4105 Clean up a few things in H5T.c
  src/H5T.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4109 Convert H5B__assert to use error checks
  src/H5Bdbg.c
  src/H5Bpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4108 Move common variables out of cache test blocks
  test/cache.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#4107 Remove lint comments
  src/H5B.c
  src/H5Dchunk.c
  src/H5Dint.c
  src/H5Dlayout.c
  src/H5E.c
  src/H5Edeprec.c
  src/H5Eint.c
  src/H5FL.c
  src/H5Tfields.c
  src/H5Tvlen.c
  src/H5VM.c
  src/H5Zshuffle.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Deprecation / Removal

#4083 Change compression tests reference files to use masking for compression ratios
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/runTest.cmake
  release_docs/USING_HDF5_CMake.txt
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/expected/tallfilters.ddl
  tools/test/h5dump/expected/tdeflate.ddl
  tools/test/h5dump/expected/tfletcher32.ddl
  tools/test/h5dump/expected/tnbit.ddl
  tools/test/h5dump/expected/tscaleoffset.ddl
  tools/test/h5dump/expected/tszip.ddl
  tools/test/h5dump/testh5dump.sh.in
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/expected/deflate_limit.h5repack_layout.h5.ddl
  tools/test/h5repack/expected/h5repack_filters.h5-gzip_verbose_filters.tst
  tools/test/h5repack/h5repack.sh.in
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Tools, Component - Testing, Type - Improvement

#4106 Add Doxygen for HDFS VFD
  src/H5FDhdfs.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Documentation, Type - Improvement

#4102 long double tests has problems setting precision with offset
  test/dsets.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4114 Fix up dsets test for some platforms with different long double format
  test/dsets.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4115 Adjust aocc workflow to fit the autotools/cmake pattern of other callable workflows.
  .github/workflows/aocc-ompi-auto.yml
  .github/workflows/aocc-ompi-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/linux-auto-aocc-ompi.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/nvhpc-auto.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Misc

#4116 Handle IBM long double issues in dsets.c test_floattypes test
  test/dsets.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Bug

#4117 Remove old cmake check
  CMakeFilters.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Deprecation / Removal

#4119 Use AC_SYS_LARGEFILE on Autotools
  acsite.m4
  configure.ac
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#4122 Overhaul CMake LFS support
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDFTests.c
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#4124 Update CMake comment about _POSIX_C_SOURCE
  config/cmake/ConfigureChecks.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4121 Sync develop branch changes March 4 - 6 to hdf5_1_14 branch
  .github/workflows/abi-report.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
  c++/examples/CMakeTests.cmake
  c++/test/CMakeTests.cmake
  c++/test/CMakeVFDTests.cmake
  config/cmake-presets/hidden-presets.json
  config/cmake/HDFMacros.cmake
  config/cmake/README.md.cmake.in
  config/cmake/mccacheinit.cmake
  config/sanitizer/sanitizers.cmake
  examples/CMakeTests.cmake
  fortran/examples/CMakeTests.cmake
  fortran/test/CMakeTests.cmake
  hl/c++/examples/CMakeTests.cmake
  hl/c++/test/CMakeTests.cmake
  hl/examples/CMakeTests.cmake
  hl/fortran/examples/CMakeTests.cmake
  hl/fortran/test/CMakeTests.cmake
  hl/test/CMakeTests.cmake
  hl/tools/h5watch/CMakeTests.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  release_docs/USING_HDF5_CMake.txt
  release_docs/USING_HDF5_VS.txt
  src/H5Tfloat.c
  src/H5Tpublic.h
  test/CMakeTests.cmake
  test/cmpd_dset.c
  test/dtypes.c
  test/select_io_dset.c
  testpar/CMakeVFDTests.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/h5repack/CMakeVFDTests.cmake
  tools/test/h5stat/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
  tools/test/perform/CMakeTests.cmake
  utils/tools/test/h5dwalk/CMakeTests.cmake
Labels: Merge, Branch - 1.14

#4128 Fix typo/stray character in cmake-ctest.yml
  .github/workflows/cmake-ctest.yml
Labels: Branch - 1.14

#4127 Deprecate bin/cmakehdf5
  bin/cmakehdf5
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Deprecation / Removal, Component - Misc

#4125 Don't set the rpath when linking statically
  bin/h5cc.in
  c++/src/h5c++.in
  fortran/src/h5fc.in
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Improvement

#4129 Remove invalid compile flag
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Confirmed - 3rd Party Library Issue

#4130 Fix segfault in vlen io API test
  test/API/H5_api_dataset_test.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug

#4131 Add cygwin CI and update yaml files for consistency and accuracy
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/cygwin-auto.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake.yml
  .github/workflows/main.yml
  .github/workflows/mingw-cmake.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  config/cmake/ConfigureChecks.cmake
  config/cmake/scripts/CTestScript.cmake
  configure.ac
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Component - Misc

#4142 Remove ros3 and hdfs VFDs from Autotools VFD list
  config/conclude.am
Labels: Component - Testing

#4136 Skip part of dsets.c test for IBM long double type
  test/dsets.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug

#4141 Capitalize option message for consistency.
  CMakeLists.txt
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#4144 Fix Autotools -Werror cleanup
  configure.ac
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#4133 Fix doxygen link to example function usage
  test/links.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#4143 Clean up some hbool_t/TRUE/FALSE stragglers
  src/H5CX.c
  src/H5FDint.c
  src/H5FDmpio.c
  src/H5Fmpi.c
  src/H5O.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4140 Fix error when overwriting an indirectly nested vlen with a shorter sequence
  release_docs/RELEASE.txt
  src/H5Tconv.c
  test/dsets.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Improvement

#4146 Defined CMAKE_H5_HAVE_DARWIN
  fortran/src/CMakeLists.txt
Labels: Priority - 1. High 🔼, Component - Fortran, Type - Bug

#4149 Make the newsletter scheme work like HDF4
  release_docs/NEWSLETTER.txt
  release_docs/NEWSLETTER_README.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Task, Component - Misc

#4151 Remove "is" at the end of list item.
  release_docs/INSTALL_CMake.txt
Labels: Component - Documentation

#4147 Fix buffer size calculation in the deflate filter
  src/H5Zdeflate.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4150 Remove H5O header and friend status from H5A.c
  src/H5A.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4157 Remove HDF from Fortran 2003 configuration check message.
  m4/aclocal_fc.m4
Labels: Component - Build

#4154 Header cleanup in C library
  src/H5AC.c
  src/H5ACmpio.c
  src/H5ACproxy_entry.c
  src/H5Adense.c
  src/H5Aint.c
  src/H5B.c
  src/H5B2.c
  src/H5B2hdr.c
  src/H5B2int.c
  src/H5B2internal.c
  src/H5B2leaf.c
  src/H5Bcache.c
  src/H5C.c
  src/H5CS.c
  src/H5Cdbg.c
  src/H5Centry.c
  src/H5Cint.c
  src/H5Cmpio.c
  src/H5Dchunk.c
  src/H5Dint.c
  src/H5Dmpio.c
  src/H5EAhdr.c
  src/H5FAhdr.c
  src/H5FO.c
  src/H5FS.c
  src/H5FScache.c
  src/H5FSsection.c
  src/H5Faccum.c
  src/H5Fefc.c
  src/H5Ffake.c
  src/H5Fint.c
  src/H5Fsuper.c
  src/H5Gcache.c
  src/H5Gint.c
  src/H5Goh.c
  src/H5Groot.c
  src/H5HF.c
  src/H5HFcache.c
  src/H5HFdblock.c
  src/H5HFhdr.c
  src/H5HFiblock.c
  src/H5HFiter.c
  src/H5HFsection.c
  src/H5HG.c
  src/H5HGcache.c
  src/H5MFsection.c
  src/H5Oattr.c
  src/H5Ochunk.c
  src/H5Ocopy.c
  src/H5Ocopy_ref.c
  src/H5Oint.c
  src/H5PB.c
  src/H5Pint.c
  src/H5RS.c
  src/H5SMbtree2.c
  src/H5Tdeprec.c
  src/H5Tinit_float.c
  src/H5VLnative_file.c
  src/H5VLnative_token.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4158 Add Doxygen to H5FDmirror.h
  src/H5FDmirror.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4163 Remove lseek64 and stat64 symbols from CMake
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#4160 Remove HAVE_IOEO checks from CMake
  CMakeLists.txt
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDFTests.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#4165 Fix some minor warnings
  HDF5Examples/C/H5T/h5ex_t_array.c
  HDF5Examples/C/H5T/h5ex_t_arrayatt.c
  HDF5Examples/C/H5T/h5ex_t_cmpd.c
  HDF5Examples/C/H5T/h5ex_t_cmpdatt.c
  HDF5Examples/C/H5T/h5ex_t_cpxcmpd.c
  HDF5Examples/C/H5T/h5ex_t_cpxcmpdatt.c
  HDF5Examples/C/H5T/h5ex_t_objref.c
  HDF5Examples/C/H5T/h5ex_t_objrefatt.c
  HDF5Examples/C/H5T/h5ex_t_opaqueatt.c
  HDF5Examples/C/H5T/h5ex_t_regref.c
  HDF5Examples/C/H5T/h5ex_t_regrefatt.c
  HDF5Examples/C/H5T/h5ex_t_vlen.c
  HDF5Examples/C/H5T/h5ex_t_vlenatt.c
  java/src/jni/h5pImp.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5Fint.c
  test/atomic_writer.c
  test/dsets.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Component - Java, Component - Parallel, Component - Testing, Type - Bug

#4167 Bump the size of the mirror VFD IP field
  src/H5FDmirror.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4170 Fix mirror VFD script
  test/test_mirror.sh.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4159 Fix an issue where the Subfiling VFD's context cache grows too large
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4172 Address code page issues w/ Windows file paths
  src/H5system.c
  src/H5win32defs.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4173 Add Doxygen to API calls in H5VLnative.h
  src/H5VLnative.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4152 Allow H5Soffset_simple to accept NULL offsets
  release_docs/RELEASE.txt
  src/H5Spkg.h
  src/H5Spublic.h
  src/H5Sselect.c
  src/H5Stest.c
  test/tselect.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4164 Remove some H5T_copy calls that are now unnecessary
  src/H5Aint.c
  src/H5D.c
  src/H5Dchunk.c
  src/H5Dcompact.c
  src/H5Dcontig.c
  src/H5Ddeprec.c
  src/H5Dfill.c
  src/H5Dint.c
  src/H5Dio.c
  src/H5Dpkg.h
  src/H5Ocopy_ref.c
  src/H5Ofill.c
  src/H5Oprivate.h
  src/H5Pdcpl.c
  src/H5Sprivate.h
  src/H5Sselect.c
  src/H5T.c
  src/H5Tconv.c
  src/H5Tenum.c
  src/H5Tpkg.h
  src/H5Tprivate.h
  src/H5VLnative_dataset.c
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Bug, Type - Improvement

#4175 Add RELEASE.txt note for compound conversion segfault fix
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Task, Branch - 1.14

#4161 Clean up CMake direct VFD handling
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDFTests.c
  config/cmake/libhdf5.settings.cmake.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#4153 Reworked H5Epush_f
  fortran/src/H5Ef.c
  fortran/src/H5Eff.F90
  fortran/src/H5f90proto.h
  fortran/test/tH5E_F03.F90
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - Improvement

#4179 Update Release Specific Information link
  release_docs/RELEASE.txt
Labels: Component - Documentation

#4176 Add initial skeleton file for daily VFD CI workflow
  .github/workflows/vfd-main.yml
  .github/workflows/vfd-subfiling.yml
  .github/workflows/vfd.yml
  README.md
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#4186 Exclude shell tests from sanitizers
  config/cmake/CTestCustom.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Testing, Type - Bug, Component - Misc

#4184 Add a missing period at the end of sentence
  src/H5PLmodule.h
Labels: Component - Documentation

#4183 Update README.md for coming Complex number support
  README.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#4185 last-file.txt should not be created for release workflow
  .github/workflows/release-files.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4182 Skip part of dtypes.c _Float16 file size check for certain VFDs
  test/dtypes.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4190 Fixes several MinGW + Autotools issues
  config/cmake/H5pubconf.h.in
  configure.ac
  src/H5private.h
  src/H5system.c
  test/testframe.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Build, Type - Improvement

#4193 Add semicolons to the end of HSYS_GOTO_ERROR
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDlog.c
  src/H5FDsec2.c
  src/H5Fint.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4187 Remove broken links in config/sanitizer/README.md
  config/sanitizer/README.md
Labels: Component - Documentation

#4038 Handle certain empty subfiling environment variables
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5subfiling_common.c
  testpar/t_subfiling_vfd.c
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Type - Improvement

#4191 h5diff compares attribute data like dataset data
  tools/src/h5diff/h5diff_common.c
  tools/test/h5diff/expected/h5diff_10.txt
  tools/test/h5diff/expected/h5diff_600.txt
  tools/test/h5diff/expected/h5diff_603.txt
  tools/test/h5diff/expected/h5diff_606.txt
  tools/test/h5diff/expected/h5diff_612.txt
  tools/test/h5diff/expected/h5diff_615.txt
  tools/test/h5diff/expected/h5diff_621.txt
  tools/test/h5diff/expected/h5diff_622.txt
  tools/test/h5diff/expected/h5diff_623.txt
  tools/test/h5diff/expected/h5diff_624.txt
Labels: Priority - 2. Medium ⏹, Component - Tools, Component - Documentation, Type - Improvement

#4192 A path component may include a dot with other characters
  src/H5Gmodule.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Type - Task

#4195 Add RELEASE.txt note for recent datatype conversion improvements
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Task

#4197 Add NEWSLETTER item about _Float16 support
  release_docs/NEWSLETTER.txt
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Task

#4196 Correct download link for develop doxygen
  doxygen/dox/Overview.dox
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Bug

#4202 Call memset before stat calls
  hl/test/test_dset_append.c
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDlog.c
  src/H5FDsec2.c
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDioc_threads.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5Fint.c
  src/H5PLpath.c
  test/big.c
  test/btree2.c
  test/file_image.c
  test/h5test.c
  test/istore.c
  test/tfile.c
  testpar/t_shapesame.c
  testpar/t_subfiling_vfd.c
  testpar/testphdf5.c
  tools/src/h5jam/h5jam.c
  tools/src/h5jam/h5unjam.c
  tools/src/h5perf/pio_engine.c
  tools/src/h5perf/sio_engine.c
  tools/src/misc/h5clear.c
  tools/src/misc/h5repart.c
  tools/test/h5repack/h5repacktst.c
  tools/test/perform/overhead.c
  tools/test/perform/zip_perf.c
  utils/tools/h5dwalk/h5dwalk.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Tools, Component - Parallel, Component - Testing, Type - Bug

#4199 Remove unused CMake configuration checks
  config/cmake/ConfigureChecks.cmake
Labels: Component - Build

#4203 Update links to Chunking in HDF5 page
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
Labels: Component - Documentation, Type - Bug

#4206 Fix H5Pset_efile_prefix documentation error
  src/H5Ppublic.h
Labels: Component - Documentation, Type - Bug

#4201 Fix grammar in README.md release template
  config/cmake/README.md.cmake.in
Labels: Component - Documentation

#4198 Add back snapshot names
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Component - Misc

#4205 Use tar.gz extension for ABI reports
  .github/workflows/abi-report.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: Component - Misc

#4194 Fix issue with Subfiling VFD and multiple opens of same file
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDsubfiling/H5subfiling_common.h
  testpar/t_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Parallel, Component - Testing, Type - Bug

#4213 Reverts AC_SYS_LARGEFILE change
  acsite.m4
  configure.ac
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4139 Propagate group creation properties to intermediate groups
  src/H5Dint.c
  src/H5Dpkg.h
  src/H5Dprivate.h
  src/H5Gint.c
  src/H5Gpkg.h
  src/H5Gprivate.h
  src/H5Gtraverse.c
  src/H5Lint.c
  src/H5Lprivate.h
  test/tmisc.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug

#4209 Addressed Fortran issues with promoted integers and reals via compilation flags
  HDF5Examples/FORTRAN/H5G/h5ex_g_traverse.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_dataset.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_file_create.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_filtered_writes_no_sel.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_chunk.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_col.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_pattern.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_row.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_subfiling.F90
  HDF5Examples/FORTRAN/H5T/h5ex_t_enum_F03.F90
  HDF5Examples/FORTRAN/H5T/h5ex_t_enumatt_F03.F90
  config/cmake/HDF5UseFortran.cmake
  fortran/src/H5Fff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5Sf.c
  fortran/src/H5f90proto.h
  fortran/test/tH5A.F90
  fortran/test/tH5L_F03.F90
  fortran/test/tH5O_F03.F90
  fortran/test/tH5T_F03.F90
  fortran/testpar/async.F90
  fortran/testpar/hyper.F90
  fortran/testpar/mdset.F90
  fortran/testpar/mpi_param.F90
  fortran/testpar/multidsetrw.F90
  fortran/testpar/ptest.F90
  fortran/testpar/subfiling.F90
  m4/aclocal_fc.m4
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - Bug

#4212 Summarize the library version table
  src/H5Ppublic.h
Labels: Merge - To 1.14, Component - Documentation, Type - Improvement

#4210 Fix URLs
  HDF5Examples/C/H5D/Makefile.am
  HDF5Examples/C/H5D/test.sh.in
  HDF5Examples/C/H5G/Makefile.am
  HDF5Examples/C/H5G/test.sh.in
  HDF5Examples/C/H5T/Makefile.am
  HDF5Examples/C/H5T/test.sh.in
  HDF5Examples/C/H5VDS/Makefile.am
  HDF5Examples/C/H5VDS/test.sh.in
  HDF5Examples/C/Makefile.am
  HDF5Examples/FORTRAN/H5D/Makefile.am
  HDF5Examples/FORTRAN/H5D/test.sh.in
  HDF5Examples/FORTRAN/H5G/Makefile.am
  HDF5Examples/FORTRAN/H5G/test.sh.in
  HDF5Examples/FORTRAN/H5T/Makefile.am
  HDF5Examples/FORTRAN/H5T/test.sh.in
  HDF5Examples/FORTRAN/Makefile.am
  HDF5Examples/JAVA/H5J/110/HDF5FileStructure.java
  HDF5Examples/JAVA/H5J/HDF5FileStructure.java
  HDF5Examples/JAVA/H5J/HDF5SubsetSelect.java
  HDF5Examples/JAVA/H5J/Makefile.am
  HDF5Examples/JAVA/H5J/runExample.sh.in
  HDF5Examples/Makefile.am
  HDF5Examples/configure.ac
  doc/parallel-compression.md
  java/src/jni/exceptionImp.c
  java/src/jni/h5Constants.c
  java/src/jni/h5Imp.c
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5eImp.c
  java/src/jni/h5fImp.c
  java/src/jni/h5gImp.c
  java/src/jni/h5iImp.c
  java/src/jni/h5jni.h
  java/src/jni/h5lImp.c
  java/src/jni/h5oImp.c
  java/src/jni/h5pACPLImp.c
  java/src/jni/h5pDAPLImp.c
  java/src/jni/h5pDCPLImp.c
  java/src/jni/h5pDXPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5pFCPLImp.c
  java/src/jni/h5pGAPLImp.c
  java/src/jni/h5pGCPLImp.c
  java/src/jni/h5pImp.c
  java/src/jni/h5pLAPLImp.c
  java/src/jni/h5pLCPLImp.c
  java/src/jni/h5pOCPLImp.c
  java/src/jni/h5pOCpyPLImp.c
  java/src/jni/h5pStrCPLImp.c
  java/src/jni/h5plImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5sImp.c
  java/src/jni/h5tImp.c
  java/src/jni/h5util.c
  java/src/jni/h5util.h
  java/src/jni/h5vlImp.c
  java/src/jni/h5zImp.c
  java/src/jni/nativeData.c
Labels: Merge - To 1.14, Component - Documentation, Type - Improvement

#4211 Fix 'make check-vfd' target for Autotools
  config/cmake/HDF5Macros.cmake
  config/conclude.am
  doc/getting-started-with-hdf5-development.md
  src/H5FDtest.c
  src/H5private.h
  test/CMakeVFDTests.cmake
  test/accum.c
  test/accum_swmr_reader.c
  test/app_ref.c
  test/btree2.c
  test/cache_image.c
  test/cork.c
  test/dangle.c
  test/dsets.c
  test/dtypes.c
  test/error_test.c
  test/fheap.c
  test/filenotclosed.c
  test/flush1.c
  test/flush2.c
  test/flushrefresh.c
  test/h5test.c
  test/h5test.h
  test/links.c
  test/links_env.c
  test/mf.c
  test/objcopy.c
  test/ohdr.c
  test/onion.c
  test/page_buffer.c
  test/reserved.c
  test/select_io_dset.c
  test/set_extent.c
  test/stab.c
  test/swmr.c
  test/tarray.c
  test/test_flush_refresh.sh.in
  test/test_swmr.pwsh.in
  test/test_swmr.sh.in
  test/test_use_cases.sh.in
  test/test_vds_swmr.pwsh.in
  test/test_vds_swmr.sh.in
  test/tfile.c
  test/tmisc.c
  test/trefer.c
  test/tselect.c
  test/tsohm.c
  test/vds.c
  test/vds_env.c
  test/vfd.c
  test/vfd_plugin.c
  test/vol.c
  testpar/t_pflush1.c
  testpar/t_pflush2.c
  tools/lib/h5tools.c
  tools/lib/h5tools.h
  tools/libtest/h5tools_test_utils.c
  utils/test/swmr_check_compat_vfd.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Testing, Type - Bug, Type - Task

#4217 Backup and clear CMAKE_C_FLAGS before performing _Float16 configure checks
  config/cmake/ConfigureChecks.cmake
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Task

#4226 Avoid file size checks in C++ testhdf5 for certain VFDs
  c++/test/tattr.cpp
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C++, Type - Task

#4222 Fix an issue with type size assumptions in h5dumpgentest
  tools/test/h5dump/h5dumpgentest.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Bug

#4223 Fix issue with -Werror cleanup sed command in configure.ac
  configure.ac
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4229 Fix Java JNI warnings
  java/src/jni/h5aImp.c
  java/src/jni/h5dImp.c
  java/src/jni/h5eImp.c
  java/src/jni/h5pDCPLImp.c
  java/src/jni/h5pFAPLImp.c
  java/src/jni/h5rImp.c
  java/src/jni/h5sImp.c
  java/src/jni/h5tImp.c
  java/src/jni/h5util.c
  java/src/jni/nativeData.c
  test/h5test.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Java, Type - Bug

#4227 Rework snapshots/release workflows for consistent args
  .github/workflows/abi-report.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4231 Fixed a cache assert with too-large metadata objects
  release_docs/RELEASE.txt
  src/H5Centry.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4228 Set DXPL in API context for native VOL attribute I/O calls
  src/H5VLint.c
  src/H5VLnative_attr.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Type - Bug

#4232 Initialize a variable in C++ testhdf5's tattr.cpp
  c++/test/tattr.cpp
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C++, Type - Task

#4221 Addressed Fortran issues with promoted integers and reals via compilation flags, part 2
  HDF5Examples/FORTRAN/H5G/h5ex_g_traverse.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_dataset.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_file_create.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_filtered_writes_no_sel.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_chunk.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_col.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_pattern.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_hyperslab_by_row.F90
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_subfiling.F90
  HDF5Examples/FORTRAN/H5T/h5ex_t_enum_F03.F90
  HDF5Examples/FORTRAN/H5T/h5ex_t_enumatt_F03.F90
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFUseFortran.cmake
  configure.ac
  fortran/src/CMakeLists.txt
  fortran/src/H5Eff.F90
  fortran/src/H5Fff.F90
  fortran/src/H5Lff.F90
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
  fortran/src/H5Sf.c
  fortran/src/H5config_f.inc.cmake
  fortran/src/H5config_f.inc.in
  fortran/src/H5f90proto.h
  fortran/test/tH5A.F90
  fortran/test/tH5E_F03.F90
  fortran/test/tH5L_F03.F90
  fortran/test/tH5O_F03.F90
  fortran/test/tH5T_F03.F90
  fortran/testpar/async.F90
  fortran/testpar/hyper.F90
  fortran/testpar/mdset.F90
  fortran/testpar/mpi_param.F90
  fortran/testpar/multidsetrw.F90
  fortran/testpar/ptest.F90
  fortran/testpar/subfiling.F90
  m4/aclocal_fc.f90
  m4/aclocal_fc.m4
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Fortran, Type - Bug

#4233 Use cp -rp in test_plugin.sh
  test/test_plugin.sh.in
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#4235 Clean up types in h5test.c
  test/h5test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4237 Fix example links
  doxygen/dox/LearnBasics3.dox
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Deprecation / Removal

#4219 Add markdown link checker action
  .github/workflows/markdown-link-check.yml
Labels: Component - Documentation

#4215 Match minimum CMake version to 3.18
  HDF5Examples/Using_CMake.txt
Labels: Component - Documentation

#4236 Take user block into account when returning chunk addresses
  release_docs/RELEASE.txt
  src/H5Dchunk.c
  src/H5Dpublic.h
  test/chunk_info.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Testing, Type - Bug

#4242 Fix a minor warning in h5test.c
  test/h5test.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Task

#4243 Turn on -Werror for Java in GitHub -Werror workflows
  .github/workflows/main-auto-spc.yml
  config/gnu-warnings/8
  config/gnu-warnings/error-8
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Build, Type - Task, Component - Misc

#4230 Update Windows CI to not install ninja
  .github/workflows/main-cmake.yml
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Type - Task, Component - Misc

#4245 Comment out unused (for now) arg
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4240 Rework Fortran macros to use the proper code.
  CMakeLists.txt
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFUseFortran.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Fortran, Component - Build, Type - Improvement, Type - Deprecation / Removal

#4244 Correct reference copy for 16 API
  HDF5Examples/C/H5T/CMakeLists.txt
  doxygen/dox/ExamplesAPI.dox
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Bug

#4251 Fix all snapshot name refs
  .github/workflows/abi-report.yml
  .github/workflows/daily-build.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc
