Repository HDFGroup/hdf5, pull requests merged in 2024-09, with the labels that each got.

#4795 Fix typo argueably in H5Cprivate.h
  src/H5Cprivate.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#4796 Fix typos in H5Cpkg.h
  src/H5Cpkg.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Bug

#4786 Add bounds checking to avoid Out-of-bounds Write for gif2h5
  hl/tools/gif2h5/decompress.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Tools, Type - Bug

#4788 Replace non-VOL calls with VOL calls - part 5
  src/H5Gdeprec.c
  src/H5M.c
  src/H5Mpublic.h
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Documentation, Type - Improvement

#4794 Fix a few issues with error reporting during sec2 reads/writes
  src/H5FDsec2.c
Labels: Merge, Priority - 3. Low 🔽, Component - C Library, Type - Bug

#4807 Use latest clang format action
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4808 Correct path to document
  doxygen/dox/Specifications.dox
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug

#4765 Detect invalid ID to H5Gmove2
  src/H5Gdeprec.c
  src/H5L.c
  src/H5VLcallback.c
  test/links.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Bug

#4809 Fix use of public API calls
  src/H5FDfamily.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4810 Remove call to H5E_clear_stack()
  src/H5Gnode.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library, Type - Improvement

#4812 Enable win Intel signing
  .github/workflows/cmake-ctest.yml
  config/cmake/SignPackageFiles.cmake
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4814 Remove unneeded file name part
  .github/workflows/cmake-ctest.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4811 Change name of libhdf5hl_fortran installed by autotools
  config/commence.am
  fortran/src/h5fc.in
  hl/fortran/src/Makefile.am
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Build, Type - Bug

#4729 Rename and add more locking infrastructure
  src/CMakeLists.txt
  src/H5TSatomic.c
  src/H5TSatomic.h
  src/H5TSpkg.h
  src/H5TSprivate.h
  src/H5TSrec_rwlock.c
  src/H5TSrwlock.c
  src/H5TSrwlock.h
  src/Makefile.am
  test/CMakeLists.txt
  test/Makefile.am
  test/ttsafe.c
  test/ttsafe.h
  test/ttsafe_rec_rwlock.c
  test/ttsafe_rwlock.c
  test/ttsafe_semaphore.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Improvement

#4815 Update NVHPC optimization settings
  config/cmake/HDFCompilerFlags.cmake
  config/nvidia-flags
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Build, Type - Improvement

#4753 Add mirror VFD to serial -Werror CI action
  .github/workflows/main-auto-spc.yml
  test/mirror_vfd.c
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#4746 Add THREADS check to configuration file
  HDF5Examples/C/CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/CMakePresets.json
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5G/Fortran_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5PAR/CMakeLists.txt
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
  HDF5Examples/FORTRAN/TUTR/CMakeLists.txt
  HDF5Examples/Using_CMake.txt
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  HDF5Examples/config/cmake/cacheinit.cmake
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/hdf5-config.cmake.in
  release_docs/USING_CMake_Examples.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4813 Rework RFC url in aliases
  doxygen/aliases
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Type - Improvement, Component - Misc

#4817 Correct URL reference to downloads
  README.md
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug

#4821 Fix a bug in Subfiling VFD vector I/O setup
  release_docs/RELEASE.txt
  src/H5FDsubfiling/H5FDsubfiling.c
  testpar/t_subfiling_vfd.c
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - C Library, Component - Parallel, Type - Bug

#4820 Remove extensions from the package binaries - msi, dmg, deb,rpm
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Type - Deprecation / Removal, Component - Misc

#4824 Fix copyright notice urls in new test/ttsafe* files.
  test/ttsafe_atomic.c
  test/ttsafe_develop.c
  test/ttsafe_rec_rwlock.c
  test/ttsafe_rwlock.c
  test/ttsafe_semaphore.c
  test/ttsafe_thread_id.c
  test/ttsafe_thread_pool.c
Labels: Merge - Develop Only, Component - Documentation, Type - Task

#4823 Correct URLs in documentation
  CITATION.cff
  HDF5Examples/README.md
  config/cmake/README.md.cmake.in
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/VOLConnGuide.dox
  doxygen/hdf5doxy_layout.xml
  hl/src/H5DOpublic.h
  hl/src/H5DSpublic.h
  hl/src/H5LTpublic.h
  java/src/hdf/overview.html
  release_docs/INSTALL
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_parallel
  release_docs/RELEASE.txt
  release_docs/RELEASE_PROCESS.md
  src/H5Ppublic.h
  src/H5VLmodule.h
  src/H5module.h
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump.h
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Bug

#4826 Add release note for signed binaries
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Type - Improvement, Component - Misc

#4827 Cleanup errors detected during merge compare
  .github/workflows/cmake-ctest.yml
  config/cmake/CPack.Info.plist.in
  config/cmake/FindHDFS.cmake
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4828 Merge changes from dev CMake and documentation
  .github/workflows/cmake-ctest.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  .github/workflows/scorecard.yml
  CITATION.cff
  CONTRIBUTING.md
  HDF5Examples/README.md
  README.md
  config/cmake/CPack.Info.plist.in
  config/cmake/FindHDFS.cmake
  config/cmake/README.md.cmake.in
  config/cmake/cacheinit.cmake
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/VOLConnGuide.dox
  doxygen/hdf5doxy_layout.xml
  hl/src/H5DOpublic.h
  hl/src/H5DSpublic.h
  hl/src/H5LTpublic.h
  java/src/hdf/overview.html
  release_docs/INSTALL
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_parallel
  release_docs/RELEASE.txt
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
  src/H5Ppublic.h
  src/H5VLmodule.h
  src/H5module.h
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump.h
  tools/src/misc/h5repart.c
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
Labels: Merge, Priority - 0. Blocker ⛔, Type - Task, Branch - 1.14, Component - Misc

#4825 Draw attention to 3rd step in process to update so numbers for release.
  config/lt_vers.am
  release_docs/RELEASE_PROCESS.md
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#4829 Remove develop only workflow
  .github/workflows/scorecard.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Deprecation / Removal, Component - Misc

#4830 Correct paths for binaries
  .github/workflows/cmake-ctest.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4834 Update so numbers for HDF5 1.14.5 release.
  config/lt_vers.am
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Task, Branch - 1.14

#4835 correct path for deb binary
  .github/workflows/cmake-ctest.yml
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4833 Sync develop changes 9/11 - 9/13 to hdf5_1_14
  config/lt_vers.am
  release_docs/RELEASE.txt
  release_docs/RELEASE_PROCESS.md
  src/H5FDsubfiling/H5FDsubfiling.c
  testpar/t_subfiling_vfd.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Documentation, Component - Build, Type - Task, Branch - 1.14

#4831 Update h5fc.in missed line for libhdf5hl_fortran filename change to libhdf5_hl_fortran.
  fortran/src/h5fc.in
Labels: Merge - Develop Only, Priority - 0. Blocker ⛔, Component - Build, Type - Bug

#4837 Updated support branch version number to 1.14.6-1.
  README.md
  config/cmake/scripts/HDF5config.cmake
  configure.ac
  java/src/hdf/hdf5lib/H5.java
  java/test/TestH5.java
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
  tools/test/h5repack/expected/h5repack_layout.h5-plugin_version_test.ddl
Labels: Priority - 1. High 🔼, Component - Build, Type - Task, Branch - 1.14

#4836 Document usage for H5TSmutex_release/acquire()
  src/H5TS.c
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4841 Print error stream when cmake greptest fails to match error ref.
  config/cmake/grepTest.cmake
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement

#4843 Fix issues with large external data files
  src/H5Defl.c
Labels: Merge - To 1.14, Component - C Library

#4845 Release related typo-corrections and NEWSLETTER.txt additions.
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
Labels: Good First Issue, Merge - To 1.14, Priority - 3. Low 🔽, Type - Improvement

#4844 Use the correct doxygen URL in 1.14 branches
  CONTRIBUTING.md
  README.md
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/examples/H5.format.1.1.html
  release_docs/INSTALL_Autotools.txt
  release_docs/RELEASE_PROCESS.md
  test/API/README.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug, Branch - 1.14

#4848 Correct doxygen URL paths
  CONTRIBUTING.md
  README.md
  doc/parallel-compression.md
  doxygen/aliases
  doxygen/examples/H5.format.1.1.html
  release_docs/INSTALL_Autotools.txt
  release_docs/RELEASE_PROCESS.md
  test/API/README.md
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug, Branch - 1.14

#4842 Fix memory leaks in ttsafe tests
  test/ttsafe_acreate.c
  test/ttsafe_attr_vlen.c
  test/ttsafe_cancel.c
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - Testing, Type - Bug

#4847 Fix issues with large external data files (#4843) - merge to 1.14
  src/H5Defl.c
Labels: Merge, Priority - 1. High 🔼, Component - C Library, Type - Bug

#4853 Reduce test iterations, etc. to keep time down on slower systems
  test/ttsafe_rwlock.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Testing, Type - Improvement

#4854 Add windows extra options
  config/cmake/examples/HDF5_Examples.cmake.in
  release_docs/USING_CMake_Examples.txt
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug, Type - Improvement

#4855 Add windows extra options and update release process doc
  config/cmake/examples/HDF5_Examples.cmake.in
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Component - Testing, Type - Bug, Type - Improvement, Branch - 1.14

#4858 Merge CMake changes for Windows and release process
  config/cmake/examples/HDF5_Examples.cmake.in
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Type - Improvement, Branch - 1.14, Component - Misc

#4859 Fix issues with large external data files (#4843) (#4847)
  src/H5Defl.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug

#4851 Add binary testing steps
  release_docs/RELEASE_PROCESS.md
Labels: Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#4863 Replace deprecated vlen release in ttsafe test
  test/ttsafe_attr_vlen.c
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Type - Bug

#4867 Update README.md
  README.md
Labels: Component - Documentation

#4868 Fix a typo in VOL user's guide
  src/H5VLmodule.h
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Documentation, Type - Task

#4866 Replace invalid email cdashhelp with help
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/scripts/CTestScript.cmake
Labels: Component - Documentation

#4870 Fix minor spellings in documentation
  src/H5Ppublic.h
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - C Library, Component - Documentation, Type - Improvement

#4869 Fix an incorrect returned value by H5LTfind_dataset()
  hl/src/H5LT.c
  hl/test/test_ds.c
  hl/test/test_lite.c
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - High-Level Library, Component - Testing, Type - Bug

#4872 Remove an unused variable from H5FDs3comms.c
  src/H5FDs3comms.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#4876 Remove Windows oneAPI warning for %ld formatting
  tools/src/h5repack/h5repack.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Tools, Type - Improvement

#4878 Remove Windows oneAPI warning for unused function in t_mpi.c
  testpar/t_mpi.c
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#4877 Add threadsafety warning doc
  doc/threadsafety-warning.md
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#4864 Add workflow that reports to CDash
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  HDF5Examples/CMakePresets.json
  HDF5Examples/Using_CMake.txt
  HDF5Examples/config/cmake-presets/hidden-presets.json
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5config.cmake
Labels: Merge - To 1.14, Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Improvement, Component - Misc

#4883 RELEASE note for threadsafety warning
  release_docs/RELEASE.txt
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4884 Add threadsafety warning and release notice
  doc/threadsafety-warning.md
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#4882 Fixed a memory leak from H5FL_blk_malloc
  src/H5Faccum.c
  src/H5Fint.c
  src/H5Fio.c
  src/H5Fpkg.h
  test/accum.c
Labels: Merge - To 1.14, Priority - 1. High 🔼, Component - C Library

#4885 Merge CMake and CI changes from develop
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  HDF5Examples/CMakePresets.json
  HDF5Examples/Using_CMake.txt
  HDF5Examples/config/cmake-presets/hidden-presets.json
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/grepTest.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5config.cmake
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Type - Improvement, Branch - 1.14, Component - Misc

#4879 Improve grammar and style of comment block in bin/genparser
  bin/genparser
Labels: Merge - To 1.14, Priority - 3. Low 🔽, Component - Build, Type - Improvement, perl

#4887 remove incorrect ref to input var
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Branch - 1.14, Component - Misc

#4889 Added an entry for the GH-4585 fix
  release_docs/RELEASE.txt
Labels: Merge - To 1.14, Component - Documentation

#4886 Correct inputs ref
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4894 Correct paths in doxygen
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/Overview.dox
Labels: Merge - To 1.14, Priority - 0. Blocker ⛔, Type - Bug

#4893 Correct aliases and usage
  doxygen/aliases
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/Overview.dox
Labels: Merge, Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug

#4896 Correct doxygen reference URLs
  doxygen/aliases
  doxygen/dox/LearnHDFView.dox
  doxygen/dox/Overview.dox
Labels: Merge, Priority - 0. Blocker ⛔, Type - Bug, Component - Misc

#4895 Hdf5 1 14 5 update
  README.md
  config/cmake/scripts/HDF5config.cmake
  configure
  configure.ac
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
Labels: Priority - 0. Blocker ⛔, Type - Task, Component - Misc

#4897 Merge CI changes from 1.14 development
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  HDF5Examples/CMakePresets.json
  HDF5Examples/Using_CMake.txt
  HDF5Examples/config/cmake-presets/hidden-presets.json
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF5_Examples.cmake.in
  config/cmake/grepTest.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF5config.cmake
Labels: Merge, Priority - 0. Blocker ⛔, Component - Testing, Component - Build, Type - Bug, Type - Improvement, Component - Misc
