Repository HDFGroup/hdf5, pull requests merged in 2024-12, with the labels that each got.

#5161 Replaced an incorrect image with the correct one
  src/H5module.h
Labels: Component - Documentation

#5062 Ensure C language when requiring MPI
  config/cmake/hdf5-config.cmake.in
Labels: Priority - 2. Medium ⏹, Component - Parallel, Component - Build, Type - Bug / Bugfix

#5152 Convert HL Dim Scales doc to doxy UG
  doxygen/dox/Overview.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/VOLConnGuide.dox
  doxygen/examples/H5DS_Spec.pdf
  doxygen/img/H5DS_fig1.png
  doxygen/img/H5DS_fig2.png
  doxygen/img/H5DS_fig3.png
  doxygen/img/H5DS_fig4.png
  doxygen/img/H5DS_fig5.png
  hl/src/H5DSpublic.h
  src/H5Ppublic.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5170 Remove the hash_size param from H5Iregister_type()
  bin/make_vers
  c++/src/C2Cppfunction_map.htm
  doxygen/examples/H5I_examples.c
  hl/src/H5PT.c
  java/src/hdf/hdf5lib/H5.java
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5I.c
  src/H5Ideprec.c
  src/H5Iint.c
  src/H5Ipkg.h
  src/H5Ipublic.h
  src/H5vers.txt
  src/H5version.h
  src/Makefile.am
  test/tid.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement, Perl

#5173 Add missing H5_DLL to Native callback
  src/H5VLnative_private.h
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#5162 Convert Library Version html to doxygen
  doxygen/dox/RelVersion.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/LibraryReleaseVersionNumbers.html
Labels: Priority - 2. Medium ⏹, Component - Documentation

#5163 Convert ImageSpec html file to doxygen
  doxygen/dox/ImageSpec.dox
  doxygen/dox/Specifications.dox
  doxygen/examples/ImageSpec.html
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5085 Rework the compression library search
  .github/workflows/aocc-cmake.yml
  .github/workflows/i386-cmake.yml
  .github/workflows/julia-cmake.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_async.yml
  .github/workflows/vol_cache.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_log.yml
  .github/workflows/vol_rest.yml
  CMakeFilters.cmake
  CMakePlugins.cmake
  config/cmake/cacheinit.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  test/dsets.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Bug / Bugfix

#5165 Split doxygen pages from spec and TN into files
  doxygen/dox/AppDbgging.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/SWMRTechNote.dox
  doxygen/dox/Specifications.dox
  doxygen/dox/TableSpec.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/Unicode.dox
  doxygen/dox/VDSTechNote.dox
  doxygen/dox/VFLTechNote.dox
  src/H5Fmodule.h
  src/H5Ppublic.h
Labels: Component - Documentation, Type - Improvement

#5172 Prevent H5Pset* routines from modifying default plists
  release_docs/RELEASE.txt
  src/H5FDcore.c
  src/H5FDdirect.c
  src/H5FDfamily.c
  src/H5FDhdfs.c
  src/H5FDlog.c
  src/H5FDmirror.c
  src/H5FDmpio.c
  src/H5FDonion.c
  src/H5FDros3.c
  src/H5FDsec2.c
  src/H5FDsplitter.c
  src/H5FDsubfiling/H5FDioc.c
  src/H5FDsubfiling/H5FDsubfiling.c
  src/H5FDsubfiling/H5subfiling_common.c
  src/H5FDwindows.c
  src/H5Fmpi.c
  src/H5Lexternal.c
  src/H5Pdapl.c
  src/H5Pdcpl.c
  src/H5Pdeprec.c
  src/H5Pdxpl.c
  src/H5Pfapl.c
  src/H5Pfcpl.c
  src/H5Pgcpl.c
  src/H5Pint.c
  src/H5Plapl.c
  src/H5Plcpl.c
  src/H5Pmapl.c
  src/H5Pocpl.c
  src/H5Pocpypl.c
  src/H5Pprivate.h
  src/H5Pstrcpl.c
  src/H5VLnative_attr.c
  src/H5VLnative_dataset.c
  src/H5Z.c
  src/H5Znbit.c
  src/H5Zscaleoffset.c
  src/H5Zshuffle.c
  src/H5Zszip.c
  test/tgenprop.c
Labels: Merge - Develop Only, Priority - 3. Low 🔽, Component - C Library, Type - Bug / Bugfix

#5180 There is no need to request libcurses for the CMake CI
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix

#5185 Update file-locking.md
  doc/file-locking.md
Labels: Component - Documentation, Type - Bug / Bugfix

#5186 Fix h5py daily CI failure.
  .github/workflows/h5py.yml
Labels: Priority - 1. High 🔼, Type - Bug / Bugfix, Component - Misc

#5179 Reissue of file format discussion html file to doxygen
  doxygen/dox/FileFormatDisc.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/examples/FileFormat.html
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement

#5192 Fix MPI_TEST_H5DIFF-h5diff_601
  tools/test/h5diff/CMakeTests.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Improvement

#5196 fix clang ci
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/main-cmake.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5190 removed link creation related c-wrappers
  fortran/src/H5Pf.c
  fortran/src/H5Pff.F90
Labels: Priority - 2. Medium ⏹, Component - Fortran, Type - Task

#5188 Correct CMake option usage and dependencies
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/i386-cmake.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  .github/workflows/msys2-cmake.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-cmake.yml
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  HDF5Examples/CMakeLists.txt
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/SignPackageFiles.cmake
  config/cmake/grepTest.cmake
  config/cmake/jrunTest.cmake
  config/cmake/runTest.cmake
  src/CMakeLists.txt
  test/CMakeLists.txt
  tools/test/perform/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc
