Repository HDFGroup/hdf5, pull requests merged in 2025-02, with the labels that each got.

#5286 Add new -testexpress option to testframe testing framework
  test/btree2.c
  test/cache.c
  test/cache_api.c
  test/fheap.c
  test/h5test.c
  test/h5test.h
  test/testframe.c
  test/testframe.h
  test/tsohm.c
  test/ttsafe_rec_rwlock.c
  testpar/t_2Gio.c
  testpar/t_filters_parallel.c
  testpar/t_shapesame.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement

#5287 RELEASE.txt updates
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
Labels: Priority - 1. High 🔼, HDF5 1.14.6

#5291 Set version to 1.14.6 for HDF5 1.14.6 release.
  README.md
  config/cmake/scripts/HDF5config.cmake
  configure
  configure.ac
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Task, HDF5 1.14.6

#5296 Fix segfault in H5Scombine_select
  src/H5Shyper.c
  test/th5s.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Bug / Bugfix

#5304 Add pkg-config.
  .devcontainer/Dockerfile
Labels: Type - Improvement, Component - Misc

#5294 Update files based on issues discovered during release
  .github/workflows/publish-release.yml
  .github/workflows/release-files.yml
  .github/workflows/tarball.yml
  README.md
  config/cmake/examples/HDF5_Examples.cmake.in
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Improvement, Component - Misc

#5307 Move TestAlarmOn()/TestAlarmOff() back into PerformTests()
  test/testframe.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Bug / Bugfix

#5311 Correct the version of zlib used by plugins
  CMakePresets.json
  config/cmake/cacheinit.cmake
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug / Bugfix, Component - Misc

#5313 Cray cce/18.0.1 work-around for failing test
  hl/fortran/test/tstlite.F90
Labels: Priority - 0. Blocker ⛔, Component - Fortran, Component - Testing, Type - Improvement

#5280 Use only one find_package call for zlib.
  .github/workflows/main-cmake-spc.yml
  CMakeFilters.cmake
  CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Improvement

#5298 Fix the rpath with option - plugins fail without
  CMakePresets.json
  config/cmake/HDF5Macros.cmake
  config/cmake/HDFMacros.cmake
  release_docs/RELEASE.txt
Labels: Priority - 2. Medium ⏹, Component - Build, Type - Bug / Bugfix, Type - Improvement

#5319 Fix the release workflow by copying before rename
  .github/workflows/tarball.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix, Component - Misc

#5320 Fix bad objcopy test cleanup on failure
  test/objcopy.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5321 Fix tag typo
  .github/workflows/release-files.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5314 Translate release-specific changes docs to doxygen
  doxygen/aliases
  doxygen/dox/HDF5CompressionTroubleshooting.dox
  doxygen/dox/HDF5ImprovingIOPerformanceCompressedDatasets.dox
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/IntroParExamples.dox
  doxygen/dox/LearnBasics1.dox
  doxygen/dox/LearnBasics2.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/Overview.dox
  doxygen/dox/SWMRTechNote.dox
  doxygen/dox/VDSTechNote.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/ViewTools2.dox
  doxygen/dox/ViewToolsJPSS.dox
  doxygen/dox/hdf5_1_10.dox
  doxygen/dox/hdf5_1_12.dox
  doxygen/dox/hdf5_1_14.dox
  doxygen/dox/hdf5_1_8.dox
  doxygen/dox/release_specific_info.dox
  doxygen/dox/sw_changes_1.10.dox
  doxygen/dox/sw_changes_1.12.dox
  doxygen/dox/sw_changes_1.14.dox
  doxygen/img/cgns.png
  doxygen/img/writeLgNumDsets.png
  hl/src/H5LDpublic.h
  src/H5Dmodule.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5Smodule.h
  src/H5Tmodule.h
  src/H5VLmodule.h
  src/H5Zdevelop.h
  tools/src/h5jam/h5jam.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5309 Add release information to enum constants - Part 4
  src/H5ESpublic.h
  src/H5FDcore.h
  src/H5FDdirect.h
  src/H5FDfamily.h
  src/H5FDhdfs.h
  src/H5FDlog.h
  src/H5FDonion.h
  src/H5FDpublic.h
  src/H5FDros3.h
  src/H5FDsec2.h
  src/H5FDsplitter.h
  src/H5FDsubfiling/H5FDioc.h
  src/H5Ldevelop.h
  src/H5Ppublic.h
  src/H5Spublic.h
  src/H5VLconnector.h
  src/H5VLpublic.h
  src/H5public.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Bug / Bugfix

#5246 Integrate shared chunk cache (H5SC) package with upper layers of library
  src/CMakeLists.txt
  src/H5CX.c
  src/H5CXprivate.h
  src/H5Dchunk.c
  src/H5Dint.c
  src/H5Dio.c
  src/H5Dpkg.h
  src/H5Dprivate.h
  src/H5Fint.c
  src/H5Fpkg.h
  src/H5Fprivate.h
  src/H5Fquery.c
  src/H5Oprivate.h
  src/H5Pdcpl.c
  src/H5Ppublic.h
  src/H5SC.c
  src/H5SCprivate.h
  src/H5VLnative_dataset.c
  test/CMakeLists.txt
  test/struct_chunk_storage.c
Labels: Merge - Develop Only, Priority - 2. Medium ⏹, Component - C Library, Type - New Feature

#5333 Fix the HL H5TB fill-info #5332
  .github/workflows/i386-cmake.yml
  HDF5Examples/C/HL/h5ex_table_01.c
  HDF5Examples/C/HL/h5ex_table_02.c
  HDF5Examples/C/HL/h5ex_table_03.c
  HDF5Examples/C/HL/h5ex_table_04.c
  HDF5Examples/C/HL/h5ex_table_05.c
  HDF5Examples/C/HL/h5ex_table_06.c
  HDF5Examples/C/HL/h5ex_table_07.c
  HDF5Examples/C/HL/h5ex_table_08.c
  HDF5Examples/C/HL/h5ex_table_09.c
  HDF5Examples/C/HL/h5ex_table_10.c
  HDF5Examples/C/HL/h5ex_table_11.c
  HDF5Examples/C/HL/h5ex_table_12.c
  HDF5Examples/C/HL/tfiles/h5ex_table_01.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_01.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_02.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_02.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_03.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_03.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_04.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_04.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_05.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_05.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_06.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_07.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_08.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_08.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_09.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_09.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_10.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_10.tst
  HDF5Examples/C/HL/tfiles/h5ex_table_11.ddl
  HDF5Examples/C/HL/tfiles/h5ex_table_12.ddl
  hl/src/H5TB.c
  hl/test/CMakeTests.cmake
  hl/test/testfiles/test_table.h5.ddl
  release_docs/RELEASE.txt
Labels: Priority - 1. High 🔼, Component - High-Level Library, Type - Bug / Bugfix

#5334 Add a readme file to workflows
  .github/workflows/README.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement, Component - Misc

#5323 Add presets cookbook and use cases
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/main-cmake.yml
  CMakeInstallation.cmake
  CMakeLists.txt
  README.md
  config/cmake/HDFLibMacros.cmake
  config/cmake/README.md.cmake.in
  config/cmake/ZLIB/devCMakeLists.txt
  configure.ac
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/Cookbook.dox
  doxygen/dox/Overview.dox
  doxygen/dox/ReferenceManual.dox
  doxygen/dox/ViewTools.dox
  doxygen/dox/cookbook/Presets.dox
  doxygen/dox/hdf5_1_10.dox
  doxygen/dox/hdf5_1_8.dox
  doxygen/dox/sw_changes_1.12.dox
  doxygen/doxygen-awesome.css
  doxygen/img/FortBuildFlow.svg
  hl/src/H5LTpublic.h
  src/H5ACpublic.h
  src/H5Fpublic.h
  src/H5Opublic.h
  src/H5PLmodule.h
  src/H5Ppublic.h
  src/H5Spublic.h
  src/H5Tmodule.h
  src/H5VLconnector.h
Labels: Component - Documentation

#5331 Fix objects not being closed on objcopy test failure
  test/objcopy.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix
