Repository HDFGroup/hdf5, pull requests merged in 2025-01, with the labels that each got.

#5198 Fix flipped calloc args
  c++/test/trefer.cpp
  tools/src/h5repack/h5repack_refs.c
  tools/test/h5dump/h5dumpgentest.c
Labels: Priority - 3. Low 🔽, Component - Tools, Component - Testing, Type - Improvement

#5200 Remove duplicate MESSAGE macro
  c++/test/h5cpputil.h
  test/testframe.c
  test/testframe.h
Labels: Priority - 3. Low 🔽, Component - C++, Component - Testing, Type - Improvement

#5199 Fix 'unused parameter' warnings in C++ tests
  c++/test/dsets.cpp
  c++/test/tarray.cpp
  c++/test/tattr.cpp
  c++/test/tcompound.cpp
  c++/test/tdspl.cpp
  c++/test/tfile.cpp
  c++/test/tfilter.cpp
  c++/test/th5s.cpp
  c++/test/titerate.cpp
  c++/test/tlinks.cpp
  c++/test/tobject.cpp
  c++/test/trefer.cpp
  c++/test/ttypes.cpp
  c++/test/tvlstr.cpp
Labels: Priority - 3. Low 🔽, Component - C++, Component - Testing, Type - Improvement

#5203 Fix cygwin CI
  .github/workflows/cygwin-cmake.yml
  config/cmake/scripts/HDF5config.cmake
Labels: Type - Bug / Bugfix, Component - Misc

#5205 Fix doxygen missing references
  .gitattributes
  doc/parallel-compression.md
  java/src/Makefile.am
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/hdf/hdf5lib/H5.java
  java/src/hdf/hdf5lib/callbacks/H5A_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5Callbacks.java
  java/src/hdf/hdf5lib/callbacks/H5D_append_cb.java
  java/src/hdf/hdf5lib/callbacks/H5D_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5E_walk_cb.java
  java/src/hdf/hdf5lib/callbacks/H5L_iterate_t.java
  java/src/hdf/hdf5lib/callbacks/H5O_iterate_t.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_close_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_copy_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_cls_create_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_iterate_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_close_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_compare_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_copy_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_create_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_delete_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_get_func_cb.java
  java/src/hdf/hdf5lib/callbacks/H5P_prp_set_func_cb.java
  java/src/hdf/hdf5lib/callbacks/package-info.java
  release_docs/RELEASE.txt
  release_docs/RELEASE_PROCESS.md
  src/H5FDmodule.h
  src/H5FDonion.h
  src/H5FDpublic.h
  src/H5Pmodule.h
  src/H5Tmodule.h
  src/H5Zmodule.h
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug / Bugfix

#5204 Convert file format html files to doxygen
  .github/workflows/netcdf.yml
  CMakeFilters.cmake
  doxygen/dox/FileFormatSpec.dox
  doxygen/dox/H5.format.1.0.dox
  doxygen/dox/H5.format.1.1.dox
  doxygen/dox/H5.format.2.0.dox
  doxygen/dox/H5.format.3.0.dox
  doxygen/dox/Specifications.dox
  doxygen/examples/H5.format.1.0.html
  doxygen/examples/H5.format.1.1.html
  doxygen/examples/H5.format.2.0.html
  doxygen/examples/H5.format.html
Labels: Priority - 1. High 🔼, Component - Documentation, Type - Bug / Bugfix, Type - Improvement

#5207 Convert IOFlow.html to doxygen
  doxygen/dox/IOFlow.dox
  doxygen/dox/TechnicalNotes.dox
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5220 Misc cleanup in s3comms code
  src/H5FDs3comms.c
  src/H5FDs3comms.h
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#5221 Remove duplicate definition in parallel API tests
  testpar/API/H5_api_test_parallel.c
Labels: Merge - Develop Only, Priority - 1. High 🔼, Component - Testing, Type - Bug / Bugfix

#5223 Enable API tests by default and fix some issues
  CMakeTests.cmake
  test/API/H5_api_attribute_test.c
  test/API/H5_api_dataset_test.c
  test/API/H5_api_link_test.c
  test/API/H5_api_object_test.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix, Type - Improvement

#5182 Develop libaec fix
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/scripts/HDF5options.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug / Bugfix

#5225 Convert CVE GitHub action to use cmake
  .github/workflows/cve.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement

#5227 Use SSL to create hex strings from byte arrays
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Improvement

#5226 Parse ros3 VFD URLs using libcurl
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Improvement

#5228 Clean up H5FDs3comms.c code
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Improvement

#5229 Test ros3 VFD in MacOS CMake GH actions
  .github/workflows/main-cmake.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement

#5230 Fix memory leak in API tests for vlen dataset I/O
  test/API/H5_api_dataset_test.c
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Bug / Bugfix

#5231 More H5FDs3comms.c/h cleanup
  src/H5FDros3.c
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/ros3.c
  test/s3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Testing, Type - Improvement

#5232 Exclude test files from coverage command
  config/cmake/CTestCustom.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing, Component - Build, Type - Improvement

#5234 Add release information to enum constants - Part 3
  src/H5Mpublic.h
  src/H5Opublic.h
  src/H5Rpublic.h
  src/H5Spublic.h
  src/H5VLpublic.h
  src/H5public.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Documentation, Type - Improvement

#5236 Comment cleanup in s3comms code
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  src/H5Mpublic.h
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Improvement

#5238 Move AWS config/auth code inside H5FDs3comms.c
  src/H5FDros3.c
  src/H5FDros3.h
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/ros3.c
  test/s3comms.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Improvement

#5235 Fix AddressSanitizer issue in cache test
  test/cache.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5210 Fix vuln OSV-2023-77
  src/H5Cimage.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug / Bugfix

#5240 Add release information to enum constants - Part 3 cont.
  src/H5Epublic.h
  src/H5Fpublic.h
  src/H5Lpublic.h
  src/H5Ppublic.h
Labels: Component - C Library, Component - Documentation

#5242 Correct H5T_decode return value description
  src/H5T.c
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#5216 Convert doc folder files to doxygen
  .codespellrc
  .github/workflows/linkchecker.yml
  CMakeLists.txt
  doc/branches-explained.md
  doc/code-conventions.md
  doc/library-init-shutdown.md
  doc/threadsafety-warning.md
  doxygen/aliases
  doxygen/dox/CollectiveMetadataIO.dox
  doxygen/dox/CopyingCommited.dox
  doxygen/dox/FreeingMemoryAllocatedByTheHdf5Library.dox
  doxygen/dox/H5.format.1.1.dox
  doxygen/dox/H5.format.2.0.dox
  doxygen/dox/H5.format.3.0.dox
  doxygen/dox/HDF5CompressionTroubleshooting.dox
  doxygen/dox/HDF5ImprovingIOPerformanceCompressedDatasets.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/ModifiedRegionWrites.dox
  doxygen/dox/RelVersion.dox
  doxygen/dox/Specifications.dox
  doxygen/dox/TechnicalNotes.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/UsingIdentifiers.dox
  doxygen/dox/branches-explained.dox
  doxygen/dox/cmake-vols-fetchcontent.dox
  doxygen/dox/code-conventions.dox
  doxygen/dox/file-locking.dox
  doxygen/dox/high_level/extension.dox
  doxygen/dox/library-init-shutdown.dox
  doxygen/dox/parallel-compression.dox
  doxygen/dox/threadsafety-warning.dox
  doxygen/examples/tables/fileDriverLists.dox
  doxygen/examples/tables/propertyLists.dox
  doxygen/img/FreeingMemory_fig1.png
  doxygen/img/improve_perf-compress_fig_1.png
  doxygen/img/improve_perf-compress_fig_2.png
  doxygen/img/improve_perf-compress_fig_3.png
  doxygen/img/improve_perf-compress_fig_6.png
  doxygen/img/improve_perf-compress_fig_7.png
  doxygen/img/improve_perf-compress_fig_8.png
  doxygen/img/improve_perf-compress_fig_9.png
  doxygen/img/modregwrite.png
  hl/src/H5DSpublic.h
  java/src/hdf/hdf5lib/package-info.java
  release_docs/RELEASE.txt
  src/H5Dmodule.h
  src/H5Fmodule.h
  src/H5Gmodule.h
  src/H5PLmodule.h
  src/H5Zmodule.h
  src/H5Zpublic.h
  src/H5module.h
  src/H5public.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Improvement

#5255 Fix a codespell issue
  .codespellrc
  doxygen/examples/ImageSpec.html
  doxygen/img/Palettes_fm_anc.gif
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5233 Update install notes
  release_docs/INSTALL_CMake.txt
Labels: Component - Documentation

#5256 Fix codespell issues
  .codespellrc
  doxygen/dox/ImageSpec.dox
  doxygen/img/Palettes_fm_anc.gif
  hl/test/test_ld.c
  src/H5B2test.c
  src/H5Dbtree.c
  src/H5Dchunk.c
  src/H5FDonion_index.c
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  src/H5FDsubfiling/H5FDioc_int.c
  src/H5Fmodule.h
  src/H5Pfapl.c
  src/H5Ppublic.h
  src/H5Rdeprec.c
  src/H5Sselect.c
  src/H5TSbarrier.h
  test/mirror_vfd.c
  test/swmr.c
  test/tmisc.c
  test/ttsafe_thread_id.c
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5260 Merge compression changes from develop
  .codespellrc
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cygwin-cmake.yml
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  CMakePresets.json
  HDF5Examples/C/CMakeLists.txt
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_zfp.ddl
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_zfp.tst
  HDF5Examples/C/TUTR/CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/config/cmake-presets/hidden-presets.json
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  HDF5Examples/config/cmake/cacheinit.cmake
  README.md
  config/cmake/CTestCustom.cmake
  config/cmake/ConfigureChecks.cmake
  config/cmake/H5pubconf.h.in
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/SignPackageFiles.cmake
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIBNG/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake/examples/HDF5_Examples_options.cmake
  config/cmake/grepTest.cmake
  config/cmake/hdf5-config.cmake.in
  config/cmake/jrunTest.cmake
  config/cmake/mccacheinit.cmake
  config/cmake/runTest.cmake
  config/cmake/scripts/HDF5config.cmake
  config/cmake/scripts/HDF5options.cmake
  config/toolchain/intel.cmake
  doxygen/examples/ImageSpec.html
  hl/CMakeLists.txt
  hl/c++/CMakeLists.txt
  hl/c++/test/CMakeLists.txt
  hl/fortran/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE_PROCESS.md
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Build, Type - Bug / Bugfix, Type - Improvement

#5262 Add missing workflows for daily build
  .github/workflows/build_mpich_source.yml
  .github/workflows/build_openmpi_source.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5265 Fix Julia wrappers
  .github/workflows/julia-cmake.yml
  src/H5Gloc.c
  test/links.c
Labels: Priority - 1. High 🔼, Component - C Library, Component - Testing, Type - Bug / Bugfix

#5266 Update plugin versions, zlib-ng header, release note
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePresets.json
  config/cmake/cacheinit.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5Zdeflate.c
  test/CMakeLists.txt
  test/chunk_info.c
  test/direct_chunk.c
  tools/test/perform/CMakeLists.txt
  tools/test/perform/direct_write_perf.c
  tools/test/perform/zip_perf.c
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Build, Type - Bug / Bugfix, Type - Improvement, Component - Misc

#5267 Update Dockerfile
  .devcontainer/Dockerfile
Labels: Component - Build

#5213 Add H5Tdecode2, rename and deprecate H5Tdecode
  c++/src/H5DataType.cpp
  fortran/src/H5Tf.c
  fortran/src/H5Tff.F90
  fortran/src/H5f90proto.h
  fortran/test/tH5T.F90
  java/src/hdf/hdf5lib/H5.java
  release_docs/RELEASE.txt
  src/H5T.c
  src/H5Tdeprec.c
  src/H5Tpublic.h
  src/H5vers.txt
  src/H5version.h
  test/dtypes.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Component - Java, Component - Fortran, Component - C++, Component - Testing, Type - New Feature

#5268 Simplify the .gitattributes file
  .gitattributes
Labels: Priority - 2. Medium ⏹, Type - Improvement, Component - Misc

#5269 Updates for updated filters
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bshuf.ddl
  config/cmake/cacheinit.cmake
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix, Merge - To 1.14.6

#5270 Update for filter version
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bshuf.ddl
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix

#5277 Revert 'Address code page issues w/ Windows file paths (#4172)'
  release_docs/RELEASE.txt
  src/H5system.c
  src/H5win32defs.h
Labels: Priority - 0. Blocker ⛔, Component - C Library, Type - Bug / Bugfix, HDF5 1.14.6

#5076 Fixed allocation-size-too-big error in H5MM.c
  src/H5Centry.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Security

#5281 Correct versions for plugins
  CMakePresets.json
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix, Component - Misc

#5282 Continue an ABI error for java too.
  .github/workflows/abi-report.yml
Labels: Priority - 0. Blocker ⛔, Type - Improvement, Component - Misc

#5271 cmake: do not override cmake rpath defines
  HDF5Examples/config/cmake/HDFMacros.cmake
  config/cmake/HDF5Macros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/scripts/CTestScript.cmake
  release_docs/INSTALL_CMake.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Improvement

#5284 Only call find_package once, by default module mode for zlib
  .github/workflows/main-cmake-spc.yml
  CMakeFilters.cmake
  CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Merge, Priority - 0. Blocker ⛔, Component - Build, Type - Bug / Bugfix, Type - Improvement, Component - Misc, HDF5 1.14.6
