Repository HDFGroup/hdf5, pull requests merged in 2025-09, with the labels that each got.

#5760 Separate test file generation from testing in external link reference test
  test/trefer.c
Labels: Component - Testing

#5766 Merge h5ls add-test macros
  tools/test/h5ls/CMakeTests.cmake
Labels: Component - Tools, Component - Testing

#5787 add the s3-build workflow to release
  .github/workflows/release.yml
Labels: Component - Build

#5762 Resolve issue with left-hand side panel
  doxygen/hdf5doxy.css
Labels: Component - Documentation

#5797 Increment version subrelease digit to -2
  README.md
  config/cmake/scripts/HDF5config.cmake
  config/examples/HDF5AsSubdirMacros.cmake
  release_docs/NEWSLETTER.txt
  release_docs/RELEASE.txt
  src/H5public.h
Labels: Component - Build

#5824 Remove 'cmake' from GitHub workflow yml filenames
  .github/workflows/README.md
  .github/workflows/analysis.yml
  .github/workflows/aocc.yml
  .github/workflows/arm-main.yml
  .github/workflows/bintest.yml
  .github/workflows/call-workflows.yml
  .github/workflows/ctest.yml
  .github/workflows/cygwin.yml
  .github/workflows/daily-build.yml
  .github/workflows/dev.yml
  .github/workflows/i386.yml
  .github/workflows/intel.yml
  .github/workflows/julia.yml
  .github/workflows/main-par-spc.yml
  .github/workflows/main-par.yml
  .github/workflows/main-spc.yml
  .github/workflows/main.yml
  .github/workflows/msys2.yml
  .github/workflows/nvhpc.yml
  .github/workflows/par-script.yml
  .github/workflows/par-source.yml
  .github/workflows/release.yml
  .github/workflows/script.yml
  .github/workflows/testxpr.yml
Labels: Component - Testing

#5816 Doxygen updates for functions that use printf expansion
  src/H5FDfamily.c
  src/H5FDfamily.h
  src/H5FDmulti.h
  src/H5Ppublic.h
Labels: Component - Documentation

#5825 Fix a snprintf warning in H5match_types.c
  fortran/src/H5match_types.c
Labels: Component - Wrappers

#5823 Skip unicode tests for specific VFDs
  test/tunicode.c
Labels: Component - Testing

#5821 Remove checks for sys/types.h
  config/ConfigureChecks.cmake
  config/H5pubconf.h.in
  config/HDFTests.c
  src/H5public.h
  tools/test/perform/direct_write_perf.c
Labels: Component - Build

#5815 Unlink file free space section on failure to update data structures
  src/H5FSsection.c
Labels: Component - C Library

#5778 Replace the RELEASE.txt file with CHANGELOG.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CMakeInstallation.cmake
  CONTRIBUTING.md
  README.md
  doxygen/Doxyfile.in
  release_docs/AutotoolsToCMakeOptions.md
  release_docs/CHANGELOG.md
  release_docs/Cmake_logo.svg
  release_docs/NEWSLETTER_README.txt
  release_docs/README.md
  release_docs/RELEASE_PROCESS.md
  release_docs/release_archive.txt
Labels: Component - Documentation

#5811 Use SSIZE_T for ssize_t on Windows
  src/H5.c
  src/H5private.h
  src/H5public.h
Labels: Component - C Library

#5799 Fix CVE-2025-6857
  release_docs/CHANGELOG.md
  src/H5B.c
Labels: Component - C Library

#5772 Generate VOL tests for h5mkgrp
  tools/test/misc/CMakeTestsMkgrp.cmake
Labels: Component - Tools, Component - Testing

#5769 Generate VOL tests for h5ls
  .github/workflows/vol_rest.yml
  tools/test/h5ls/CMakeTests.cmake
Labels: Component - Tools, Component - Testing, HDFG-internal

#5876 More minor Changelog changes
  release_docs/CHANGELOG.md
Labels: Component - Documentation

#5850 Fix CVE-2025-6269
  release_docs/CHANGELOG.md
  src/H5Cimage.c
  src/H5Ocont.c
Labels: Type - Security

#5877 Include VDS changes in CHANGELOG
  release_docs/CHANGELOG.md
Labels: Component - Documentation
