Repository HDFGroup/hdf5, pull requests merged in 2025-08, with the labels that each got.

#5675 Consolidate h5diff add-test macros
  tools/test/h5diff/CMakeTests.cmake
Labels: Component - Tools, Component - Testing

#5700 Avoid placing CMake generator expressions in pkg-config files
  src/CMakeLists.txt
Labels: Component - Build

#5696 Add AI generated (reviewed) comments for config CMake files
  config/ConfigureChecks.cmake
  config/HDF5Macros.cmake
  config/HDF5UseFortran.cmake
  config/HDFMacros.cmake
  config/HDFUseFortran.cmake
  config/cmake/HDF5ExampleCache.cmake
  config/cmake/HDF5PluginCache.cmake
  config/cmake/HDF5PluginMacros.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/fileCompareTest.cmake
  config/cmake/runProxy.cmake
  config/cmake/stopProxy.cmake
  config/cmake/userblockTest.cmake
  config/cmake/vfdTest.cmake
  config/cmake/volTest.cmake
Labels: Component - Documentation

#5688 Add file header comments to CMake files
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  CMakeTests.cmake
  HDF5Examples/CMakeLists.txt
  c++/src/CMakeLists.txt
  c++/test/CMakeLists.txt
  fortran/src/CMakeLists.txt
  fortran/test/CMakeLists.txt
  fortran/testpar/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/c++/test/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/fortran/test/CMakeLists.txt
  hl/src/CMakeLists.txt
  hl/test/CMakeLists.txt
  hl/tools/h5watch/CMakeLists.txt
  java/src/hdf/hdf5lib/CMakeLists.txt
  java/src/jni/CMakeLists.txt
  java/test/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  testpar/CMakeLists.txt
  tools/lib/CMakeLists.txt
  tools/libtest/CMakeLists.txt
  tools/src/h5copy/CMakeLists.txt
  tools/src/h5diff/CMakeLists.txt
  tools/src/h5dump/CMakeLists.txt
  tools/src/h5format_convert/CMakeLists.txt
  tools/src/h5import/CMakeLists.txt
  tools/src/h5jam/CMakeLists.txt
  tools/src/h5ls/CMakeLists.txt
  tools/src/h5perf/CMakeLists.txt
  tools/src/h5repack/CMakeLists.txt
  tools/src/h5stat/CMakeLists.txt
  tools/src/misc/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5import/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5ls/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
  tools/test/misc/vds/CMakeLists.txt
  tools/test/perform/CMakeLists.txt
  utils/mirror_vfd/CMakeLists.txt
Labels: Component - Documentation

#5673 Fix Family VFD filename conflict in tests
  test/dsets.c
Labels: Component - Testing

#5680 Generate VOL tests for h5diff
  .github/workflows/vol_rest.yml
  tools/test/h5diff/CMakeTests.cmake
Labels: Component - Tools, Component - Testing

#5717 Correct VFD h5repack test file cleanup
  tools/test/h5repack/h5repackgentest.h
  tools/test/h5repack/h5repacktst.c
Labels: Component - Testing

#5716 Rename the install config variables to indicate library state
  HDF5Examples/C/CMakeLists.txt
  HDF5Examples/C/H5D/CMakeLists.txt
  HDF5Examples/C/H5D/C_sourcefiles.cmake
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5G/CMakeLists.txt
  HDF5Examples/C/H5PAR/C_sourcefiles.cmake
  HDF5Examples/C/H5T/CMakeLists.txt
  HDF5Examples/C/H5VDS/CMakeLists.txt
  HDF5Examples/C/HL/CMakeLists.txt
  HDF5Examples/C/Perf/CMakeLists.txt
  HDF5Examples/CMakeLists.txt
  HDF5Examples/CXX/CMakeLists.txt
  HDF5Examples/FORTRAN/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/CMakeLists.txt
  HDF5Examples/FORTRAN/H5D/Fortran_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5G/CMakeLists.txt
  HDF5Examples/FORTRAN/H5PAR/Fortran_sourcefiles.cmake
  HDF5Examples/FORTRAN/H5T/CMakeLists.txt
  HDF5Examples/FORTRAN/HL/CMakeLists.txt
  HDF5Examples/JAVA/H5D/Java_sourcefiles.cmake
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  config/examples/HDF5AsSubdirMacros.cmake
  config/install/hdf5-config.cmake.in
  release_docs/RELEASE.txt
Labels: Component - Build
