Repository HDFGroup/hdf5, pull requests merged in 2025-06, with the labels that each got.

#5523 Fix threads and variables.
  CMakeLists.txt
  config/cmake/HDF5PluginCache.cmake
  config/install/hdf5-config.cmake.in
  release_docs/AutotoolsToCMakeOptions.md
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/libhdf5.settings.cmake.in
Labels: Priority - 0. Blocker, Component - C Library, Component - Build

#5562 Correct filtered test file cleanup paths
  HDF5Examples/config/cmake/runExecute.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/runExecute.cmake
  config/cmake/runTest.cmake
Labels: Priority - 1. High, Component - Testing

#5583 Replace filtered temporary files with streams
  HDF5Examples/config/cmake/runExecute.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/runExecute.cmake
  config/cmake/runTest.cmake
Labels: Priority - 0. Blocker, Component - Tools, Component - Testing

#5456 Bring h5diffgentest in line with expected test files
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5diff/expected/h5diff_53.txt
  tools/test/h5diff/expected/h5diff_540.txt
  tools/test/h5diff/h5diffgentest.c
  tools/test/h5diff/testfiles/compounds_array_vlen1.h5
  tools/test/h5diff/testfiles/compounds_array_vlen2.h5
Labels: Priority - 2. Medium, Component - Testing

#5458 Bring h5dumpgentest in line with expected test files
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5dump/h5dumpgentest.h
  tools/test/h5gentest.c
Labels: Priority - 2. Medium, Component - Testing

#5587 Correct name of CMake option to HDF5_ENABLE_DEPRECATED_SYMBOLS
  .github/workflows/hdfeos5.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/netcdf.yml
  HDF5Examples/C/H5G/h5ex_g_intermediate.c
  HDF5Examples/C/H5G/h5ex_g_iterate.c
  HDF5Examples/C/H5G/h5ex_g_traverse.c
  HDF5Examples/C/H5G/h5ex_g_visit.c
  HDF5Examples/C/H5T/h5ex_t_cmpd.c
  HDF5Examples/C/H5T/h5ex_t_cmpdatt.c
  HDF5Examples/C/H5T/h5ex_t_commit.c
  HDF5Examples/C/H5T/h5ex_t_cpxcmpd.c
  HDF5Examples/C/H5T/h5ex_t_cpxcmpdatt.c
  HDF5Examples/C/H5T/h5ex_t_objref.c
  HDF5Examples/C/H5T/h5ex_t_objrefatt.c
  HDF5Examples/C/H5T/h5ex_t_opaque.c
  HDF5Examples/C/H5T/h5ex_t_opaqueatt.c
  HDF5Examples/C/H5T/h5ex_t_regref.c
  HDF5Examples/C/H5T/h5ex_t_regrefatt.c
  HDF5Examples/C/H5T/h5ex_t_vlen.c
  HDF5Examples/C/H5T/h5ex_t_vlenatt.c
  HDF5Examples/C/H5T/h5ex_t_vlstring.c
  HDF5Examples/C/H5T/h5ex_t_vlstringatt.c
  HDF5Examples/FORTRAN/H5G/h5ex_g_traverse.F90
  doxygen/dox/api-compat-macros.dox
  fortran/src/CMakeLists.txt
Labels: Priority - 0. Blocker, Component - Testing, Component - Misc

#5506 Add H5Dread_chunk2()
  .github/workflows/netcdf.yml
  doxygen/dox/H5.format.2.0.dox
  doxygen/dox/H5.format.3.0.dox
  doxygen/examples/tables/volAPIs.dox
  fortran/src/H5Dff.F90
  fortran/src/hdf5_fortrandll.def.in
  fortran/test/tH5D.F90
  hl/src/H5DO.c
  release_docs/RELEASE.txt
  src/H5D.c
  src/H5Dchunk.c
  src/H5Ddeprec.c
  src/H5Dpkg.h
  src/H5Dpublic.h
  src/H5VLnative.h
  src/H5VLnative_dataset.c
  src/H5vers.txt
  src/H5version.h
  test/chunk_info.c
  test/direct_chunk.c
Labels: Component - C Library, Component - Build

#5603 Upgrade MS cert service
  .github/workflows/cmake-ctest.yml
Labels: Priority - 1. High, Component - Testing

#5607 Correct tools test files ref paths
  java/test/CMakeLists.txt
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5diff/CMakeTests.cmake
  tools/test/h5dump/CMakeTests.cmake
  tools/test/h5dump/CMakeTestsPBITS.cmake
  tools/test/h5dump/CMakeTestsVDS.cmake
  tools/test/h5dump/CMakeTestsXML.cmake
  tools/test/h5dump/CMakeVFDTests.cmake
  tools/test/h5format_convert/CMakeTests.cmake
  tools/test/h5import/CMakeTests.cmake
  tools/test/h5jam/CMakeTests.cmake
  tools/test/h5ls/CMakeTests.cmake
  tools/test/h5ls/CMakeTestsVDS.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/misc/CMakeTestsClear.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
Labels: Priority - 0. Blocker, Component - Testing, Component - Build

#5617 Fix resource leak in Subfiling example programs and tests
  HDF5Examples/C/H5PAR/ph5_subfiling.c
  HDF5Examples/FORTRAN/H5PAR/ph5_f90_subfiling.F90
  src/H5FDsubfiling/H5FDsubfiling.h
  testpar/t_subfiling_vfd.c
  testpar/t_vfd.c
Labels: Priority - 1. High, Component - C Library, Component - Testing

#5598 Resolve spurious linkchecker timeouts
  .github/workflows/linkchecker.yml
Labels: Priority - 2. Medium, Component - Testing

#5618 H5Dmodule.h: Fix documentation for max number of filters
  src/H5Dmodule.h
Labels: Component - Documentation

#5619 Remove references to autotools options in documentation/comments
  .github/workflows/README.md
  config/ConfigureChecks.cmake
  config/flags/HDFCompilerCXXFlags.cmake
  config/flags/HDFCompilerFlags.cmake
  config/flags/HDFGnuCXXFlags.cmake
  config/flags/HDFGnuFlags.cmake
  config/flags/HDFIntelCXXFlags.cmake
  doxygen/dox/HDF5CompressionTroubleshooting.dox
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/ThreadSafe.dox
  release_docs/AutotoolsToCMakeOptions.md
  release_docs/INSTALL_Cygwin.txt
  release_docs/RELEASE.txt
  src/H5Fpublic.h
Labels: Priority - 3. Low, Component - Documentation

#5609 Remove private headers from list of headers installed
  src/CMakeLists.txt
  src/H5FDsubfiling/CMakeLists.txt
Labels: Priority - 2. Medium, Component - Build

#5623 Fix daily build S3 testing
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/cmake.yml
  .github/workflows/daily-build.yml
  .github/workflows/vfd-main.yml
  .github/workflows/vfd-ros3.yml
Labels: Priority - 2. Medium, Component - Testing

#5637 Convert autotools option name to CMake
  doxygen/dox/api-compat-macros.dox
Labels: Priority - 0. Blocker, Component - Documentation
