Repository HDFGroup/hdf5, pull requests merged in 2025-03, with the labels that each got.

#5341 Update AOCC and OpenMPI versions
  .github/workflows/aocc-cmake.yml
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Task

#5344 Fix an oversize allocation in t_bigio on 32-bit systems
  release_docs/RELEASE.txt
  testpar/t_bigio.c
Labels: Priority - 2. Medium ⏹, Component - Parallel, Component - Testing, Type - Bug / Bugfix

#5340 Correct references to groups in RM
  doxygen/aliases
  src/H5Ppublic.h
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Bug / Bugfix

#5347 Fix for external test for cray compiler
  test/external.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5348 Update API tests README.md with current information
  test/API/README.md
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Improvement

#5349 Change md file links to correct locations
  CONTRIBUTING.md
  release_docs/INSTALL_Autotools.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE_PROCESS.md
  test/API/README.md
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug / Bugfix, Component - Misc

#5350 Fix last linkcheck issues and linkchecker must pass
  .github/workflows/linkchecker.yml
  config/cmake/README.md.cmake.in
  release_docs/RELEASE_PROCESS.md
Labels: Priority - 1. High 🔼, Type - Improvement, Component - Misc

#5356 Define __STDC_WANT_IEC_60559_TYPES_EXT__ before including other headers
  src/H5private.h
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#5355 Fix two assertion failures in hyperslab code
  release_docs/RELEASE.txt
  src/H5Shyper.c
  src/H5Sselect.c
  test/th5s.c
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Bug / Bugfix

#5360 Close attribute after shared attr dtype test
  test/API/H5_api_attribute_test.c
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5351 Add code to H5SC layer to calculate selections for every chunk in I/O
  src/H5Dio.c
  src/H5SC.c
Labels: Component - C Library, Type - Improvement

#5353 Fix segfault in H5S__get_select_hyper_blocklist()
  release_docs/RELEASE.txt
  src/H5Shyper.c
  test/th5s.c
Labels: Priority - 3. Low 🔽, Component - C Library, Type - Bug / Bugfix

#5392 Remove Autotools from VFD daily build workflow
  .github/workflows/vfd-main.yml
  .github/workflows/vfd-subfiling.yml
  .github/workflows/vfd.yml
Labels: Priority - 3. Low 🔽, Component - Testing, Component - Build, Type - Task

#5378 Update Intel oneAPI version to 2025.0 for CI
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/intel-cmake.yml
Labels: Priority - 1. High 🔼, Component - Testing, Type - Improvement, Component - Misc

#5395 Remove bypassed autotools files, references and CI commands
  .github/workflows/main-cmake.yml
  .github/workflows/tarball.yml
  .github/workflows/vol_adios2.yml
  .github/workflows/vol_ext_passthru.yml
  .github/workflows/vol_rest.yml
  CONTRIBUTING.md
  README.md
  doxygen/dox/HDF5CompressionTroubleshooting.dox
  doxygen/dox/branches-explained.dox
  doxygen/dox/file-locking.dox
  test/test_abort_fail.sh.in
  test/test_check_version.sh.in
  test/test_error.sh.in
  test/test_external_env.sh.in
  test/test_libinfo.sh.in
  test/test_links_env.sh.in
  test/test_mirror.sh.in
  test/test_plugin.sh.in
  test/test_vds_env.sh.in
  testpar/t_pread.c
  tools/lib/Makefile.am
  tools/libtest/Makefile.am
  tools/src/Makefile.am
  tools/src/h5copy/Makefile.am
  tools/src/h5diff/Makefile.am
  tools/src/h5dump/Makefile.am
  tools/src/h5format_convert/Makefile.am
  tools/src/h5import/Makefile.am
  tools/src/h5jam/Makefile.am
  tools/src/h5ls/Makefile.am
  tools/src/h5perf/Makefile.am
  tools/src/h5repack/Makefile.am
  tools/src/h5stat/Makefile.am
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Testing, Component - Build, Type - Deprecation / Removal, Component - Misc

#5345 Changes to internal library routines for structured chunk
  src/H5Dbtree.c
  src/H5Dbtree2.c
  src/H5Dchunk.c
  src/H5Dearray.c
  src/H5Dfarray.c
  src/H5Dint.c
  src/H5Dlayout.c
  src/H5Dnone.c
  src/H5Dpkg.h
  src/H5Dprivate.h
  src/H5Dscatgath.c
  src/H5Dsingle.c
  src/H5Dstruct_chunk.c
  src/H5FA.c
  src/H5FAcache.c
  src/H5FAdbg.c
  src/H5FAdblock.c
  src/H5FAhdr.c
  src/H5FApkg.h
  src/H5FAprivate.h
  src/H5FAtest.c
  src/H5Olayout.c
  src/H5Oprivate.h
  src/H5Pdcpl.c
  src/H5Shyper.c
  src/H5Sprivate.h
  src/Makefile.am
Labels: WIP, Type - New Feature

#5404 Enable building of test generator programs against shared libraries
  hl/test/CMakeLists.txt
  test/CMakeTests.cmake
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5stat/CMakeLists.txt
  tools/test/misc/CMakeLists.txt
Labels: Priority - 2. Medium ⏹, Component - Tools, Component - High-Level Library, Component - Testing, Component - Build, Type - Improvement

#5391 Ignore gnu.org for #5377
  .github/workflows/linkchecker.yml
Labels: Component - Testing, Type - Improvement, Component - Misc

#5406 Fix incorrect link size for VOL connectors in h5ls/h5diff
  tools/lib/h5diff.c
  tools/src/h5ls/h5ls.c
Labels: Priority - 3. Low 🔽, Component - Tools, Type - Bug / Bugfix

#5408 Do not install H5fortran_types.F90 in include diretory #4985
  fortran/src/CMakeLists.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug / Bugfix

#5407 Improve the default plugin path #5399
  config/cmake/ConfigureChecks.cmake
  release_docs/RELEASE.txt
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Improvement, Component - Configure
