Repository HDFGroup/hdf5, pull requests merged in 2025-07, with the labels that each got.

#5647 FLOSS schema update
  .github/.well-known/funding-manifest-urls
  .github/.well-known/funding.json
  .github/CODEOWNERS
  funding.json
Labels: Priority - 3. Low, Component - Misc

#5653 Correct usage of H5_HAVE__FLOAT16 macro
  tools/test/h5gentest.c
Labels: Priority - 2. Medium, Component - Tools

#5650 Consolidate h5copy add-test macros
  tools/test/h5copy/CMakeTests.cmake
Labels: Priority - 2. Medium, Component - Testing

#5657 Add variable called HDF5_VERSION to install config file
  config/install/hdf5-config.cmake.in
Labels: Component - Misc

#5635 Add cmake_dependent_option command
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePlugins.cmake
  CMakeTests.cmake
  config/ConfigureChecks.cmake
  config/HDF5Macros.cmake
  config/HDFMacros.cmake
  doxygen/Doxyfile.in
  hl/CMakeLists.txt
  java/CMakeLists.txt
Labels: Component - Build

#5661 Fix Fortran name mangling in test library
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake-spc.yml
  CMakeLists.txt
  config/H5pubconf.h.in
  config/HDFUseFortran.cmake
Labels: Component - Wrappers, Component - Build

#5640 Optimizations for repeated VDS source file and dataset names
  doxygen/aliases
  doxygen/dox/FileFormatDisc.dox
  doxygen/dox/FileFormatSpec.dox
  doxygen/dox/H5.format.4.0.dox
  doxygen/dox/Specifications.dox
  release_docs/RELEASE.txt
  src/H5Dvirtual.c
  src/H5Olayout.c
  src/H5Oprivate.h
  src/H5Pdcpl.c
  src/uthash.h
  test/dsets.c
Labels: Component - C Library

#5486 Add script to test examples with h5*cc pkg-config wrappers
  .github/workflows/cmake-bintest.yml
  HDF5Examples/C/H5D/test-pc.sh
  HDF5Examples/C/H5G/test-pc.sh
  HDF5Examples/C/H5T/test-pc.sh
  HDF5Examples/C/H5VDS/test-pc.sh
  HDF5Examples/C/HL/test-pc.sh
  HDF5Examples/C/test-pc.sh
  HDF5Examples/CXX/test-pc.sh
  HDF5Examples/FORTRAN/H5D/test-pc.sh
  HDF5Examples/FORTRAN/H5G/test-pc.sh
  HDF5Examples/FORTRAN/H5T/test-pc.sh
  HDF5Examples/FORTRAN/HL/test-pc.sh
  HDF5Examples/FORTRAN/test-pc.sh
  HDF5Examples/JAVA/test-pc.sh
  HDF5Examples/README.md
  HDF5Examples/Using_CMake.txt
  HDF5Examples/test-pc.sh
  bin/h5cc.in
  bin/h5redeploy.in
  c++/src/CMakeLists.txt
  config/ConfigureChecks.cmake
  doxygen/dox/IntroHDF5.dox
  doxygen/dox/LearnBasics3.dox
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  src/CMakeLists.txt
Labels: Component - Wrappers, Component - Testing

#5666 Create a file containing the major CMake options
  CMakeBuildOptions.cmake
  CMakeFilters.cmake
  CMakeLists.txt
  CMakeTests.cmake
  CMakeVOL.cmake
  HDF5Examples/C/H5FLT/h5ex_d_bitgroom.c
  HDF5Examples/C/H5FLT/h5ex_d_blosc.c
  HDF5Examples/C/H5FLT/h5ex_d_blosc2.c
  HDF5Examples/C/H5FLT/h5ex_d_bshuf.c
  HDF5Examples/C/H5FLT/h5ex_d_bzip2.c
  HDF5Examples/C/H5FLT/h5ex_d_jpeg.c
  HDF5Examples/C/H5FLT/h5ex_d_lz4.c
  HDF5Examples/C/H5FLT/h5ex_d_lzf.c
  HDF5Examples/C/H5FLT/h5ex_d_mafisc.c
  HDF5Examples/C/H5FLT/h5ex_d_zfp.c
  HDF5Examples/C/H5FLT/h5ex_d_zstd.c
  config/ConfigureChecks.cmake
  config/HDF5Macros.cmake
  config/HDFMacros.cmake
  hl/CMakeLists.txt
  java/CMakeLists.txt
  release_docs/RELEASE.txt
Labels: Component - Build

#5636 Improve the installation and usage docs for CMake
  CMakeLists.txt
  CMakePresets.json
  HDF5Examples/Using_CMake.txt
  README.md
  config/examples/HDF5AsSubdirMacros.cmake
  doxygen/dox/LearnBasics3.dox
  doxygen/dox/cookbook/Presets.dox
  release_docs/INSTALL
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_Cygwin.txt
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF5_CMake.txt
Labels: Component - Documentation
