Repository HDFGroup/hdf5, pull requests merged in 2025-04, with the labels that each got.

#5386 Update H5SCprivate.h to be in sync with API doc
  src/H5SCprivate.h
Labels: Component - Documentation, Type - Improvement

#5387 Suppress GCC warnings about invalid float16 literal suffix before C23
  src/H5Tconv_complex.c
  src/H5Tconv_float.c
  src/H5Tconv_integer.c
  test/dt_arith.c
Labels: Priority - 3. Low 🔽, Component - C Library, Component - Testing, Type - Improvement

#5415 Suppress unhelpful error messages from tentative file opens in h5tools_fopen()
  tools/lib/h5tools.c
Labels: Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#5420 Remove release_docs/INSTALL_Warnings
  CMakeInstallation.cmake
  release_docs/INSTALL_Warnings.txt
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Deprecation / Removal

#5396 Add Developer build mode workflow
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-par-script.yml
  .github/workflows/cmake-par-source.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/dev-cmake.yml
  config/cmake/HDF5DeveloperBuild.cmake
  config/cmake/HDFClangCXXFlags.cmake
  config/cmake/HDFClangFlags.cmake
Labels: Priority - 3. Low 🔽, Component - Testing, Type - Improvement, Component - Misc

#5425 Fixed a typo
  src/H5ACmpio.c
Labels: Priority - 1. High 🔼, Component - C Library, Type - Bug / Bugfix

#5437 Add missing if check on developer workflow
  .github/workflows/daily-build.yml
Labels: Priority - 0. Blocker ⛔, Component - Misc, github_actions

#5433 Add FUSE report to RFC documentation
  doxygen/aliases
  doxygen/dox/RFC.dox
Labels: Priority - 3. Low 🔽, Component - Documentation, Type - Task

#5401 Fortran configury: Ensure F08 real_kinds are actually valid kinds
  m4/aclocal_fc.f90
Labels: Component - Wrappers, Component - Configure

#5429 Fix bad connector ID management during file open fallback
  src/H5VLcallback.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Bug / Bugfix

#5441 Include 400/500 HTTP status codes in ROS3 VFD error stacks
  release_docs/RELEASE.txt
  src/H5FDros3.c
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  test/s3comms.c
Labels: Priority - 2. Medium ⏹, Component - C Library, Type - Improvement

#5337 Fix bad VOL env var handling in CMake tests
  test/CMakeTests.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing, Type - Bug / Bugfix

#5438 Improve install and documentation
  config/cmake/examples/HDF5AsSubdirMacros.cmake
  doxygen/CMakeLists.txt
  release_docs/INSTALL
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#5423 Fix incorrect link size for VOL connectors in h5dump
  tools/src/h5dump/h5dump_ddl.c
Labels: Priority - 3. Low 🔽, Component - Tools, Type - Bug / Bugfix

#5422 Add file exists checks and fix policy 53 warnings
  CMakeVOL.cmake
  HDF5Examples/config/cmake/grepTest.cmake
  HDF5Examples/config/cmake/jrunTest.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/HDF5UseFortran.cmake
  config/cmake/HDFUseFortran.cmake
  config/cmake/grepTest.cmake
  config/cmake/jrunTest.cmake
  config/cmake/runTest.cmake
  config/cmake/userblockTest.cmake
Labels: Priority - 0. Blocker ⛔, Type - Improvement, Component - Misc

#5462 Move doxygen latest upload to daily-schedule
  .github/workflows/daily-build.yml
  .github/workflows/daily-schedule.yml
  .github/workflows/publish-release.yml
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Improvement

#5416 Correct fix for h5diff-601 tools test
  tools/test/h5diff/CMakeTests.cmake
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix

#5464 Correct indentation in workflow
  .github/workflows/daily-build.yml
Labels: Priority - 0. Blocker ⛔, Component - Testing, Type - Bug / Bugfix

#5475 Use ubuntu-22.04 for ubuntu clang
  .github/workflows/cmake-script.yml
  .github/workflows/dev-cmake.yml
Labels: Priority - 0. Blocker ⛔, Type - Bug / Bugfix

#5470 Fix usage of string (FIND ...) command in CMake files
  CMakeVOL.cmake
  HDF5Examples/config/cmake/grepTest.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/HDF5UseFortran.cmake
  config/cmake/grepTest.cmake
  config/cmake/runTest.cmake
Labels: Priority - 1. High 🔼, Component - Build, Type - Bug / Bugfix

#5476 Correct variable name for publishing doxygen
  .github/workflows/daily-schedule.yml
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Component - Testing, Type - Bug / Bugfix

#5469 Use stream variables in tools
  tools/lib/h5diff.c
  tools/lib/h5diff_util.c
  tools/lib/h5tools_filters.c
  tools/lib/h5tools_utils.c
  tools/src/h5copy/h5copy.c
  tools/src/h5diff/ph5diff_main.c
  tools/src/h5format_convert/h5format_convert.c
  tools/src/h5import/h5import.c
  tools/src/h5jam/h5jam.c
  tools/src/h5jam/h5jam.h
  tools/src/h5jam/h5unjam.c
  tools/src/h5ls/h5ls.c
  tools/src/h5stat/h5stat.c
  tools/src/misc/h5clear.c
Labels: Priority - 2. Medium ⏹, Component - Tools, Type - Improvement

#5465 h5cc shell portability fixes
  config/cmake/libh5cc.in
Labels: Priority - 0. Blocker ⛔, Component - Build, Type - Bug / Bugfix, Type - Improvement, Component - Misc

#5472 Fix doc for H5Fget_access_plist
  src/H5Fpublic.h
  src/H5Ppublic.h
Labels: Priority - 2. Medium ⏹, Component - Documentation, Type - Bug / Bugfix

#5489 Fix issue with H5Fget_file_image() when using newer file formats
  src/H5Fint.c
  test/file_image.c
Labels: Priority - 0. Blocker ⛔, Component - C Library, Component - Testing, HDFG-internal

#5467 h5cc: Allow overriding the compilers written into the file
  CMakeLists.txt
  c++/src/CMakeLists.txt
  config/cmake/HDFCompilerCXXFlags.cmake
  config/cmake/HDFCompilerFortranFlags.cmake
  fortran/src/CMakeLists.txt
  hl/c++/src/CMakeLists.txt
  hl/fortran/src/CMakeLists.txt
  hl/src/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
  src/CMakeLists.txt
Labels: Priority - 2. Medium ⏹, Component - Build

#5490 Deprecate the h5dump XML feature.
  release_docs/RELEASE.txt
  tools/src/h5dump/h5dump.h
  tools/test/h5dump/testfiles/xml/HDF5-File.dtd
  tools/test/h5dump/testfiles/xml/HDF5-File.xsd
Labels: Priority - 0. Blocker ⛔, Component - Tools, Type - Task

#5463 Increase a default number of filter cd_values used by tools
  release_docs/RELEASE.txt
  tools/lib/h5tools.h
  tools/lib/h5tools_dump.c
  tools/src/h5dump/h5dump_xml.c
  tools/src/h5ls/h5ls.c
  tools/src/h5repack/h5repack.c
  tools/src/h5repack/h5repack.h
  tools/src/h5repack/h5repack_copy.c
  tools/src/h5repack/h5repack_opttable.c
  tools/src/h5repack/h5repack_verify.c
Labels: Priority - 0. Blocker ⛔, Component - Tools
