Repository HDFGroup/hdf5, pull requests merged in 2025-05, with the labels that each got.

#5478 Add more install info
  HDF5Examples/Using_CMake.txt
  release_docs/INSTALL_CMake.txt
Labels: Component - Documentation

#5507 Fix caching issue in ROS3 VFD
  release_docs/RELEASE.txt
  src/H5FDros3.c
Labels: Priority - 1. High 🔼, Component - C Library

#5473 Mask values in h5dump output files
  config/cmake/HDF5Macros.cmake
  config/cmake/grepTest.cmake
  config/cmake/runTest.cmake
Labels: Priority - 2. Medium ⏹, Component - Testing

#5499 Update HDF5Examples cmake files from root files
  HDF5Examples/config/cmake/HDFExampleMacros.cmake
  HDF5Examples/config/cmake/grepTest.cmake
  HDF5Examples/config/cmake/jrunTest.cmake
  HDF5Examples/config/cmake/runTest.cmake
Labels: Component - Testing

#5524 Fix missing table elements
  doxygen/dox/H5.format.1.0.dox
  doxygen/dox/H5.format.1.1.dox
  doxygen/dox/H5.format.2.0.dox
  doxygen/dox/H5.format.3.0.dox
Labels: Priority - 0. Blocker ⛔, Component - Documentation, Type - Bug / Bugfix

#5520 ci: change spack repo path
  .github/workflows/h5py.yml
Labels: Component - Testing

#5522 Add Enable-Native-Access: ALL-UNNAMED to avoid JNI warning/error for newer Java
  java/src/hdf/hdf5lib/CMakeLists.txt
Labels: Priority - 1. High 🔼, Component - Wrappers, Type - Task

#5514 Add bitgroom filter support
  CMakePresets.json
  HDF5Examples/C/H5FLT/CMakeLists.txt
  HDF5Examples/C/H5FLT/h5ex_d_bitgroom.c
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bitgroom.ddl
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bitgroom.err
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bitgroom.h5
  HDF5Examples/C/H5FLT/tfiles/h5ex_d_bitgroom.tst
  config/cmake/cacheinit.cmake
  config/cmake/mccacheinit.cmake
  doxygen/dox/cookbook/Presets.dox
  release_docs/INSTALL_CMake.txt
Labels: Priority - 1. High 🔼, Component - Build, Type - Task

#5530 Updated "hdfgroup.github.io" links to "support.hdfgroup.org"
  CONTRIBUTING.md
  README.md
  doxygen/aliases
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE_PROCESS.md
  test/API/README.md
Labels: Component - Documentation

#5534 Fix typo in DLS test message
  test/dsets.c
Labels: Priority - 3. Low 🔽, Component - Testing

#5535 Correct LICENSE header comment
  config/cmake/HDFClangCXXFlags.cmake
  config/cmake/HDFClangFlags.cmake
  config/cmake/HDFCompilerCXXFlags.cmake
  config/cmake/HDFCompilerFortranFlags.cmake
  config/cmake/HDFGnuCXXFlags.cmake
  config/cmake/HDFGnuFlags.cmake
  config/cmake/HDFGnuFortranFlags.cmake
  config/cmake/HDFIntelCXXFlags.cmake
  config/cmake/HDFIntelFlags.cmake
  config/cmake/HDFIntelFortranFlags.cmake
  config/cmake/HDFMsvcCXXFlags.cmake
  config/cmake/HDFMsvcFlags.cmake
  config/cmake/HDFNvhpcCXXFlags.cmake
  config/cmake/HDFNvhpcFlags.cmake
  config/cmake/HDFNvhpcFortranFlags.cmake
  src/H5FDmulti_int.c
  src/H5FDstdio_int.c
  src/H5FDstdio_private.h
  src/H5Tcomplex.c
  src/H5Tconv_complex.c
  src/H5Tconv_complex.h
Labels: Priority - 0. Blocker, Component - Misc

#5536 Move define check out of windows only block
  fortran/src/CMakeLists.txt
Labels: Priority - 0. Blocker, Component - Wrappers, Component - Build

#5542 Don't use quotes with html formatting constructs
  doxygen/dox/H5.format.1.0.dox
  doxygen/dox/H5.format.1.1.dox
  doxygen/dox/H5.format.2.0.dox
  doxygen/dox/H5.format.3.0.dox
Labels: Priority - 0. Blocker, Component - Documentation

#5543 Cleanup obsolete files and references
  .codespellrc
  HDF5Examples/test-driver
Labels: Component - Misc

#5545 Fix syntax error in zlib setup
  CMakeFilters.cmake
Labels: Priority - 0. Blocker, Component - Build

#5480 Corrected colon behavior and UD with zero elements
  release_docs/RELEASE.txt
  tools/src/h5repack/h5repack_parse.c
  tools/test/h5repack/CMakeTests.cmake
Labels: Priority - 0. Blocker, Component - Tools

#5515 Merge test file generators for tools
  tools/test/CMakeLists.txt
  tools/test/h5copy/CMakeLists.txt
  tools/test/h5copy/h5copygentest.c
  tools/test/h5copy/h5copygentest.h
  tools/test/h5diff/CMakeLists.txt
  tools/test/h5diff/h5diffgentest.c
  tools/test/h5diff/h5diffgentest.h
  tools/test/h5dump/CMakeLists.txt
  tools/test/h5dump/h5dumpgentest.c
  tools/test/h5dump/h5dumpgentest.h
  tools/test/h5format_convert/CMakeLists.txt
  tools/test/h5format_convert/h5format_convertgentest.c
  tools/test/h5format_convert/h5format_convertgentest.h
  tools/test/h5gentest.c
  tools/test/h5gentest.h
  tools/test/h5jam/CMakeLists.txt
  tools/test/h5jam/h5jamgentest.c
  tools/test/h5jam/h5jamgentest.h
  tools/test/h5repack/CMakeLists.txt
  tools/test/h5repack/h5repackgentest.c
  tools/test/h5repack/h5repackgentest.h
  tools/test/h5stat/CMakeLists.txt
  tools/test/h5stat/h5statgentest.c
  tools/test/h5stat/h5statgentest.h
  tools/test/misc/CMakeLists.txt
  tools/test/misc/h5repartgentest.c
  tools/test/misc/h5repartgentest.h
Labels: Priority - 2. Medium, Component - Testing

#5548 Re-write ROS3 VFD S3 backend to use AWS' C S3 library
  .github/workflows/arm-main-cmake.yml
  .github/workflows/main-cmake-par-spc.yml
  .github/workflows/main-cmake-par.yml
  .github/workflows/main-cmake-spc.yml
  .github/workflows/main-cmake.yml
  config/ConfigureChecks.cmake
  release_docs/RELEASE.txt
  src/CMakeLists.txt
  src/H5FDros3.c
  src/H5FDros3.h
  src/H5FDros3_s3comms.c
  src/H5FDros3_s3comms.h
  src/H5FDs3comms.c
  src/H5FDs3comms.h
  src/H5warnings.h
  test/h5test.c
  test/h5test.h
  test/ros3.c
  test/s3comms.c
  test/vfd.c
  tools/src/h5dump/h5dump.c
  tools/src/h5dump/h5dump.h
  tools/src/h5ls/h5ls.c
  tools/src/h5ls/h5ls.h
  tools/src/h5stat/h5stat.c
  tools/src/h5stat/h5stat.h
  tools/test/h5dump/expected/h5dump-help.txt
  tools/test/h5dump/expected/pbits/tnofilename-with-packed-bits.ddl
  tools/test/h5dump/expected/pbits/tpbitsIncomplete.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsLengthPositive.ddl
  tools/test/h5dump/expected/pbits/tpbitsMaxExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetExceeded.ddl
  tools/test/h5dump/expected/pbits/tpbitsOffsetNegative.ddl
  tools/test/h5ls/expected/help-1.ls
  tools/test/h5ls/expected/help-2.ls
  tools/test/h5ls/expected/help-3.ls
  tools/test/h5ls/expected/textlinksrc-nodangle-1.ls
  tools/test/h5ls/expected/tgroup-1.ls
  tools/test/h5stat/expected/h5stat_help1.ddl
  tools/test/h5stat/expected/h5stat_help2.ddl
  tools/test/h5stat/expected/h5stat_nofile.ddl
Labels: Component - C Library, Component - Tools, Component - Documentation, Component - Testing

#5555 Correct CMake to match version 2.2.4 zlib-ng
  config/cmake/ZLIBNG/CMakeLists.txt
  release_docs/INSTALL_CMake.txt
Labels: Priority - 0. Blocker, Component - Build, Component - Misc

#5552 Rework test file filtering
  HDF5Examples/config/cmake/runExecute.cmake
  HDF5Examples/config/cmake/runTest.cmake
  config/cmake/runExecute.cmake
  config/cmake/runTest.cmake
  tools/test/h5copy/CMakeTests.cmake
  tools/test/h5repack/CMakeTests.cmake
  tools/test/misc/CMakeTestsMkgrp.cmake
Labels: Priority - 2. Medium, Component - Testing
